### ISSUE TITLE
Error using numbers as arguments via tagged sql templates

### ISSUE THREAD

**Issue by rmzg** [porsager/postgres#1002]
Example code:

```
const limit = 50;
await sql`SELECT blah, blah FROM table WHERE so on LIMIT ${limit}`;
```

Error:

```
The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (50)
```

**Comment by rmzg** [comment]
Further investigation, this is specifically because of adding this to my `sql` constructor:
```
 types: {
   bigint: {
     to: 20,
     from: [20],
     parse: (x) => parseFloat(x)
     serialize: (x) => x, 
   },
 },
```

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Query class constructor to convert number arguments to strings, addressing the issue with number arguments in template literals.

You can review changes in this commit: https://github.com/mark-addams001881/porsager-postgres-1002/commit/cfd0f9cb4692baebd89046bd3e46d22242885d49.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by porsager** [comment]
Not gonna entertain this
