### ISSUE TITLE
sql` `.toNodeStream() : ReadableStream

### ISSUE THREAD

**Issue by tracker1** [porsager/postgres#109]
As much as I appreciate the current stream method... It Would be awesome to have a method that returns a readable stream so that each row can be iterated more easily.

```
async fn() {
  for await (const row of sql`...`.toNodeStream()) {
    // do something with row.
  }
}
```

**Comment by porsager** [comment]
I think this is a dupe of https://github.com/porsager/postgres/issues/30 right?

**Comment by tracker1** [comment]
@porsager yes, sorry, didn't realize #30 was still there, I recall some discussion before, but not really traction, closing as a dupe.  Either would be nice to have to support the syntax.
