### ISSUE TITLE
Wait for listen

### ISSUE THREAD

**Issue by emilbayes** [porsager/postgres#11]
Hi!

Looking at the source for the listen function, it returns the query to listen. Does this mean that it can be `await`ed to pause execution until the listen has been registered by the database?

https://github.com/porsager/postgres/blob/bc8f6f25bec4d159a46aee876dd3bcb6330e1c2b/lib/index.js#L301

**Comment by porsager** [comment]
Hi.

Yes that's correct :)

**Comment by porsager** [comment]
I see it's not obvious in the documentation, so I'll get that fixed ;)
