### ISSUE TITLE
mix case column name insert error

### ISSUE THREAD

**Issue by hcheng2002cn** [porsager/postgres#111]
I got error message for insert mix case column record:

warehouse = {"code":"0c956389","name":"TestWarehouse","address":"Test address","directory":"test dir","createdById":1,"createdOn":"2020-09-03T05:36:59.347Z"}

sql`
        insert into warehouse ${
        sql(warehouse, 'code', 'name', 'address', 'directory', 'createdById', 'createdOn')
        }
      `
(node:34136) UnhandledPromiseRejectionWarning: Error: column "createdbyid" of relation "warehouse" does not exist
    at Object.generic (/Users/hcheng/project/test/process/node_modules/postgres/lib/types.js:200:5)
    at Object.ErrorResponse (/Users/hcheng/project/test/process/node_modules/postgres/lib/backend.js:124:33)
    at Socket.data (/Users/hcheng/project/test/process/node_modules/postgres/lib/connection.js:167:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

db table define:
select * from warehouse;
        createdOn        |         modifiedOn         | rowStatus | rowVersion | id |   code   |  name  | address | geoLocation | levels |  directory  | createdById | modifiedById 

Thanks for help.

**Comment by xiaoyu-tamu** [comment]
Postgres currently don't do reverse change case. see #16.

before it implemented, you can do 
```
sql\`insert into warehouse ${ params(warehouse, 'code', 'name', 'address', 'directory', 'createdById', 'createdOn') }\`

function mapKeys<T extends Record<string, any> = Record<string, any>>(
  obj: Record<string, any>,
  transformer: (key: string) => string = (x) => x,
): Record<string, T[keyof T]> {
  return Object.fromEntries(Object.entries(obj).map(([k, v]) => [transformer(k), v])) as T;
}

export function params<T extends Record<string, any>>(
  objOrArray: T | T[],
  ...columns: (keyof T)[]
) {
  return sql(
    Array.isArray(objOrArray)
      ? objOrArray.map((item) => mapKeys(item, snakeCase))
      : mapKeys(objOrArray, snakeCase),
    ...columns.map((x) => snakeCase(x as string)),
  );
}

```

**Comment by spacejack** [comment]
I ran into this problem as well. Using the debug feature mentioned here: https://github.com/porsager/postgres/issues/113#issuecomment-703186498 I can see that identifiers aren't quoted. @porsager I think all identifiers should be quoted, no?

**Comment by joaopaulobdac** [comment]
I also just ran into this problem. Dynamic query helpers should quote column names.

Given this sql schema:

```sql
CREATE TABLE "Monitor" (
    "monitorId" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "triggerThreshold" numeric NOT NULL
);
```

and this statement:

```js
const monitor = { triggerThreshold: 3 }
const [newMonitor] = await sql`INSERT INTO "Monitor" ${sql(monitor)} RETURNING *`
```

postgres.js throws this error:

```
PostgresError: column "triggerthreshold" of relation "Monitor" does not exist
```
