### ISSUE TITLE
Insert multiple rows at once: Error: Max number of parameters (65534) exceeded

### ISSUE THREAD

**Issue by PeHo89** [porsager/postgres#112]
Hi,

I have an issue with your library: When I am trying to insert 35k rows with each having 13 parameters at once, I get the error mentioned above. I get it even if I try to split the inserts up into several ones (e.g. 5000 rows per insert but 7 times). It seems that this maximum number is somehow absolute, no matter how many inserts I am trying to proceed at once. I also tried to close and re-open the connection on every insert with multiple rows, but I am having the same issue.

How can I insert 35k rows at once or in reasonable parts (e.g. 5000 rows at once)?

Many thanks!

**Comment by PeHo89** [comment]
I run this line of code 7 times with each inserting 5000 rows at once out of an array having 35k rows.

`for (let i = 0; i < fullInsertCycles; i++) {
            result = await this.sql`insert into crm.consumption_data ${this.sql(entriesToInsert.splice(i*5000,(i+1)*5000),'direction_id', 'start_time', 'end_time', 'customer_id', 'pod', 'type_id', 'version_time', 'quality', 'quantity', 'unit', 'granularity', 'updated_by', 'file_import_id')}`;

            insertCounter += result.count;
        }`

This is how I add rows to the array:
`entriesToInsert.push({
                direction_id: directionId,
                start_time: entry.startTime.toISOString(),
                end_time: entry.endTime.toISOString(),
                customer_id: customerId,
                pod: consumptionInfo.consumptionMetaData.meteringPoint,
                type_id: typeId,
                version_time: consumptionInfo.consumptionMetaData.versionTime,
                quality: entry.quality,
                quantity: entry.quantity,
                unit: entry.unit,
                granularity: granularityId,
                updated_by: process.env.user,
                file_import_id: fileId
            });`

Keys have the same name as the column is named.

**Comment by TobiasNickel** [comment]
i count 13 columns, times 5000 is 65000, that s to much. i guess there are some null values in the first chunk?

also: be carefull with `entriesToInsert.splice(i*5000,(i+1)*5000)` it removes items from `entriesToInsert`, I think you want `slice`. with splice, the entries 0~5000 and then 10000-15000 where tried to be inserted.

**Comment by Minigugus** [comment]
@TobiasNickel is right: the second parameter of `splice` is the __number of rows to delete__, not the end index where to stop like `slice`. Thus, your `(i+1)*5000` becomes bigger and bigger until the error is thrown.

**Comment by PeHo89** [comment]
Oh, damn. Such a silly mistake. Of course with `slice` it works. You saved my day! Many many thanks to you both for your help!
