### ISSUE TITLE
Connections leak when left unused for a period of time

### ISSUE THREAD

**Issue by jsdw** [porsager/postgres#116]
Hello! Thanks for this lovely library; I am a big fan of the API.

I'm having a go with `2.0.0-beta2` to chat to a postgres database. I've noticed that if I leave my application running for a while and then come back to it, I start seeing this error when it tries to retrieve things from the DB:

```
Error: read ETIMEDOUT\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
```

I find myself having to restart the application in order to fix this. I then notice that the old connections are left around in the database (`select * from pg_stat_activity where application_name = 'postgres.js'`) when new ones are created. 

I'm worried that it wouldn't take much of this connection leaking to max out the 100 connection limit, but moreso I am concerned that the app needs restarting in order to handle any requests properly once it gets into this state.

I realise that I haven't provided much in the form of error messages; I'll have to see whether I can extract a proper stack trace from the logs. Hopefully this gives some vague idea though in the meantime :)

**Comment by jsdw** [comment]
(I discovered the `idle_timeout` option after posting this, which looks to work reliably, and so that _might_ end up resolving both of my issues. I'll update as I learn more!)

**Comment by jsdw** [comment]
(one other slightly off topic note; using `prexit` as suggested seems to work to close connections sometimes, but not always)

**Comment by porsager** [comment]
I think there's still a small race condition wrt. connections in v2-beta, but I haven't had time to dig into it yet.. Hopefully this evening :)

**Comment by porsager** [comment]
This should be fixed in `master`. Please reopen if that is not the case
