### ISSUE TITLE
Document global var / setting `idle_timeout` solutions for long-running development processes eg. Next.js

### ISSUE THREAD

**Issue by karlhorky** [porsager/postgres#119]
Hi @porsager! 👋

Since a while now, students at @upleveled have been running into an issue where refreshes of a page (and [Fast Refresh](https://nextjs.org/docs/basic-features/fast-refresh)) are causing further database connections, and the old connections are not going away. This leads to confusing errors like (also mentioned in #42):

```
Error: remaining connection slots are reserved for non-replication superuser connections
```

The [teardown / cleanup](https://github.com/porsager/postgres#teardown--cleanup) section in the readme with the `prexit` example appears to be helpful, but `process.exit` is not actually called during the development workflow (multiple page refreshes and Fast Refresh hot reloads when a file is changed).

As far as I can tell, there are a couple of different solutions to this:

1. Set a global variable that will persist across page reloads and Fast Refresh (like this: https://github.com/vercel/next.js/issues/7811#issuecomment-715259370)
2. Set an `idle_timeout` that will cause the idle connections to be terminated fairly quickly (eg. after 2 seconds)

Would you be open to me creating a section in the readme addressing this problem with option 1 as a recommended solution for development workflows for these long-running apps? With maybe option 2 as an "alternative" solution?

**Comment by porsager** [comment]
Hi @karlhorky .. Is this with v1 or v2-beta?

**Comment by porsager** [comment]
Ah ok, I see the issue now. I think this is probably an issue for a lot of libraries using next.js. I'm afraid it might be more confusing if information about the global workaround is added to the Postgres.js documentation - what do you think?

**Comment by karlhorky** [comment]
Yes, on further consideration, I think documenting Option 1 would be misplaced in the docs here. I have asked if they would accept a PR for me to document it in the Next.js docs instead.

However, for Option 2, I would see value in having a short readme section on the fact Postgres.js does not automatically close connections, including example usage of the `idle_timeout` option (eg. the conversation from #42) - does that sound reasonable?

**Comment by porsager** [comment]
Yeah, that would be great! Much welcomed 🙂

**Comment by karlhorky** [comment]
Ah, thanks for f90eb2c9aeabf2c3c57e9565e3ab3063ec108d6a, never ended up circling back around to this one 😨

Quick PR to add an example too: https://github.com/porsager/postgres/pull/171
