### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by joshxyzhimself** [porsager/postgres#121]
Just encountered this while testing, will close for now as I'm not sure what caused it and I don't have a repro yet.

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at Immediate.write [as _onImmediate] (/home/project/node_modules/postgres/lib/connection.js:331:12)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by joshxyzhimself** [comment]
2nd time encountering it, same error.

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at Immediate.write [as _onImmediate] (/home/project/node_modules/postgres/lib/connection.js:331:12)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by porsager** [comment]
Hey @joshxyzhimself 

I think it's fine keeping the issue open even though you don't have a repro. Maybe others can chime in with ideas / a repro. 

Is this with v1?

**Comment by joshxyzhimself** [comment]
Hi @porsager, thanks just reopened it. Currently using `2.0.0-beta.2`

**Comment by joshxyzhimself** [comment]
Encountered this again locally with `^2.0.0-beta.2`, been doing some initialization script (e.g. create x tables, insert x rows), noticed this one's a bit different that the errors above. It's not consistent, it mostly works, but this one has shown up 3 times today already and I'm not even using third-party stuff like `nodemon`

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at write (/home/project/node_modules/postgres/lib/connection.js:331:12)
    at Object.write (/home/project/node_modules/postgres/lib/connection.js:317:16)
    at send (/home/project/node_modules/postgres/lib/connection.js:136:18)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by joshxyzhimself** [comment]
I'm starting to think it is caused by me using `nodemon` and not using `prexit`

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at Immediate.write [as _onImmediate] (/home/project/node_modules/postgres/lib/connection.js:331:12)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at Immediate.write [as _onImmediate] (/home/project/node_modules/postgres/lib/connection.js:331:12)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
{
  "code": "ERR_STREAM_WRITE_AFTER_END"
}
```

**Comment by naumf** [comment]
Don't have a repro too and not sure if it helps, but I got that error twice since setting the `idle_timeout` to 2 seconds.
Previously it was set to 8 seconds and didn't get that error.
Now I set it to 0, the default value and hopefully will see in the coming days if this is related to `idle_timeout` or not.

**Comment by joshxyzhimself** [comment]
Hey @naumf, just noticed that my `idle_timeout` value is also `2`. Maybe worth exploring.

**Comment by naumf** [comment]
> Hey @naumf, just noticed that my `idle_timeout` value is also `2`. Maybe worth exploring.

In my case, the error didn't show up since setting the `idle_timeout` to `0`.

**Comment by joshxyzhimself** [comment]
> > Hey @naumf, just noticed that my `idle_timeout` value is also `2`. Maybe worth exploring.
> 
> In my case, the error didn't show up since setting the `idle_timeout` to `0`.

I'll try that. The error message also implies that we're writing on the socket while it's ending, could be the case.

**Comment by naumf** [comment]
> I'll try that. The error message also implies that we're writing on the socket while it's ending, could be the case.
Sure thing. Given the difficulty of reproducing the bug, this was the easier "fix" (workaround). It might not work for everyone though, as someone might need the `idle_timeout` to be enabled.

**Comment by joshxyzhimself** [comment]
Note: links below are at `v2.0.0-beta.2` snapshot, which was the version we were at upon encountering the errors above.

Usage of `idle_timeout` here calls then `socket.end` method.

https://github.com/porsager/postgres/blob/0e919894b82c2ab68683ba0de9cb5d511466ea1e/lib/connection.js#L184

According to nodejs docs[1], calling the stream.write() method after calling stream.end() will raise an error.

It seems that `setImmediate(write)` below

https://github.com/porsager/postgres/blob/0e919894b82c2ab68683ba0de9cb5d511466ea1e/lib/connection.js#L318

calls the `socket.write(buffer)` line below 

https://github.com/porsager/postgres/blob/0e919894b82c2ab68683ba0de9cb5d511466ea1e/lib/connection.js#L331

which raises the error below

https://github.com/nodejs/node/blob/e65a25c077fb8b45fc8fe1fea5a7cc20d27aa744/lib/internal/streams/writable.js#L319

which leads to

https://github.com/nodejs/node/blob/e65a25c077fb8b45fc8fe1fea5a7cc20d27aa744/lib/internal/streams/writable.js#L630-L632

so, maybe check if the socket is ending already before we call any `socket.write`?

References

- [1] https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback
- [2] https://nodejs.org/api/net.html#net_socket_end_data_encoding_callback

**Comment by naumf** [comment]
> so, maybe check if the socket is ending already before we call any `socket.write`?

That would prevent the error from showing up, but I think we need to know what data is lost, should we queue it and retry writing to the socket once re-connected etc.

**Comment by joshxyzhimself** [comment]
it seems like setting `idle_timeout` to `0` solved it on my end, havent seen that error for a long time. we're also using v2.0.0-beta.6 now :)
