### ISSUE TITLE
NUMERIC performance

### ISSUE THREAD

**Issue by alancnet** [porsager/postgres#125]
I was able to boost the performance of a query like

```sql
select * from myTable where id = ${123}
```

from ~300 ms to ~2ms by adding the following code:

```javascript
debug (connection, query, parameters) {
  for (const parameter of parameters) {
    if (parameter.type === 1700 && parseInt(parameter.value) === parseFloat(parameter.value)) {
      parameter.type = 20 // int8
    }
  }
},
```

The reason for this is integer values are passed as type 1700 (NUMERIC) which does not play nicely with indices based on int8.

I'm sure there is a better way to do this, but the way it works _without_ this is really non-performant. 

I am running against AWS RDS / PostgreSQL 12.4 

Cheers!

**Comment by porsager** [comment]
Hi @alancnet 

Sorry for the late reply.

That's a very interesting benchmark.

How does it perform if you do your query like this:
```
select * from myTable where id = ${123}::int8
```
