### ISSUE TITLE
Cannot insert an array of integers

### ISSUE THREAD

**Issue by stalniy** [porsager/postgres#127]
## Steps to reproduce

1. Create a table 
    ```sql
    CREATE TABLE public.test
    (
        id integer NOT NULL DEFAULT nextval('test_id_seq'::regclass),
        "array" integer[] NOT NULL,
        CONSTRAINT test_pkey PRIMARY KEY (id)
    )
    ```
2. Execute the code
    ```js
    await sql`
      insert into test ("array")
      values (${sql.array([1, 2, 3])})
    `;
    ```

## Actual result

Query is not executed and I get error back

```
Failed query:  insert into test
      ("array")
    values
      (array[$1,$2,$3]) [ '1', '2', '3' ]
PostgresError: column "array" is of type integer[] but expression is of type text[]
    at Object.ErrorResponse (/home/sergii/projects/fahr/morpheus/node_modules/postgres/lib/backend.js:130:33)
    at Socket.data (/home/sergii/projects/fahr/morpheus/node_modules/postgres/lib/connection.js:233:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at query (/home/sergii/projects/fahr/morpheus/node_modules/postgres/lib/index.js:169:36)
    at postgres (/home/sergii/projects/fahr/morpheus/node_modules/postgres/lib/index.js:70:12)
    at main (/home/sergii/projects/fahr/morpheus/src/example/index.ts:20:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42804',
  hint: 'You will need to rewrite or cast the expression.',
  position: '52',
  file: 'parse_target.c',
  line: '592',
  routine: 'transformAssignedExpr',
  query: 'insert into test\n      ("array")\n    values\n      (array[$1,$2,$3])',
  parameters: [
    { type: 0, value: '1' },
    { type: 0, value: '2' },
    { type: 0, value: '3' }
  ]
}
```

## Expected result

The row with array is inserted

**Version**: 2.0.0-beta.2

**Comment by stalniy** [comment]
The workaround is to serialize array by yourself:

```js
  const array = JSON.stringify(position.caretakers);

  await sql`
    insert into test
      ("array")
    values
      (${`{${array.slice(1, -1)}}`})
  `;
```

**Comment by makoven** [comment]
Faced the same problem. Already rewrote almost the entire project from slonik. And at the end I found that the library turns numbers into strings when using sql.array()

@porsager, please help!

**Comment by joshxyzhimself** [comment]
I do it by

```sql
    INSERT INTO "ya_favourite_table" (
      "some_text_array_column",
      "some_integer_array_column"
    ) VALUES (
      ${postgres.array(["alice", "bob", "charlie"])}::text[],
      ${postgres.array([1, 2, 3])}::int[]
    ) RETURNING *;
```

**Comment by porsager** [comment]
@makoven 

the way @joshxyzhimself describes how to do it is correct. How does that work for you?

**Comment by stalniy** [comment]
Isn’t it kind of hack? The same as serialism goes it manually. 

If there is a special helper, why can’t it handle at least majority of cases for me?

**Comment by porsager** [comment]
No, this is exactly how you'd do it in raw SQL. 

You can't represent int or most of the other Postgres types directly in javascript, so it's a question of supplying that information somewhere, and I prefer to do as much in SQL as possible.

We only have Number (and now BigInt) in javascript, and iterating over the array to check if every Number is an integer of some size just to pass a better guess of the type to Postgres is both a little magical, and probably worse for performance (My first draft for Postgres.js did this only to find a very big amount of bad edge cases it led to). 

We could also add the type info in JS if we changed `sql.array()` to take it like this:

```
sql.array([1,2,3], [20])
```

But that'd just be sugar over sql.array([1, 2, 3].map(value => ({ value, type: 20 }))

**Comment by makoven** [comment]
@porsager 
I use a function like this for lists of numbers and/or strings (thanks for the above examples):

```typescript
export function sqlArray(array: (number | string)[]) {
  return `{${array.map(v => JSON.stringify(v))}}`;
}
```
This problem and the lack of [partials](https://github.com/yckao/postgres-partiall) almost made me come back to slonik. Fortunately, there were solutions in the issues and now your library successfully works on a small project with several users. Looking forward to real version 2. And thanks for the best driver for postgres )

**Comment by stalniy** [comment]
> No, this is exactly how you'd do it in raw SQL.
> 
> You can't represent int or most of the other Postgres types directly in javascript, so it's a question of supplying that information somewhere, and I prefer to do as much in SQL as possible.
> 
> We only have Number (and now BigInt) in javascript, and iterating over the array to check if every Number is an integer of some size just to pass a better guess of the type to Postgres is both a little magical, and probably worse for performance (My first draft for Postgres.js did this only to find a very big amount of bad edge cases it led to).
> 
> We could also add the type info in JS if we changed `sql.array()` to take it like this:
> 
> ```
> sql.array([1,2,3], [20])
> ```
> 
> But that'd just be sugar over sql.array([1, 2, 3].map(value => ({ value, type: 20 }))

Can we just assume it's the most standard integer or let postgres do this for us? For some reason we do not cast type when interpolate a regular number value, why do we do this for array?

```ts
sql`select * from table where id = ${1}` // why don't we put something like `::int` at the end?
```

**Comment by porsager** [comment]
We could say `js:Number -> pg:float8`, but we can't say `pg:float8 -> js:Number` because we'd loose precision.

We can say `js:Number -> int` if we iterate over the entire array and check the `js:Number`s are integers, but I think that's bad..

The Postgres protocol allows the type to be undefined by passing `0`, but that doesn't work for arrays because Postgres would have to do the same inefficient iteration just to establish the type. This is why I'm saying we have to supply the type information at some point.

**Comment by stalniy** [comment]
I see. 

I'm curious what happens when I serialize an array and pass it as a string (as in [this case](https://github.com/porsager/postgres/issues/127#issuecomment-7305022540)? Does postgres do casting under the hood?

**Comment by porsager** [comment]
In that case you're good, cause Postgres doesn't see it as text :) It sees `{1,2,3}`

It's a good point! Maybe we could return that from `sql.array()` to arrive at a better solution for letting PostgreSQL handle the array. 

Lol.. oh my.. Just checked my implementation for serializing arrays 🙈 I was sure I created arrays using parameter placeholders but we're just creating a serialized array string.. I'm sorry! Should definitely be possible to solve this in a better way then.

**Comment by porsager** [comment]
Ah, ok, I was too quick to dismiss myself 🤪 It does indeed use parameters, which I changed it to do in this commit: https://github.com/porsager/postgres/commit/22651e3cf9b40843a66f5310530f71e24e486b74

I'll dig a little deeper ;) To be continued

**Comment by uasan** [comment]
perhaps it makes sense to define the translation of the array, according to the specified type in the SQL?
```JS
const items = [1, 2, 3];

sql` SELECT ${items}::int[]`
// SELECT '{1, 2, 3}::int[]';

sql` SELECT json_array_length(${items}::json)`
// SELECT json_array_length('[1, 2, 3]'::json);

sql` SELECT VALUES(${items})`
// SELECT VALUES(1, 2, 3);
```

**Comment by porsager** [comment]
@uasan doing string parsing of the query is something I'd like to avoid. I already feel it's a bit too much with the insert and select helpers.

**Comment by stalniy** [comment]
@porsager are you OK to change `sql.array([1, 2, 3])` to return `{1,2,3}`

**Comment by Josehower** [comment]
https://github.com/porsager/postgres/issues/127#issuecomment-739258223
ty!
worked for me!!

**Comment by porsager** [comment]
Supporting ParameterDescription as mentioned by @uasan in https://github.com/porsager/postgres/issues/221 will make a case like this more ergonomic, so I'll close this one for now and we can track the other isssue.
