### ISSUE TITLE
Question: `sql.end()` behavior between version 1.0.2 and 2.0.0-beta.2

### ISSUE THREAD

**Issue by jmcantrell** [porsager/postgres#129]
I noticed that in version 1.0.2, `sql.end()` never resolves after running certain queries. `select 1` doesn't seem to cause a problem, but `create table ...` does. In version 2.0.0-beta.2, it resolves fine. If you run the code below with `testSimple`, you'll see the "closed" log, but not if you run it with `testComplex`.

```js
const postgres = require("postgres");

const debug = (conn, query, params) => console.log({ conn, query, params });

const sql = postgres(process.env.POSTGRES_URL, { debug });

test();

async function test() {

	await testSimple();
	// await testComplex();

	console.log("closing");

	await sql.end();

	console.log("closed");
}

async function testSimple() {
	await sql`select 1`;
}

async function testComplex() {
	const table = "test";

	try {
		await sql`create table ${sql(table)} (test text)`;
	} finally {
		await sql`drop table if exists ${sql(table)}`;
	}
}
```

[This line](https://github.com/porsager/postgres/blob/v2.0.0-beta.2/lib/index.js#L373) seems to indicate that the problem was because of the lack of `Promise.resolve(arrayTypesPromise)` in version 1.0.2. Is this the case?

Also in version 1.0.2, using `sql.end({ timeout: 0 })` (or any number) will cause it to resolve, obviously, but this leaves the possibility that a query might be killed before finishing.

Would you recommend just using 2.x? Or is there a better way to handle this in 1.x?

**Comment by porsager** [comment]
I don't know why I'm missing some issues here - so sorry 😔

Yes, I would recommend using the v2 beta, I will hopefully come around to making it the main release soon.

**Comment by jmcantrell** [comment]
@porsager Happens to us all. Thanks for the reply.
