### ISSUE TITLE
Provide a way to create a custom `sql`  function with custom `transform` option without creating a separate connection

### ISSUE THREAD

**Issue by stalniy** [porsager/postgres#130]
## Problem

Very often I need to pluck a single column (e.g., `id`) from table and usually I do this:

```js
const rows = await sql`
  SELECT id
  FROM table
`;
const ids = rows.map(row => row.id)
```

I know there is a `transform.row` option which I can pass to driver but in this case I want to pass this option per query. Sometimes, I need an array of objects and sometimes I need an array of column values.

## Suggestion

I suggest to add this API:

```ts
const ids = await sql.pluck<number>`
  SELECT id
  FROM table
`
```

Also, I'd like `transform.row` to receive all columns that is used in query, so the resulting signature is this:

```ts
transform: {
  row(row: Postgres.Row, columns: string[]): any
}
```

So, then this use case with pluck can be implemented efficiently:

```ts
const transform = {
  row(row, columns) {
    return row[columns[0].name]
  }
}
```

**Comment by stalniy** [comment]
@porsager let me know what you think about this, I'm happy to send a PR if you agree with this suggestion

**Comment by Minigugus** [comment]
You can easily add this feature with a simple wrapper, like:
```js
import postgres from 'postgre';

const config = {
  // Your postgres config here
};

export const sql = postgres(config);

export const sqlPluck = postgres({
  ...config,
  transform: {
    ...(config.transform || {}),
    row: (rows, columns) => rows[columns[0].name];
  }
});

// You can even add it manually to the sql tag
Object.assign(sql, { pluck: sqlPluck });
```

I think a `pluck` helper is bit too specific, but something like a map on the result that apply a specific transform on each query:
```js
const rows = await sql`
  SELECT id
  FROM table
`.map(row => row.id);
```
It improves a lot performances for huge arrays, as well as composability (`.map(row => ...).map(row => ...)` for instance).

**Comment by stalniy** [comment]
there are several issues with your suggestions:

1. `row` transformer doesn’t accept `columns` argument currently 
2. for this to work I need to create 2 separate connections and close 2 instead of one. Looks like additional overhead for such a simple thing. 
3. Currently `map` is the only possible workaround (which I use) but it slow for big arrays that’s why I want `pluck`

So, for me it will be enough to have a possibility to pass `transform` option per query basis, so will be happy with something like `pluck = sql.transform(transformOption)`. Basically instead of creating 2 connections, we create a separate `sql` tag function with bound transform options:

```ts
const pluck = sql.transform({
  row: (row, columns) => ...
})

const ids = await pluck`select I’d from table`

**Comment by porsager** [comment]
If i understand correctly, you could do it in SQL? 

```
const [{ ids }] = await sql`
  SELECT array_agg(id) as ids
  FROM table
`
```

**Comment by stalniy** [comment]
@porsager this is a vert neat workaround! I like it.

But I'm afraid that this doesn't work in all the cases, especially if I define custom `GROUP BY`. Imagine I want to get all ids of  entities grouped by another column:

```sql
SELECT array_agg(id)
FROM table
GROUP BY short_code
```

In this case, I will get a list of arrays buy I want to get a list of all ids as a single array. Obviously, this example is simplified buy I have some cases with group by that illustrate this issue.

That's why, I'd like to have a possibility to specify `transform` option per query basis.

**Comment by porsager** [comment]
Well, I'm a big fan of letting Postgres do as much of the work as possible. It's very likely faster than JS, and avoids us reinventing stuff ;)

I'm not sure I understand your other example, could you provide which output you'd expect?

**Comment by stalniy** [comment]
Sure. The expected output for that query is an array of ids. The same as I would do:

```ts
const rows = await sql`
  SELECT id
  FROM table
  GROUP BY short_code
`
const ids = rows.map(row => row.id) // the list of ids
```

If I do `array_agg`, I get back an array of arrays

**Comment by porsager** [comment]
But somehow that already smells. You want a list of unique ids correct?

**Comment by porsager** [comment]
Do you have a real life example, and the shape you'd like returned?

**Comment by stalniy** [comment]
I just showed you that when you have a group by that doesn't include aggregation column (for whatever reason), this doesn't work anymore. 

I want pluck to work in the same way, everywhere, in every use case, so that, I don't need to think each time whether by adding `GROUP BY`, I will shoot myself in a leg.

**Comment by porsager** [comment]
I'm sorry, but I just don't understand the example and purpose. The query appears invalid to me, `id` must appear in the GROUP BY clause or be used in an aggregate function?

**Comment by stalniy** [comment]
OK, fair enough. I will get back to this issue when I find a more realistic use case in our apps. For now, will use `array_agg`, thank you for the hint!

**Comment by stalniy** [comment]
@porsager, I found an issue with `array_agg` approach. When I try to order ids by some column:

```ts
await sql`
  SELECT array_agg(id)
  FROM table
  ORDER BY sort_order DESC
`
Postgres throws an exception:

```
column "sort_order" must appear in the GROUP BY clause or be used in an aggregate function
```

**The issue** is that I cannot put `sort_order` neither in `GROUP BY` nor put it in aggregation function because I will loose all the benefits of `pluck`

Do you have other recommendations how to approach that other than adapting `transform` option?

**Comment by porsager** [comment]
Ah, you'd use it with the array_agg like this:

```sql
  SELECT array_agg(id order by sort_order desc)
  FROM table
```

**Comment by stalniy** [comment]
Cool, it solves the issue! I'm a bit new to advanced postgres features like arrays. So, thanks for the help!
