### ISSUE TITLE
Using null or undefined as a value.

### ISSUE THREAD

**Issue by bas080** [porsager/postgres#134]
```js
    selectUserReservations({email, operator_code}) {
      return sql`
        select * from rezerv.reservation
        where email = ${email}
          and (operator_code = ${operator_code} or ${operator_code} is null)`
    },
```

The idea is to return all the reservations when operator code is undefined or null. 

This won't return any results and instead throw this error:

```
Error: could not determine data type of parameter $3
```

Should I be writing two separate queries? Does postgres.js have a safe way of achieving this behavior without having to write several queries?

**Comment by porsager** [comment]
The reason `undefined` is not allowed is to avoid undefined behavior and force you to make an intentional decision on how to handle those cases. In your example here I'd do:

```
sql`
  select * from rezerv.reservation
  where email = ${email}
    and (operator_code = ${ operator_code || null } or ${ operator_code || null } is null)
`
```

**Comment by bas080** [comment]
I see, one of them had the undefined value. In that case it seems that postgres.js does support null as a value.

Appreciate the quick response and a delightfully simple library. :love_letter:

**Comment by bas080** [comment]
I tried your approach and it doesn't work. I get the following error.

```
2 select * from rezerv.reservation
        where email = $1
          and (availability ->> 'operator_code' = $2 or
               ($3 is null)) [
  { type: 0, value: 'bassimhuis@gmail.com' },
  { type: 0, value: null },
  { type: 0, value: null }
]
Error: could not determine data type of parameter $3
    at Object.generic (/home/women/projects/rezerv/node_modules/postgres/lib/types.js:200:5)
    at Object.ErrorResponse (/home/women/projects/rezerv/node_modules/postgres/lib/backend.js:124:33)
    at Socket.data (/home/women/projects/rezerv/node_modules/postgres/lib/connection.js:167:25)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

I tried a similar query in the postgres prompt and it works there. Not sure what is causing this error.

**Comment by porsager** [comment]
Ah sorry, didn't read your error message properly.
Postgres needs an explicit type for this so you'd have to do it like this:

```
sql`
  select * from rezerv.reservation
  where email = ${email}
    and (operator_code = ${ operator_code || null } or ${ operator_code || null }::text is null)
`
```

**Comment by bas080** [comment]
It seems that there is no need to do `undefined || null`.

**Comment by porsager** [comment]
If you're using v1 that's right, but v2 beta will complain if a parameter is undefined ;)
