### ISSUE TITLE
Trying to select rows searching for accented values

### ISSUE THREAD

**Issue by xinxilas** [porsager/postgres#138]
```
app.get("/:vari", async (req, res, next) => {
    const estoques = await db`SELECT * FROM estoque WHERE vari LIKE ${ req.params.vari + '%' }`
    res.json(estoques)
});
```
/Fumê
No rows are returing when i look for vari = Fumê

Using psql it works
```
express=> SELECT * FROM estoque WHERE vari = 'Fumê'
express-> ;
             id_capa             | vari | qtd
---------------------------------+------+-----
 alcatel~pixi4_4.0~tpu           | Fumê |   0
 alcatel~pixi4_4.0~silicone-lisa | Fumê |  51
(2 rows)
```

Tried 
db`SELECT * FROM estoque WHERE vari LIKE ${ req.params.vari + '%' }`
db`SELECT * FROM estoque WHERE vari = ${ req.params.vari  }`
db`SELECT * FROM estoque WHERE vari LIKE ${ req.params.vari  }`

**Comment by xinxilas** [comment]
OK i fixed it

Changed everything to LATIN1:

on cmd.exe before login on psql i typed:
**chcp 28591**
So my cmd terminal will use characters based on **ISO-8859-1**
(i need set it because on next steps ill update older cells values using cmd.exe / psql)
**28591** is the code for **ISO-8859-1** (LATIN1)
ref:

> Windows-1250  1250
> Windows-1252  1252
> UTF-8         65001
> ISO-8859-1    28591
> ISO-8859-2    28592

(ISO-8859-1 stands for 'LATIN1' ref: https://www.postgresql.org/docs/9.3/multibyte.html)

Now i login to psql with my root admin user...
Then inside psql i changed my db SERVER_ENCODING to LATIN1:
`update pg_database set encoding = pg_char_to_encoding('LATIN1') where datname = 'express';`
(my database name is 'express')

Now i set my psql encoding to 'LATIN1' typing:
`SET client_encoding = 'LATIN1';`

Then i selected all rows looking for all crazy characters which my old accented characters became after i changed my db encode LATIN1
**SELECT * FROM estoque**

For example if "Fumê" (a normal latin1 word) became "FumX" (X = some crazy character)
I update all cells from FumX to Fumê
**UPDATE estoque SET column = 'Fumê' where column = 'FumX'**

Now changed postgres connection to:
```
const db = postgres({
  client_encoding: 'LATIN1',
  ...
}
```

But the question stays..:
Why it wasnt working when it was UTF8? UTF8 is good enough to handle latin characters :/

Thank you!

**Comment by porsager** [comment]
Glad to see you figured it out. 

UTF8 `ê = 0xC3AA` is not the same as LATIN1 `ê = 0xEA`, so if you search a db for UTF8 `ê` and the values stored are LATIN1 `ê` you won't get a match.
