### ISSUE TITLE
How would you handle migrations / ensuring schema?

### ISSUE THREAD

**Issue by brielov** [porsager/postgres#14]
So, I have a GraphQL application. What is the recommended way to ensure a certain database schema every time the server starts? I currently do `sql.fileI(schema.sql)` and then start the server, but every time I get `table already exists`. So, I add CREATE TABLE IF NOT EXISTS but this does not work with Postgres scalars. Also, what if I need to alter a table? I come from MongoDB so I have no idea how to manage this.

**Comment by adamtysonsmith** [comment]
You will need a separate package to handle migrations. I am considering these:
- https://github.com/salsita/node-pg-migrate
- https://github.com/db-migrate/node-db-migrate

All you have to do is create your up and down migrations in js, and then run them via cli (or node script preferably)

**Comment by porsager** [comment]
Hi @brielov 

This is a driver that you can use to talk to your database. It doesn't make any decisions about schemas.

You would probably need to look at some sort of migration solution like @adamtysonsmith metions.

I've got my own little forwards only migration module which is using `postgres.js`. I've yet to document it, so it's not something I'd recommend now, but I'll link it here once I have.

**Comment by karlhorky** [comment]
As per @porsager's comment on https://github.com/porsager/postgres/issues/33#issuecomment-584880571, here's the link to his forward-only migration tool:

https://github.com/porsager/postgres-shift
