### ISSUE TITLE
Expose raw values for parameters, before serialization

### ISSUE THREAD

**Issue by stalniy** [porsager/postgres#140]
To illustrate what I mean (silly example that generates error):

```js
sql`
  SELECT CONT(id)::int as amount
  FROM "person"
  WHERE nationality = ${'UK'} and id = ${1}
`
```

This query fails because of typo and the error has `parameters` property. When I check this property, I see this:
 
```js
 [ { type: 0, value: 'UK' }, { type: 0, value: '1' } ]
```

I understand that this is serialized parameters with their data types in Postges but this is not what I passed to `sql` function. So, it's not fine to log something like this into log file (or even in stack trace) because it confuses. I also cannot map values to `value` property because then it looks like I passed string `'1'` to id but I passed a normal number. This becomes even more confusing when we deal with booleans and the value equals to `f` or `t`

`debug` option behaves the same way, I'd like to have a way to get back parameters I passed to `sql` function without writing additional logic on my end to unserialize all of those

**Comment by stalniy** [comment]
@porsager we discussed this in gitter but after that I don't see any commits that address this. That's why decided to create an issue, just to keep this in repo

**Comment by porsager** [comment]
Hi @stalniy 

Good thing you created an issue so we don't loose track of it ;) - And sorry for the late reply.

I think it's a good point, and we should get it fixed for v2.
