### ISSUE TITLE
Connection defaults inconsistent with psql

### ISSUE THREAD

**Issue by lightmare** [porsager/postgres#141]
Minor issue that caused me some head scratches.

There's this example with an inaccurate comment in readme:
```js
const sql = postgres({ ...options }) // will default to the same as psql
```

In `psql`, if you omit database name, it defaults to user name. So `psql -U dummy` connects to database `dummy`, and `PGUSER=funny psql` connects to database `funny`.

`pg (node-postgres)` mimics this behaviour

With this module, if you don't set `PGDATABASE` in env or the corresponding option, it always connects to database `postgres`, ignoring `PGUSER` var.

**Comment by porsager** [comment]
Hey, good catch, thank you. I'll get that fixed for v2.
