### ISSUE TITLE
transaction SET CONSTRAINTS

### ISSUE THREAD

**Issue by joshxyzhimself** [porsager/postgres#146]
Hi, just curious, does the current transaction api support SET CONSTRAINTS?

https://www.postgresql.org/docs/13/sql-set-constraints.html

Thank you :100:

**Comment by porsager** [comment]
Hi @joshxyzhimself :) 

Sorry for the late response. I don't see why it shouldn't support it, there's nothing library specific as this would just be a query by itself at some point in the transactions.

Eg.
```js
sql.begin(sql => [
  sql`insert into x values(1)`,
  sql`set constraints all deferred`,
  sql`insert into x values(2)`
])
```
