### ISSUE TITLE
Database connection problem

### ISSUE THREAD

**Issue by thge** [porsager/postgres#148]
Hi, I'm running a postgres server and an application in two docker containers. Normally this works really fine.

But when I restart my server the application docker container starts up faster than the postgres container and when it tries to connect to the database the first time it cannot reach the server. I wrote a small connection test to wait for the database but unfortunately my app cannot connect to the database after this first failure. 

I understood from your documentation, that after a failed connection the next request should try a new connection automatically, but this doesn't seem to be the case.

I don't know if my usage of the postgres package is the problem or if I need to handle the error in another way.
Here is a simplified version of my code, which shows the problem (using your postgres V1.0.2).

As suggested by your README I have a db.js file to setup the database connection.
```javascript
import postgres from 'postgres';

export const sql = postgres({
  host        : 'postgres',     // Postgres ip address or domain name
  port        : 5432,           // Postgres server port
  database    : 'dbname',    // Name of database to connect to
  username    : 'dbuser',       // Username of database user
  password    : 'dbpass'
});
```
Then I import `db.js` in my application to use the `sql` object, when I need access to the database:
```javascript
import {sql} from "db";

export async function checkDatabase() {
    return sql`SELECT 1 as test WHERE 1 = 1`
            .then(() => console.log("database ok"))
            .catch(err => {
                console.log("select test failed", err);
                setTimeout(checkDatabase, 2000);
    });
}

checkDatabase();
```
If the test fails the first time with "getaddrinfo ENOTFOUND postgres", it keeps failing with this error, even if the postgres server is available later on. After restarting the app it works. Can I force a kind of reconnect in case the connection fails?

BTW: If I create a new sql object in every checkDatabase() call, the test succeeds as soon as the database server is available, but I would prefer to keep the above setup.

**Comment by Minigugus** [comment]
Probably a problem with query cache... What about the beta version of posgres (`npm i postgres@beta`) ?

**Comment by thge** [comment]
> What about the beta version of posgres (`npm i postgres@beta`) ?

I just checked it and the beta version runs fine :) But is it stable enough to run in a production environment?

**Comment by porsager** [comment]
Hi @thge . Sorry I didn't see your last message, but yes - I've been running the beta in production since then. 

With regard to the pg_catalog query, it should only run once, so if you can reproduce this - please create a new issue.

It is also possible to disable fetching types by passing `fetch_types: false` in options.
