### ISSUE TITLE
Is there a way to get SELECT field object keys in camelCase

### ISSUE THREAD

**Issue by IdpugantiSanjay** [porsager/postgres#15]
```
SELECT usernameCount, emailCount FROM 
   (
      SELECT COUNT(username) as usernameCount FROM users WHERE username = ${options.username}
   ) X,
   (
	SELECT COUNT(email) as emailCount FROM users WHERE email = ${options.email}
   ) Y
`
```

Here in the above query even if I specify to get column names ```usernameCount, emailCount```  in camelCase they still get converted into lowercase column names. Is there a way to get column names as specified

**Comment by porsager** [comment]
Hi @IdpugantiSanjay ...

That's case insensitive to PostgreSQL, so you will get it back in lower case.

There are two ways you can solve it. 

- Either you can put the name in quotes like ` as "usernameCount" `

or 

- You can write your query with `snake_case` - eg (` as username_count `), and then have Postgres.js convert any `snake_case` column name to `camelCased` upon retrieval by using the `transform.column` option.
```js
postgres({
  transform: {
    column: postgres.toCamel
  }
})
```

**Comment by Minigugus** [comment]
Be aware of sql injections with ``WHERE username = ${options.username}``, prefer ``WHERE ${sql(options, 'username')}`` for instance :wink:

**Comment by porsager** [comment]
Nono, that's perfectly fine @Minigugus.. That's the entire point of the tagged template call. Those values will be replaced by `$1` and passed as a parameter to Postgres preventing sql injections 😉

**Comment by Minigugus** [comment]
Oops, I forgot (library too amazing)... :smile:  However, `WHERE ${sql(options, 'username')}` is still a shorter approach :wink:

**Comment by porsager** [comment]
Hehe :P 

It might be shorter, but I would very much like that it's not the recommended way to do it :)

**Comment by Minigugus** [comment]
Actually, you're right. It's also easier to pass another operator than `=` :+1:

**Comment by porsager** [comment]
I hope https://github.com/porsager/postgres/issues/15#issuecomment-574048355 answered your questions @IdpugantiSanjay

**Comment by IdpugantiSanjay** [comment]
@porsager Thank you for your time
