### ISSUE TITLE
Recommendations for test database

### ISSUE THREAD

**Issue by brielov** [porsager/postgres#151]
Is there an example for testing? I would like to setup `jest` to run my tests and I'm having trouble coming up with a good solution. I'm currently using `ley` to handle migrations. The idea would be to have a `setupTests` file that creates a new database using something like `nanoid` and drop it after the test concludes, but `postgres` only connects to an existing database, and even if I use something like `pg` to connect to the postgres database and then create a new one, `postgres` seem to try to connect to the yet-to-be-created database before setup because of import order. Does somebody has a recommendation for how to handle this scenario?

**Comment by porsager** [comment]
How about something like `require('child_process').execSync('createdb testdb')` and then after `require('child_process').execSync('drop testdb')`? You can replace the name with something from nanoid if you want to.

You can also just have 2 postgres instances where one is connected to the `postgres` db, and then create / drop through that one.

Btw. Postgres.js connects lazily. That means it won't connect until you make your first query.

**Comment by brielov** [comment]
@porsager Thanks man, I'll try that today. Awesome work by the way.

**Comment by brielov** [comment]
This is how it looks like in the end and it works perfectly. Closing this now.

```typescript
import "dotenv/config";

import { createHttpTestBed, createTestBedSetup } from "@marblejs/testing";
import { execSync } from "child_process";
import { up as migrate } from "ley";
import { nanoid } from "nanoid";

import { listener } from "./http.listener";

const testBed = createHttpTestBed({
  listener,
  defaultHeaders: {},
});

export const useTestBedSetup = createTestBedSetup({
  testBed,
  dependencies: [],
  cleanups: [],
});

const database = `test_${nanoid()}`;
process.env.PGDATABASE = database;

// Create a temporary test database
beforeAll(async () => {
  execSync(`createdb ${database}`);
  await migrate({
    dir: "migrations",
    driver: "postgres",
  });
});

// Drop test database
afterAll(() => execSync(`dropdb ${database}`));
```

**Comment by porsager** [comment]
You're welcome. Thanks a lot for posting your result - might be useful to others 👍

And thank you for the kind words too.
