### ISSUE TITLE
v2.0.0 [BUG] sql`select ${null} is null and ${null} is null;`

### ISSUE THREAD

**Issue by mortifia** [porsager/postgres#153]
```js
sql`select ${null} is null and ${null} is null;`
```

error code : 42P18
error msg : could not determine the data type of parameter $1

**Comment by mortifia** [comment]
bug only with null

tested with :
'1'
1
true
null

**Comment by porsager** [comment]
PostgreSQL can't know the type of the parameter when preparing the statement. This only happens if you're doing `is null` because there is no column to infer the type from.

To make it work you need to add an explicit type:

```js
sql`select ${null}::int is null and ${null}::int is null;`
```
