### ISSUE TITLE
listen/notify doesn't work if channel name contains uppercase letter

### ISSUE THREAD

**Issue by stalniy** [porsager/postgres#157]
## Example

```ts
await sql.listen('cacheInvalidated', (payload) => {
  console.log(process.pid, ' -> ', payload);
});

await sql.notify('cacheInvalidated', 'test');
```

## Cause

This is due to improper escaping of channel during `listen` command execution. Postgres.js sends `listen cacheInvalidated` but should instead send `listen "cacheInvalidated"` (pay attention at double quotes).

**Comment by eugene1g** [comment]
Ah yes, hello case-sensitivity. Every so often we hit the same issue with column/property names in analytics queries, and even file names in the source code. Good catch!
