### ISSUE TITLE
timestamptz as strings instead of Date objects

### ISSUE THREAD

**Issue by joshxyzhimself** [porsager/postgres#161]
Hi,

Is it possible to have `timestamptz` types be returned as strings instead of Date objects?

Reason for this is we using `luxon` (https://moment.github.io/luxon/) to work with ISODateTime strings and all our insert values are valid ISODateTime strings, hence we are also expecting return values to be strings.

We can do `x instanceof Date` checks and `x.toISOString()` conversion, and thinking to just modify the `types.date.parse` function at https://github.com/porsager/postgres/blob/master/lib/types.js#L29-L33,

from

```js
parse: x => new Date(x),
```

to

```js
parse: x => x,
```

is it the right thing to do?

**Comment by porsager** [comment]
Hey @joshxyzhimself 

Yeah, it makes sense to not cast postgres timestamps automatically. You also loose sub millisecond precision, which you might want at times.

To handle this on a per-query base you should simply cast to ::text from postgres like this
```js
sql`
  select
    some_timestamp::text
  from some_table
`
```

or if you want per connnection you should do this:

```js
const sql = postgres({
  types: {
    date: {
      to: 1184,
      from: [1082, 1083, 1114, 1184],
      serialize: x => x, // Serialize Luxon / Date object to a string somehow
      parse: x => x // Just pass the text value or parse with Luxon
    }
  }
}) 
```

You should hopefully never have to change Postgres.js internal code ;)

**Comment by porsager** [comment]
I hope this worked for you @joshxyzhimself , but if not, feel free to reopen.

**Comment by joshxyzhimself** [comment]
Hi @porsager, thank you it worked!

Just learned too that postgres returns timestamptz strings in SQL format, which required us to use `luxon.fromSQL(value)`.

- https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromSQL

Also, it's surprising that JavaScript's `new Date(value)` constructor parses SQL formats too, which isn't documented at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date (only says RFC 2822 and ISO 8601).

**Comment by uasan** [comment]
Try
```SQL
SELECT to_json('2021-04-23 18:30:00+08'::timestamp);
```
Result:
```
2021-04-23T18:30:00
```
