### ISSUE TITLE
sql.begin() : UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by throrin19** [porsager/postgres#162]
If `sql.begin` is called and throw error (database not reachable, impossible to connect, ...), the error is not able to be captured by `try`/`catch`.

Example : I try to run this sql script but the sql server is not available (I don't run the service) : 

```js
try {
    const sql = postgres(config);

    await sql.begin(async (sql) => {
        await sql`insert into test (label, value) values (${measure.label}, ${measure.value})`
    });

    await sql.end();
} catch (err) {
    console.log('error catched');
    console.error(err);
}
```

Code inside `sql.begin` and after it is never called and the catch part is never called. Otherwise we got this nodeJS error :  

```
(node:13328) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:13328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

## Informations

- Node.js version : `14.15.4`
- postgres version : `1.0.2`

**Comment by porsager** [comment]
Hi Thorin.

Thanks for the report.

Would you mind checking with postgres@beta ?

If that works we could backport the fix.

**Comment by porsager** [comment]
Ok, I just tested myself, and the issue is also present on `master`. I'll look into it.
