### ISSUE TITLE
Syntax to release a connection rather than kill the pool?

### ISSUE THREAD

**Issue by kingram6865** [porsager/postgres#163]
I don't see the command to release a connection once a db call is completed.
is <>.end() the only option? That doesn't make sense. When I use that one I can't make any other db calls. The pool is gone.

**Comment by porsager** [comment]
There is no manual handling of connections, unless you create a separate postgres instance with `max: 1` like `postgres({ max: 1 })` and call `.end()` on that.

You can also set `idle_timeout` so that connections are closed automatically after a set period of inactivity.

**Comment by porsager** [comment]
Feel free to reopen if you think there's a better way to achieve this or if I misunderstood your question 🙂

**Comment by kingram6865** [comment]
> Feel free to reopen if you think there's a better way to achieve this or if I misunderstood your question

You got it. I hear, understand and comprehend.
