### ISSUE TITLE
create table support

### ISSUE THREAD

**Issue by lexmarionB** [porsager/postgres#166]
New to PostgreSQL and was using MySQL before. I am currently rewriting a script I wrote years back which handled the creation of the database and its tables for MySQL by defining its columns and data types. This came about when I was unable to access the database from my machine. It came pretty handy in the years that followed since I no longer need to set up the database manually myself.

I've got passed the hurdle of creating the database with code by taking advantage of dynamic table names described in the documentation.
```
sql`CREATE DATABASE ${ sql(database) }`
```

I am trying to create a simple table from code to test with the following object containing the field name paired to their data type.
```
{
    id: "SERIAL NOT NULL PRIMARY KEY",
    date_created: "timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP"
}
```
I honestly have no clue how to do this, but I did try a few things. No luck. Is this even possible?
```
sql`CREATE TABLE IF NOT EXISTS ${ sql(table) } (${ sql(fields) })`
``` 
Doesn't work, I know now. I can't figure out a way to insert the proper clause without it being sanitized to a quoted string.

**Comment by porsager** [comment]
Hi @lexmarionB 

I imagine you might have been using an ORM with MySQL previously. 

Postgres.js embraces pure SQL so you write as little as JS, and the most in SQL.

Your example above would look like this with no js interpolation:

```js
sql`
create table users (
  user_id        serial primary key, 
  date_created   timerstamptz not null default now()
)
`
```

Some things to note. 
- the table name is `users` in my example
- `timestamptz` is timestamp with time zone and almost always better than without (`timestamp`)
- `not null` is not required with `primary key`
- `now()` is the same as `current_timestamp`

**Comment by lexmarionB** [comment]
No, I was not using an ORM with MySQL. I wrote a script myself years before to handle the creation and synchronization of a database and its tables. I'm looking into rewriting the script for use with Postgres, if at all possible.

So my case goes on the opposite direction, more JS less static SQL. For example given the following object defining a table's columns and its types:
```
var columns = {
    user_id: "serial primary key",
    date_created: "timestamp not null default now()"
}
```
Is there a way to somehow insert that to a `CREATE TABLE users` query?

**Comment by porsager** [comment]
Ah, I see.

I would change that to actual SQL then 🙂

**Comment by lexmarionB** [comment]
I see. It is unfortunate.

**Comment by Minigugus** [comment]
@lexmarionB What about writing a `.sql` file on the fly with your script and run it with `sql.file('your_file.sql')`? If your script don't use unsanitized users data, it's not really unsafe :wink:

**Comment by sduwal** [comment]
> Hi @lexmarionB
> 
> I imagine you might have been using an ORM with MySQL previously.
> 
> Postgres.js embraces pure SQL so you write as little as JS, and the most in SQL.
> 
> Your example above would look like this with no js interpolation:
> 
> ```js
> sql`
> create table users (
>   user_id        serial primary key, 
>   date_created   timerstamptz not null default now()
> )
> `
> ```
> 
> Some things to note.
> 
> * the table name is `users` in my example
> * `timestamptz` is timestamp with time zone and almost always better than without (`timestamp`)
> * `not null` is not required with `primary key`
> * `now()` is the same as `current_timestamp`

Does it work if the table name is passed as a variable such as `....create table ${table_name}`. I am currently getting this error when I do so:
` syntax error at or near "$1"`

**Comment by porsager** [comment]
Yeah, I don't see why @lexmarionB couldn't just go with `sql.unsafe` and generate the queries from JS himself when he knows there's no user input. It would make little sense to support his specific js to sql syntax in a library like this, when it probably wouldn't be of any use to anyone else, and a userland implementation is trivial.
