### ISSUE TITLE
String escaping not working

### ISSUE THREAD

**Issue by B-3PO** [porsager/postgres#169]
I am able to write this `<img src onerror="alert('hi')">` to the database. Also i cannot get to my variables in either to row or value transformers. I am using version 1.0.2. Below is the query i am using

```javascript
const created = await sql`
    INSERT INTO accountable (
      uuid,
      identifier,
      email,
      password,
      first_name,
      last_name,
      admin,
      organization_id
    ) VALUES (
      ${userUUID},
      ${identifier},
      ${email},
      ${hash},
      ${first_name}, // <img src onerror="alert('hi')"> VARCHAR
      ${last_name},
      ${admin || false},
      ${organization.id},
    )
    RETURNING id
  `;
```

**Comment by B-3PO** [comment]
It appears that the input value is the culprit for the transformer not working

**Comment by porsager** [comment]
I'm, sorry, but postgres does not do any kind of XSS input sanitizing for you, and it's not its purpose.

It helps you against SQL injection. 

Would you mind try to describe how you got that impression? Then we can see if the docs need to be more clear.
