### ISSUE TITLE
SSL connectivity issues

### ISSUE THREAD

**Issue by didinele** [porsager/postgres#177]
This seems to be an issue introduced in https://github.com/porsager/postgres/commit/0cb2981016356d0ec18a73b2aee12af76f2c0b96 (or somewhere in `2.0.0-beta.5`) where using a URL for connecting (i.e `postgres(urlHere)`) works in unexpected manners when it comes to the `sslmode` query parameter.

Before beta 5 `postgres://user:password@host:port/db?sslmode=disable` worked just fine.
On beta 5 this leads into any query rejecting with `"Server does not support SSL"`.

I'm not entirely certain if this was intended but nevertheless, it is very breaking.

Interestingly enough, a work-around I found was making the `m` uppercase, so `?sslMode=disable` worked fine.

**Comment by porsager** [comment]
Ah thank you. Before `sslmode=disable` wouldn't do anything, but after implementing sslmode=required, the presence of it, even thought it's the string `disabled` becomes truthy.. I will make a fix asap.

**Comment by iby** [comment]
@porsager v2.0.0-beta.6 this doesn't seem to be working as expected with the following error:

```
      Error: the string "Server does not support SSL" was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Seems like there's a typo, it should be `disable` not `disabled`:

https://github.com/porsager/postgres/blob/e3ace38fcc20670239e3b00ea42b11d16153bd7d/lib/index.js#L578

Get the following when trying to use dbmate:

```
Error: pq: unsupported sslmode "disabled"; only "require" (default), "verify-full", "verify-ca", and "disable" supported
```

The [official docs](https://www.postgresql.org/docs/13/libpq-ssl.html) also use `disable` not `disabled.
