### ISSUE TITLE
row mode equvalent?

### ISSUE THREAD

**Issue by hellower** [porsager/postgres#18]
equivalent options exist?
sorry for poor english.
------------------
https://node-postgres.com/features/queries

**Row mode**
By default node-postgres reads rows and collects them into JavaScript objects with the keys matching the column names and the values matching the corresponding row value for each column. If you do not need or do not want this behavior you can pass rowMode: 'array' to a query object. This will inform the result parser to bypass collecting rows into a JavaScript object, and instead will return each row as an array of values.

**Comment by porsager** [comment]
Hi @hellower .. Your english is just fine to me 👍 I'm also a non-native speaker..

If you just need the values you can do like this:

```
const sql = postgres({
  transform: {
    row: x => Object.values(x)
  }
})
```

I have been considering exposing the columns on the result object too, but currently they are not. If I did that the above would give you the same setup.

I'm curious to hear about your use case, would you mind sharing?

**Comment by hellower** [comment]
Thans for you reply.

We received the result in json  format and convert it to  datagrid in my application.
So we need a list of column names.

Butg, When there are many rows, json size is too big!!
So I considering row mode not json format.
