### ISSUE TITLE
Cockroachdb support

### ISSUE THREAD

**Issue by ansarizafar** [porsager/postgres#183]
Is there any plan to support Cockroachdb https://www.cockroachlabs.com/

**Comment by Minigugus** [comment]
@ansarizafar According to https://www.cockroachlabs.com/docs/v21.1/postgresql-compatibility.html, `postgres` should already be compatible (`postgres` implements the Postgresql wire protocol)

**Comment by porsager** [comment]
Correct @minigugus - Should work already.. If there's something that doesn't work because of this library, feel free to reopen or create a new issue.
