### ISSUE TITLE
Return value from `sql` is really confusing 

### ISSUE THREAD

**Issue by Adidi** [porsager/postgres#186]
If you perform simple select
```js
        const data = await sql`SELECT * FROM users';
```
`data` is an array where the first elements are the rows and then there is `count`, `columns`, `command`, `state` 
if you want to extract only the data to return it for example in a rest api call as the output of the request you need to use spread or some other hacky stuff
and also you use `array` as an object with keys on it (like count columns etc...)
why not always return an object and the data will be separated with the unique key like this:
```js
{
    rows: [...sql row data],
    count: 10,
    columsn: ...
    ....
}
```

This way we can take the data with the specific key `rows` and also it won't break any change in the future if you want to replace the response.

**Comment by porsager** [comment]
Check out https://github.com/porsager/postgres/issues/147 ;)

**Comment by Adidi** [comment]
Its not only relate to logging - think that you want to return whatever you get from the database to a different provider - then u have to inject the data rows and then return it - really inconvenience.
all this mixed up of properties inside an array! is not good API - why just use an object with specific keys then u won't have any of this problem ?

**Comment by porsager** [comment]
Did you read the linked issue? I can't imagine any place you pass the result would care about those properties if they expect an array. If so, I'd love to know.

I think you misunderstand how arrays and objects in JavaScript works. Those properties are not in the array. If you do eg. `JSON.stringify` they won't be included either.
