### ISSUE TITLE
Rewrite library using TypeScript

### ISSUE THREAD

**Issue by maxpain** [porsager/postgres#187]
Why is this library still not type-safe?

**Comment by porsager** [comment]
Haven't had time to finish v2, but you can give it a try with `npm install postgres@beta`.

**Comment by maxpain** [comment]
> Haven't had time to finish v2, but you can give it a try with `npm install postgres@beta`.

Yes, I already tried and it is a much more feature-rich postgres library than `node-pg`, especially for built-in transactions support, SQL tag, etc. Thank you for the awesome project.

I know that v2 has typescript definitions for API. I mean why not rewrite the entire library to TypeScript? It will be much more stable and will have less bugs.

**Comment by maxpain** [comment]
> Haven't had time to finish v2, but you can give it a try with `npm install postgres@beta`.

@porsager 

Yes, I already tried and it is a much more feature-rich postgres library than `node-pg`, especially for built-in transactions support, SQL tag, **usable stacktraces**, query/parameter fields in errors, etc. Thank you for the awesome project.

I know that v2 has typescript definitions for API. I mean why not rewrite the entire library to TypeScript? It will be much more stable and will have fewer bugs.

**Comment by porsager** [comment]
Ah, that's because I don't like Typescript 😉 

@Minigugus has made the Typescript definitions, which probably wouldn't have been there if it wasn't for him.

**Comment by maxpain** [comment]
@porsager maybe I can make Merge Request for this?

**Comment by porsager** [comment]
No, I don't want to convert to Typescript.

A fork / new library is the way to go if you want it.

**Comment by maxpain** [comment]
> Ah, that's because I don't like Typescript 😉

Could you please describe any reasons?

**Comment by maxpain** [comment]
@porsager Got it.

**Comment by porsager** [comment]
Sorry, but I'd like to spend the little free time I have for my projects actually working on them. Starting a talk about why I don't like Typescript just eats off of that time. If you're ever in Copenhagen, I'd maybe do it over a beer 😉
