### ISSUE TITLE
Select with list of fields from an array doesn't work with fields including a dot

### ISSUE THREAD

**Issue by mohe2015** [porsager/postgres#188]
Code similar to the following doesn't work:
```typescript
sql`SELECT ${sql(["projects.id"])} FROM projects`
```
because this generates:
```sql
SELECT "projects.id" FROM projects;
```
which is not valid for postgresql

**Comment by porsager** [comment]
Are you trying to select the key `id` from a json object in the `projects` column?

**Comment by mohe2015** [comment]
No, I'm trying to select the id column from the projects table. So just using the explicit syntax where you specify the column name also.

**Comment by mohe2015** [comment]
In theory useful for:
`SELECT projects.id, users.id FROM projects, users;`

**Comment by porsager** [comment]
Ah right, of course 👍 

There should definitely be a way to do that.. If just make it work as you tried there we'd break anyone with periods in their column names, but I kind of feel that's ok?

**Comment by mohe2015** [comment]
I would assume the problem is sql injection but I don't know. The correct way to do this with arbitrary names (excluding ones containing a dot) is `SELECT "projects"."id" FROM projects;`

I would assume that a dot is such a strange thing in a column name that it should be fine. Should still be noted in the release notes of course.

**Comment by mohe2015** [comment]
I don't need this feature currently so if nobody else needs it it may be worth to wait until the dynamic queries feature is more finished and maybe it's then build in there

**Comment by ersinakinci** [comment]
I would very much like to see this implemented, as would https://github.com/porsager/postgres/issues/731.

Is there a workaround?
