### ISSUE TITLE
Accept raw result without parsing JSON

### ISSUE THREAD

**Issue by uasan** [porsager/postgres#194]
Hello.
We have many endpoints that do not need to parse the json type and receive it as an object, because these endpoints send this `values` as a `JSON.stringify(values)` to the client socket.
```SQL
SELECT json_agg(values) AS values FROM ...
```
In this case, two expensive blocked operations, `JSON.parse` and `JSON.stringify`, are constantly performed.
Ideally, I would like to be able to receive the response in the form of a binary buffer, without parsing json, to send this buffer to the client.

How do you like the idea?
Thanks.

**Comment by porsager** [comment]
It's right along what I just played with regarding sending bytea as binary, the issue is deciding return results as binary or text or mixed.

I'll play a bit more with it, but until then you could get a long way simply casting json(b) to text in your query `::text` and passing it directly.

**Comment by porsager** [comment]
You can also override the json types and set the serializer to null which will disable JSON.parse

**Comment by uasan** [comment]
> I'll play a bit more with it, but until then you could get a long way simply casting json(b) to text in your query ::text and passing it directly.

I know about this ugly hack )

> You can also override the json types and set the serializer to null which will disable JSON.parse

I can do this, only for some queries, or only settings for the connection?

**Comment by porsager** [comment]
`types` are set per instance.

Why do you find casting to text ugly? Now I'm curious if there's any overhead compared to skipping JSON.parse 😋

**Comment by uasan** [comment]
1. because I have to edit the original queries
2. this will worsen the understanding of the SQL code for people who will support it and there may be a situation when I need to execute the same prepared request in different places and somewhere I want to get the result in the form of an object, I will have to call JSON.parse there )

**Comment by porsager** [comment]
That sounds reasonable.

How about adding the following?
```js
await sql`select 1 as x, 2 as x`.raw()
```

That would return this result: 
```
[ <Buffer 31>, <Buffer 32> ],
columns: [
  { name: 'x', parser: [Function: parse], type: 23 },
  { name: 'x', parser: [Function: parse], type: 23 }
]
```

This would help some other requests as well who wanted rows as arrays instead of objects, and allow same named columns to be retrieved.

**Comment by uasan** [comment]
Great, I like your interfaces

**Comment by porsager** [comment]
Would you mind trying out the #raw branch to see if it works well for you?

**Comment by uasan** [comment]
How about `unsafe` method, how to get buffer?

**Comment by porsager** [comment]
Same way :) the methods on a tagged query and an unsafe query are the same:
```js
sql.unsafe('select '{"a":"b"}'::jsonb').raw()
```

**Comment by uasan** [comment]
> Would you mind trying out the #raw branch to see if it works well for you?

I checked in my test version:
```JS
const [[value]] = await sql`SELECT '{"key": "value"}'::jsonb`.raw()
console.log(JSON.parse(value))
```
Everything works fine, thanks!

P.S.
Unfortunately, I cannot check the performance in real conditions, we do not have enough of this functionality for production
https://github.com/porsager/postgres/issues/170

**Comment by porsager** [comment]
I still need some improvements around connection handling, but copy from / to works now https://github.com/porsager/postgres/tree/copy
