### ISSUE TITLE
Multiple statements triggering transaction

### ISSUE THREAD

**Issue by JAForbes** [porsager/postgres#198]
I've been experimenting with using postgres.js for migrations, and so far it's been really great!  

I'm trying to convert some psql migrations to postgres.js, and the moment I execute multiple statements within sql.unsafe a an implicit transaction is introduced.  

I can't seem to isolate to any code in postgres.js, and I'm completely stumped as to what the cause may be.

Here's a sample I've been using to repro this.

```
import pg from 'postgres'
const sql = pg('postgres://postgres@localhost/example')

await sql.unsafe`
	CREATE INDEX CONCURRENTLY fki_contracts_organizations_disciplines ON public.contract_items USING btree (organizations_disciplines_id);
`

await sql.end()
```

The above will work fine, but the moment I add a second `CREATE INDEX` to the `unsafe`, I get the following error:

>  PostgresError: CREATE INDEX CONCURRENTLY cannot run inside a transaction block

Which makes complete sense, there are some statements that can't be run in a transaction, except, I didn't use `sql.begin` so I'm not sure how a transaction was introduced.

E.g. here's a sample I used to introduce that error:

```js
import pg from 'postgres'
const sql = pg('postgres://postgres@localhost/prod')

await sql.unsafe`
	CREATE INDEX CONCURRENTLY fki_contracts_organizations_disciplines ON public.contract_items USING btree (organizations_disciplines_id);
	CREATE INDEX CONCURRENTLY fki_project_extras_projects ON public.project_extras USING btree (project_id);
`

await sql.end()
```

This seems to happen if I add any 2nd statement, e.g. if I add `select 1;` as the second statement, I get the same error.

Apologies if I'm missing something very obvious!

----

I should've noted, I'm seeing this on v1 and v2.0.0-beta.6

**Comment by porsager** [comment]
Hey James.

The PostgreSQL protocol distinguishes between simple queries, and extended queries. Simple queries are only used by default in Postgres.js when you make unsafe queries without any arguments (simple queries cannot be prepared, and cannot take any dynamic arguments), but you are allowed to have multiple statements in a simple query, with the caveat that PostgreSQL will [automatically wrap them in a transaction for you](https://www.postgresql.org/docs/11/protocol-flow.html#PROTOCOL-FLOW-MULTI-STATEMENT). 

The solution is to split each statement into it's own query, and then you don't need `unsafe` either.

```js
import pg from 'postgres'
const sql = pg('postgres://postgres@localhost/prod')

await sql`CREATE INDEX CONCURRENTLY fki_contracts_organizations_disciplines ON public.contract_items USING btree (organizations_disciplines_id);`
await sql`CREATE INDEX CONCURRENTLY fki_project_extras_projects ON public.project_extras USING btree (project_id);`

await sql.end()
```

**Comment by JAForbes** [comment]
Ah wow I had no idea, thanks so much.

I was hoping to avoid individually awaiting each statement mainly because I was porting older large psql script files over, but that makes sense.

**Comment by porsager** [comment]
Ah I see. You could set max connections to 1. Which would ensure queries are sent in order.

**Comment by JAForbes** [comment]
That's a great tip, probably the must logical setting for a migration as well.
