### ISSUE TITLE
Is metadata on the response array part of the public API?

### ISSUE THREAD

**Issue by JAForbes** [porsager/postgres#200]
I noticed the returned array from a query has a few super useful properties e.g. (`count`, `columns`).

I'm wondering if I can rely upon those metadata properties on the array staying around, or if this is more of an internal thing I shouldn't rely on for anything beyond debugging.

I can imagine all kinds of uses for those fields.

Thanks in advance!

**Comment by porsager** [comment]
It sure is, and it's going to stay, [even though it has lead to some confussion](https://github.com/porsager/postgres/issues/186).

It's mentioned in the docs, although almost invisibly at the first line of https://github.com/porsager/postgres#query-sql----promise.

Re-reading that I see it was even wrong, so just fixed `rows -> count`.

**Comment by JAForbes** [comment]
Hey that's great!  Thank you!
