### ISSUE TITLE
sql.savepoint as tagged template function?

### ISSUE THREAD

**Issue by JAForbes** [porsager/postgres#201]
I imagine `savepoint` will often be used for a single query.  Would it make sense to offer sql.savepoint as both a callback and a tagged template function?

E.g.

```js
let unavailable;
sql.savepoint`insert into users(username) ${username}`.catch( () => unavailable = true )
```

vs

```js
let unavailable;
sql.savepoint( sql => sql`insert into users(username) ${username}` ).catch( () => unavailable = true )
```

It might not be worth the sugar, but I thought I'd mention the idea because all my savepoint usages so far had been for a single query.

**Comment by porsager** [comment]
Yeah, that makes sense, but it breaks a bit with trying to keep queries inside a `sql` named tagged function. 

The reason for keeping SQL syntax only in `sql` named tagged functions is to help eg. syntax highlighters, and also (my own usage), searching for ``` sql` ``` will show me all SQL queries.

How about ``` sql``.savepoint() ``` instead perhaps?

**Comment by JAForbes** [comment]
Yeah way better 👏
