### ISSUE TITLE
Add quotes around column names/table names

### ISSUE THREAD

**Issue by tamino-martinius** [porsager/postgres#21]
Postgres supports camel cased column and table names - but only when you quote your table/column names. Same for column names which use reserved words - they also need to be quoted.
```
sql`SELECT * from ${sql('tableName')} where ${sql({firstName: 'John'})}`
```
This generates the sql query `SELECT * from tableName where firstName = $1`
Which will fail if you used camelCased names while creating the table
`SELECT * from "tableName" where "firstName" = $1` would be the expected query.

Not that important, but also related and unexpected is that dollar quoted names become quoted
```
sql`SELECT * from ${sql('$$table_name$$')} where ${sql({firstName: 'John'})}`
```
This generates the sql query `SELECT * from "$$table_name$$" where firstName = $1`
Which will fail as `$$` are already quotes
`SELECT * from $$table_name$$ where "firstName" = $1` would be the expected query.

**Comment by porsager** [comment]
Ah yes, that's a very interesting gotcha. So you are correct - currently it only adds `"` if necessary because you might be trying to use it for an sql keyword, and there you wouldn't want `"` added.

Unfortunately I don't see a way currently to handle this without it being ambiguous, so I'll have to think about it some more.

Maybe fixing your second point about dollar quoted strings could be a solution so that it could be used instead. 

Still it's not as elegant as I'd like.

**Comment by tamino-martinius** [comment]
I would suggest to have a separate escape for identifiers and column names quoted by default
```
sql`SELECT * from ${sql.identifier('tableName')} where ${sql({firstName: 'John'})}`
```
=> `SELECT * from "tableName" where "firstName" = $1`
```
sql`SELECT * from ${sql.identifier('schema.tableName')} where ${sql({firstName: 'John'})}`
```
=> `SELECT * from "schema"."tableName" where "firstName" = $1`

**Comment by porsager** [comment]
Yes, that's probably the way to go :)

**Comment by porsager** [comment]
I'll include these considerations when making better query composition. I'll track the work in #12 ;)

**Comment by MartinPavlik** [comment]
Hi, any update on this? I really like this library but being not able to use camelCase names of columns/tables is blocking me from using it in some projects that can not be easily migrated.

Any suggestion for a simple work-around?

Btw what is the problem that all column/table names can not be always wrapped with double quotes?

Thanks :+1:

**Comment by porsager** [comment]
Hi @MartinPavlik . This is fixed in master ;)
