### ISSUE TITLE
How to insert value into jsonpath?

### ISSUE THREAD

**Issue by ulvidamirli** [porsager/postgres#213]
I'm a `node-postgres` user looking for a new library with better `JSON path` support.

You can look at the problem I recently run into [here](https://github.com/brianc/node-postgres/issues/2598).

Simply saying I need to insert value coming from the client into $1 (without SQL/JSON Path injection risk):

```
SELECT items.discount
FROM items
WHERE items.discount @? '$[*] ? (@.discount[*].shift == $1)'
```

Before starting, I would like to know how it is done in `Postgres.js`. Do I need to use a workaround code in `Postgres.js` as well?

**Comment by porsager** [comment]
There's nothing specific for jsonpath in Postgres.js, but if we come up with something reasonable I would consider to include it.

You could already now do something like the following, which I think is actually not that bad?

Add a jsonpath `sql.$` tagged template function for use everywhere. This will ensure all arguments in jsonpaths are put through `JSON.stringify`.
### db.js
```js
const sql = postgres({ ... })
sql.$ = (xs, ...args) => '$' + xs.reduce((acc, x, i) => acc + JSON.stringify(args[i - 1]) + x)
// 
```

### route.js
```js
app.get("/items/:data", (req, res, next) => {
  sql`
    select items.discount
    from items
    where items.discount @? ${ 
      sql.$`[*] ? (@.discount[*].shift == ${ req.params.data })` 
    }
  `.then(
    ([x]) => res.json(x),
    next
  )
});
```

Let me know what you think? 🙂

This is all assuming it's enough to `JSON.stringify` any jsonpath arguments to avoid injection of unwanted jsonpath logic.

**Comment by ulvidamirli** [comment]
Thank you for the solution! I think it is very convenient to use it like that. I really like `Postgres.js`. Thank you again for your fast response and explanation 👍
