### ISSUE TITLE
Undefined backend.query.result object

### ISSUE THREAD

**Issue by adilumer** [porsager/postgres#215]
Recently, something unexpected happened. I was monitoring system logs and I came across a few of these:

uncaught exception: TypeError: Cannot read property 'result' of undefined
at Object.RowDescription (.../node_modules/postgres/lib/backend.js:175:23)
at Socket.data (.../node_modules/postgres/lib/connection.js:167:25)
at Socket.emit (events.js:375:28)
at addChunk (internal/streams/readable.js:290:12)
at readableAddChunk (internal/streams/readable.js:265:9)
at Socket.Readable.push (internal/streams/readable.js:204:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

At first, I thought it was an issue with my code, but it seems everything is happening after I have made the call to the postgres module and before I have received anything back. Interestingly, I couldn't co-relate the events, but it seems that for some reason, the backend.query.result turns out to be undefined. I do have adequate system resource and connections reserved for the DB and the events do not seem to have happened because of choking due to high traffic.

If this is virtually improbable to occur, please let me know where I might need to look. 
And If there is a possibility that backend.query object could have some things going undefined, might I suggest optional chaining, something like 
```
if (backend?.query?.result?.command) {     //(postgres/lib/backend.js:175)
```
I don't know, I might be off by a lot here. Thanks for any help.

**Comment by joshxyzhimself** [comment]
hi @adilumer what version are you on?

**Comment by adilumer** [comment]
varsion 1.0.2

**Comment by adilumer** [comment]
I still don't know what caused the hiccup, but something has changed and not on the this module's side. I haven't seen the same error message for last 6 days and I have been monitoring the logs like crazy. Perhaps it was too many synchronous calls to the same function? bad promise handling? I'd never know, as I doubt I'll have enough time to ravel out everything. 

Sorry for taking the time of whoever had to look into it. I am closing this issue for now. Will bother again if have the same problem in other projects/irrelevant code and I am able to provide more details, thanks.
