### ISSUE TITLE
How to use the pgcrypto module with this package?

### ISSUE THREAD

**Issue by alexbode** [porsager/postgres#219]
https://www.postgresql.org/docs/9.4/pgcrypto.html

Can the pgcrypto module be used?

I am interested in hashing passwords in a users table during insertion, how should that be done with this package?

**Comment by porsager** [comment]
Surely 🙂 There's nothing client library specific to doing that. So Postgres.js will be just as fine as any other client in that regard 😉

Now for the PostgreSQL specific parts you could do it using triggers like this:

### Schema setup
```
create table users (
  username text,
  password text
);

create or replace function hash_password() returns trigger as
$$
begin
  new.password := crypt(new.password, gen_salt('bf', 8));
  return new;
end;
$$ language plpgsql;

create trigger hash_password before insert or update of password on users for each row execute procedure hash_password();
```

### Check password (login etc.)
```js
const [user] = await sql`
  select
    username
  from users
  where username = ${ username } 
    and password = crypt(${ password }, password)
`
```

Hope that gets you going - the above would probably need some more to be ready for production, but the basics should be there ☺️

**Comment by alexbode** [comment]
Thanks for the example, I got it working.
