### ISSUE TITLE
methods Buffer.utf8Write and Buffer.utf8slice do not exist

### ISSUE THREAD

**Issue by fjf2002** [porsager/postgres#22]
According to 
- the docs at https://nodejs.org/api/buffer.html
- the https://github.com/feross/buffer source code,

there are no methods Buffer.utf8Write and Buffer.utf8slice .

Please replace your calls to
- `Buffer.utf8Write`by https://nodejs.org/api/buffer.html#buffer_buf_write_string_offset_length_encoding
- `Buffer.utf8slice` by https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end

Thank you! Then your package is not just conforming to the nodejs Buffer API, but also seems to work client-side using browserify and net-browserify package.

**Comment by porsager** [comment]
Hehe.. Good point. I tried just to get the shortest path when aiming for performance initially, but there is no measurable difference in my benchmarks now, so I'll use the documented methods instead.

**Comment by fjf2002** [comment]
Thank you, that was fast!
