### ISSUE TITLE
Support ParameterDescription (statement variant)

### ISSUE THREAD

**Issue by uasan** [porsager/postgres#221]
Hello.

The documentation says:
> The Describe message (statement variant) specifies the name of an existing prepared statement (or an empty string for the unnamed prepared statement). The response is a ParameterDescription message describing the parameters needed by the statement
https://www.postgresql.org/docs/13/protocol-flow.html

This means that you will get a list of the types of all input parameters.
Then you just need to encode all the input parameters in accordance with the types that you received from this response.

Then this query will work correctly:
```JS
sql`SELECT ${[1, 2, 3]}::int[]`
```

**Comment by porsager** [comment]
Yeah, doing that only once per prepared statement would be very little overhead, so that's a cool idea!

**Comment by uasan** [comment]
You do not need to make an additional request for Describe.
You just need to change the current flow of requests, on such:
```
send Parse sql
send Describe 'S'
receive RowDescription - save result for reuse
receive ParameterDescription - save result for reuse
send Bind
send Execute
```
In response `ParameterDescription` - all oid for type params.
Users will not need to use helper methods such as `sql.json()`, `sql.array()` ...
