### ISSUE TITLE
Make PostgresError available in module

### ISSUE THREAD

**Issue by iby** [porsager/postgres#226]
I need to access `PostgresError` to run violation checks. Right now it's declared like below along with case transformers.

```ts
declare namespace postgres {
  type PostgresError = PostgresErrorType
  function toPascal(str: string): string;
  function toCamel(str: string): string;
⠇
```

Case transformers are directly available in the import, but `PostgresError` isn't. It's only available via an existing sql connection, which is really inconvenient to access in a helper file where it doesn't exist.

```ts
console.log(postgres.toCamel);                  // [Function (anonymous)]
console.log(postgres.prototype.PostgresError);  // undefined
console.log(error instanceof sql.PostgresError); // true
```

Can `PostgresError` be exposed directly and made easily accessible in the module? Perhaps there are other handy types in the same situation?

**Comment by porsager** [comment]
You're right. It would make sense to expose it on the exported `postgres` function too. :) PR is welcome for adding `postgres.PostgresError`, but if not I can quickly add it one of these days.
