### ISSUE TITLE
Allow adding helper methods

### ISSUE THREAD

**Issue by dizlexik** [porsager/postgres#23]
I find the more I use this library the more I'd like for there to be a way that I could augment `sql` with common helper methods that I use frequently. For example, instead of importing helper functions throughout my code and calling them like `checkTableExists(sql, 'my_table')` it would be a lot nicer to be able to add that to `sql` and do something like `sql.checkTableExists('my_table')`, or perhaps `sql.helpers.checkTableExists('my_table')`. I know it's trivial to set up the second example by doing `sql.helpers = { checkTableExists: table => ... }` but then the helpers aren't available within transactions, etc. I've hacked around this by overriding `begin` and `savepoint` to attach the helpers object, but I think it would be really cool if a helpers object was a first-class notion in this library that you could set up within options and it would always be available. Thoughts?

**Comment by Minigugus** [comment]
I don't know how you structure your projects but by keeping the business logic and the database logic separate, there is no real reasons for helpers :
```js
const postgres = require('postgres')
const { db } = require('./config')

const sql = postgres(db)

const checkTableExists = async (table, _sql = sql) => (await _sql`...`)[0].count !== 0;

module.exports = {
  async isSetupRequired() {
    return await checkTableExists('products'); // no need to pass the `sql` function
  },
  async ensureUsersTableExists() {
    sql.begin(async sql => {
      if (!(await checkTableExists('users', sql))) // pass the transaction version of the `sql` function
        await sql`CREATE TABLE users (...);`
    }
  },
  // ...
}
```
Personally, I find that helpers are not good for the maintainability of projects, as they introduce a global state that could be difficult to debug. However, I understand that this can be useful in some cases. https://en.wikipedia.org/wiki/Referential_transparency

**Comment by dizlexik** [comment]
I understand, and I'll probably end up wrapping my `sql` instance inside of an object that exposes it along with the common helper functions and then pass that around to each of my various entities. But I do think it would be nice to have something similar to what I proposed so that only the `sql` instance itself needs to be passed around. I think it would help in a number of potential use cases, but I suppose I don't feel strongly enough about it to push the issue here so I'll close it for now. Just something to think about maybe.
