### ISSUE TITLE
Postgres 14 Pipeline Mode

### ISSUE THREAD

**Issue by marcbachmann** [porsager/postgres#236]
Postgres 14 just got released and a new pipeline query mode landed in there.
That would drastically improve the performance of queries and is definitely worth to check out.

https://www.postgresql.org/docs/14/libpq-pipeline-mode.html

**Comment by porsager** [comment]
Postgres.js has been using pipeline mode since the beginning ;) https://twitter.com/RPorsager/status/1439994524919545856

The reason they're mentioning it in v14 notes is because `libpq` (the client) now supports it too. Nothing has changed on the server side.
