### ISSUE TITLE
question about null characters

### ISSUE THREAD

**Issue by alextes** [porsager/postgres#238]
Crypto Twitter likes to have fun, and somehow someone crafted a name, bio, or location containing a valid UTF-8 null character.
```
PostgresError: invalid byte sequence for encoding "UTF8": 0x00
```

I'm guessing just "0x0" in there somewhere. If I understand StackOverflow correctly, as the driver and DB agreed to use null-terminated strings, postgres is surprised to see a null character early but I'm not sure.

Should the driver be escaping this? Should I be escaping this somehow? I don't have the exact string it's trying to dig up but I could find it with some work.

Ideally, there'd be a method to store these nullbytes people put in so they neatly come out again too. All I can think of now is simply taking them out.

**Comment by alextes** [comment]
Found a good piece of writing on this challenge: https://www.commandprompt.com/blog/null-characters-workarounds-arent-good-enough/

For now, storing as bytes is too much for us, guess stripping it is 😭 .

That also concludes this issue I'd say. Certainly, this driver shouldn't fake your columns or anything like that just to preserve null bytes, but then, until postgres supports this and this case starts working automatically, there is also nothing to do. Perhaps this issue guides someone else (:

**Comment by alextes** [comment]
I thought a bit more and came up with the following options:
1. offer a "strip all null characters" option, but that involves running string replace on all passed text 😬 .
2. offer a "strip null characters for these columns" option
3. no added feature, perhaps a small note in the docs maybe using transform.row?
4. wait for postgres to support null strings 😩 .

1 / 2 are pretty terrible 🙈 . I guess nothing still is the most reasonable.

**Comment by uasan** [comment]
> I guess nothing still is the most reasonable.

I think this problem needs to be addressed at the application level, string sanitization and unicode normalization are best done early on.

Of course it's a shame to postgres that they still use a zero byte as a special character.

**Comment by alextes** [comment]
@uasan any suggestions? Now I have:
```ts
str.replaceAll("\x00", "");
```
Ideally, I'd like to retain the NUL / 0x00 bytes, but not all that excited to come up with my own encoding. Even if I would, wouldn't it make sense to actually to the conversion as _late_ in the process as possible? That way the strings can stay UTF-8, and we just take care when storing / sending it when communicating with postgres.

**Comment by alextes** [comment]
@uasan ah I see. Thanks for the example, I was unaware. Sadly we get this data from an API we do not control, but luckily the fields are only for display to users, not any logic. Thanks!

**Comment by tonyxiao** [comment]
The tricky thing is that I have a JSONB field and would have to recursively go through it and strip all `\x00` :/
