### ISSUE TITLE
browserify: Replace net package by net-browserify?

### ISSUE THREAD

**Issue by fjf2002** [porsager/postgres#24]
Thanks a lot for solving issue #22 so fast. As you might have read there, I am considering to use your library on the client side, that is, in the browser(!)

[Browserify](http://browserify.org/) does a great job on supplying node.js built-in libraries such as `Buffer`, but is lacking the `net` package (i. e. TCP connections) out of the box.

Fortunately, the npm package [net-browserify](https://www.npmjs.com/package/net-browserify) does a great job at tunnelling TCP over websockets(!)

At this point you might say,
_Nice story, but what does that have to do with the  porsager/postgres package?_

So, to get to the point:

Is it too much to ask you to add the following to your `package.json` file:
```json
`browser": {"net": "net-browserify"}`
```
That would mean you instruct browserify to replace the `net` package by `net-browserify`.

I have already tested and I would work, but I had to manipulate your package in the way described above.

**Comment by porsager** [comment]
You're welcome ;) 

No it's fine to ask, but I think browserify is too specific, and would be weird adding to Postgres.js. 

You can simply add it to the package.json of the project where you use browserify + postgres.js instead of messing with the package.json in postgres.js.

**Comment by fjf2002** [comment]
Yeah I agree my suggestion is really too specific.

>You can simply add it to the package.json of the project where you use browserify + postgres.js

Sorry that didnt work, which is conforming to the browserify readme at https://github.com/browserify/browserify/blob/master/readme.markdown : 

>"Note that the browser field only applies to files in the local module, and like transforms, it doesn't apply into node_modules directories."

I've solved my problem now by forking your project and applying "my patch" .

**Comment by porsager** [comment]
Properly simpler to maintain by using something like https://github.com/benbria/aliasify ;)

**Comment by fjf2002** [comment]
Thank you for the tip to aliasify, I have tested that package and it doesn't work either. Aliasify is a trnasform, and as I quoted above,

> "Note that the browser field only applies to files in the local module, and like transforms, it doesn't apply into node_modules directories."

So I stick to my fork of your project.

**Comment by fjf2002** [comment]
If someone's interested, finally I got it working with webpack by adding following content to `webpack.config.json`:

```
plugins: [
    new webpack.NormalModuleReplacementPlugin(
      /^net$/,
      'net-browserify'
    )
]
```
