### ISSUE TITLE
question: events for on.connect and on.error

### ISSUE THREAD

**Issue by basaran** [porsager/postgres#240]
Hi, I'm trying to setup a flow in my server.js where I check database connections before the app is initialized.

Are there any events I can use to resolve, reject? Like for instance, this is what I made for redis:

```js
const redisConnect = new Promise((resolve, reject) => {
    const client = redis.createClient({
        host: config.get("redis.host"),
        port: config.get("redis.port"),
        ttl: config.get("redis.ttl"),
    });

    client.on("error", (err) => {
        const debug = dbg.extend("error");
        debug("error", err.message);
        reject("redis connection has failed");
    });

    client.on("connect", () => {
        const debug = dbg.extend("connect");
        debug("redis connection established");
        resolve(client);
    });
});
```

What I do is, I import this promise in server.js and await it. Is there a similar mechanism I could use with postgres?

P.S Also, thank you for not writing this in typescript :)

**Comment by porsager** [comment]
Hi @basaran 

Postgres.js lazily connects to your database so you would simply achieve the above by running a `select 1` query for instance

eg.
```js
// db.js
const postgres = postgres()
    , http = require('http')

const sql = postgres(...)
const server = http.createServer(...)

sql`select 1`.then(() => 
  server.listen(...)
)
```
