### ISSUE TITLE
Error: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by kronos-999** [porsager/postgres#241]
Hello,
it may be that my nodejs server was started too often, but with this is my simple setup (later used in routes))

const sql = require("postgres")(process.env.PGSTRING, {
  max: 999,         // Max number of connections
  idle_timeout: 5 // close after 5 seconds
})
app.set("sql", sql)

I get the following message sometimes: Error: remaining connection slots are reserved for non-replication superuser connections

**Comment by porsager** [comment]
Running with 999 connections is probably your issue. A default postgres install max allows 100 connections. I would say 20 is good for most apps, but this is very specific to your requirements.
