### ISSUE TITLE
returned result iteration

### ISSUE THREAD

**Issue by basaran** [porsager/postgres#243]
Hello :)

I know this was discussed before in heat about the returned result set and those extra keys. 

If possible, could you please update the docs to include:

```
const [...result] = sql`SELECT * FROM something`
```

as an example for select queries, that is when the intention is to just iterate over the results like you would do in a traditional/cli app.

It would also help if you could add the enumerable config as was discussed in the other issues when you have time.

Thank you, have a nice week coming up.

**Comment by basaran** [comment]
Actually, I was puzzled with doing Object.entries on the result. It's an array and should be iterated as an array, so if we could just update the docs, that will be helpful for new users of the library.

Perhaps even a recipes section where users can submit their query examples. Between the use of template literals, it could get confusing for new users. One such simple recipe would be:

## Simple Select Statement

### query

```js
const result = await sql`
  SELECT fruit_name, fruit_origin FROM fruits
`;
```

#### iteration 
```js
for (const row of result) {
   console.log(row.fruit_name, row.fruit_origin);
} ​
```

#### checking number of rows affected by the query
```js
if (result.count === 0) {
 ​console.log("no records were found");
}
```

**Comment by porsager** [comment]
> I know this was discussed before in heat about the returned result set and those extra keys.

Hehe, I assume you've read through https://github.com/porsager/postgres/issues/147 ? 🙂

> ```const [...result] = sql`SELECT * FROM something` ``` 
> Actually, I was puzzled with doing Object.entries on the result. It's an array and should be iterated as an array, so if we could just update the docs, that will be helpful for new users of the library.

I think you're overthinking it. Result **is** an array. It just has some extra properties set on it relevant to the query. 

``` const [...result] = await sql`...` ``` is not valid javascript. You cannot destructure like that.

Why would you want to do `Object.entries` on the result? When would you do that on an array?

If anything should be done to the docs it should be overstating that the result is an array. 

Adding some more examples could be fine, but the very first examples (both gif and code block) actually shows the result.

**Comment by basaran** [comment]
like I said, I was puzzled to do so :)

**Comment by basaran** [comment]
and the last few days, I made some redis get wrappers  and used the same logic you had. It's the appropriate and convenient the way you are returning the results. Please don't change it. Thank you.
