### ISSUE TITLE
try catch blocks

### ISSUE THREAD

**Issue by basaran** [porsager/postgres#245]
Hello once more :)

I'm noticing I will be doing a lot of try/catches inside my sql function. I know one can write a general wrapper function, and call it like `tryMe(selectCat, "pickles")` is there another way?

Is it possible to pass the template literal around?

```js
const statement = sql`SELECT * FROM cats WHERE cat = 'pickles'`

const result = await runQuery(statement, errorHandler) 
```

**Comment by basaran** [comment]
I just noticed `PostgresError` was being exposed. I can probably just use that in node's `uncaught` handler.

**Comment by porsager** [comment]
Yeah, just use functions 😉

```js
const statement = () => sql`SELECT * FROM cats WHERE cat = 'pickles'`

const result = await runQuery(statement(), errorHandler) 
```

**Comment by basaran** [comment]
ha :)
