### ISSUE TITLE
Feature requedt: Add  Malloy Language support

### ISSUE THREAD

**Issue by ansarizafar** [porsager/postgres#246]
SQL is complete but ugly: everything is expressible, but nothing is reusable; simple ideas are complex to express; the language is verbose and lacks smart defaults. Malloy is immediately understandable by SQL users, and far easier to use and learn. It is usable in place of SQL to manipulate and explore data.

Malloy postgresdb support is coming next month but Malloy only allow querying database, writes are not supported. It would be great If somehow we can use Malloy with postgresjs

https://github.com/looker-open-source/malloy

**Comment by porsager** [comment]
Hi @ansarizafar.. 

Sounds interesting. I think the pitch can be done without dissing SQL though 😉

As for supporting it with Postgres.js, I don't see why that should be an issue considering eg. Cockroach DB works fine with this driver. As long as it speaks the PostgreSQL protocol everything should be fine. (except the language specific helpers that generate sql of course).
