### ISSUE TITLE
Selecting * dynamically

### ISSUE THREAD

**Issue by dizlexik** [porsager/postgres#25]
I have a bit of code where I'd like to select only specified columns, if provided, or else all columns. I can't seem to figure out how to select `*` dynamically within the template string.

I'd like to do something like one of these, but neither work:
```js
sql`SELECT ${sql(columns || '*')} FROM my_table`
sql`SELECT ${columns ? sql(columns) : '*'} FROM my_table`
```

Here are a couple of failed attempts to select * dynamically:
```js
sql`SELECT ${sql('*')} from my_table` // becomes: SELECT "*" FROM my_table
sql`SELECT ${'*'} FROM my_table` // becomes: SELECT $1 FROM my_table [{ value: '*' }]
```

**Comment by porsager** [comment]
Hi @dizlexik it's not optimal now, and needs to be improved upon .. I'll track and cover this in #12 ;)
