### ISSUE TITLE
 Error: non-integer constant in ORDER BY: $1

### ISSUE THREAD

**Issue by codergautam** [porsager/postgres#251]
This might be a mistake on my end, but I'm constantly getting this error:
` Error: non-integer constant in ORDER BY: $1`

My query is
await sql`SELECT * from games ORDER BY ${type} DESC LIMIT 23`;

Now when I run it like:
await sql`SELECT * from games ORDER BY coins DESC LIMIT 23`;
It works perfectly. 

The value of the type variable is also "coins". How do I fix this?

**Comment by porsager** [comment]
The order by column is not a variable, so it can't be passed as a variable to postgres. For dynamic values like this you need to wrap it in `sql(type)`, so your query becomes
```js
await sqlSELECT * from games ORDER BY ${ sql(type) } DESC LIMIT 23;
```
