### ISSUE TITLE
sql(...).cursor is not a function

### ISSUE THREAD

**Issue by se8820726** [porsager/postgres#256]
hi
I'm using nodejs postgres v1.0.2

and I can't use cursors because of this error:

`sql(...).cursor is not a function`

example code:
```
const pgConStr = `postgres:1@localhost:5432/postgres`; 
const postgres = require('postgres')
var sql = postgres('postgres://' + pgConStr)

async function a(){

	await sql`
		select * from generate_series(1,400) as x
	`.cursor(row => {
		console.log(row)
	})
	
}

a();
```

**Comment by porsager** [comment]
Cursor is only available in v 2@beta (github master). You can get that using `npm install postgres@beta`

**Comment by se8820726** [comment]
why don't you add it to release version ?

**Comment by porsager** [comment]
It needed an overhaul of some internals to get the last features in. That's done now, and an release is coming up this week.
