### ISSUE TITLE
Query building

### ISSUE THREAD

**Issue by dizlexik** [porsager/postgres#26]
Is there any plan to add query building functionality to this whereby I could build a query dynamically bit by bit before executing it? Or should I use another library for that sort of thing and call `sql.unsafe(queryBuilderResult)`?

And a related question, is it possible to build a dynamic query in a manner similar to this?
```js
const query = sql`SELECT * FROM my_table ${order && sql`ORDER BY ${order}`}`;
```
I know code snippet is nonsense, but hopefully you get the idea.

**Comment by porsager** [comment]
Hi @dizlexik ..

Yeah, I'd like to improve on the helpers already there now so you can achieve exactly something like what you're requesting. I've got a few other things I'll finish first, but it shouldn't be long :)

**Comment by porsager** [comment]
I'm moving the tracking of all this to #12 ;)
