### ISSUE TITLE
Typing for .subscribe()/publication API is not defined

### ISSUE THREAD

**Issue by oOBoomberOo** [porsager/postgres#262]

**Comment by porsager** [comment]
If you want to make a PR for this that would be appreciated 😉

cc @Minigugus

**Comment by oOBoomberOo** [comment]
I do want to, but I'm afraid I'm not used to the codebase yet; combined with the lack of documentation around the feature, I'm just not sure what its types are supposed to be.
Hopefully, someone who better understands the API can teach me/write the PR themselves.

**Comment by Minigugus** [comment]
@oOBoomberOo The #257 PR already added publication API types to the `rewrite` branch, for the v3 version :

https://github.com/porsager/postgres/blob/43d78d548694dea7643b98c434f139ca4c18fdbf/types/index.d.ts#L363-L385
https://github.com/porsager/postgres/blob/43d78d548694dea7643b98c434f139ca4c18fdbf/types/index.d.ts#L568

@porsager Maybe @oOBoomberOo could open another PR for a v2 backport of thoses types? I guess thoses types hasn't changed between the 2 versions, that shouldn't be complicated. What do you think @oOBoomberOo?

**Comment by porsager** [comment]
@Minigugus No I don't think that should be necessary. Better to focus on getting v3 out.
