### ISSUE TITLE
Is constructing `DO` queries possible? (PostgresError: could not determine data type of parameter $1)

### ISSUE THREAD

**Issue by prescience-data** [porsager/postgres#263]
I'm attempting to construct a `DO` query but getting the following error: 
```
PostgresError: could not determine data type of parameter $1
```

### Example

Note that I've attempted to set the type manually as `varchar` here but the issue is the same without.

```pgsql
        DO
        $$
          DECLARE
            _api_key_id  bigint;
            _bar_id bigint;
            _baz_id    bigint;
          BEGIN
            -- Validate api key token.
            SELECT
              id
              INTO _api_key_id
              FROM data.api_keys
              WHERE
                data.api_keys.token = ${token}::varchar(100)
              LIMIT 1;

            -- ... etc...
          END
        $$;

```

Is there some additional step required here?

**Comment by porsager** [comment]
It seems PostgreSQL doesn't do type inference or bind on parameters inside DO queries, so we need a better way to define the type together with the value in our query.

For now you can define the custom types you need to use and do like this:
```js
const sql = postgres({
  types: {
    varchar100: {
      to: 1043,
      from: 1043,
      parse: x => x,
      serialize: x => x
    }
  }
})

sql`
  DO
  $$
    DECLARE
      _api_key_id  bigint;
      _bar_id bigint;
      _baz_id    bigint;
    BEGIN
      -- Validate api key token.
      SELECT
        id
        INTO _api_key_id
        FROM data.api_keys
        WHERE
          data.api_keys.token = ${ sql.types.varchar100(token) }
        LIMIT 1;

      -- ... etc...
    END
  $$;
`
```

I'm also a bit curious what your use case is with that DO query ☺️?

**Comment by uasan** [comment]
Maybe for [Row Security Policies](https://www.postgresql.org/docs/current/ddl-rowsecurity.html)

**Comment by prescience-data** [comment]
@porsager Ah this is neat, I didn't fully understand how this tied in to the flow, that example is super clear now though:
```js
const sql = postgres({
  types: {
    varchar100: {
      to: 1043,
      from: 1043,
      parse: x => x,
      serialize: x => x
    }
  }
})

// ...
` data.api_keys.token = ${ sql.types.varchar100(token) }`
```

Regarding the use-case, it's a fairly complex set of queries _(ie selecting and inserting from several tables, and raising exceptions if certain things don't validate etc)_ 

Presently it's defined as Postgres Function (which takes the execution time from several seconds due to remote server (Postgres) round trips if executed from within the application code as individual queries to basically zero time by comparison when provided as a Function (single round trip). 

The application requirement is that this logic is too likely to change semi-frequently to make sense as part of a permanent database schema (which would require touching several teams for approval each time it needed to change), and Supabase doesn't seem to provide access to `pg_temp` to send as a temporary Function _(which in any case has the same issues as the `DO` statement)_ - thus the "one shot" `DO` statement seemed to make the most sense in this case as it allows application team to modify the logic without touching the database schema.

**Comment by prescience-data** [comment]
Closed with https://github.com/porsager/postgres/issues/263#issuecomment-1030700194

**Comment by porsager** [comment]
@prescience-data Sorry, I was wrong! The reason it doesn't work is because PostgreSQL functions uses the parameter placeholders `$1, $2, ...` for the function parameters instead of the protocol level parameters. So even with my above suggestion, it won't work.

Now for you specific use case, would you not be able to achieve the same using CTE's?

**Comment by jedwards1211** [comment]
Since `DO` takes code as a string (which is usually dollar-quoted), I wonder if you could at least use `FORMAT`?

```
await sql`
        DO
        FORMAT($$
          DECLARE
            _api_key_id  bigint;
            _bar_id bigint;
            _baz_id    bigint;
          BEGIN
            -- Validate api key token.
            SELECT
              id
              INTO _api_key_id
              FROM data.api_keys
              WHERE
                data.api_keys.token = %1$s::varchar(100)
              LIMIT 1;

            -- ... etc...
          END
        $$,
        ${token}
      ) LANGUAGE plpgsql;
`
```

**Comment by porsager** [comment]
Unfortunately doesn't help much, since parameters aren't allowed there either. You'd still need to use a string with eg sql.unsafe and therefore be careful to avoid sql injections.

**Comment by jedwards1211** [comment]
@porsager actually, I checked and `DO` only accepts a string literal anyway, not an expression
