### ISSUE TITLE
add BigInt support

### ISSUE THREAD

**Issue by devcat** [porsager/postgres#27]
right now any bigint passed from database is converted to `Number()` instead of `BigInt()`

this can be already done with types:
```js
postgres({
  types: {
    bigint: {
      to: 20,
      from: [20],
      parse: data => BigInt(data),
      serialize: bigint => bigint.toString(),
    },
  },
}
```
but would be great if it was in the library

**Comment by porsager** [comment]
Totally agree 👍 Thanks for bringing it to my attention. Feel free to do a PR
