### ISSUE TITLE
NUMERIC type not handled by number type

### ISSUE THREAD

**Issue by thecoolwinter** [porsager/postgres#270]
The postgres [`NUMERIC`](https://www.postgresql.org/docs/9.1/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL) type (iod 1700) isn't handled by postgres.js's built-in number converter.

## Steps to Reproduce

SQL Setup
```sql
CREATE TABLE t(
  number NUMERIC
);

INSERT INTO t(number) VALUES (3.1415);
```

Javascript
```js
const sql = require("postgres")();

let data = await sql`SELECT * FROM t`;

console.log(typeof data.number); // string
```

## Temporary Fix

I've gotten around this by adding a custom type according to the docs:
```js
const config = {
	types: {
		numeric: { // This conversion is identical to the `number` conversion in types.js line 11
			to: 0,
			from: [1700],
			serialize: (x) => "" + x,
			parse: (x) => +x,
		},
	}
}

const sql = require("postgres")(config);
let data = await sql`SELECT * FROM t`;

console.log(typeof data.number); // number
```
----
I wanted to make an issue first before creating a PR to add the `NUMERIC` oid to the built-in type converter to make sure that the exclusion wasn't intentional. If it wasn't intentional to leave it out I can create a PR to fix this.

**Comment by porsager** [comment]
https://github.com/porsager/postgres#numbers-bigint-numeric
