### ISSUE TITLE
Made connection with the `-X` mode

### ISSUE THREAD

**Issue by throrin19** [porsager/postgres#271]
Hello,

It's possible to made a postresJS withe the psql `-X` option to avoid `psqlrc` system file ?

I need it to directly set a command to upgrade postgres extensions in specific use case and, with the `psql` command, I have to do the `-X` argument and directly made the `ALTER EXTENSION` request.

**Comment by porsager** [comment]
Hi @throrin19 .

Postgres.js doesn't use the `psqlrc` file for anything. Can you describe a bit more of your scenario, cause I'm not sure what you're trying to achieve?

**Comment by throrin19** [comment]
I try to upgrade an extension (timescaledb in my case) with `ALTER EXTENSION timescaledb UPDATE;` But, If I made directly that, I have this error in postgres : 

```
Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql.
```

**Comment by porsager** [comment]
Ah. That makes sense. Try running with `fetch_types: false` in options.

**Comment by throrin19** [comment]
I'm in 2.0 Beta 11

It works fine. Thank you 👍
