### ISSUE TITLE
[v3] Slowdown because of large source maps for queries that don't error

### ISSUE THREAD

**Issue by mohe2015** [porsager/postgres#273]
I assume because of https://github.com/porsager/postgres/blob/51d033c17e5af58e2fda5476ca60b0400fed07f6/lib/index.js#L187

stack traces are generated. It seems like the caching does not work as they seem to be re-generated for every request. https://github.com/nodejs/node/issues/41541 also plays into this but still I don't understand why this is necessary. If you need a minimally reproducible example please tell me and I will try to provide one. The relevant thing is probably that cachedError should only calculate the stack trace the first time. What are some reasons this does not work? The queries are wrapped in a transaction. The following is the code that creates the pool.

```typescript
export const sql = postgres(process.env["DATABASE_URL"], {
  host: process.env["DATABASE_HOST"],
});
```

![image](https://user-images.githubusercontent.com/13287984/157916071-416f6260-fb3a-46b0-a49e-fe9d8d442afa.png)

**Comment by porsager** [comment]
Thanks a lot for this issue. I'll give it a closer look Sunday.

**Comment by porsager** [comment]
Yeah, that looks like an oversight on my part for `.unsafe()`... Since the caching relies on the first argument from the tagged template function it's not possible to make origin work for unsafe. I think it should simply be disabled so that you'll only get the origin if `debug: true`.

**Comment by porsager** [comment]
Would you mind trying https://github.com/porsager/postgres/commit/0aacdb3231e3b725276f71613d74d9cb6daefc18 out to see if there's an improvement?

**Comment by mohe2015** [comment]
It looks fixed. If it will happen again I will reopen. Thanks for fixing this!
