### ISSUE TITLE
Dynamic schema name

### ISSUE THREAD

**Issue by kryptus36** [porsager/postgres#277]
Any thoughts on how I could best implement this? It's related to schema based multi tenancy.

```
const res = sql `SELECT * FROM ${schema}.users`

```

Obviously the lib tries to parameterize it and fails.

**Comment by porsager** [comment]
You can use the `sql` instance as a regular function to escape identifiers. 

```
const res = sql `SELECT * FROM ${ sql(schema) }.users`
```
