### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by kryptus36** [porsager/postgres#278]
In the readme it says typing is in beta so maybe this is expected.

When I run const sql = postgres({...}); The returned value is of type any, so I get no type hints.

Very minor issue, but thought I'd ask.

**Comment by porsager** [comment]
Hi @kryptus36 .. could you try with the rewrite (v3) branch? `npm install porsager/postgres#rewrite`

**Comment by kryptus36** [comment]
Yeah that is much nicer :) can I safely use that version?
