### ISSUE TITLE
knex integration

### ISSUE THREAD

**Issue by throrin19** [porsager/postgres#28]
It would be nice if it's possible to use this with knex to easily build requests. 

It's just a suggestion to improve usage of this library in many projects.

I think, with that, we have the solution for building queries dynamically. I know it's not simple to do that and, maybe it's not compatible with this library to have the integration with knex.

Thanks in advance

**Comment by porsager** [comment]
Ah yes. This would be up to knex, and not something I can decide, but if they want to I don't see why they shouldn't be able to support Postgres.js 🙂

You could create an issue and ask them?

**Comment by throrin19** [comment]
I made this and I have a response from knex team : we should create knex plugin to do that : https://github.com/knex/knex/issues/3642

**Comment by porsager** [comment]
Ah cool. I was not aware they had a plugin system 😊 

Well i guess it's just a matter of trying to do that 😉 I'd love to take a look or answer questions that might come up if you or someone else makes something, but I don't have a use for knex, so not anything I'm interested in taking on myself 🤗

**Comment by throrin19** [comment]
Unfortunately, I don't have the time right now. If I do, why not, but I'm still blocked in some query compositions with your library to play to it with knex.

**Comment by doron2402** [comment]
@throrin19 you can always use Knex to construct your sql query and than call `.toString()` and pass as a string.

**Comment by porsager** [comment]
Seems like Knex has an easy wrapper system to achieve this :)

**Comment by throrin19** [comment]
Ok, I made a simple version using knex query building and pass generated query to `postgres.unsafe`. My function is like this : 

```js
'use strict';

const Knex              = require('knex');
const Dialect           = require('knex/lib/dialects/postgres/index.js');
const postgres          = require('postgres');

// saw this here : https://github.com/knex/knex/issues/3642#issuecomment-588054490
Dialect.prototype._driver = () => postgres;

module.exports = {
    /**
     * Get knex instance used only for query building. You can't request server with that
     *
     * @return {knex}       Knex instance only for query building
     */
    knex() {
        return Knex({
            client : Dialect,
        });
    },
    /**
     * Send request builded with knex to timescaleDB.
     * You can only use SELECT with this method.
     *
     * @param {object}      params              Function params
     * @param {knex}        params.query        Query builded by Knex to request with postgres
     * @param {string}      params.host         Database host
     * @param {number}      params.port         Database port
     * @param {string}      params.database     Database to connect
     * @param {string}      params.username.    Database username.
     * @param {string}      params.password     Database password.
     * @param {object}      [params.transform]  Postgres transform config
     * @param {function}    [params.debug]      Function called on request debug (Ex: `debug : console.log`)
     */
    async request(params) {
        const sql = postgres({
            host      : params.host,
            username  : params.username,
            password  : params.password,
            port      : params.port,
            database  : params.database,
            transform : params.transform,
            debug     : params.debug,
        });

        const result = await sql.unsafe(params.query.toString());

        await sql.end();

        return result;
    },
};
```

Whit this, I can easilly build requests using knex and execute them using postgres : 

```js
const helper = require('my/helper');
const knex   = helper.knex();
const qb     = knex('example');

qb.select(knex.raw('time_bucket_gapfill(\'60s\', time) AS "time"'))
    .select(knex.raw('locf(last(value, time)) as "value"'))
    .groupBy(1)
    .orderBy(1);

const response = await helper.request({
    query    : qb,
    database : 'testing',
    username : 'test_user',
    password : 'test_password',
});
```

> In this example, I create TimescaleDB requests

**Comment by doron2402** [comment]
Why do you call `sql.end()`? would that return the connection to the pool connections?

**Comment by throrin19** [comment]
In my case I use postgres over lambda functions and I want limit connections over different executionsLe 12 mai 2020 21:25, Doron Segal <notifications@github.com> a écrit :
Why do you call sql.end()? would that return the connection to the pool connections?
