### ISSUE TITLE
Column type Date error: PostgresError: syntax error at or near "$2"

### ISSUE THREAD

**Issue by kazzkiq** [porsager/postgres#281]
Whenever I try to run a query with these parameters:

```js
// Data example
const date = "2022-03-23";
const city_uid = "123etc";

const query = sql`
  SELECT *
  FROM schedules
  WHERE city_uid = ${city_uid}
  AND date_trunc('month', date) = date_trunc('month', DATE ${date})
  AND date_trunc('year', date) = date_trunc('year', DATE ${date})
  `;
```

I keep getting this error:

```
PostgresError: syntax error at or near "$2"
```

The exact same query works successfully when running directly with SQL:

```sql
SELECT *
  FROM schedules
  WHERE city_uid = '123etc'
  AND date_trunc('month', date) = date_trunc('month', DATE '2022-03-23')
  AND date_trunc('year', date) = date_trunc('year', DATE '2022-03-23')
```

It seems to be related to the `date` field since when I remove it and keep just the `WHERE city_uid = '123etc'` the query executes successfully with `sql()`.

**Comment by porsager** [comment]
Hi @kazzkiq . You can't use constructors (`DATE`) like that when using parameters. You have to either call it as a function or cast. The following works:
```
date_trunc('month', DATE(${ date }))
```

or 
```
date_trunc('month', ${ date }::timestamp)
```
