### ISSUE TITLE
TypeScript error on await-ing sql`[...]`

### ISSUE THREAD

**Issue by jadbox** [porsager/postgres#283]
```js
const sql = postgres(`postgres://${PGUSER}:${PGPASS}@${PGDOMAIN}:5432/tpp`, { debug });
const [u] = await sql`select id from users where twitterid = ${id}`;
```

Error:
```Type of 'await' operand must either be a valid promise or must not contain a callable 'then' member.```

Lib version: 3.0
Typescript: 4.6.3

This error did not occur in 2.0.

**Comment by jadbox** [comment]
It looks like this occurs when not passing a type parameter. If I use, ```await sql<any[]>`[...]` ``` it passes type check. Is it possible to make this optional so that we can continue to use: ```await sql`[...]` ``` ?

**Comment by porsager** [comment]
I'm not using typescript, so I'll just ping @Minigugus who was kind enough to make the typings.

**Comment by eugene1g** [comment]
@jadbox Perhaps the type of `id` is `any | unknown`. 

This should work:
```ts
const id = "abc123";
const [u] = await sql`select id from users where twitterid = ${id}`;
```

This probably will not:
```ts
const id:any = "abc123";
const [u] = await sql`select id from users where twitterid = ${id}`;
```

See if you can help TypeScript to determine what the type of your `id` is, or manually cast it like so
```ts
const [u] = await sql`select id from users where twitterid = ${id as string}`;
```

**Comment by remorses** [comment]
For anyone finding this issue while passing generic arguments, you have to pass an array type, not the row type

```diff
- const query = sql<{ id: number }>`SELECT * FROM users`
+ const query = sql<{ id: number }[]>`SELECT * FROM users`
```
