### ISSUE TITLE
Feature request: allow passing Duplex stream for the underlying connection

### ISSUE THREAD

**Issue by mscdex** [porsager/postgres#284]
This makes it much easier to do things like in-process ssh tunneling of database connections and is already supported by various other database drivers.

**Comment by porsager** [comment]
That would be really cool.. Would you mind posting where in which other drivers supporting this? 

If you have an idea for how the usage would look, that would also be great. I'm imagining a function in the options object that should return the duplex stream for Postgres.js to use? Something like this perhaps?

```js
const sql = postgres({
  duplex: (...) => {
    return duplexStream
  }
})
```

Ideas for a proper name for that option would also be great.

**Comment by mscdex** [comment]
Off the top of my head I can think of:

* `pg` supports it by setting `stream` in the `pg.Client` config object, but is currently undocumented (although it's supported custom streams since at least 2010). For pooling, I *think* you need to extend/"sublcass" `pg.Pool` to support using custom streams, but I haven't really dived into their code.

* `mysql2` supports it by setting `stream` in the connection config object either to the stream itself or to a function that passes a stream to a callback (useful especially for pooling). Nothing extra is needed for pooling as the pool object just uses connection objects that inherit from the normal connection object, which means connecting works in the same way (and thus connecting with custom streams works the same).

IMO `mysql2` handles this pretty well and is flexible.

**Comment by eugene1g** [comment]
This could help with testing. Right now we creat a thin proxy to inspect & pass through `postgres` traffic (mainly to test timeouts etc), and pint the library to connect to our proxy port. If we could inject a stream/socket instead, that would make life simpler.

**Comment by porsager** [comment]
@mscdex This is now possible like this using your ssh2 library 👍

```js
import ssh2 from 'ssh2'

const sql = postgres({
  ...options,
  socket: ({ hostname, port }) => new Promise((resolve, reject) => {
    const ssh = new ssh2.Client()
    ssh
    .on('error', reject)
    .on('ready', () => 
      ssh.forwardOut('127.0.0.1', 12345, hostname, port, 
        (err, socket) => err ? reject(err) : resolve(socket)
      )
    )
    .connect(sshOptions)
  })
})
```

https://github.com/porsager/postgres#custom-socket
Let me know if you have any wishes for improving the docs or other suggestions.

**Comment by Radiergummi** [comment]
In case anyone else ends up here, this option also allows to connect to Postgres via a Socks5 proxy, for example the TailScale CLI in a Docker container:

```ts
import postgres from 'postgres';
import { SocksClient } from 'socks';

const sql = postgres({
    socket: async ({ host: [host], port: [port] }) => {
        const { socket } = await SocksClient.createConnection({
            destination: { host, port },
            command: 'connect',
            proxy: {
                host: '127.0.0.1',
                port: 1055,
                type: 5,
            },
        });

        return socket;
    },
});
```

@porsager I'd just wish the TypeScript stubs would contain the `socket` option; that would be amazing!

**Comment by porsager** [comment]
PR welcome 😉

**Comment by Radiergummi** [comment]
Fair enough! Got it on my todo list :)
