### ISSUE TITLE
Throwing exceptions from sql.begin has some caching issue

### ISSUE THREAD

**Issue by megous** [porsager/postgres#289]
This code should fail with exception 'throws from tx', but instead fails with 'SELECTexception' syntax error:

```
async function main() {
        try {
                await sql.begin(async sql => {
                        try {
                                let r = await sql`SELECTexception`;
                        } catch (ex) {
                                throw new Error('throws from tx');
                        }
                });
        } finally {
                await sql.end();
        }
}
```

Looks like the original exception is cached somewhere in sql.begin()...

Other than that, v3 is beautiful. :) I've made a bit of a quick and dirty compat layer for migrating from `vitaly-t/pg-promise`:

https://megous.com/dl/tmp/compat.patch

And was able to use your DB connector on a fairly large project that uses pg-promise just like that, and it works nicely. :) I've only found this issue so far during porting.

Great job with v3 :) I'm looking forward to using those lovely batched cursors, and streaming replication protocol support. :)

**Comment by megous** [comment]
Typical pattern where this is used is to return nicer user friendly errors for ` duplicate key value violates unique constraint` errors by re-throwing them in a different shape.

Interestingly:

```
async function main() {
        try {
                await sql.begin(async sql => {
                        try {
                                let r = await sql`SELECTexception`;
                        } catch (ex) {
//                              throw new Error('throws from tx');
                        }
                });
        } finally {
                await sql.end();
        }
}
```

This results in exception, too. I wonder if this is designed so, because transaction can't continue if one of the SQL queries fails, so sql.being is made to always fail after that?

**Comment by porsager** [comment]
Very nice description of your issue, and thank you for the kind words ! 

I think you'd want savepoints to achieve this if I'm not mistaken?

**Comment by porsager** [comment]
I'm gonna look closer at that pg-promise wrapper tomorrow - I think others could use that too - maybe you should publish it as a package?

**Comment by megous** [comment]
Yes, savepoints would probably work. It's just that it's a bit surprising to throw a certain exception from the callback, and it not being propagated by begin() as is, if there was SQL exception thrown previously.

Anyway, I rewrote the code to have the `try {} catch () {}` around the whole transaction and not inside the `begin()`'s callback, and I re-throw nicer error from there. That works with both `pg-promise` and `postgres` packages. :)

I'll have to remember that catching exceptions inside the callback is a bit tricky.

Re compat layer: It's not really a wrapper currently, but I guess it can be made as such, if everything it accesses is available from outside. (which it looks like, it may be...) Anyway, it's too trivial and incomplete (I just implemented a very small subset of features I actually use) to publish, and anyone searching for pg-promise on your repo will probably find the patch and modify it to their needs.

**Comment by porsager** [comment]
Yeah, I think you're right. I'll look closer at this today / tomorrow.

**Comment by porsager** [comment]
Ok, we're now rethrowing the correct error. The issue is that I'm also catching "uncaught" queries inside the transaction scope to ensure we don't get out of sync with the protocol. Now we're instead checking on final throw if the error is '25P02', instead of rejecting on first query error.

Thanks a lot for the great description, and it would be great if you'd give current https://github.com/porsager/postgres/commit/f7c8ae6ac63682ce747c0f645cde0c028cd020a6 a try.

**Comment by megous** [comment]
Thank you very much. It works. :)

**Comment by megous** [comment]
Maybe not perfectly, though... I've patched in some simple queue statistics reporting to the library:

https://megous.com/dl/tmp/stats.patch

And discovered that if I run the code in the first comment repeatedly, the full queue keeps growing in size indefinitely. There's probably some leak somewhere, still.

Test code:

```
async function main() {
        try {
                for (let i = 0; i < 100; i++) {
                        try {
                                await sql.begin(async sql => {
                                        try {
                                                let r = await sql`SELECTexception`;
                                        } catch (ex) {
                                                throw new Error('throws from tx');
                                        }

                                        r = await sql`SELECT 1`;
                                });
                        } catch (ex) {
                        }
                }

                await new Promise(r => setTimeout(r, 10000));
        } finally {
                await sql.end();
        }
}

main().catch(console.error);
```

Result:

```
{
  queues: {
    closed: 10,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 0,
    busy: 0,
    full: 99
  }
}
```

**Comment by megous** [comment]
Re-throw doesn't matter, it happens even with:

```
async function main() {
        try {
                for (let i = 0; i < 100; i++) {                                      
                        try {                                                        
                                await sql.begin(async sql => {                       
                                        let r = await sql`SELECTexception`;          
                                });                                                  
                        } catch (ex) {                                               
                        }                                                            
                }                                                                      

                await new Promise(r => setTimeout(r, 10000));
        } finally {
                await sql.end();
        }
}
```

but not with:

```
async function main() {
        try {
                for (let i = 0; i < 100; i++) {
                        try {
                                let r = await sql`SELECTexception`;
                        } catch (ex) {
                        }
                }

                await new Promise(r => setTimeout(r, 10000));
        } finally {
                await sql.end();
        }
}
```

Which returns

```
{
  queues: {
    closed: 10,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 0,
    busy: 0,
    full: 0
  }
}
```

**Comment by megous** [comment]
It would ne nice to have some reporting about the status of the internals (especially things that can accumulate), to catch things like these, or may usage errors of the library, etc. I'll try to patch in tracking of the queries queues, too. Though that's a bit harder, since they are scoped by begin(). :)

**Comment by porsager** [comment]
@megous I'm also seeing this with v3.0.0, but not latest master?

**Comment by megous** [comment]
Anyway, here's a part of a trace of what's happening on the queues:

```
....
{
  msg: [ 'open push ', { id: 1, state: 'open' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 1,
    busy: 0,
    full: 0
  }
}
{
  msg: [ 'open shift ', { id: 1, state: 'open' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 0,
    busy: 0,
    full: 0
  }
}
{
  msg: [ 'open remove ', { id: 1, state: 'open' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 0,
    busy: 0,
    full: 0
  }
}
{
  msg: [ 'reserved push ', { id: 1, state: 'reserved' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 1,
    open: 0,
    busy: 0,
    full: 0
  }
}
{
  msg: [ 'full push ', { id: 1, state: 'full' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 1,
    open: 0,
    busy: 0,
    full: 1
  }
}
{
  msg: [ 'reserved remove ', { id: 1, state: 'reserved' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 0,
    busy: 0,
    full: 1
  }
}
{
  msg: [ 'open push ', { id: 1, state: 'open' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 1,
    busy: 0,
    full: 1
  }
}
{
  msg: [ 'open shift ', { id: 1, state: 'open' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 0,
    busy: 0,
    full: 1
  }
}
{
  msg: [ 'open remove ', { id: 1, state: 'open' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 0,
    open: 0,
    busy: 0,
    full: 1
  }
}
{
  msg: [ 'reserved push ', { id: 1, state: 'reserved' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 1,
    open: 0,
    busy: 0,
    full: 1
  }
}
{
  msg: [ 'full push ', { id: 1, state: 'full' } ],
  queues: {
    closed: 9,
    ended: 0,
    connecting: 0,
    reserved: 1,
    open: 0,
    busy: 0,
    full: 2
  }
}
....
```

From it I can see where the leak happens (after push to open queue, it's not removed from full queue).

It's pushed to full in go() when c.execute() returns false function and also to reserved in onexecute()

```
  function go(xs, query) {
    const c = xs.shift()
    return c.execute(query)
      ? (c.state = 'busy', busy.push(c))
      : (c.state = 'full', full.push(c))
  }
```

but in c.execute() onexecute is called too, which ends up pushing it to reserved queue, too.

```
    function onexecute(c) {
      queues[c.state].remove(c)
      c.state = 'reserved'
      c.reserved = () => queries.length
        ? c.execute(queries.shift())
        : c.state = 'reserved'
      reserved.push(c)
      connection = c
    }
```

And after that, it's never removed from full queue.

It only leaks when picking up reserved connections, not when picking the connection from closed queue. :)

**Comment by megous** [comment]
I don't know what the expectation is for presence of connection object in various queues, so I can't assist any further. Is it supposed to be exclusive - that is: connection has to be in exactly one of the queues?

**Comment by porsager** [comment]
No luck sleeping yet, but lucky me, I get to see your awesome debugging :) Good job @megous!

I've been meaning to centralize the queue movement (not separate set states and queue pushes), and that should fix a pitfall like this. A connection is only ever in one queue, since it's just a way of being able to cycle / use connections with a specific state.

**Comment by megous** [comment]
A simple fix then may be noting the queue the connection is in on the connection object itself, and when pushing it into a new queue just calling `c.queue && c.queue.remove(c)` instead of trying to track which queue it was last in by c.state.

```
function move(c, queue) {
  c.queue && c.queue.remove(c);
  queue.push(c);
}
```

Or something like that.

> No luck sleeping yet,

Hopefully not because of this bug. :)

**Comment by porsager** [comment]
Yeah! I like that - much better :)

> Hopefully not because of this bug. :)

Hehe, I don't think so, but who knows.. sleep just never arrived, so got up again.

**Comment by megous** [comment]
This seems to work: https://megous.com/dl/tmp/0001-move.patch

**Comment by megous** [comment]
Also this is the stats patch I use for testing: https://megous.com/dl/tmp/0002-stats.patch

**Comment by porsager** [comment]
Very nice @megous 

I've gone ahead and used that to remove state completely and clean things up a bit at the same time. Would you mind trying out https://github.com/porsager/postgres/tree/connection-queue-fix ?

**Comment by megous** [comment]
Even better. Tested, and works fine.
