### ISSUE TITLE
Feature: Create GAS(Google Apps Script) project/library to access postgres / postgresql in new V8 runtime

### ISSUE THREAD

**Issue by jlprado** [porsager/postgres#29]
Maybe it can be straightforward to make some adaptations to this project so it can be used directly in GAS/Google Apps Scripts, and enable direct access to postgres/posgresql databases using the recent V8 runtime?
https://developers.google.com/apps-script/guides/v8-runtime
(caveat, it does not support ECMAScript modules).
thanks,

**Comment by porsager** [comment]
As far as I can see there is no tcp socket support in Google App Scripts, which would be the bare minimum needed for this to work.

Correct me if I'm wrong ;)
