### ISSUE TITLE
Expensive instantiation of Errors to capture stack traces?

### ISSUE THREAD

**Issue by leiffoged** [porsager/postgres#290]
First of all, very thrilled that this library exists. I saw this on hacker news the other day and benchmarked it against the library I currently use and it's loads faster. Excellent, so I'm moving over.

For a number of reasons, I'm not able to migrate most of the queries in the code base right away, so I'm utilizing sql.unsafe to unblock these queries for now (for a number of reasons, I can't use prepared statements in these places). However, every unsafe query instantiates a new Error object to capture the stack trace at the point of query creation, which is quite expensive.

This is the line that's dominating CPU usage (over half of query-related CPU usage): https://github.com/porsager/postgres/blob/a9bfd19fc1a620f26d8ad447d40092895052f73c/src/query.js#L35

Is there a way I could disable this functionality? Thanks for your input and appreciate the hard work as making such an awesome library.

**Comment by porsager** [comment]
Ah yes, I guess my hunch was correct here: https://github.com/porsager/postgres/issues/273#issuecomment-1066170854

I'll make a new release that only creates errors for stack trace in unsafe if `debug: true`.
