### ISSUE TITLE
Not working with latest nestjs

### ISSUE THREAD

**Issue by onsummer** [porsager/postgres#297]
In `db.ts`:

```typescript
import postgres from 'postgres'

console.log(postgres)

const sql = postgres({
  host: 'localhost',
  port: 5432,
  database: 'datareposity',
  username: 'postgres',
  password: 'mypassword'
})

export default sql
```

Then I use it in my controller:

```typescript
// app.controller.ts

import { Controller, Get } from '@nestjs/common'
import { AppService } from './app.service'
import sql from './db'

const getSysInfo = async () => await sql`
  select postgis_full_version()
`

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) { }

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  @Get('postgis-version')
  async getPostGISVersion() {
    const info = await getSysInfo()
    return info
  }
}
```

But when I `pnpm start:dev`:

![image](https://user-images.githubusercontent.com/26168955/160935226-1c6a27b1-71e9-4a49-b257-c8942cc71bfb.png)

Is it a postgres problem or a nestjs problem? Thank you.

**Comment by porsager** [comment]
How does the compiled js look? Doesn't seem nest related, but perhaps rather typescript related

**Comment by onsummer** [comment]
> How does the compiled js look? Doesn't seem nest related, but perhaps rather typescript related

Hi, after compile, `db.ts` looks like:

``` js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const postgres_1 = require("postgres");
const sql = (0, postgres_1.default)({
    host: '182.254.139.35',
    port: 9876,
    username: 'postgres',
    password: 'IFindXYD',
    database: 'datareposity'
});
exports.default = sql;
//# sourceMappingURL=db.js.map
```

I ensure that `compileOption.target` in `tsconfig.json` is `"es2017"`, but I do not konw why it compile to commonjs format.

**Comment by onsummer** [comment]
> @onsummer change your db password ASAP!

Thank you, do not worry, this is a test database for test only, then will delete later.

**Comment by onsummer** [comment]
When I change `compilerOptions.module` to `"esnext"`(or other es format) in `tsconfig.json`, the error turn to be nestjs', like:

```
Error: Cannot find module 'dist\src\app.module' imported from dist\src\main.js
```

**Comment by ngotowczyc** [comment]
I am not sure what exactly this option does, but it works when I add 
`"esModuleInterop": true`
option to `tsconfig.json`.

Is this the right solution?

**Comment by porsager** [comment]
Yes `"esModuleInterop": true` is the correct solution.

See https://itnext.io/great-import-schism-typescript-confusion-around-imports-explained-d512fc6769c2 for more info

**Comment by onsummer** [comment]
@ngotowczyc @porsager Thank you very much!!
