### ISSUE TITLE
Deno: Ensure deno can cache all modules from registry.

### ISSUE THREAD

**Issue by hastebrot** [porsager/postgres#298]
>If you figure out a way we can fix the querystring issue with a change to Postgres.js let me know and I'll include that.

_Originally posted by @porsager in https://github.com/porsager/postgres/issues/287#issuecomment-1080445334_

**Comment by hastebrot** [comment]
A possible solution would be to let `[transpile.deno.js](https://github.com/porsager/postgres/blob/master/transpile.deno.js)` add  `import "https://deno.land/std@0.120.0/node/querystring.ts"` to the source file where it is needed.

**Comment by hastebrot** [comment]
My guess is that `querystring.ts` is used by node legacy `Url` and somehow included from  `fs`, `os`, `process`, `buffer`, or `stream`. I'll add the `querystring.ts` import to `deno/polyfills.js` and test it.

**Comment by hastebrot** [comment]
Updated to `std@0.132.0` and it worked without need for `--allow-net=deno.land`.

**Comment by porsager** [comment]
If I understood you correctly you didn't find any issue with 0.132, so I've updated to that now and also enabled the remaining 3 tests for deno.

I think that solves this issue, but if not - please reopen.
