### ISSUE TITLE
Omitting pathname on database url generates "Cannot read property 'slice' of null" error

### ISSUE THREAD

**Issue by Blitzsturm** [porsager/postgres#3]
Not likely to be a common problem but easy to fix; omitting a slash at the end of the url if you want to connect to the default database generates an error:

**Error generating example:**
```javascript
var sql = postgres("postgres://username:password@database.domain.com");
var res = await sql`SELECT 1 AS one;`;
await sql.end();
// > TypeError: Cannot read property 'slice' of null
// > at parseOptions (...\node_modules\postgres\lib\index.js:474:55)
```
**No Error generating example:**
```javascript
var sql = postgres("postgres://username:password@database.domain.com/");
var res = await sql`SELECT 1 AS one;`;
await sql.end();
// > No error
```

\[_**Proposed fix @ [index.js:457](https://github.com/porsager/postgres/blob/8ad6ae421f2aae7081ee5f9294f2edbf918a2686/lib/index.js#L457) (cursor branch)**_\]

**Update line from:**
```javascript
    database    : o.database || o.db || url.pathname.slice(1) || env.PGDATABASE || 'postgres',
```
**to:**
```javascript
    database    : o.database || o.db || url.pathname && url.pathname.slice(1) || env.PGDATABASE || 'postgres',
```

**Comment by porsager** [comment]
Ah that's really interesting. So node's `url.parse()` only defaults to a `'/'` pathname if the protocol is http or https. 

Thanks a lot :) I'll get that fixed and add some tests too..
