### ISSUE TITLE
Doesn't work with ts

### ISSUE THREAD

**Issue by weinr0ck** [porsager/postgres#301]
I'm unable to use this library with the nest.js depedency injection system. I have the following module
```
import { PostgresClientConfig } from './postgres-client-config';
import { PostgresClientWrapper } from './postgres-client-wrapper';
import postgres from 'postgres';

export class PostgresClientFactory {
  static create(config: PostgresClientConfig): PostgresClientWrapper {
    return new PostgresClientWrapper(postgres(config));
  }
}
```
The config is a very simple interface
```
export interface PostgresClientConfig {
  host: string;
  port: number;
  username: string;
  password: string;
  database?: string;
  max: number;
  idle_timeout: number;
  connect_timeout: number;
  ssl: boolean;
}
```
Now, when I start my server I get the error
```
ERROR [ExceptionHandler] postgres_1.default is not a function
TypeError: postgres_1.default is not a function
    at Function.create (/Users/weinr0ck/my-project/dist/apps/server/core/webpack:/rak-core/libs/server/shared/postgres/src/lib/postgres-client.factory.ts:7:46)
```

**Comment by porsager** [comment]
Haha :) Literally just closed this yesterday ;) https://github.com/porsager/postgres/issues/297

Set `"esModuleInterop": true` in TS configs and you're good to go.

**Comment by weinr0ck** [comment]
Also, I'm kind of new to ts. I didn't see an exported class or an interface I can use for typing purposes. That's why I used a wrapper class. Is there something I'm missing?

**Comment by weinr0ck** [comment]
> Haha :) Literally just closed this yesterday ;) #297
> 
> Set `"esModuleInterop": true` in TS configs and you're good to go.

This doesn't work for my setup. I get the following error
```
/Users/weinr0ck/my-project/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:15
    class MixinStrategy extends Strategy {
TypeError: Class extends value #<Object> is not a constructor or null
    at Object.PassportStrategy (/Users/weinr0ck/my-project/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:15:33)
    at Object../libs/server/authentication/src/lib/auth/keycloak.strategy.ts (/Users/weinr0ck/my-project/dist/apps/server/core/webpack:/my-project/libs/server/authentication/src/lib/auth/keycloak.strategy.ts:8:39)
```

**Comment by porsager** [comment]
I'm not very fond of TS, so probably the wrong person to ask :P This doesn't appear to be Postgres.js related.

**Comment by hfhchan** [comment]
You can also use `import * as postgres from 'postgres';` instead for ts if you don't want to enable `"esModuleInterop": true`.

**Comment by porsager** [comment]
Thanks a lot @hfhchan - very useful for future searches!

**Comment by Minigugus** [comment]
There's also `"skipLibCheck": false,` that works with `"esModuleInterop": true` (your issue is that TS type-check dependencies)
