### ISSUE TITLE
ORDER BY 'PostgresError: syntax error 

### ISSUE THREAD

**Issue by TGlock** [porsager/postgres#306]
The code below results in a 'PostgresError: syntax error at or near "$2"

`let fld = 'uname',
     dir = 'ASC';`

``let qry = sql`SELECT id, email, dname, uname, dt_create FROM tbl_user order by ${ fld } ${ dir };``

`let res = qry.execute()`

causes error **PostgresError: syntax error at or near "$2"**

statement shows:  `SELECT id, email, dname, uname, dt_create FROM tbl_user order by $1 $2;`

parameters:(2)` ['uname', 'ASC']
0:'uname'
1:'ASC'`

Any help is appreciated!

**Comment by porsager** [comment]
Keywords need to be tagged template literals. And identifiers need to be wrapped in `sql()`, so you query should look like this perhaps? 

```js
sql`
  select 
    id, email, dname, uname, dt_create 
  from tbl_user 
  order by ${ fld === 'ASC' ? sql`asc` : sql`` } ${ sql(dir) }
`

```

**Comment by TGlock** [comment]
THANk YOU!   Understanding **Keywords need to be tagged template literals. And identifiers need to be wrapped in sql()**  is critical!

And understanding that led to correct query below.  

qry = sql`
    select
      id, email, dname, uname, dt_create
    from tbl_user
    order by ${ sql(fld) } ${ dir === 'ASC' ? sql`asc` : sql`desc` } ;`
