### ISSUE TITLE
local `peer` authentication

### ISSUE THREAD

**Issue by ryanmjacobs** [porsager/postgres#308]
This functionality doesn't seem to be supported. I believe it works with `pg` on `npm`.

I might dig into adding this support. Any input would be nice. Maybe it is already supported but I'm not passing a flag...

---

(PS: This library is amazing! Thank you for such an awesome package.)

**Comment by porsager** [comment]
Thank you for the kind words :)

It should work though, how are you connecting? (can you paste your connection parameters?)

**Comment by porsager** [comment]
I'll close this out, but would love to have a reproducible sample to check this out if you could post that - then we'll reopen ;)

**Comment by Henry-Hiles** [comment]
I seem to be having this issue. If I `sudo -u degoog node`, and in there do something like:
```js
const postgres = require("postgres");
await postgres("postgresql://degoog@localhost?host=/var/run/postgresql")`select current_user`
```

I get an error: `password authentication failed for user "degoog"`.

However, if I instead `sudo -u degoog psql "postgresql://degoog@localhost?host=/var/run/postgresql" -c "select current_user"`, that works fine.

**Comment by Henry-Hiles** [comment]
Hmm, it's worth noting that:
```js
await postgres({host: "/var/run/postgresql", username: "degoog", database: "degoog"})`select current_user`
```
Does work. So, the issue is in the URI / this package's handling of the URI.

**Comment by Henry-Hiles** [comment]
Could this issue be re-opened, or should I make a new one @porsager?
