### ISSUE TITLE
Subscribe error handling

### ISSUE THREAD

**Issue by megous** [porsager/postgres#315]
Please consider improving subscribe error handling. Currently I can catch the initial rejection:

```
sql.subscribe('*', (row, {command, relation, key, old}) => {
         console.log(command, relation.schema + '.' + relation.table, row, key, old);
}).catch(ex => {
        console.log('SUBSCRIBE FAILED', ex);
});
```

But there's no way to catch failures happening later on or success if initial attempt fails, but later one succeeds. (promise is already settled) Promises are probably not the right interface here, when subscribe seems to be doing auto-recovery and connection retries under the hood. Something like EventEmitter or config object with user supplied onconnect/ondisconnect callbacks would be more useful. In any case subscribe generates periodical unhandled rejections for any subsequent retries after the first failure, which are not possible to handle from the app code.

Ideally, the app should be able to catch two events whenever they happen: when the connection is established and when it's lost. At that point the app can perform whatever is needed to handle potentially missed events in between.

BTW, being able to use user defined slots instead of ephemeral ones might be also a useful feature. That way it may be possible to not lose changes in between reconnects, too. ;)

**Comment by megous** [comment]
Or alternatively don't re-try the subscribe automatically and leave it to the app code.

**Comment by megous** [comment]
That would still need an interface change, though, because promise returned from sql.subscribe would already be settled if some connection error happens on already established connection, later on, so there would no longer be possible to reject it to indicate the failure.

**Comment by porsager** [comment]
@megous Yeah, that should definitely be improved. 

There is a discussion here https://github.com/porsager/postgres/discussions/311 about defining slot name and lsn.

The current use case is very much targeted at having optimistic delivery of change events. I think for that use case you don't want your service to be able to hold the db back wrt. undelivered changes, so focusing on improving the success/error handling in this issue would be good, and then we can continue the named slot in the other discussion or a PR?

**Comment by megous** [comment]
Yes, please ignore my suggestion about persistent slots. That was just a fleeting idea. Connection state reporting and better recovery without unhandled rejections from within the library are the core of this issue.

**Comment by porsager** [comment]
@megous I've recently added a 3rd function for listen that will be called on first connect and reconnects. I think the same functionality should be added to subscribe.

The reasoning behind returning a promise was that your first connect should expose any issues with the configuration / setup, and if that succeeded reconnection on various failures should be implicit. It's the same reasoning behind the listen functionality. Then if you need to do something on connect+reconnect that 3rd function can be used.

I can see an issue with that setup if eg. your service starts while the db is down, and the subscribe / listen throws. In that case you could simply retry / restart your service, but perhaps you'd just like it to go into reconnecting instead.

Would you think adding the 3rd function `onsubscribe` is sufficient, or do you need the errors on reconnect for some reason?

**Comment by megous** [comment]
@porsager Thank you. I'll have to play with it a bit to see whether onsubscribe will be enough. It will certainly cover the need to perform a re-sync after disconnect, which is the most important thing. My original idea for onerror was to be able to inform websocket clients or sysadmin about a degraded state of the system (so that clients can temporarily switch to polling mode). But I guess there will not be many situations at runtime where subscibe fails but other DB requests work. Either way, it should be quite easy to add it myself at this point, after your refactoring. Thanks again. :)
