### ISSUE TITLE
question: how to dynamically return a column list (returning)? 

### ISSUE THREAD

**Issue by fessacchiotto** [porsager/postgres#317]
hi! sorry if i overlooked this in the documentation.
is it possible to do something like this:
```
const a = 100
const columns = ['a', 'b', 'c']
sql`
   update table set a=${a} returning ${columns}
`
```
i tried using the sql helper and array joined string but without luck.
tia

**Comment by porsager** [comment]
Hey :) 

No that's a missing feature, and should definitely be supported! It should work like this:

```
const a = 100
const columns = ['a', 'b', 'c']
sql`
   update table set a=${ a } returning ${ sql(columns) }
`
```

I'll look into getting support for that added.
