### ISSUE TITLE
sql.end({timeout: null}) hangs

### ISSUE THREAD

**Issue by ffissore** [porsager/postgres#32]
Hi and thanks for making this driver available. I'm evaluating it as a replacement to pg-promise.

Our tests hangs in the teardown phase if we end the connection with `sql.end({timeout: null})`. This is due to the implementation of `socket.end` available in version 1.0.2
```
    end: () => {
      return new Promise(r => socket && socket.end(r))
    }
```
If there's no socket, `r` is never called.

This has been fixed in 4156c3f2fddf5c6694a3877b5d3516f16f55ba48 but it hasn't been released yet. Can you please release a new version?

**Comment by ffissore** [comment]
Uhm after further investigation, the mentioned change is not enough. We still cannot end gracefully the connection. `connection.end` is `() => ready && ended()`, and `ready` is false despite `backend.query` being `undefined` and `queries.length` being 0

**Comment by porsager** [comment]
Thanks for the investigation @ffissore .. I'll look closer at it tomorrow

**Comment by porsager** [comment]
Hey @ffissore .. I can't replicate it with `master`.. Would you mind trying? 

I'll do a release soon if that works for you.

**Comment by ffissore** [comment]
I tried to dig deeper, and what I ended up with is a situation in which I have 5 connections in the pool, even though I run 3 queries only. Apparently these 2 stale connections come from this create db statement I have in my code
```
this.sql `CREATE DATABASE ${this.sql(this.database)} OWNER = ${this.sql(this.options.username)}`
```

If I turn it into
```
this.sql.unsafe(`CREATE DATABASE ${this.database} OWNER = '${this.options.username}'`)
```
it works as expected (it doesn't block at `end`)

Hope this helps

**Comment by porsager** [comment]
Was this with all the recent commits on master?

**Comment by ffissore** [comment]
Yes, I'm using latest master (commit 60dc30f922857ff1159a157b041521345804c64c)

While investigating, I've stumbled on a slightly different problem, although maybe related. I have this test script
```js
const postgres = require('postgres')

const sql = postgres({
	username: 'federico'
})

async function main () {
	await sql`select version()`
	await sql`select version()`
	await sql`select version()`
	await sql`CREATE DATABASE ${sql(`test_${parseInt(Math.random() * 1000)}`)} OWNER = ${sql('federico')}`
	await sql.end({ timeout: null })
}

main()
	.then(() => {
		console.log('done')
	})
	.catch((e) => {
		console.log('catch', e)
	})
```
I would expect it to print `done` and terminate, instead it just terminates, with exit code 0 (all good), and without printing anything. But how? This looks to me like a basic nodejs thing I'm missing

Also, by modifying the driver code this way
```patch
diff --git a/lib/index.js b/lib/index.js
index e9c9bfb..dd9258d 100644
--- a/lib/index.js
+++ b/lib/index.js
@@ -354,8 +354,17 @@ function Postgres(a, b) {
 
     let destroy
 
+    let values
+
+    setInterval(() => {
+      console.log(values)
+    }, 1000)
+
     return ended = Promise.race([
-      Promise.resolve(arrayTypesPromise).then(() => Promise.all(all.map(c => c.end())))
+      Promise.resolve(arrayTypesPromise).then(() => {
+        values = all.map(c => c.end())
+        return Promise.all(values)
+      })
     ].concat(
       timeout === 0 || timeout > 0
         ? new Promise(r => destroy = setTimeout(() => (all.map(c => c.destroy()), r()), timeout * 1000))
```

and re-running the script, it doesn't terminate (expected: there's a running `interval`), and it prints
```
[
  Promise { undefined },
  Promise { undefined },
  Promise { undefined },
  Promise { <pending> },
  Promise { <pending> },
  Promise { undefined }
]
```

which confirms what I've previously reported. Some promises passed to `Promise.all` stay `pending` and never resolve

**Comment by ffissore** [comment]
More on the above weirdness. It suffices to print the create statement to make it behave strangely
```js
console.log(`CREATE DATABASE ${sql(dbname)} OWNER = ${sql('federico')}`)
// await sql`CREATE DATABASE ${sql(dbname)} OWNER = ${sql('federico')}`
```
However if you comment out both lines, it behaves correctly: it prints `done`

**Comment by ffissore** [comment]
For the record, I'm using node v12.16.0 (latest LTS)

**Comment by Minigugus** [comment]
> I would expect it to print `done` and terminate, instead it just terminates, with exit code 0 (all good), and without printing anything. But how? This looks to me like a basic nodejs thing I'm missing

NodeJS exits when the Event Loop is empty, which happen when the callback function passed to the Promise constructor never calls the resolve function (`new Promise(resolve => { /* not calling 'resolve' */ })`). It's therefore a real bug.

> 

> More on the above weirdness. It suffices to print the create statement to make it behave strangely
> 
> ```js
> console.log(`CREATE DATABASE ${sql(dbname)} OWNER = ${sql('federico')}`)
> // await sql`CREATE DATABASE ${sql(dbname)} OWNER = ${sql('federico')}`
> ```

It's normal that ```console.log(`CREATE DATABASE ${sql(dbname)} OWNER = ${sql('federico')}`)``` behave strangly as the `sql` template string tag transforms parameters before concatenation. `sql(dbname)` and `sql('federico')` thus returns objects and not strings. Try ```console.log`CREATE DATABASE ${sql(dbname)} OWNER = ${sql('federico')}` ``` to see what is really passed to the `sql` template tag.

**Comment by ffissore** [comment]
It took me while but I got the reason of the weirdness. The promises created [here](https://github.com/porsager/postgres/blob/60dc30f922857ff1159a157b041521345804c64c/lib/connection.js#L88), which are then used as arguments [here](https://github.com/porsager/postgres/blob/60dc30f922857ff1159a157b041521345804c64c/lib/index.js#L358) don't run anything asynchronously.
They are a way to provide `ended` with a `resolve`, but `ended` is never called, so these promises are *empty*: they don't put anything in the event loop, and my script above terminates even if the call to `sql.end()` is a pending promise

I'll keep digging for the reason why my tests hang when calling sql.end

**Comment by ffissore** [comment]
So, the best thing I could come up with is #34

**Comment by porsager** [comment]
Hey @ffissore . I've been trying hard to replicate this with latest master, but so far no luck. Is there any chance you could post a reproducible test case?

**Comment by porsager** [comment]
Ok, I'm pretty sure this is solved now, but do reopen if you experience any issues. Thanks.
