### ISSUE TITLE
Expanding array inside `FROM (VALUES ${array})` clause

### ISSUE THREAD

**Issue by eighty-three** [porsager/postgres#321]
When running this in my code:
```    
await sql`
      INSERT INTO teams (name, used, team_id, company_id)
        SELECT (ut.name, ut.used, ut.team_id, ut.company_id)
        FROM (VALUES ${sql(teams)}) AS ut (name, used, team_id, company_id, is_default)
          INNER JOIN accounts a1 ON a1.company_id = ut.company_id
          INNER JOIN accounts a2 ON a2.username = a1.username
          WHERE LOWER(a2.username) = ${username}
          AND ut.is_default = false
      ON CONFLICT (team_id) DO
      UPDATE SET name = EXCLUDED.name, team_id = EXCLUDED.team_id, company_id = EXCLUDED.company_id, used = EXCLUDED.used;
    `;
```
It throws this error:
`PostgresError: table "ut" has 3 columns available but 5 columns specified`

Because the `teams` array has 3 items. When `teams.length === 5`, it showed this error instead: 
`PostgresError: operator does not exist: integer = text`

I am not sure if it's a matter of syntax because when I ran the query manually, it worked:
```
INSERT INTO teams(name, used, team_id, company_id) 
        SELECT ut.name, ut.used, ut.team_id, ut.company_id
        FROM (VALUES ('t1', true, '123456789123456789x1', 2, false), ('t2', true, '123456789123456789x2', 1, false)) AS ut(name, used, team_id, company_id, is_default) 
        	INNER JOIN accounts a1 ON a1.company_id = ut.company_id
        	INNER JOIN accounts a2 ON a2.username = a1.username
        	WHERE LOWER(a2.username) = 'admin'
        	AND is_default = false
ON CONFLICT (team_id) DO
UPDATE SET name = EXCLUDED.name, team_id = EXCLUDED.team_id, company_id = EXCLUDED.company_id, used = EXCLUDED.used;


INSERT 0 1
```

The issue seemed similar to #248 so I've tried to use `sql.array` and `sql.json` like in the comment (I'm not sure where to find those in the docs so I just messed around), but sadly to no avail...

**Comment by eighty-three** [comment]
In case it's relevant:
```
CREATE TABLE IF NOT EXISTS teams(
  id SERIAL PRIMARY KEY,
  name CITEXT NOT NULL,
  used BOOLEAN NOT NULL DEFAULT TRUE,
  company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
  team_id CHAR(20) NOT NULL UNIQUE,
  is_default BOOLEAN NOT NULL DEFAULT FALSE
);
```

The `teams` variable is of type `ITeam[]`:
```
interface ITeam {
  name: string;
  used: boolean;
  team_id: string;
  company_id: number;
  is_default: boolean;
}
```

**Comment by porsager** [comment]
> Because the teams array has 3 items.

The `values` helper expects an array of values for single row insert, or an array with arrays of values for multi row insert. 

Perhaps your "rows" are objects instead of arrays?

**Comment by eighty-three** [comment]
> Perhaps your "rows" are objects instead of arrays?

Yes like I said it's of type `ITeam[]`. I see, so is this what I'm supposed to do to make use of the `values` syntax?

```
  const fixedTeams = teams.map((team) => [
    team.name,
    team.used.toString(),
    team.team_id,
    team.company_id,
    team.is_default.toString(),
  ]);
//  [
//    [
//      'YgNQ4wOP-FfzYm3KCxbq7',
//      'true',
//      3,
//      'aILT1DadnicjDsYfgYet',
//      'false'
//    ],
//    [ 'asd', 'true', 3, 'lXzR08YivNsL9J0orYik', 'false' ],
//    [ 'b', 'true', 3, 'ZkBaddDINMsKjnYj2ezP', 'false' ]
//  ]

...

await sql`
      INSERT INTO teams (name, used, team_id, company_id)
        SELECT (ut.name, ut.used, ut.team_id, ut.company_id)
        FROM (VALUES ${sql(fixedTeams)}) AS ut (name, used, team_id, company_id, is_default)
          INNER JOIN accounts a1 ON a1.company_id = ut.company_id
          INNER JOIN accounts a2 ON a2.username = a1.username
          WHERE LOWER(a2.username) = ${username}
          AND ut.is_default = false
      ON CONFLICT (team_id) DO
      UPDATE SET name = EXCLUDED.name, team_id = EXCLUDED.team_id, company_id = EXCLUDED.company_id, used = EXCLUDED.used;
    `;
```

I've also had to turn the booleans into a string too because it was complaining about this type:
`type EscapableArray = (string | number)[]`

Regardless, it's still not working, throwing this error instead:
`PostgresError: operator does not exist: integer = text`
At least it's not mentioning  the initial `table has x columns available but y columns specified` anymore, even with just 3 teams it's going straight to this error.



I've tried simplifying the query into this:
```
    const fixedTeams2 = teams.map((team) => [team.name, team.used, team.company_id, team.team_id, team.is_default]);
    ...
    const query = await sql`
      SELECT * FROM (VALUES ${sql(fixedTeams2 as any)}) AS ut(name, used, company_id, team_id, is_default)
    `;
    console.log(query);
Result(3) [
  {
    name: 'YgNQ4wOP-FfzYm3KCxbq7',
    used: true,
    company_id: '3',
    team_id: 'aILT1DadnicjDsYfgYet',
    is_default: false
  },
  {
    name: 'asd',
    used: true,
    company_id: '3',
    team_id: 'lXzR08YivNsL9J0orYik',
    is_default: false
  },
  {
    name: 'b',
    used: true,
    company_id: '3',
    team_id: 'ZkBaddDINMsKjnYj2ezP',
    is_default: false
  }
]

```
And it seems to be working, just that the returned value for the `company_id` has been turned into a `string`, from its original `number` type. I guess that's where the error is coming from? I tried forcing the matter with regards to `EscapableArray[]` error I mentioned earlier using `any` and it seems to have worked properly too btw.

**Comment by eighty-three** [comment]
I've managed to make it work with this (I've changed the query too because there were some issues with it previously :sweat_smile: ):
```
    const fixedTeams = teams.map((t) => [t.name, t.used, t.company_id, t.team_id, t.is_default]);
    await sql`
      WITH ut AS (
        SELECT utt.name, utt.used, utt.company_id::int, utt.team_id
          FROM (VALUES ${sql(fixedTeams as any)})
        AS utt(name, used, company_id, team_id, is_default)
        WHERE utt.is_default = false
      )
      INSERT INTO teams (name, used, company_id, team_id)
      SELECT DISTINCT ON (team_id) ut.name, ut.used, ut.company_id, ut.team_id FROM ut
        INNER JOIN teams t ON
          ((t.team_id = ut.team_id AND t.company_id = ut.company_id)
          OR t.team_id < ut.team_id)
        INNER JOIN accounts a1 ON a1.company_id = ut.company_id
        WHERE LOWER(a1.username) = ${username}
      ON CONFLICT (team_id) DO
      UPDATE SET name = EXCLUDED.name, team_id = EXCLUDED.team_id, used = EXCLUDED.used;
    `;
```
1. I've had to cast the `company_id` into an `int`, otherwise it keeps throwing this error: 
`PostgresError: operator does not exist: integer = text`
2. Also, I've had to assert the `any` type (it could probably have been better but...)` because it was complaining about this:
![Screenshot from 2022-04-17 23-25-39](https://user-images.githubusercontent.com/60061977/163721149-c3580229-4f47-497e-8645-ade4880c97e4.png)

I'd appreciate it if you can point out whether or not I just went at it the wrong way (e.g. there's some method I should have used like `sql.array(fixedTeams)` instead of `sql(fixedTeams)` so I can avoid asserting the `any` type, or if there's a way I could've avoided casting `company_id` to `int`). Otherwise I'm fine closing this issue since I was able to work around the problems I encountered anyway

**Comment by porsager** [comment]
As I see it, casting to int is necessary because you're comparing to an int column later in your query. 

And ```sql(fixedteams) ``` is the right way to go about it 😊 Supporting arrays of objects would be too brittle since we often don't know the order of the keys. (unless specified explicitly, then we could. Perhaps that's something to explore.

**Comment by eighty-three** [comment]
Thank you for the advice, good to know I didn't miss anything that important. Re: arrays of objects, that makes sense. If you specify it I guess it really wouldn't be all that different from the way it has been mapped :D
```
  sql.someNewMethod(arrayOfObjects, ['order', 'of', 'keys']);

  vs
  
  const fixedArray = array.map((i) => [i['order'], i['of'], i['keys']]);
  sql(fixedArray);
```

But anyway, closing the issue. Thanks again!
