### ISSUE TITLE
Parameter not assignable to string for json insert

### ISSUE THREAD

**Issue by alextes** [porsager/postgres#324]
In version 2 I used to pass a string for a jsonb column and all would be well. In v3 the library would also stringify making it double stringified and breaking the queries into the jsonb column.

So I changed my input to be just the object and let the library handle the stringify, great, but now I get a type error.

```ts
import postgres from "postgres";

const sql = postgres({
  user: "postgres",
});

const rows = await sql`
  INSERT INTO example
    ${sql([{ name: "alex", value: { age: 29 } }])}
`;

console.log(rows);
```

Truncated version is:
```
 Type '{ age: number; }' is not assignable to type '{ age: number; } &
      SerializableParameter'.
```

**Comment by porsager** [comment]
Yes, v3 get's the input types from the db so it knows to call JSON.stringify, but I realize I'm missing this specific difference in the changelog for v3 so I should mention that too.

About the types I don't use Typescript, so if you can figure out a fix, we can get that in ;) @Minigugus might be able to help here.

**Comment by eugene1g** [comment]
@alextes An alternative solution is to do what you did in V2: serialize `jsonb` yourself, then pass the string parametr to `postgres`. I had a similar issue but needed full control over how `jsonb` values are serialized, so had to tell postgres to use those values as provided by overriding their type - 
```js
const sql = postgres({
// ...
types: {
  jsonb: {
    to: 3802, // PG oid for jsonb
    from: [3802],
    serialize: (value)=>value,
    parse: (x: string | null) => (x ? JSON.parse(x) : null)
  }
})
```
