### ISSUE TITLE
Release for working Deno?

### ISSUE THREAD

**Issue by tmikaeld** [porsager/postgres#325]
I'm really struggling with getting this to work on Deno, first it was the Buffer issue (that's fixed) and so I tried running from the latest master, but then I get the `Property 'FsFile' does not exist on type 'typeof Deno'` error.

How do I compile it locally to work for deno?

**Comment by Tricked-dev** [comment]
update your Deno version

**Comment by tmikaeld** [comment]
Upgrading my deno version solved the `FsFile` issue, i pulled from master for now, seems to work.

**Comment by porsager** [comment]
Yeah, it should work out of the box for the latest Deno version. Feel free to re-open if that isn't the case 😉

**Comment by tmikaeld** [comment]
@porsager It does work, but only from master due to https://github.com/porsager/postgres/issues/312 not being in a release yet.

**Comment by porsager** [comment]
Oh my. I thought I had gotten that released 😩 I'll release a new version with it tonight.

**Comment by tmikaeld** [comment]
@porsager No stress, I got it working! Thanks for the awesome lib, I love the simplicity of it 👍

**Comment by porsager** [comment]
Awesome - Thanks a lot ❤️

Just to be sure, it's working with no "workarounds" from master for you - correct?

**Comment by tmikaeld** [comment]
@porsager Almost, I have to run it with --unstable flag due to `Deno.unrefTimer is not a function`, I would have preferred the stable variant, since I plan on using this in production soon.

**Comment by porsager** [comment]
Ah I see. Is that really the only unstable feature used? I thought there were more 🧐

**Comment by tmikaeld** [comment]
@porsager there might be more, but this was the only one I got so far.

**Comment by tmikaeld** [comment]
Latest Deno has come a long way though, pushing new features to stable all the time :)

**Comment by porsager** [comment]
That would be really great! 🎉 I just realized that the unref is actually unnecessary since some improvements I've made to reconnect handling - I'll get that removed before release, so you don't need unstable.

It seems the only one left as unstable is Deno.connect(unixSocket), but if you don't use that you should be good :)

**Comment by tmikaeld** [comment]
I don’t need a sock proxy to connect, if that’s what it is? So should be good 👍

**Comment by hastebrot** [comment]
> Is that really the only unstable feature used? I thought there were more 🧐

Node compatibility mode in Deno currently needs `--unstable` flag.

> Using compatibility mode currently requires the `--unstable` flag. 
> &mdash; https://deno.land/manual@v1.20.6/node/compatibility_mode

**Comment by porsager** [comment]
@hastebrot Postgres.js doesn't use node compatibility mode, but the polyfills directly.
