### ISSUE TITLE
Inserts do not allow partial queries with parameters

### ISSUE THREAD

**Issue by michaellat** [porsager/postgres#326]
Hi, I'm in a situation where I'm trying to do something like this:
```			await sql`
				INSERT INTO article ${sql(
					articles.map((article) => ({
						article.id,
						someValue: sql`EXISTS(SELECT 1 FROM article WHERE id = ${ anotherId })`
					}))
				)}`;```

This results in my query being:
`INSERT INTO article (id, someValue) VALUES ($1, EXISTS(SELECT 1 FROM article WHERE id = ))`

It looks like while I can pass an array of objects into the insert as the documentation specifies, even with partial queries, I cannot add parameters to them as it just comes back as blank.

**Comment by porsager** [comment]
Very nice @michaellat - thank you - that functionality should be supported, but for some reason it's not - I was sure I had made that, but tests for it are missing too 🧐
