### ISSUE TITLE
Share: Migration Tool

### ISSUE THREAD

**Issue by lukeed** [porsager/postgres#33]
Hey~! 

> Feel free to insta-close this by the way. Didn't know how else to contact you :)

I discovered `postgres` a few weeks ago & just started migrating some of my projects over to it. It's working great so far :)

One roadblock I ran into was the lack of a migration tool.
All the ones I've used in the past were made explicitly for a particular client driver, which meant I had to keep `pg` installed _just_ so that I could continue running migrations.

I didn't like that – so I made [`ley`](https://github.com/lukeed/ley) that I could use `postgres` purely!

It relies on ENV vars for connection by default (`PGHOST`, `PGUSER`, etc). You can use something like `dotenv` to load them up:

```sh
$ ley -r dotenv/config up
$ ley -r dotenv/config down
```

You can also add a `ley.config.js` file to project root to declare a config object.

**Note:** It's only _not_ 1.0 because I fell into a nice abstraction that can easily accomodate any/all client drivers. Of course, `postgres` was the first one I added. Once I add another 2-3 drivers I'll consider it done.

That's all from me. Keep up the great work~!

**Comment by porsager** [comment]
Hey @lukeed 👋 Thanks!

That looks really cool!! I'll see if I can have a chance to play around with it one of these days..

I'm using my own [forwards only migration tool](https://github.com/porsager/postgres-shift) at my company, but I didn't get further than make it work for our needs, so it's still lacking docs, and could do with a bit more dog-fooding :P It's very basic, but it allows us much freedom in our migrations, and just ensures that migrations run in order and in a single transaction..

I'll keep this issue open for now, it's great if people are looking for a migration tool, which there has already been questions related to :)

**Comment by lukeed** [comment]
Ah, I should have searched your profile 😉 

But truth be told, I needed a runner that was compatible with existing systems _and_ one that didn't enforce a client lock-in. Forward-only is definitely the way to go (it's what I do too) but again, compatibility with existing systems.

One important thing I forgot to mention is that the `exports.up` and `exports.down` functions within each migration file receives the `postgres` client directly. There's no stupid/ugly abstraction you have to learn in order to run your migrations. Instead, you're using the [`sql` template literals directly](https://github.com/lukeed/ley/blob/master/test/postgres/migrations/001.js), just like you would anywhere else.

**Comment by porsager** [comment]
Nah, I don't think postgres-shift is of much use to anyone but me right now 😋

`ley` looks really great! It's definitely nice how you'll just use the client api you're used to!

Maybe it could support forward-only migrations too? :) I guess it already does if you only ever use `up` - hehe..

**Comment by lukeed** [comment]
Thanks! Yeah, that decision is up to you & your team. `ley` will never run a `down` migration unless you tell it to – and you can certainly guarantee that by never writing a `down` task 😆

**Comment by tamino-martinius** [comment]
As this thread is about sharing - i also wrote my [own package](https://www.npmjs.com/package/@nextcode/postgres-migrator) which might be a little bit overkill for most use cases as its USP is that you can define how migrations are dependant and it migrates as much in parallel as possible - useful if you have a lot of migrations and you care about some milliseconds - but can also be used _normally_

**Comment by lukeed** [comment]
Cool! It's a bit much for what I've ever needed but looks good 👍
