### ISSUE TITLE
Add `bigint` to `Serializable` type

### ISSUE THREAD

**Issue by rafaelcr** [porsager/postgres#330]
While using this library in TypeScript (`es2020`), it's currently not possible to interpolate a `bigint` variable into an `INSERT` query, like so:
```typescript
import postgres from "postgres";

const sql = postgres({});
export default sql;

export function hello() {
  const num: bigint = BigInt(109810981098); 
  sql`INSERT INTO test VALUES (${num})`;
}
```
Error is: `Argument of type 'bigint' is not assignable to parameter of type 'SerializableParameter | PendingQuery<any>'.`

The [`Serializable` type](https://github.com/porsager/postgres/blob/9628118c9d4574c2095fc8c60a4ce41b95b61ea5/types/index.d.ts#L453) should allow `bigint` as well.

**Comment by porsager** [comment]
I hope that fix is enough ;)

**Comment by rafaelcr** [comment]
thanks for the quick turnaround @porsager ! appreciate it
