### ISSUE TITLE
Inserting object with no columns: No overload  matches this call

### ISSUE THREAD

**Issue by kryptus36** [porsager/postgres#331]
I just upgraded to 3.1.0 and this broke:
```js
await sql`INSERT INTO mytable ${ sql(object) }`;
```
Does not work. I have to list all the columns:
```js
await sql`INSERT INTO mytable ${ sql(object, 'col1', 'col2') }`;
```
Works as expected, but is much less convenient.

**Comment by porsager** [comment]
Seems to work fine - Is this a typescript issue?

**Comment by kryptus36** [comment]
It must be - I was previously on the rewrite branch and it was fine. Any ideas on what might have changed?

**Comment by porsager** [comment]
I wouldn't know - perhaps @Minigugus who contributed the types has an idea?

**Comment by kryptus36** [comment]
Found a hiint: It has something to do with an optional parameter in my class. It becomes non-optional when passed in to postgres. 

Property 'parentId' is optional in type 'Page' but required in type 'Record<"name" | "home" | "id" | "parentId" | "sort" | "type" | "urlSlug" | "published" | "hidden", SerializableParameter>'.

**Comment by kryptus36** [comment]
Sorry for the noise, but in case it's helpful:

I'm pretty sure it's to do with line 160 in the index.d.ts file. I don't understand it well enough to fix it properly, but if I replace it with "any", Typescript stops complaining.

**Comment by kryptus36** [comment]
One final update that makes me wonder if this is a bug or a feature (and that's not sarcasm).

Instead of using 

parentId?: string

I used

parentId: string | null

Problem solved. But I think this might need to be documented or others will run into it.

**Comment by Minigugus** [comment]
@kryptus36 Yes it's kind of feature, because if you pass an object like `{ aColumn: undefined }`, `postgres` will throw with a `UNDEFINED_VALUE` error since the value passed to the column is `undefined`:

https://github.com/porsager/postgres/blob/eab71e5936ca8658e19af853a957ea5fb99ca991/src/types.js#L169-L173

I tried to prevent these kind of errors with types but I agree sometimes they can be a bit confusing. But at least you don't get unexpected runtime errors :laughing:

**Comment by eezing** [comment]
@porsager @Minigugus Need to reopen this. The type doesn't match the behavior when column is JSON.

Postgres.js will JSON.stringify if column type is json:
https://github.com/porsager/postgres/blob/e0483a58f3554cf5b107093b9ecac51cddb95463/src/types.js#L16-L21

This is valid in JavaScript but not in TypeScript:
![Screen Shot 2022-04-28 at 9 24 33 AM](https://user-images.githubusercontent.com/6968110/165800525-0bd78009-3093-4197-86c0-bff4b2679e3c.png)

**Comment by Minigugus** [comment]
@eezing I was concerned with that case because types would allow `{ id: 'foo', json: () => '' }`, which isn't valid for `postgres`. But TS is smart enough now :smirk::

https://github.com/porsager/postgres/blob/66e9d0cb6318080b2c1aa427c2b4a905cd9f7959/types/index.d.ts#L469-L481

**Comment by eezing** [comment]
@Minigugus good deal, thanks!
