### ISSUE TITLE
cannot insert `bytea` values using strings like `\x123f`

### ISSUE THREAD

**Issue by rafaelcr** [porsager/postgres#340]
on postgres I'm able to perform an insert into a `bytea` column like this
```sql
insert into test (tx_id) values ('\x123f');
```
this in turn lets me query this value like
```sql
select tx_id::text from test;
```
and I get `\x123f` as a result.

when I try to do this using the library (using TypeScript), however, the value is first decoded through utf8 and then stored as a `bytea`, thus storing a longer (and incorrect) value in the column:
```typescript
const values = {
  tx_id: '\x123f' // I've also tried '123f', same effect
}
await sql`insert into test ${sql(values)}`
```
how can I perform this insert correctly? I'd like to avoid the overhead of having to convert the string into a Buffer using JS

----
PS: additionally, I'd also like to know how to filter these values using strings, something like:
```sql
select tx_id::text from test where tx_id in ('\x123f');
```

**Comment by porsager** [comment]
Yeah, this issue was actually discussed in the v3 PR, and I did not want to pass strings through if they started with `\x`. That would have solved your issue here, but would in my opinion be the wrong way to solve it. 

I think a better way would be to simply pass anything through stringified as is, and only convert Buffers.

You can achieve that functionality by adding this custom type:

const sql = postgres({
  types: {
    bytea: {
      to: 17,
      from: 17,
      serialize: x => x instanceof Uint8Array ? '\\x' + Buffer.from(x, x.byteOffset, x.byteLength).toString('hex') : x,
      parse: x => Buffer.from(x.slice(2), 'hex')
    }
  }
})

**Comment by rafaelcr** [comment]
Thanks, that worked. I'm only having an issue with a query similar to this one:
```typescript
const values = [['123f', '1342'], ['123a', 'aa42']];
sql`SELECT * FROM events WHERE (tx_id, hash) IN (VALUES ${sql(values)})`;
```
I'm getting an error saying that a comparison can't be made between text and bytea, I've been transforming them to `\x${str}::bytea` strings as a workaround.

Could this be related to this issue?

**Comment by porsager** [comment]
No, in that case the db doesn't know the type of the values in the `VALUES` list, so it defaults to text. ( although I would say it probably could know due to the `WHERE (tx_id, hash)` part, it doesn't :P )

You could do like this:
```js
const values = [['123f', '1342'], ['123a', 'aa42']].map(x => x.map(x => sql.typed(x, 17)))
sql`SELECT * FROM events WHERE (tx_id, hash) IN (VALUES ${ sql(values) })`;
```

**Comment by rafaelcr** [comment]
Good idea. I got this TS error when trying to do so, though: ```Property 'typed' does not exist on type 'TransactionSql<any>'. Did you mean 'types'?```

**Comment by porsager** [comment]
Yeah that works too, it's an alias ;) Apparently not in the Typescript types though :P

**Comment by rafaelcr** [comment]
🤔 no luck, if I try `sql.types()` I get
```
This expression is not callable.
  Type '{ [x: string]: ((...args: unknown[]) => Parameter<any>) | ((...args: any) => Parameter<any>); }' has no call signatures.
```
If I try `sql.types.bytea()`, when I try to interpolate into the query I get
```
Argument of type 'Parameter<any>[][]' is not assignable to parameter of type 'TemplateStringsArray'.
```

**Comment by porsager** [comment]
I did test my code above, could you post a repro sample of your case?
