### ISSUE TITLE
`sql.json` helper is missing in the docs

### ISSUE THREAD

**Issue by paulovieira** [porsager/postgres#342]
It seems this helper was documented before, according to old issues like this: https://github.com/porsager/postgres/issues/114

But it's not anymore. Was it on purpose?

**Comment by porsager** [comment]
Yeah, since v3 gets parameter descriptions from the db it's not needed anymore 😊 

v1:
```
select ${ aJsObject }::jsonb
// doesn't work: returns [object Object]
```

v3
```
select ${ aJsObject }::jsonb
// works: returns parsed js object
```

**Comment by paulovieira** [comment]
When I created the issue I had in mind insert and update queries. I was predicting some problems with more complex queries, such as those involving `jsonb_set` or the `@>`. 

But meanwhile I have done some tests and no problems at all! The bridge between javascript objects and json/jsonb in the postgresql database is perfect.

Wonderful work! Thank you.

**Comment by tmewett** [comment]
Is there a case for documenting it, due to #386 ?
