### ISSUE TITLE
Pitfalls for using pipeline mode in high throughput application with DB transactions

### ISSUE THREAD

**Issue by ankitAtVauld** [porsager/postgres#343]
Hi, 

my code snippet looks like below:
```js

const SUCCESS_STATUS = 'fulfilled';

async function createRowsInPipeline(sql, key, {id}, { value, source }, table1Id, table2Id) {
  let archive = false;
  return [
    sql `update table0 set updated_at = ${new Date().toISOString()}, reserved = reserved + ${value} where id = ${id}`,
    sql `insert into table1 (id, value, archive, op, reserved, status, table0_id) values
            (${table1Id}, ${value}, ${archive}, 1, ${value}, 2, ${id}) returning id`,
    sql `insert into table2 (id, value, archive, table1_id, source, status, table0_id) values
            (${table2Id}, ${value}, ${archive}, ${table1Id}, ${source}, 2, ${id}) returning *`,
    sql `insert into table3 (generated_at, key, resource_type) values (${getGenerateAtISO(key)}, ${key}, 2) returning *`
  ]
}

export async function request(key, from, { value, source }) {
  let { user, atype, anum } = from;
  let table1Id = "some_table1Id"
  let table2Id = "some_table2Id"

  let updates = await dbConnection.begin(async sql => {
    const rows = await sql `select * from table0 where anum = ${anum} and user_id = ${user} and atype = ${atype} `
    if(!!rows && rows.length === 1){
      const row = rows[0];
      let res = await createRowsInPipeline(sql, key, row, {value, source}, table1Id, table2Id)
      return res;
    }else {
      throw new Error("Illegal Operation");
    }
  });
  let result = await Promise.allSettled(updates);
  if(result.some(f=>f.status!=SUCCESS_STATUS))
    throw new Error("Shit happened!");
  return result[2].value[0];
}
```

We have a very high throughput application which does a lot of the operation like above. We were using Knex, but we had latency issues and also, it seems like we can scale better with postgres.js in terms of throughput.  

Would really appreciate your thoughts on above if there any pitfalls to take care of while using this lib. Also, if the above approach is right way to get result from pipeline transaction queries and ordering is maintained, so that we can return specific results.

Also, we were going through one of the articles from percona:
[How Postgres pipeline mode works](https://www.percona.com/blog/how-postgresql-pipeline-mode-works/)

at one places it says, "_It is possible to bundle asynchronous SQL statements as a single transaction. But as with all transactions, failure of any one of these asynchronously sent SQL statements will result in a rollback for all the SQL statements.

Of course, the API does provide error handling in the case of pipeline failures. In the case of a FATAL condition, when the pipeline itself fails, the client connection is informed of the error thus flagging the remaining queued operations as lost. Thereafter normal processing is resumed as if the pipeline was explicitly closed by the client, and the client connection remains active._"

Do we have an opinion on the above since I didn't understand the FATAL condition part saying, what if pipeline itself fails.

**Comment by porsager** [comment]
Currently pipelining works within a transaction with Postgres.js, but it won't pipeline several transactions after each other since it's waiting for begin to come back successful.

That means that as soon as you start a transaction you "reserve" a connection and prevent pipelining of further transactions on that connection until the transaction is over. Any queries inside that transaction can still be pipelined.

I can see quite some improvements you can make to your above snippet, possibly achieving full pipelining, but that's beyond what I can help with for free since it's not really an issue with Postgres.js but an optimization of your implementation.

**Comment by ankitAtVauld** [comment]
Thanks a lot @porsager. Your answer helped clear one of the thing. 
Could you please share your contact if we want to get support in future.

Appreciate your response!

**Comment by porsager** [comment]
> Your answer helped clear one of the thing.

Do you have other unanswered issues with Postgres.js or can I close this issue?
