### ISSUE TITLE
where...in not working with parenthesis around list

### ISSUE THREAD

**Issue by 700software** [porsager/postgres#344]
```sql
await sql`select count(*) from users where users.id in ${sql([1,2,3])}`
// works fine

await sql`select count(*) from users where users.id in (${sql([1,2,3])})`
// PostgresError: operator does not exist: bigint = record
```

**Comment by 700software** [comment]
Reminds me of #305 but might be quite different.

**Comment by porsager** [comment]
Yes, `in` and `values` helpers will add the parentheses themselves in v3.

The second options was removed to improve the general support for things like json, arrays etc. So now raw values don't have any special meaning. Before v3 you could actually do  ` ... in (${ [1, 2, 3] })`, which would translate to ` ... in ($1, $2, $3)` but that had to go to improve the cases for json and arrays. Which for instance means that you can now do:

```js
await sql`select count(*) from users where users.id = any(${ [1,2,3] })`
```

This was mentioned in the changelog as:
> - Implicit array value to multiple parameter expansion removed (use sql([...]) instead)
