### ISSUE TITLE
Return column names with .values() or alternative to .values() which has includes column names in response

### ISSUE THREAD

**Issue by half-metal** [porsager/postgres#345]
Hi, the .values() will return just the values in arrays, and the .describe() returns info about columns. Both nice to have for different situations.

Is there a way, or may I suggest an enhancement to include returning an array with column names along with the values()? E.g.
```
  columns: [
      first, last, age
    ],
    rows: [
     [john,smith,20],[frank, thomas, 40]
    ]
```
This would make one call to allow making a dynamic table from the results. OracleDb does something like this
![image](https://user-images.githubusercontent.com/58837299/166413799-8a393ca4-e643-4827-8efe-165de92d3c2b.png)

**Comment by porsager** [comment]
There is a `columns` property with that on the returned results array 😉

**Comment by half-metal** [comment]
I think I'm missing it in the documentation then, I do see `Result(1)`.  Can you give an example how to return the columns with the .values call? This is what I have
```
async function queryDatabase(query, user, password, connectString) {
  result = await sql`
  SELECT * FROM schema.table
  ORDER BY id ASC 
    
  `.values() //or use .describe()
  // users = Result [{ name: "Walter", age: 80 }, { name: 'Murray', age: 68 }, ...]
  console.log('result in call is:', result)
  return result
}
```
Which results in 
```
result in call is: Result(1) [
  [
    1,
    'test rule',
    'test rule description',
.
.
.
```

**Comment by half-metal** [comment]
And I should probably point out, I am interested in the values in their own arrays and column names in their own array. Which is different from the default behavior.

**Comment by porsager** [comment]
Oh Wow, that seems to have disappeared with the v3 docs update 😫 I'll get that added immediately.

**Comment by porsager** [comment]
Ok, if you check out the documentation at https://github.com/porsager/postgres#result-array does that answer your questions ? :)

**Comment by half-metal** [comment]
Awesome, exactly what I was looking for. So now I see that result.columns has all that info! Thanks for updating the documentation. I like this implementation.
