### ISSUE TITLE
Support for percent-encoded host in connection string

### ISSUE THREAD

**Issue by eezing** [porsager/postgres#346]
### Problem

On Google Cloud, when connecting to Cloud SQL from Cloud Run, the host is specified as:

`/cloudsql:my-project:us-central1:my-instance/my_db`

And the connection string as:

`postgresql://foo:bar@/cloudsql:my-project:us-central1:my-instance/my_db`

⚠️  But that's an invalid URI because the host contains `/` and `:`

So let's encode the host as:

`%2Fcloudsql%3Amy-project%3Aus-central1%3Amy-instance%2Fmy_db`

With the final connection string as:

`postgresql://foo:bar@%2Fcloudsql%3Amy-project%3Aus-central1%3Amy-instance%2Fmy_db`

🛑  But Postgres.js doesn't decode the host.

**From Postgres docs:**

The host part is interpreted as described for the parameter [host](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-HOST). In particular, a Unix-domain socket connection is chosen if the host part is either empty or looks like an absolute path name, otherwise a TCP/IP connection is initiated. Note, however, that the slash is a reserved character in the hierarchical part of the URI. So, to specify a non-standard Unix-domain socket directory, either omit the host part of the URI and specify the host as a named parameter, or percent-encode the path in the host part of the URI:

```
postgresql:///dbname?host=/var/lib/postgresql
postgresql://%2Fvar%2Flib%2Fpostgresql/dbname
```

https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by porsager** [comment]
Very nice description! Thank you. I think there was an issue with en/decoding related to cockroachdb parameters too. I'll take a look

**Comment by porsager** [comment]
Would you try to give the [decode-host](https://github.com/porsager/postgres/tree/decode-host) branch a go?

**Comment by porsager** [comment]
Added in 1adc11343aadeed39a0afc89c6c4b0bbb7264ab3
