### ISSUE TITLE
Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by codergautam** [porsager/postgres#349]
Got this error recently, is this my fault?

<img width="763" alt="image" src="https://user-images.githubusercontent.com/66850133/166586689-415d88f8-e367-4f96-8458-449b181fd7d2.png">

**Comment by porsager** [comment]
That's an unsolved issue with v1, so I would recommend upgrading to v3 😊

**Comment by codergautam** [comment]
Thank you
