### ISSUE TITLE
SSL Connection issue on Heroku Postgres

### ISSUE THREAD

**Issue by tclzcja** [porsager/postgres#359]
Hi there, 

Basically this is exactly the same as #38 , and the same issue happens again on my project. Here's the error message:

<img width="821" alt="Screenshot 2022-05-12 at 11 17 52 PM" src="https://user-images.githubusercontent.com/20711476/168109646-c4be4bcd-b8d2-4af3-9210-70782bd5e681.png">

And here's my code:

```
const sql = postgres(Deno.env.get("DATABASE_CONNECTION_STRING"), {
	min: 5,
	max: 50,
	ssl: {
		rejectUnauthorized: false
	}
});
```

My code is in Deno 1.21.2.

I can connect to the Heroku Postgres via Postico (a Postgres client on Mac), from my local machine. Any idea how should I  make it run? Thank you, much appreciated.

**Comment by japorized** [comment]
The options for `ssl` is different for Deno when compared to Node. In particular, for Deno, it's polyfilled to use Deno's [`Deno.startTls`](https://doc.deno.land/deno/stable/~/Deno.startTls).

**Comment by porsager** [comment]
@tclzcja yes for basic heroku postgres you need to run with `ssl: { rejectUnauthorized: false }` in node, and `--unsafely-ignore-certificate-errors` in deno (which is worse than node because it applies to all connections made from deno and not only the ones started by postgres). Instead you should check out https://devcenter.heroku.com/articles/heroku-postgres-enhanced-certificates and see if you could make that work?

**Comment by japorized** [comment]
Just a note for the flag for Deno.
> The --unsafely-ignore-certificate-errors flag optionally accepts a list of hostnames for which the verification should be disabled. If no argument is provided then no verification of certificates is preformed. This is very insecure, and should not be used. This flag impacts both internal Deno functions (eg. downloading dependencies), as well as runtime APIs like fetch, WebSocket, or Deno.connectTls.]

Source: https://deno.com/blog/v1.13#disable-tls-verification

This still holds true in the current v1.21.2.

**Comment by tclzcja** [comment]
Got it, thank you everyone, I'll check those documents.
