### ISSUE TITLE
question: good way to add logging

### ISSUE THREAD

**Issue by JoJo2112** [porsager/postgres#368]
Hello there,
Currently switching my project over to using this client, but i'm having a bit of trouble with logging the queries.
I tried porting my old solution:

```
const sql = postgres();

async function query(text) {
  console.log(text);
  const start = Date.now();
  const res = async () => await sql(text);
  const duration = Date.now() - start;
  console.log('executed query', {
    text: res.statement.string,
    duration,
    rows: res.count,
  });
  return res;
}

export { query };
```

Calling this like query\`SELECT * FROM foo;\` is working well, as long as i'm not using a parametrized string like this:
query\`SELECT * FROM foo WHERE id > ${test};\`

This gives Error:
`Error: UNDEFINED_VALUE: Undefined values are not allowed`

I do not have much experience using Template Iterals, so excuse me if the solution is too obvious.

**Comment by porsager** [comment]
Have you looked at the `debug` option?

Try to do 
```js
const sql = postgres({
  debug: console.log
})
sql`select 1`
```

**Comment by JoJo2112** [comment]
> Have you looked at the `debug` option?
> 
> Try to do
> 
> ```js
> const sql = postgres({
>   debug: console.log
> })
> sql`select 1`
> ```

Nice! is there some way to include the Query Duration this way?

**Comment by porsager** [comment]
No nothing currently. What is your need for this? Have you considered using `pg_stat_statements`?

**Comment by JoJo2112** [comment]
> No nothing currently. What is your need for this? Have you considered using `pg_stat_statements`?

The project uses some quite big tables, its basically just for getting performance comparisons. I considered using `pg_stat_statements` and I think thats the way im going. Anyway: Thanks for your help, really enjoying this client!

**Comment by porsager** [comment]
If this is to get logs / performance info in production `debug` is probably not the right option. Debug enables full stack errors per query which will give you quite a performance hit.

You could make your function above like this then:
```js
const _sql = postgres()

async function sql() {
  const start = Date.now()
  const res = await _sql.apply(_sql, arguments)
  console.log('executed query', {
    text: res.statement.string,
    duration: Date.now() - start,
    rows: res.count
  })
  return res
}

export sql
```

**Comment by JoJo2112** [comment]
> If this is to get logs / performance info in production `debug` is probably not the right option. Debug enables full stack errors per query which will give you quite a performance hit.
> 
> You could make your function above like this then:
> 
> ```js
> const _sql = postgres()
> 
> async function sql() {
>   const start = Date.now()
>   const res = await _sql.apply(_sql, arguments)
>   console.log('executed query', {
>     text: res.statement.string,
>     duration: Date.now() - start,
>     rows: res.count
>   })
>   return res
> }
> 
> export sql
> ```

Yes, exactly, sorry for my unclear description, this is working perfectly.

**Comment by porsager** [comment]
Cool... Remember that you will also need to wrap the sql instance if using transactions inside `.begin(sql => ...)`

**Comment by JoJo2112** [comment]
Thanks for the notice and your help again.

**Comment by budarin** [comment]
> If this is to get logs / performance info in production `debug` is probably not the right option. Debug enables full stack errors per query which will give you quite a performance hit.
> 
> You could make your function above like this then:
> 
> ```js
> const _sql = postgres()
> 
> async function sql() {
>   const start = Date.now()
>   const res = await _sql.apply(_sql, arguments)
>   console.log('executed query', {
>     text: res.statement.string,
>     duration: Date.now() - start,
>     rows: res.count
>   })
>   return res
> }
> 
> export sql
> ```

is it possible to add types to this example?
TypeScript swears :)

**Comment by xerosanyam** [comment]
@porsager 
```
Promise { <pending> }
file:///Users/sanyamjain/dev/xerosanyam/my-project/node_modules/postgres/src/types.js:178
  throw Errors.generic('NOT_TAGGED_CALL', 'Query not called as a tagged template literal')
               ^

Error: NOT_TAGGED_CALL: Query not called as a tagged template literal
    at notTagged (file:///Users/sanyamjain/dev/xerosanyam/my-project/node_modules/postgres/src/types.js:178:16)
    at Builder.then (file:///Users/sanyamjain/dev/xerosanyam/my-project/node_modules/postgres/src/types.js:42:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'NOT_TAGGED_CALL'
}
```
