### ISSUE TITLE
How can I catch ERR_UNHANDLED_ERROR

### ISSUE THREAD

**Issue by panthershark** [porsager/postgres#37]
I'm using this in a unit test suite and our test harness force closes all connections at the server. This is done by opening a master db connection and running this:

```
SELECT pg_terminate_backend(pid) FROM pg_stat_activity
    WHERE datname = 'dbname' AND pid <> pg_backend_pid();
```

When this is run, any open connection throws this error. 

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (error: terminating connection due to administrator command
          at Connection.Object.<anonymous>.Connection.parseE (/path-to-app/node_modules/pg/lib/connection.js:614:13)
          at Connection.Object.<anonymous>.Connection.parseMessage (/path-to-app/node_modules/pg/lib/connection.js:413:19)
          at Socket.<anonymous> (/path-to-app/node_modules/pg/lib/connection.js:129:22)
```

#### Question

How can I catch this exception so I can prevent from tearing down the whole process?  (obv we can do `process.on('uncaughtException'`, but I'd prefer not to do that)

**Comment by porsager** [comment]
Hi @panthershark .. This is definitely a bug / missing support in Postgres.js. I'll look into fixing it

**Comment by porsager** [comment]
Fixed in master ;)

**Comment by panthershark** [comment]
Rad thanks!
