### ISSUE TITLE
Bug with dynamic inserts and JSON

### ISSUE THREAD

**Issue by itziksn** [porsager/postgres#379]
Hi!
Thanks for this awesome package!

I just started using it today and was trying to use the dynamic insert for values including `jsonb` type, and noticed this weird/inconsistent behavior.

What I'm trying to do is, given the following schema:
```sql
CREATE TABLE schedule.jobs (
	callback_url text NOT NULL,
	status text NOT NULL,
	args jsonb NULL,
	"time" timestamp NOT NULL
);
```
Do the following request:
```javascript
sql`INSERT INTO schedule.jobs ${sql([{time: 1, status: "", callback_url: "", args: {}}], 'args', 'callback_url', 'status', 'time')}`;
```

The bug is that this line _sometimes_ will result in `args` column containing a string `"{}"`, instead of `jsonb` empty object.

This behavior is not happening all the time though, and I can't really tell what's going on.

But the thing I was able to tell for sure was that only the first time I execute this query it sometimes result in a string. any consecutive queries will, for sure, insert a string.

So I was able to make the following repro:
Given the above schema, run the following script:
```javascript
const sql = require("postgres")({
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DB,
});

async function main() {
    await sql`INSERT INTO schedule.jobs ${sql([{time: 1, status: "", callback_url: "", args: {}}], 'args', 'callback_url', 'status', 'time')}`;
    await sql`INSERT INTO schedule.jobs ${sql([{time: 2, status: "", callback_url: "", args: {}}], 'args', 'callback_url', 'status', 'time')}`;
}

main();
```

The first one will insert args as `jsonb`, the second will be a string.

Let me know if you need anymore information.

Regards

**Comment by itziksn** [comment]
UPDATE: After testing and investigating a bit more, I can tell it has something to do with `prepare` mode.

When `prepare` mode is disabled this bug never happens. i.e by passing `false` in postgres options like this:
```javascript
const sql = require("postgres")({
    prepare: false,
    // ...rest of options
});
```

Hope this will help to pinpoint the problem a bit more.

**Comment by porsager** [comment]
Oh interesting! Thanks for the repro, looking forward to check it out when I'm back at my computer.

**Comment by porsager** [comment]
Which version of PostgreSQL, Postgres.js, are you running? Do you connect directly to PostgreSQL or eg through pgbouncer? I can't replicate this behaviour myself yet.

**Comment by itziksn** [comment]
PostgreSQL v12
Postgres.js 3.2.4
There is a pgbouncer.

**Comment by itziksn** [comment]
Oh I'll check that, but I guess you're right.

Thanks a lot!
