### ISSUE TITLE
Where in does not work when array has only 1 item

### ISSUE THREAD

**Issue by thomasconner** [porsager/postgres#381]
### Issue
I am trying to create a where in filter with an array that contains only 1 item. The result is an invalid query.

```javascript
var statuses = ['foo'];
sql`SELECT * FROM test WHERE status IN ${sql(statuses)}`
```

### Expected
`SELECT * FROM test WHERE status IN ($1)`

### Actual
`SELECT * FROM test WHERE status IN "foo"`

**Comment by thomasconner** [comment]
I am sorry this was my fault. The value passed in was a string and not an array of strings. It does work correctly with a single value in an array.

**Comment by porsager** [comment]
Glad you worked it out, and thanks for following up
