### ISSUE TITLE
Timezone Issues

### ISSUE THREAD

**Issue by RyanHirsch** [porsager/postgres#388]
I'm on version 3.2.4, and am having timezone issues. My database is configured to use UTC, but when making queries, the javascript object results seem to be timezone shfited (I'm currently -5 UTC).

```sql
SELECT current_setting('TIMEZONE');
-- returns  UTC
```

In my connection I have the following:
```js
const sql = postgres(process.env.DATABASE_URL, {
  prepare: false,
  connection: {
    timezone: "UTC",
  },
});
```

And when returning results this is what I'm seeing (notice that the all the dates are +5 hours from what my GUI shows):
```js
[
  {
    id: 'c65a7945-7544-4105-a0f5-a31685c75987',
    createdAt: 2022-05-26T23:20:56.527Z,
    updatedAt: 2022-05-26T23:20:56.527Z,
    startAt: 2022-05-27T01:00:00.000Z,
    endAt: 2022-06-04T01:00:00.000Z
  }
]
```
However, in my GUI editor this is what I see:
![Screen Shot 2022-06-01 at 1 55 39 PM](https://user-images.githubusercontent.com/1883231/171481073-d27a034c-bdc4-443d-b8f8-a95185425e87.png)

Manually querying for this item using a UTC timestamp returns the one item I expect:
```sql
SELECT *
FROM promo
WHERE "endAt" = '2022-06-03T20:00:00.000Z'
```
![Screen Shot 2022-06-01 at 1 59 03 PM](https://user-images.githubusercontent.com/1883231/171481643-6fe682ac-c4f7-4447-91e8-81d6430e274e.png)

I'm assuming I'm just doing something dumb, but I can't figure out why this is happening.

**Comment by porsager** [comment]
Is your column type perhaps `timestamp` instead of `timestamptz` ?

**Comment by RyanHirsch** [comment]
Oh snap it is! Is the appropriate action here to alter the table to use `timestamptz`?

**Comment by porsager** [comment]
Yeah, well you would best know how to get the right timestamps by testing, but also perhaps read this from the PostgreSQL wiki: https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_timestamp_.28without_time_zone.29

That's specifically for timestamp vs timestamptz, but the whole page is a real gem :)

**Comment by transtone** [comment]
the connect timezone with or without `connection: { timezone: "America/Chihuahua", }` , it be set as `UTC`.

**Comment by porsager** [comment]
@transtone how do you verify that? What does ``` sql`select now()::text` ``` give you?

**Comment by transtone** [comment]
I use `java/golang-gorm/pgrst` with `TimeZone=America/Los_Angeles` connect option to put a `timestamp` field named `ct_date` by `ct_date: 2022-10-13 08:00:00` , in the table it get `2022-10-13 08:00:00.000`.
but use `postgres.js`, it get `2022-10-13 16:00:00.000`.

**Comment by transtone** [comment]
I just test with `pg`([node-postgres](https://github.com/brianc/node-postgres)), it's the same with `java/golang-gorm/pgrst`.
sent `2022-10-13 09:00:00`  get `2022-10-13 09:00:00.000`.

**Comment by pencilcheck** [comment]
I can't modify the DB easily, as there are tons of data already exist and it spans across multiple tables, is there a workaround when connecting to not use new Date() when transforming?

**Comment by nscott** [comment]
I'm surprised this was closed. While I agree `timestamptz` is the better type, I'm sure there are plenty of people accidentally using `timestamp`, myself included! I'm using PGlite when I came across this, and found they pulled the typing largely from this repo.

Here's my issue: https://github.com/electric-sql/pglite/issues/532

I think that sums up what's happening and a proposed fix, although given the wiki page, perhaps it won't. I would have assumed both `timestamp` and `timestamptz` would be epoch-based, but clearly not.

**Comment by stereosteve** [comment]
@pencilcheck you can skip date parsing like this:

```
export const sql = postgres('', {
  prepare: false,
  types: {
    skipDateParse: {
      to: 1114,
      from: [1114],
      serialize: (v: string) => v,
      parse: (v: string) => v,
    },
  },
})
```
