### ISSUE TITLE
An onConnect event is needed

### ISSUE THREAD

**Issue by budarin** [porsager/postgres#391]
For the normal operation of the service, we need the `onConnect` event - our service is subscribed for notification and takes data from the database on the incoming signal. 
In case of loss of communication with the database, we lose signals and, accordingly, do not have time to perform the necessary actions with the data in DB.

We would have been saved by the `onConnect` event, in which, after restoring the connection, we could get all the data from the database for which, due to the lack of communication, there was no notification

**Comment by porsager** [comment]
There's an onlisten event for that 😉 
https://github.com/porsager/postgres#listen-await-sqllistenchannel-onnotify-onlisten----state-

If you're using subscribe, the same goes there.

**Comment by budarin** [comment]
listen listen does not solve the problem - in it I cannot determine this signal came during a normal connection or after the connection was restored

**Comment by porsager** [comment]
That's exactly what you can? There's even an example for what you're trying to do?

**Comment by budarin** [comment]
thanks!
