### ISSUE TITLE
Use WHATWG Streams

### ISSUE THREAD

**Issue by lucsoft** [porsager/postgres#397]
NodeJS and Deno both support WHATWG Streams

It would be great if this library uses whatwg streams as default

**Comment by porsager** [comment]
Yeah would be nice, but it's still experimental in nodejs. We could look into returning WHATWG streams for Deno at least.

**Comment by lucsoft** [comment]
Its not experimental anymore, its default in nodejs 18

**Comment by porsager** [comment]
Let's revisit this once stable

**Comment by lucsoft** [comment]
But what should have "Experimental" for an impact? Its stable for years in the web world?

Its just how nodejs marks there new stuff? the api will not change really as its already defined by WHATWG?

**Comment by surprisetalk** [comment]
For anybody else running into issues with this, I think this solves the problem in deno:

``` ts
import { Writable } from "node:stream";

myReadable.pipeTo(Writable.toWeb((await sql`...`.writable()) as Writable));
```

**Comment by lucsoft** [comment]
![image](https://github.com/porsager/postgres/assets/11093382/00bef1ed-a39d-4ef9-bea0-60f8a88e054a)
@porsager Can this issue be Reopened now?
