### ISSUE TITLE
Calling a SQL function with an array of parameters

### ISSUE THREAD

**Issue by jerryjeremiah** [porsager/postgres#401]
I would like to call a function that takes multiple parameters using an array of parameter values much in the smae way that we can do a select with an array of column names:

This works fine:

```
  const parameter = 'def';
  const records = await sql`select get_customer('abc',${ parameter });`;
```

But I would like to do something like:

```
  const parameter = [abc,'def'];
  const records = await sql`select get_customer(${ parameter });`;
```

The error I get is:

```
{"error":{"name":"PostgresError","message":"function get_customer(unknown) does not exist",...}}
```

Is there a way to pass an array of parameters to a function?

**Comment by porsager** [comment]
@jerryjeremiah That is a little tricky, but you can use fragments to achieve what you want although I would suggest supplying each argument individually if possible.

Recommended static argument count:
```js
const a = abc
    , b = 'def'
const records = await sql`select get_customer(${ a }, ${ b })`
```

Alternative Dynamic argument count:
```js
const parameter = [abc,'def'];
const records = await sql`select get_customer(${
  parameter.map((x, i) => sql`${ i ? sql`,` : sql`` }${ x }`)
})`
```

Would love to hear your reason if needing dynamic argument count for the function calls..

@kevinmungai Thanks for the suggestion, but that would add the array items as `identifiers` instead of values, so it wouldn't work as intended.

**Comment by jerryjeremiah** [comment]
So maybe I am doing something silly, but I have a whole bunch of database functions and I wanted to make one AWS lambda that could call them.  In order to keep ALL their configuration in one place, the lambda contains an object of function calls and each one uses the same code to execute the function:

```
const call = async function(procedure,parameterArray)
{
  // call the stored procedure
  const records = await sql`select ${ sql(procedure) }(${
    parameterArray.map((x, i) => sql`${ i ? sql`,` : sql`` }${x}`)
  })`;

  // flatten the object
  const result = JSONPath({path: '$..'+procedure,json: records});

  // only return an array if there is one
  return result.length==1?result[0]:result;
};

const mapping = {
  getCustomer:            function(headers,parameters) {
                            return dbfunc('sp_get_customer',[
                              parameters['serviceID'],
                              headers['conversationId']
                            ]);
                          },
  getDepartments:         function(headers,parameters) {
                            return dbfunc('sp_get_departments',[
                              parameters['departmentID'],
                              parameters['serviceID'],
                            ]);
                          },
  getPreviousMessages:      ...
};

exports.handler = async (event, context, callback) => {
    const api = event.pathParameters['api'];
...
    // get the database results
    const data = await mapping[api](event.headers,JSON.parse(event.body));
...
    // and return the result
    return {
      statusCode: 200,
      headers: responseHeaders,
      body: JSON.stringify(responseBody),
    };
}
```

It is either that or I need a bunch of `dbfunc`-style functions that each contain hard-coded procedures and parameters.  It is more conventional but you have to scroll all over the place to see what parameters are being passed to what functions so I thought having it all in one place was better.

Do you think this idea of keeping all the config in one place is good practive or should I do it more conventionally?

**Comment by porsager** [comment]
No, that looks cool 😃 I think that if this setup works well for you it's great! Conventional to me usually means "more useless plumbing", and I don't see anything inherently wrong with your approach.
