### ISSUE TITLE
TypeError: socket.setKeepAlive is not a function

### ISSUE THREAD

**Issue by movila** [porsager/postgres#404]
I got a `TypeError: socket.setKeepAlive is not a function` error from `postgres/cjs/src/connection.js:357` file.

**Comment by porsager** [comment]
Are you connecting using unix sockets? (using `path` in options? )

**Comment by movila** [comment]
> Are you connecting using unix sockets? (using `path` in options? )

Hi, I didn't specify the `path` value. 

I'm using a custom socket with ssh tunnel:

```
const ssh2 = require('ssh2')
const ssh = new ssh2.Client()

const sshOptions = {
    host: 'my-host-ip-addr',
    port: 22,
    username: 'someuser',
    privateKey: fs.readFileSync('some-key.pem'),
    keepaliveInterval: 3000,
}

const sql = postgres({
  // ... other options
  socket: ({ host: [host], port: [port] }) => new Promise((resolve, reject) => {
        ssh
        .on('error', reject)
        .on('ready', () => 
            ssh.forwardOut('127.0.0.1', port, host, port, 
                (err, socket) => err ? reject(err) : resolve(socket)
            )
        )
        .connect(sshOptions)
    })
})
```

**Comment by porsager** [comment]
Ah, that makes sense. So this socket doesn't support calling `setKeepAlive`. We could add that check in Postgres.js, or you can add the method yourself or disable setKeepAlive call by setting `keep_alive: null`.

**Comment by movila** [comment]
`keep_alive: null` works. Thanks!

**Comment by PierBover** [comment]
Just in case anyone stumbles upon this issue as I did...

I made a repo with a full example on how to use `ssh2` with `postgres`:

https://github.com/PierBover/test-ssh-postgres-node

I used `0.0.0.0` instead of `127.0.0.1` because my db is running in a Docker container installed with Coolify.
