### ISSUE TITLE
TypeError: doesn't work if `exactOptionalPropertyTypes:true` in tsconfig.json

### ISSUE THREAD

**Issue by xerosanyam** [porsager/postgres#407]
`exactOptionalPropertyTypes` just makes type system a little stricter. It is a good to have flag, suggested by [zapatos](https://jawj.github.io/zapatos/).

The error that's currently thrown is:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/3167278/176410444-dcf19060-2b16-46f0-b724-b5a6de76a365.png">

**Comment by porsager** [comment]
I'm not into Typescript, but perhaps @Minigugus could share a comment? :)
