### ISSUE TITLE
Infer array type when first value is null

### ISSUE THREAD

**Issue by andreamatte-smartpricing** [porsager/postgres#408]
I'm trying to follow the solution from https://github.com/porsager/postgres/issues/72#issuecomment-922452087.
There are 3 columns of type timestamptz. 2 of them work fine, but one of them gets infered as type string instead of date.
This happens because the first row has value null in that column.
How should I proceed? Is there any way to force the type inferred by sql.array(...)?

**Comment by porsager** [comment]
sql.array should not be necessary since v3. What happens if you pass the array directly instead? If that's still an issue the change in this PR might help https://github.com/porsager/postgres/pull/392

**Comment by andreamatte-smartpricing** [comment]
Removing the sql.array() call fixed the issue, thanks
