### ISSUE TITLE
Non prepared execution mode

### ISSUE THREAD

**Issue by char101** [porsager/postgres#41]
Hi,

First I want to say that this is a great library, simple but powerful.

Anyway, I just found a case where executing a query with bind parameters results in much more slow execution time (5s) vs running it with hardcoded values (30ms). I believe this is caused due to the use of prepared statement, where the server created an execution plan without looking at the types of the bind parameters, thus some indexes are not used. To fix this we could  explicitly cast the bind parameter, e.g. `${value}::INT`, but it is a bit of an annoyance to have to cast every bind parameter. So if possible I think it would be great to have a non-prepared execution mode as an alternative.

For comparison, the same query runs fast with python/psycopg2 because although it supports bind parameter in the client (via `%s` format)  it sends the query to the server in non-prepared mode, that is it directly replaces the bind parameter placeholder with its values.

**Comment by Minigugus** [comment]
By doing `${value}::INT`, `postgres` translate it to `$1::INT`, so it seems that the problem is not really adding a non-prepared mode but imposing types for parameters in queries.

Moreover, `postgres` already detects parameter types to encode them, maybe it could automatically add casts ? e.g. `${1337}` -> `$1::int` instead of just `$1` ?

**Comment by porsager** [comment]
Hi @char101 .. 

First off, thanks..

That's a really interesting case. Which PostgreSQL version are you using?

Postgres.js will pass along the types it has inferred over the wire. Maybe you could try to run an `explain` with dynamic values and one with static values?

**Comment by porsager** [comment]
@Minigugus the inferred types are already passed alongside the parameters in the protocol, and I think it'd be a mess to start rewriting queries by adding explicit types, it's best to leave that up to the only one who knows what it should be for sure - the user 🙂

@char101 by the way, I can't read if you tested with explicit types (`::int`) and got good results?

**Comment by porsager** [comment]
Uh btw @char101 . Could you try your query with the latest on `master` as well? (just `npm install porsager/postgres`)

**Comment by char101** [comment]
> By doing `${value}::INT`, `postgres` translate it to `$1::INT`, so it seems that the problem is not really adding a non-prepared mode but imposing types for parameters in queries.

Sure if that can be done automatically and accurately.

> Moreover, `postgres` already detects parameter types to encode them, maybe it could automatically add casts ? e.g. `${1337}` -> `$1::int` instead of just `$1` ?

What if the user supply an incorrect type, for example, a numeric string to an integer column?

**Comment by char101** [comment]
> Uh btw @char101 . Could you try your query with the latest on `master` as well? (just `npm install porsager/postgres`)

I have changed it to the master branch and still experience the long execution time without type casts.

Also I am using `express` and with the master branch version, I am getting this error: `Do not know how to serialize a BigInt` when sending the query result as `json`. This does not happen before when using the released version. From what I saw, the result if a `SELECT COUNT(n)` query is a `BigInt` in the master branch version.

I am using PostgreSQL 12.2 and node 13.7.0.

> Postgres.js will pass along the types it has inferred over the wire. Maybe you could try to run an explain with dynamic values and one with static values?

A prepared statement is supposed to be run multiple times, so the planner might not look at the type of the bind variable since it can change later. Also I think the bind variable is only used in the execution phase, not in the preparing phase.

This are the query plans
* bind parameter without type cast [bind-no-type.txt](https://github.com/porsager/postgres/files/4273134/bind-no-type.txt)
* bind parameter with type cast [bind-type.txt](https://github.com/porsager/postgres/files/4273150/bind-type.txt)
* hardcoded values [hardcoded.txt](https://github.com/porsager/postgres/files/4273149/hardcoded.txt)

As you can see the plan is similar when using hardcoded values and bind parameter with type casts, while time execution time of the query with bind parameter without type casts is 160x slower.

**Comment by char101** [comment]
My solution currently is to add type casts to all the bind variables. TBH it isn't really that annoying 😀 since they are only either `INT` or `TEXT`.

**Comment by char101** [comment]
In the parameterized without type cast query plan the query planner choose to cast the integer values to `numeric` rather than `int`. This might be a possible cause for the slow execution since it means that existing index will not be used and numeric operations are also slower compared to integer operations.

**Comment by porsager** [comment]
This is great debugging @char101 :) 

In the next major version I think I'll switch to unknown types instead for javascript Numbers, since Postgres itself is better at casting to the correct type.
