### ISSUE TITLE
Error with dynamic schema and params

### ISSUE THREAD

**Issue by budarin** [porsager/postgres#413]
```js
const props = {...};
const schema = 'public';
const result = await sql`select * from ${sql(schema)}.func1( ${props}::jsonb )`;
```
=> Error: `NOT_TAGGED_CALL: Query not called as a tagged template literal`

when use 
```js
const props = {...};
const result = await sql`select * from public.func1( ${props}::jsonb )`;
```

everything works fine

**Comment by porsager** [comment]
I don't see any issue with this on my end. What version are you seeing this with?

**Comment by budarin** [comment]
You are right - a strange error when building the project
Now everything is working as expected

**Comment by porsager** [comment]
Great to hear 😊 Thanks for the quick follow up

**Comment by budarin** [comment]
@porsager I hurried to be happy, but the error is stable in test mode - try to run it in test with jest

**Comment by porsager** [comment]
Is the code transpiled in any way? Can you make a full repro? I don't use jest

**Comment by budarin** [comment]
yes it transpiled with Babel
I'll try to

**Comment by porsager** [comment]
Ah, I think that babel is messing something up then. Can you look at the transpiled code?

**Comment by budarin** [comment]
I found the reason - I use the [code](https://github.com/porsager/postgres/issues/368#issuecomment-1128722614) to log requests to pg 

```js
const pg = postgres(options);

async function sql() {
  const start = Date.now()
  const res = await _sql.apply(_sql, arguments)
  console.log('executed query', {
    text: res.statement.string,
    duration: Date.now() - start,
    rows: res.count
  })
  return res
}

...

const props = {...};
const schema = 'public';
const result = await sql`select * from ${sql(schema)}.func1( ${props}::jsonb )`;
```

when I apply it to a string constant in a test environment, something is transpiled wrong.

But if I use the original object  (not the logging wrapper), then in text mode everything is broadcast without errors and the tests pass

```js
const pg = postgres(options);
...
const result = await sql`select * from ${pg(schema)}.func1( ${props}::jsonb )`;
```
