### ISSUE TITLE
sql(value) errors on dynamic queries

### ISSUE THREAD

**Issue by joshxyzhimself** [porsager/postgres#414]
#### Overview

Yesterday I crafted some CRUD helpers to reduce redundancy in my code. The crud script let me validate rows according to some table schema which got each column's type. And of course it let me create, read, update, delete rows.

- https://github.com/joshxyzhimself/modules/blob/main/postgres.mjs
  - crud script
- https://github.com/joshxyzhimself/modules/blob/main/postgres.test.mjs
  - test script
- https://github.com/joshxyzhimself/modules/runs/7162331674?check_suite_focus=true
  - ci test results, at "Run postgres test" section

I've had success in doing dynamic inserts and updates, but on the other cases I've had to use `sql.unsafe(query)` because `sql(value)` would throw an error. Hereunder are my findings.

#### Error on `sql(table-name)`

```js
const users_table = {
  name: 'users',
  columns: [
    { name: 'id', type: 'serial', primary: true },
    { name: 'email', type: 'text' },
    { name: 'email_verified', type: 'boolean', default: 'false' },
    { name: 'created_at', type: 'timestamp', default: 'NOW()' },
  ],
};

const tables = [users_table]

for (let i = 0, l = 1; i < l; i += 1) {
  const table = tables[i];
  await sql`
    CREATE TABLE ${sql(table.name} ... ;
  `;
  // error
}
```

#### Error on `sql(column-name)` and `sql(operator)`

```js
const column_name = 'email_verified';
const operator = '=';
const value = true;
await sql`
  SELECT * FROM "users" WHERE ${sql(column_name)} ${sql(operator)} ${sql(value)};
`;
// error
```

#### Questions

My workaround in my script is I use `sql.unsafe(query)`, then I've had a separate function to encode table names and column names, and another function to encode column values.

```js

/**
 * @type {[RegExp, string]}
 */
const rx_single_quote = [/'/g, '\''];

/**
  * @type {[RegExp, string]}
  */
const rx_double_quote = [/"/g, '\\"'];

/**
  * @type {[RegExp, string]}
  */
const rx_backslash = [/\\/g, '\\\\'];

/**
  * @param {string} value
  */
const escape = (value) => {
  assert(typeof value === 'string');
  return value.replace(rx_single_quote[0], rx_single_quote[1])
    .replace(rx_double_quote[0], rx_double_quote[1])
    .replace(rx_backslash[0], rx_backslash[1]);
};

/**
  * @param {string} value
  */
const encode_name = (value) => {
  assert(typeof value === 'string');
  return `"${escape(value)}"`;
};

/**
  * @param {boolean|string|number} value
  */
const encode_value = (value) => {
  assert(typeof value === 'boolean' || typeof value === 'string' || typeof value === 'number');
  switch (typeof value) {
    case 'boolean': {
      return value;
    }
    case 'string': {
      return `'${escape(value)}'`;
    }
    case 'number': {
      return value;
    }
    default: {
      break;
    }
  }
  return null;
};
```

Example usage:

```js
await sql.unsafe(`DROP TABLE IF EXISTS ${encode_name(table.name)} CASCADE;`);
```

Another example usage:

```js
const items = await sql.unsafe(`SELECT * FROM ${encode_name(table.name)} WHERE ${encode_name(name)} ${operator} ${encode_value(value)} LIMIT ${encode_value(limit)} OFFSET ${encode_value(offset)};`);
```

1. Am I doing it right?
2. Am I using sql.unsafe safely, or did I just allow SQL injection in ways I'm not aware of?

**Comment by porsager** [comment]
### 1 
Almost :) You correctly use `sql(someString)` for identifiers, but should use eg ``` sql`=` ``` for operators/keywords/sql, and nothing for values - So it should look like this:

```js
await sql`
  SELECT * FROM "users" WHERE ${ sql('email_verified') } ${ sql`=` } ${ value }
`;
```

Which will be translated to this:
```sql
SELECT * FROM "users" WHERE "email_verified" = $1
```

With regards to your error in `CREATE TABLE ...` then that shouldn't be a problem, so if you can make a repro case of that one we can look into it ;)

### 2
Yes I think you did.. I would be able to set value to eg ```'\';--\ndrop table students;--'``` and thereby dropping that famous students table (or whatever else I had in mind).

**Comment by joshxyzhimself** [comment]
> ### 1
> Almost :) You correctly use `sql(someString)` for identifiers, but should use eg `` sql`=` `` for operators/keywords/sql, and nothing for values - So it should look like this:
> 
> ```js
> await sql`
>   SELECT * FROM "users" WHERE ${ sql('email_verified') } ${ sql`=` } ${ value }
> `;
> ```
> 
> Which will be translated to this:
> 
> ```sql
> SELECT * FROM "users" WHERE "email_verified" = $1
> ```

This worked, thank you!

However if my operator is from a variable, it looks like this

```js
  const items = await sql`SELECT * FROM ${sql(table.name)} WHERE ${sql(name)} ${operator} ${value} LIMIT ${limit} OFFSET ${offset};`;
```
```js
  const items = await sql`SELECT * FROM ${sql(table.name)} WHERE ${sql(name)} ${sql`${operator}`} ${value} LIMIT ${limit} OFFSET ${offset};`;
```

I get this error:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
PostgresError: syntax error at or near "$1"
    at ErrorResponse (file:///home/user/modules/node_modules/postgres/src/connection.js:761:26)
    at handle (file:///home/user/modules/node_modules/postgres/src/connection.js:468:6)
    at Socket.data (file:///home/user/modules/node_modules/postgres/src/connection.js:312:9)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at cachedError (file:///home/user/modules/node_modules/postgres/src/query.js:166:23)
    at new Query (file:///home/user/modules/node_modules/postgres/src/query.js:36:24)
    at sql (file:///home/user/modules/node_modules/postgres/src/index.js:105:11)
    at read_items_where (file:///home/user/modules/postgres.mjs:228:26)

Node.js v18.4.0
```

Using `${sql(operator)}` won't work too because it results to `"="`.

**Comment by porsager** [comment]
Operators / keywords or sql fragments cannot be simple strings. That would not make it any different than using `unsafe` and regular string concatenation. Instead it needs to be static references through eg ``` sql`=` ```.

So, to make your operator example work you need to decide exactly which operators you'd want to allow at that place in your query. How you do it is up to you, but one example could be like this:

```sql
const operators = {
  '=': sql`=`,
  '!=': sql`!=`,
  'like': sql`like`
}

const items = await sql`
  SELECT * FROM ${ sql(table.name) } 
  WHERE ${ sql(name) } ${ operators[operator] } ${ value } 
  LIMIT ${ limit } 
  OFFSET ${ offset }
`

```

**Comment by joshxyzhimself** [comment]
Got it. Thank you very much @porsager!
