### ISSUE TITLE
Typescript error: No overload matches this call.

### ISSUE THREAD

**Issue by budarin** [porsager/postgres#415]
Try to use helper fo query data from function in pg
```ts
    const sql = postgres(options);

    async function runQuery(schema: string, props: object) {
        const result = await sql`select * from ${sql(schema)}.func1(${props}::jsonb )`;

        return result;
    }
```
but get the error 

![image](https://user-images.githubusercontent.com/8055157/177029951-d5489f3a-d898-48a4-9345-86607f8b4032.png)

```
"message": "No overload matches this call.
Overload 1 of 2, '(first: TemplateStringsArray, ...rest: never): PendingQuery<Row[]>', gave the following error.
Argument of type 'Helper<string, []>' is not assignable to parameter of type 'never'.  
Overload 2 of 2, '(template: TemplateStringsArray, ...parameters: readonly (SerializableParameter<never> | PendingQuery<any>)[]): PendingQuery<Row[]>', gave the following error.
Argument of type 'object' is not assignable to parameter of type 'SerializableParameter<never> | PendingQuery<any>'."
```

**Comment by thebearingedge** [comment]
The `JSONValue` type might be what you want here.

```ts
    import postgres, { JSONValue } from 'postgres';

    const sql = postgres(options);

    async function runQuery(schema: string, props: postgres.JSONValue) {
        const result = await sql`select * from ${sql(schema)}.func1(${sql.json(props)}::jsonb )`;

        return result;
    }
```

**Comment by budarin** [comment]
thanks

**Comment by timonson** [comment]
I have the same issue and JSONValue doesn't work neither for me. Is there another solution? Thank you!

```ts
type Services = { aud: string; createdAt: string }[];

export async function insertRow(
  { services, email, hash }: {
    services: Services;
    email: string;
    hash: string;
  },
) {
  return await sql`
insert into account (email, hash, services) values (${email}, ${hash}, ${services}) returning *
`;
}
```

> error: TS2769 [ERROR]: No overload matches this call.
  Overload 1 of 2, '(first: TemplateStringsArray, ...rest: never): PendingQuery<Row[]>', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.  Overload 2 of 2, '(template: TemplateStringsArray, ...parameters: readonly ParameterOrFragment<never>[]): PendingQuery<Row[]>', gave the following error.
    Argument of type 'Services' is not assignable to parameter of type 'ParameterOrFragment<never>'.
      Type '{ aud: string; createdAt: string; }[]' is not assignable to type 'readonly SerializableParameter<never>[]'.
        Type '{ aud: string; createdAt: string; }' is not assignable to type 'SerializableParameter<never>'.
  return await sql`
