### ISSUE TITLE
ERROR in ./node_modules/postgres/src/index.js 2:0-19 Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by fibag21** [porsager/postgres#418]
Hi,

I'm trying to build using yarn but I keep receiving this error message ERROR in ./node_modules/postgres/src/index.js 2:0-19 Module not found: Error: Can't resolve 'fs' 

On my Windows 10 Node.js installation, fs is however installed.

Any hint ?
Thanks

**Comment by porsager** [comment]
'fs' is a Node.js core module, so it's not something you can install.. Are you trying to use Postgres.js in the browser? (that's not possible).

**Comment by fibag21** [comment]
Before installing fs (yes, "npm install fs" works), I had the same issue. But actually looking at https://stackoverflow.com/questions/57161839/module-not-found-error-cant-resolve-fs-in, applying the solution to the webpack seems to work.
