### ISSUE TITLE
Dynamic values 'where ... in ...' conflicts with dynamic column names

### ISSUE THREAD

**Issue by akoltun** [porsager/postgres#419]
Hello,

This simplified code:
```
const column = "code";
const years = [2018,2019,2020]

await sql`SELECT ${ sql([column]) }, year, sum(amount) 
FROM report 
WHERE year in ${ sql(years) }
GROUP BY ${ sql([column]) }, year;`
```
fails because it generates the following SQL:
```
SELECT "code", year, sum(amount)
FROM report
WHERE year in ($1,$2,$3)
GROUP BY ($4), year;
```
So it successfully substitute column name before `where ... in ...` section but considers column name as just a parameter after this section.

If I remove `where ... in ...` section, then column names are successfully substituted everywhere.
Ex.
```
const column = "code";
const years = [2018,2019,2020]

await sql`SELECT ${ sql([column]) }, year, sum(amount) 
FROM report 
GROUP BY ${ sql([column]) }, year;`
```
succeeds because it generates the following SQL:
```
SELECT "code", year, sum(amount)
FROM report
GROUP BY "code", year;
```

**Comment by porsager** [comment]
Should work fine if you don't wrap `column` in an array?

**Comment by akoltun** [comment]
Yes, it works.
Thank you!
