### ISSUE TITLE
Error: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by joshxyzhimself** [porsager/postgres#42]
Related to https://github.com/porsager/postgres/issues/40#issuecomment-592322987

Finally encountered it live, when I'm doing user-side actions quite fast

```
Error: remaining connection slots are reserved for non-replication superuser connections
    at Object.generic (/home/nonroot/transac/node_modules/postgres/lib/types.js:200:5)
    at Object.ErrorResponse (/home/nonroot/transac/node_modules/postgres/lib/backend.js:125:22)
    at TLSSocket.data (/home/nonroot/transac/node_modules/postgres/lib/connection.js:167:25)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  severity_local: 'FATAL',
  severity: 'FATAL',
  code: '53300',
  file: 'postinit.c',
  line: '789',
  routine: 'InitPostgres'
}
```

**Comment by joshxyzhimself** [comment]
Some context: the user-side actions I was testing got around 6 queries per call, so If I call it fast at around twice per second, it looks like I'm hitting DigitalOcean's 22 connection limit, which is weird since my understanding is it should queue it, correct?

**Comment by porsager** [comment]
@joshxyzhimself are you sure you are the only one connecting to the database (there could be other clients, psql, monitoring using some of those 22 connections)? Also note that if you use `sql.listen` and max: 22, you will occupy 23 connections in total since `sql.listen` gets a dedicated connection.

You can run the following query to see what connections are currently active:
```sql
select *
from pg_stat_activity
where datname = 'yourdbname';
```

**Comment by porsager** [comment]
Important note. Postgres.js doesn't automatically close connections unless you use the `timeout: seconds` option.

So yes, it will lazily create the connections when you start to run queries, and it will only create new connections if the current connections have queries queued.

**Comment by joshxyzhimself** [comment]
Understood, thanks a lot for clarifying.

I changed

```
const sql = postgres('postgresql://...', {
  max: 22,
  timeout: 10,
  ssl: { ca },
});
```

to


```
const sql = postgres('postgresql://...', {
  max: 20,
  timeout: 2,
  ssl: { ca },
});
```

And the errors are gone.
