### ISSUE TITLE
ERR_INVALID_ARG_TYPE when using Custom Types

### ISSUE THREAD

**Issue by zero245** [porsager/postgres#421]
"name": "postgres",
  "version": "3.2.4",

When try to use the Custom Type as stated in the front page documentation. Got this error when try to parse info from the db. 

Error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array
`

Here is the code that initiated the postgres connection. a,b,c,d are just a test custom type that I have created in the db. They are string and number. 

```
const TYPE_OID = 22252;
const pgSql2 = postgres({
	host : cfg.dbHost,
	port: cfg?.dbPort ?? 5432,
	database: cfg.dbName, 
	user: cfg.dbUsername, 
	pass: cfg.dbPassword,
  types: {
    'docusign': {
      // The pg_types oid to pass to the db along with the serialized value.
      to        : TYPE_OID,

      // An array of pg_types oids to handle when parsing values coming from the db.
      from      : [DOCUSIGN_OID],

      serialize : ({  a, b,c,d}) => [ a, b,c,d ],
      parse  : ([a, b,c,d]) => {
					console.log(a, b,c,d)
			}
  	}	
	}
}) 
```

**Comment by zero245** [comment]
It seems that the parse method is expecting a string instead of an array. I mean I can custom parse the input coming from the db as string, but I thought the whole point of passing the OID is that the lib knows how to deal with the custom types. Currently the value being passed into the parse method is expecting a string, not an array.

**Comment by porsager** [comment]
The serialize method must return a string, you're returning an array.

**Comment by Minigugus** [comment]
> The serialize method must return a string, you're returning an array.

I guess that's because of the [README](https://github.com/porsager/postgres/tree/bfd6a23a529c847cca1e8cfef16a80dbc5a45603#custom-types):
```js
const sql = postgres({
  types: {
    rect: {
      // The pg_types oid to pass to the db along with the serialized value.
      to        : 1337,

      // An array of pg_types oids to handle when parsing values coming from the db.
      from      : [1337],

      //Function that transform values before sending them to the db.
      serialize : ({ x, y, width, height }) => [x, y, width, height],

      // Function that transforms values coming from the db.
      parse     : ([x, y, width, height]) => { x, y, width, height }
    }
  }
})
```

If I remember well, this example exists since more than 2 years by the way... Is it still valid? :confused:

**Comment by porsager** [comment]
Ouch.. That should definately be fixed 😝

**Comment by zero245** [comment]
Hmm, as of right now, serialize method seems fine the way it is in README. the parse method is expecting to parse a CSV separated text.

**Comment by zero245** [comment]
```
      serialize : ({  geo, appDescription, type, envelopeId, status, agreementText}) => {[geo, appDescription, type, envelopeId,  status, agreementText]},

 parse :	async (val ) => {
   // val has the value of  ('active', 8, 9.23)
    let customObj = CSV.parse(val);
    return customObj;
}
```
This works. However, the custom type object is usually in a promise.  This can be resolve by 

tablea.customType = await tablea.customType

Just wonder if there is a better way to handle custom types?

**Comment by Minigugus** [comment]
> serialize : ({  geo, appDescription, type, envelopeId, status, agreementText}) => {[geo, appDescription, type, envelopeId,  status, agreementText]}

Are you sure you `serialize` function works correctly? Braces (`{ }`) around your array cause your function to always return `undefined`... Did you forgot the `return` keyword?

> tablea.customType = await tablea.customType

What is your `tablea`? Maybe it's just a type issue?

Anyway I'm not sure PostgreSQL is using CSV as types encoding :thinking: Maybe it works in your case but probably not for any custom type

**Comment by zero245** [comment]
Ok being super busy, I'll try to put up an example on gh. However, I need to check with work to see if we are allowed to do that.  In the mean time would really appreciate someone put up a correct example for postgres composite type.

**Comment by zero245** [comment]
> Are you sure you `serialize` function works correctly? Braces (`{ }`) around your array cause your function to always return `undefined`... Did you forgot the `return` keyword?


Hey thanks for the reply. Got caught up at work.  So `serialize` works fine. I'm having trouble understanding how `parse` function is suppose to work without CSV parsing. 

The first and only argument coming from the `parse` function is a CSV type of value set such as `('chicken', 'fish', 2.3, 5, true)`  from postgres.  I have confirmed this by adding coma **`,`** in the text value, and the values are escaped using CSV standard.  Don't know if this is making sense? It is a bit difficult to extract out this example from other code I'm working. I'll see if I can put up an isolated example on gh soon.

Or let me ask it another way:  how does the `parse` function knows the column names of the campsite type with only one argument? My guest is that is what the `from` and `to` OIDs are used get the list of the column names?  Or shall I ask this on the postgres forum?  

Would I need to run something such as 

`SELECT
    pg_type.typname, 
     pg_enum.enumlabel
FROM
    pg_type 
JOIN
    pg_enum ON pg_enum.enumtypid = pg_type.oid;
`
to actually just get the column names of the composite types?
