### ISSUE TITLE
on connect handler?

### ISSUE THREAD

**Issue by bonesoul** [porsager/postgres#426]
I'm using postrgres.js with next.js and vercel. I'm trying to debug the root cause of builds being slow under vercel and wonder if postgres.js supports some kind of debugging logic for connection and similar events so I can see how many connections are being utilized and how much does it each of them take.

**Comment by porsager** [comment]
@bonesoul you can use the debug option. Try eg:

```js
const sql = postgres({ debug: console.log })
```
