### ISSUE TITLE
Requires --unstable?

### ISSUE THREAD

**Issue by qgates** [porsager/postgres#427]
Sorry to bother, but this seems to have appeared recently and I can't seem to figure out why.

Running a script with ```await sql `` ```, recently started bombing with
```
Unstable API 'Deno.Conn#setKeepAlive'. The --unstable flag must be provided.
```
Can fix things with `--unstable` but I'm wondering where / why this crept in, also there's no mention of it in the docs?

Excuse in advance if I missed something obvious!

**Comment by porsager** [comment]
You can avoid using --unstable by disabling keep alive. 

```js
const sql = postgres({
  keep_alive: false
})
```
