### ISSUE TITLE
Sql type does not have `values()` method in TS definition

### ISSUE THREAD

**Issue by mattbishop** [porsager/postgres#431]
The docs describe the Sql query function as having a `values()` method: https://github.com/porsager/postgres#rows-as-array-of-values

The TypeScript definition file is missing this method declaration, so one has to use `//@ts-ignore` to access the function.

**Comment by porsager** [comment]
PR's welcome ;)

**Comment by Minigugus** [comment]
I thought #393 was already solving that :thinking:

https://github.com/porsager/postgres/blob/599d0e782ae0ea12cd5558e6de4393efad1b612f/types/index.d.ts#L570

**Comment by porsager** [comment]
Maybe it's not in an npm release yet?

**Comment by porsager** [comment]
Yeah, that appears to be it. I'll get around to make a release this weekend.
