### ISSUE TITLE
right way to test postgres with jest

### ISSUE THREAD

**Issue by xiangnanscu** [porsager/postgres#432]
```js
import postgres from 'postgres'

const sql = postgres({
  host: 'localhost',
  user: 'postgres',
  password: '111111',
  database: 'test',
})
await sql.unsafe(`
DROP TABLE IF EXISTS usr;

CREATE TABLE usr (
  id serial PRIMARY KEY,
  name varchar(4) UNIQUE,
  age integer);

INSERT INTO usr (name, age) VALUES ('u1', 22);
`)
// this is ok
const [u1] = await sql.unsafe("SELECT * FROM usr WHERE usr.name = 'u1'")
test('test select', async () => {
  expect(u1).toMatchObject({name: 'u1', age: 22})
});
// this will trigger error CONNECTION_ENDED
test('test select inner await', async () => {
  const [u2] = await sql.unsafe("SELECT * FROM usr WHERE usr.name = 'u1'")
  expect(u2).toMatchObject({ name: 'u1', age: 22 })
});
await sql.end()
```

**Comment by porsager** [comment]
I would suggest simply setting `idle_timeout: 1`. That way your connections will close one second after tests have finished, and no active handlers will keep the process alive.

**Comment by pat154** [comment]
> I would suggest simply setting `idle_timeout: 1`. That way your connections will close one second after tests have finished, and no active handlers will keep the process alive.

Hi @porsager, I find with db tests in jest the process doesn't exit correctly unless specifying the `idle_timeout`. Why does calling `await sql.end()` not release the connection/pool and allow the tests to exit gracefully? Setting an idle timeout feels a bit hacky.

Thanks!
