### ISSUE TITLE
How to add dynamic var to the INTERVAL function

### ISSUE THREAD

**Issue by dbeja** [porsager/postgres#433]
I need to do something like:
```javascript
sql`
INSERT INTO waiting(job_type, start_after)
VALUES(${job_type}, NOW() + 'INTERVAL ${delay} minutes'))
`
```
But I get the error
`could not determine data type of parameter $2`

Is there any way I can make the number of minutes dynamic?

**Comment by boromisp** [comment]
You probably need to do something like this:
```js
sql `select now() + ${delay + ' minutes'}::interval`
```
This would result in a query like this: `select now() + $1::interval` with `'123 minutes'` value for the parameter.

This might also work based on the [docs](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT):
```js
sql `select now() + interval ${delay} minutes`
```
Or you could use the [Custom Types](https://github.com/porsager/postgres#custom-types) mechanism instead.

**Comment by dbeja** [comment]
Perfect, it's working.
I went with first option.
Thanks, @boromisp.
