### ISSUE TITLE
sql throws "Could not infer helper mode" error for DELETE FROM 

### ISSUE THREAD

**Issue by henry132109** [porsager/postgres#434]
I'm using postgres@3.2.4 in Node v16.13.1. Here's a simple test case demonstrating the issue:
``` js
console.log(await sql`DELETE FROM test WHERE ${sql({ id: 3 }, 'id')}`)
```
gives:
```
Error: Could not infer helper mode
    at Builder.build (~/node_modules/postgres/cjs/src/types.js:71:13)
    at stringifyValue (~/node_modules/postgres/cjs/src/types.js:111:38)
    at stringify (~/node_modules/postgres/cjs/src/types.js:102:16)
    at build (~/node_modules/postgres/cjs/src/connection.js:221:20)
    at Object.execute (~/node_modules/postgres/cjs/src/connection.js:166:7)
    at go (~/node_modules/postgres/cjs/src/index.js:296:14)
    at Promise.handler (~/node_modules/postgres/cjs/src/index.js:285:14)
    at Promise.handle (~/node_modules/postgres/cjs/src/query.js:136:65)
```

The table is described by:
``` sql
CREATE TABLE IF NOT EXISTS public.test
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT test_pkey PRIMARY KEY (id)
)
```

**Comment by porsager** [comment]
There's currently no helper to generate `where` clauses from objects. Mainly because it's rare that you only need strict equality on dynamic columns, so the uses cases quickly evolve to require lower than, greater than, begins with, contains etc..

I am assuming you know that your test case above should simply be written like below, but I'm adding it for other readers in the future:

```js
const obj = { id: 3 }
await sql`
  delete from test 
  where id = ${ obj.id }
`
```

If you want a dynamic equality check on all keys + values in an object you can do it using fragments instead, even though it's a bit more involved.

```js
const equals = { age: 17, city: 'Boston' }
await sql`
  delete from test 
  ${ 
    Object.entries(equals).map(([key, value], i) => 
      sql`${ i ? sql`and` : sql`where` } ${ sql(key) } = ${ value }`
    )
  }
`
```

**Comment by lithdew** [comment]
> I am assuming you know that your test case above should simply be written like below, but I'm adding it for other readers in the future:
> 
> ```js
> const obj = { id: 3 }
> await sql`
>   delete from test 
>   where id = ${ obj.id }
> `
> ```
> 
> If you want a dynamic equality check on all keys + values in an object you can do it using fragments instead, even though it's a bit more involved.
> 
> ```js
> const equals = { age: 17, city: 'Boston' }
> await sql`
>   delete from test 
>   ${ 
>     Object.entries(equals).map(([key, value], i) => 
>       sql`${ i ? sql`and` : sql`where` } ${ sql(key) } = ${ value }`
>     )
>   }
> `
> ```

The following helper fragment code doesn't seem to work for me on the latest version - should this help anyone stumbling upon this thread, here is an alternative that recursively reduces the equality checks into a single fragment:

```ts
const equals = (params: object, schema: string = "") => Object.entries(params).reduce(
    (x, [k, v], i) => sql`${x}${i ? sql`and` : sql``} ${schema ? sql`${sql(schema)}.` : sql``}${sql(k)} = ${v}`,
    sql``
);

const deleteSession = async (sql: postgres.Sql, params: { publicKey?: string, nonce?: string }) => {
    const [session] = await sql`delete from sessions using (${sessions(sql)}) s where ${equals(params, "s")} returning *`;
    return session;
};
```
