### ISSUE TITLE
Fundamental tools for this project

### ISSUE THREAD

**Issue by vitaly-t** [porsager/postgres#44]
@porsager  Greetings!

First of all, congratulations on making good progress with this project! The community does need it a lot, considering just how badly stale things are with the old [node-postgres] maintenance, which feels like it is going nowhere. Somebody had to shake off the ongoing apathy, rethink everything and get started from scratch 👍 

We had a discussion not so long ago (I am the author of [pg-promise] library), in relation to the performance considerations, but that's another topic.

I mentioned that I did a similar attempt within [pg-core], but unfortunately, never made enough progress there. Your attempt picked up very nicely here!

My only wish is that you were to choose TypeScript from day one for this project :wink:

Finally, as to why I opened this issue, in addition to what I said above...

I've done tons of development over the years, for postgres and in general. And there are two modules in particular that I wrote, which I think you should definitely adopt within your project, either directly, or at least within your documentation and examples:

* [connection-string]
* [pg-minify]

These are essential, basic tools for just about every app that uses Postgres in NodeJS. Each is fundamental, and without any dependencies.

[connection-string]:https://github.com/vitaly-t/connection-string
[pg-minify]:https://github.com/vitaly-t/pg-minify
[node-postgres]:https://github.com/brianc/node-postgres
[pg-promise]:https://github.com/vitaly-t/pg-promise
[pg-core]:https://github.com/vitaly-t/pg-core

**Comment by Minigugus** [comment]
*That's just a personal opinion we can discuss :wink:*

> My only wish is that you were to choose TypeScript from day one for this project

As a TypeScript enthusiast, I admit it's appealing :smile: But in TypeScript, `postgres` wouldn't be what it is today : a dependency-free library (even `@types/*` *are* dependencies :disappointed:). You said `considering just how badly stale things are with the old node-postgres`, and I think a big problem with these old libs is that they don't use dependencies injections, resulting in a complex API and a contributing guide. With `postgres`, users and contributors can develop and it *just works*.

> And there are two modules in particular that I wrote, I think you should definitely adopt within your project, either directly, or at least within your documentation and examples

As explained above, `within your documentation and examples` seems a better idea than `within your project` directly, to keep the library simple and with 0 dependencies, and relying on dependencies injections for more complex use cases. I'm not saying that your suggestion should be rejected, but perhaps you could agree on a common interface? :wink:

**Comment by vitaly-t** [comment]
@Minigugus Use of TypeScript does not require any dependencies at all. Look at the [connection-string] as an example, it is 100% TypeScript, with zero dependencies. And the ones in `devDependencies` are irrelevant.

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by porsager** [comment]
Hey @vitaly-t .. Thank you 🙂

I don't see the value add of Typescript, and I would love to detail it with a longer response and discuss it, but it'll have to wait until I find some more time, it's not something I'm able to go into now.

I've got [a branch with multi-host support](https://github.com/porsager/postgres/tree/multi-host) which seems to be the only thing lacking from my own url parsing, so if you could detail where your connection-string module would be useful I can better consider it.

About pg-minify that's certainly interesting, and the overhead would be minimal if caching per query by the unique tagged template call. Maybe the best combination would be a pre-query hook that would allow the user to plug in a transform like pg-minify.

**Comment by vitaly-t** [comment]
@porsager Library [connection-string] supports multiple hosts standard right out of the box, which is documented right on the main page, where you get property `host` (array of hosts), with automatic host type detection: `domain`, `socket`, `IPv4` or `IPv6`.

Plus it does additional host parsing, it can generate a valid connection string from parameters, an an easy and safe  way to set defaults for the connection.

If you have any question about adopting it - please throw them at me ;)

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by vitaly-t** [comment]
@porsager 
> About pg-minify that's certainly interesting, and the overhead would be minimal if caching per query by the unique tagged template call. Maybe the best combination would be a pre-query hook that would allow the user to plug in a transform like pg-minify.

The main value `pg-minify` offers is for SQL files, which I do hope you support :smile:

**Comment by pauldraper** [comment]
> pg-minify

The use of pg-minify to "reduce I/O usage" is questionable at best.

The main reason for it, IMO, would be to reduce query size in order to fit within length limits for `pg_stat_statements`.

**Comment by porsager** [comment]
I'd like to keep this dependency free as it is now, and since it's fairly straight forward to use pg-minify if it's needed for a project, I don't think it's needed to be included directly. I'd be happy to have a description of usage in the README, so feel free to do a PR with an example and perhaps a use case.
