### ISSUE TITLE
Listen always use one connection and it never this connection use for transactions

### ISSUE THREAD

**Issue by uasan** [porsager/postgres#441]
Hello.
Method `sql.listen()`, it random selects connections from the pool, as a result, the pool cannot clean up these connections because they are used for listen.

There is also a problem if this connection opens a transaction, it will not receive a notify message until the transaction completes, so long running transactions are very slow to receive notifications.

I suggest that the `sql.listen()` method always use only one connection, and that connection is never used for transactions, then there will be no problems with notification delays and the connection pool will not hold many connections if each of them has a listener

**Comment by porsager** [comment]
sql.listen creates a completely isolated instance of postgres with max 1, so I don't know what you're referring to?

**Comment by uasan** [comment]
So I misunderstood the causes of the symptoms, sorry )
I noticed an increase in the number of connections with a large number of listeners.
Will 10 connections be created for 10 listeners?

**Comment by porsager** [comment]
Ah ok, cool. 

No, only a single one per postgres() instance.

**Comment by porsager** [comment]
So if you have postgres({ max 4 }) and you use listen, you will have 4 connections in your pool and 1 connection for listen, so 5 connections total

**Comment by uasan** [comment]
Ok, I'll close the ticket then, thanks
