### ISSUE TITLE
bug: types are not exported

### ISSUE THREAD

**Issue by RealShadowNova** [porsager/postgres#448]
I am creating a provider for [josh-development/providers](https://github.com/josh-development/providers), but I have encountered an issue where not all of the types used in this package are actually exported. As an example, you export the declared `Sql` function type, but none of the types in it's generic that are used in the [source code](https://github.com/porsager/postgres/blob/master/types/index.d.ts#L3-L21)

What's the solution here? Export all the types that are used, it's not useful for end users to be given types they cannot reproduce or use to declare with. I understand this package doesn't have direct TypeScript support, so if needed I can attempt to export all the missing types.

I hope you understand my frustration as I'm trying to use this nice package with only partial types.

**Comment by RealShadowNova** [comment]
After doing some further research, I have realized that I did not need these types I talked about here. I think adding a default generic type for `Sql` and some documentation explaining what those types do would make it better to avoid confusion later on.

**Comment by Minigugus** [comment]
`PostgresTypeList` and `JSToPostgresTypeMap` are just `Record`s so you can use `{}` as constraint

https://github.com/porsager/postgres/blob/599d0e782ae0ea12cd5558e6de4393efad1b612f/types/index.d.ts#L129-L135

Anyway #416 is going to fix that :+1:
