### ISSUE TITLE
Improve error messages of 

### ISSUE THREAD

**Issue by karlhorky** [porsager/postgres#450]
Hi @porsager ! 👋  

I wanted to open an issue to improve the error messages when errors like `Error: UNDEFINED_VALUE: Undefined values are not allowed` happen.

Currently it's not easy to know what undefined values are being passed, especially if you're passing multiple interpolated values and are not using 100% TypeScript in the project.

If possible, with a code snippet showing the tagged template literal and which parameter is undefined, similar to the experience when you break JSX code in Next.js:

```
ReferenceError: Badgee is not defined

pages/index.tsx (650:37) @ eval

  648 | <div css={candidateBadgeStyles}>
  649 |   {!isEditing ? (
> 650 |     <Badgee
      |     ^
  651 |       data-cy="candidate-badge"
  652 |       color={
  653 |         (
```

![Screen Shot 2022-08-02 at 18 22 05](https://user-images.githubusercontent.com/1935696/182424637-bd9764cd-d31c-4831-a30a-3d3349b1ba70.png)

**Comment by porsager** [comment]
Agreed, that would be a great improvement, but should at least be done at no cost to performance. Currently the undefined error is thrown before the query string has finished building, but I just did a quick test, and getting an error that includes the part of the string up to the undefined value is pretty easy. Eg.

```js
sql`
  select
    name, content
  from users
  join posts using(user_id)
  where user_id = ${ undefined }
  limit 1
`
```
would then throw
```sql
Error: UNDEFINED_VALUE: Undefined values are not allowed:

    select
      name, content
    from users
    join posts using(user_id)
    where user_id = $1
                     ^ is undefined
```

That solves the raw parameter values, but we'd also need to cover the dynamic ones passed using `sql()`.

**Comment by porsager** [comment]
Closing this as we already have #380 :)

**Comment by karlhorky** [comment]
Or sorry, didn't see this one, I'll comment over there!
