### ISSUE TITLE
Inline parameters values into query SQL string

### ISSUE THREAD

**Issue by uasan** [porsager/postgres#454]
Hello.

Many SQL commands do not support parameters in queries, for example:
```SQL
COPY (SELECT * FROM t WHERE id = $1 ) TO STDOUT;
```
```SQL
CREATE VIEW AS SELECT * FROM t WHERE id = $1;
```

I plan to implement my own function, serialize the values by described SQL string, and substitute them into the SQL string.

Maybe there is a better solution?
Thanks.

**Comment by porsager** [comment]
Yeah, I've been having the same issue with DO statements where the protocol parameters doesn't work because they collide with the internal parameters. Perhaps the solution should be to allow nesting sql.unsafe too, so that it'd look like this?

```js
sql`COPY (SELECT * FROM t WHERE id = ${ sql.unsafe(user_provided_id_that_needs_to_be_sanitized) } ) TO STDOUT;`
```

**Comment by uasan** [comment]
I also did this, but there were SQL requests that must be given to JSON in one case and to COPY to csv in another, I made such a decision:
```JS
const { types } = await sql.unsafe(queryString, values).describe();

for (let i = 0; i < types.length; i++)
  values[i] = serializers[types[i]](values[i]);

return await sql.unsafe(queryString, values);
```
perhaps if many users need it, it is worth making a built-in helper in the sql function so that it does this

**Comment by ChristophP** [comment]
I'm having a similar problem where I want to pass the table name and columns to a copy query dynamically.

```js
const query = sql`COPY ${tableName} ${columns} FROM STDIN`;
```

The solution to nest `unsafe` would be sufficient for me.

**Comment by porsager** [comment]
@ChristophP that is different and should be possible to do as things are currently. You should wrap your table name and columns in `sql()`

eg like this (not tested as i don't know what your variables contain ;) ):
```
const query = sql`COPY ${ sql(tableName) } ${ sql(columns) } FROM STDIN`;
```

**Comment by ChristophP** [comment]
@porsager I tried this sql`COPY ${ sql('table') } ${ sql(['peter', 'assi']) } FROM STDIN` but I got "Could not infer helper mode".
<img width="900" alt="grafik" src="https://user-images.githubusercontent.com/5880236/184898467-0da558c6-5ebd-41a5-8c13-6364cf003393.png">

**Comment by ChristophP** [comment]
Nesting `sql.unsafe()` is not something that's supported yet is it?
I tried it on a copy query like this.

```js
const cols = `(col1, col2)`;
sql`COPY some_table ${sql.unsafe(cols)} FROM STDIN`;
```
But my DB gave errors and it appeared that it only the first part of the query was sent to the DB.
<img width="626" alt="grafik" src="https://user-images.githubusercontent.com/5880236/194060842-b7807791-a28e-42d3-b491-8d9140e2eb19.png">

**Comment by porsager** [comment]
What version are you seeing that with? (the screenshot error doesn't match the code you posted)

**Comment by porsager** [comment]
```
sql`COPY ${ sql('users') } ${ sql(['peter', 'assi']) } FROM STDIN`
```
`sql(['peter', 'assi'])`, won't work there, but I'm looking into fixing that...

**Comment by porsager** [comment]
nesting sql.unsafe works now, so closing this :)

**Comment by acehand** [comment]
@porsager  - am trying to do the following in the Latest Master 
`await sql`copy (select * from events where customer_id = ${sql.unsafe(customer_id)}) to stdout`.readable()`
but it just doesnt seem to work. My `customer_id` is an uuid String. 

My intention is to make both the tableName and condition value to be interpolated. Can you tell me how I can get this to work. Thanks

**Comment by porsager** [comment]
You need to single quote the customer id 😉

**Comment by acehand** [comment]
thanks @porsager  . that worked.
