### ISSUE TITLE
Erroneous use closed connection by timeout from pool

### ISSUE THREAD

**Issue by uasan** [porsager/postgres#457]
Hello.
We get an error `write CONNECT_TIMEOUT undefined:undefined` every day.

From the TCP dump, we can see that when the application starts, the client opens many connections, in each connection a response from postgres for authorization is received, some connections instead of sending a password send a FIN packet and close the connections, but it looks like this closed connection remains in the pool and later it is used for sending SQL requests, at this moment we get the indicated error.

To connect, we use the default settings, there are no specific settings, the connection takes place directly, Postgres 14.

**Comment by porsager** [comment]
Hi @uasan . 

Does your application run at least the same amount of queries at startup as connections being opened?

**Comment by uasan** [comment]
yes, many requests are processed, but this error appears from time to time, this error sometimes occurs when a new connection is created to send a SQL request

**Comment by uasan** [comment]
We seem to have identified the problem, it is not on the side of postgres.js, I am closing the ticket

**Comment by porsager** [comment]
Hey @uasan - glad to hear, and sorry for the silence, my time is limited these days.

Still, I'm very curious to hear what the issue was?

**Comment by uasan** [comment]
When the network is congested, the socket does not respond within the specified time limit
