### ISSUE TITLE
"UNDEFINED_VALUE: Undefined values are not allowed" even though all values are set

### ISSUE THREAD

**Issue by ChristophP** [porsager/postgres#466]
When trying to build a query from for inserting rows from one table into another I get an unexpected error. I am trying to do this.
```js
    const tableName = "users";
    const tempTableName = "temp_users";
    const columns = ["id", "name"];
    const query = sql`
      INSERT INTO ${sql(tableName)} ${sql(columns)}
      SELECT ${sql(columns)} FROM ${sql(tempTableName)} 
      ON CONFLICT DO NOTHING`;
```
Then I get this error saying that something is undefined, even though from what I can tell all values for the query interpolation are set.

```
{
    "errorMessage": "UNDEFINED_VALUE: Undefined values are not allowed",
    "errorType": "Error",
    "stackTrace": [
        "Error: UNDEFINED_VALUE: Undefined values are not allowed",
        "    at handleValue (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:84:20)",
        "    at stringifyValue (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:114:5)",
        "    at /Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:126:7",
        "    at Array.map (<anonymous>)",
        "    at /Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:125:19",
        "    at Array.map (<anonymous>)",
        "    at valuesBuilder (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:124:16)",
        "    at Object.insert [as fn] (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:173:5)",
        "    at Builder.build (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:72:20)",
        "    at stringifyValue (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:110:38)",
        "    at stringify (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/types.js:101:16)",
        "    at build (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/connection.js:221:20)",
        "    at Object.execute (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/connection.js:166:7)",
        "    at Promise.handler (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/index.js:247:15)",
        "    at Promise.handle (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/query.js:136:65)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at new Query (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/query.js:35:9)",
        "    at sql (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/index.js:105:11)",
        "    at /Users/d441365/projects/cpx/data-ingestion-service/src/lib/db.js:52:23",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at async scope (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/index.js:217:18)",
        "    at async Function.begin (/Users/d441365/projects/cpx/data-ingestion-service/node_modules/postgres/cjs/src/index.js:204:14)",
        "    at async run (/Users/d441365/projects/cpx/data-ingestion-service/src/csv-to-rds/index.js:69:24)"
    ]
}
```

**Comment by ChristophP** [comment]
As a workaround I used `sql.unsafe` for the query and manually format the values, which works for now, but it would be nice to use `sql` for it.

**Comment by StevenJPx2** [comment]
Facing the same issue right now. It had been working fine even in tests, but it is suddenly failing

**Comment by porsager** [comment]
@StevenJPx2 you most likely have dynamic input values that are undefined. If users can supply these values and you aren't handling undefined cases, this can happen at any time.

**Comment by StevenJPx2** [comment]
I figured it out. It happened to be some other unrelated issue where this package was in the crossfire. Still no idea why it works again... but that's life!

**Comment by porsager** [comment]
Great to hear ☺️ Out of curiosity, was it a good thing in your case that Postgres.js didn't allow undefined to be implicitly converted to null? eg. what would have happened if that undefined value had just been converted to `null` instead of an error?

**Comment by StevenJPx2** [comment]
Tbh, I would prefer if it would implicitly set it to null. Maybe you could consider adding a flag for that!

**Comment by porsager** [comment]
there already is ;) https://github.com/porsager/postgres#transform-undefined-values

**Comment by StevenJPx2** [comment]
Oh nice! No way we can do it at a query level? Only as a global setting?

**Comment by porsager** [comment]
at a query level just convert to null like:
```
update x set name = ${ someValue || null
```

But no there is currently no way to convert all parameters from undefined to null like the transform. Could be a good idea to have maybe :P

**Comment by Chandra-Panta-Chhetri** [comment]
> @StevenJPx2 you most likely have dynamic input values that are undefined. If users can supply these values and you aren't handling undefined cases, this can happen at any time.

How do we handle that case? For example, say you have an update endpoint and let the user supply the properties they can update. How do we make the property names passed to sql(object, "property_name1", ...etc) dynamic?

**Comment by porsager** [comment]
@Chandra-Panta-Chhetri Map over them and set values to null... 

Lately I've been very happy about the PostgreSQL json functions, almost not even using these dynamic helpers myself..

Wrt' to the initial query I think the `undefined` error was a red herring. The issue was rather in the query not having parenthesis around the columns (I'm getting syntax error with the latest version).
