### ISSUE TITLE
How to call pg_dump?

### ISSUE THREAD

**Issue by vineryap** [porsager/postgres#467]
Hello, how can I call pg_dump from this library? is it possible?
I tried :
```js
sql`pg_dump`
// and
sql`select pg_dump`
```

**Comment by porsager** [comment]
[`pg_dump`](https://www.postgresql.org/docs/current/app-pgdump.html) is not an sql command - it is a cli tool included in the PostgreSQL toolset, and not really related to Postgres.js in any way.

You can however execute it using node.js [`child_process`](https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html) if you'd like to run it from node.

**Comment by vineryap** [comment]
Thanks for confirming.
I just moved from Mikro-ORM and wondering just maybe I can also use something similar too here.
Anyway, I ended up using the node child_process.

Again, thanks!
