### ISSUE TITLE
Inconsistent transformation behavior when using SET / SHOW local variables 

### ISSUE THREAD

**Issue by sectos** [porsager/postgres#468]
Postgres package version: 3.2.4

I have the library configured to transform columns to and from camelCase:
```js
transform: {
    column: {
        to: postgres.fromCamel,
        from: postgres.toCamel
    }
}
```

When executing a query to set variables, the library transforms the value of my variable from camelCase.
For example:
```js
const tenantId = 'aBCDe';
await sql`SET LOCAL request.tenant_id = ${sql(tenantId)}`;
const getTenantId = (await sql`SHOW request.tenant_id`)[0];
```
The value of `getTenantId` is: `a_b_c_de` rather than the expected `aBCDe`.

I believe the transformation occurs by using the helper `sql(tenantId)` but passing the value as a normal interpolated parameter:
```js
await sql`SET LOCAL request.tenant_id = ${tenantId}`;
```
Produces the following error:
`syntax error at or near "$1"`

Why am I forced to use the SQL helper to pass this value to the query?
Is it expected behavior for the value to transform from camelCase but not back to camelCase upon retrieval?

**Comment by sectos** [comment]
[https://github.com/porsager/postgres#unsafe-raw-string-queries](Unsafe raw string queries) seems to solve the issue for now but feels like an unsafe workaround.

**Comment by porsager** [comment]
You should use the function [`set_config`](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SET) with third parameter as true (local) instead of `SET LOCAL` since that allows you to use parameters. For retrieving values you could also use `current_setting()` function instead of `SHOW` Your example would be the following and work as expected:

```js
await sql.begin(async sql => {
  const tenantId = 'aBCDe';
  await sql`select set_config('request.tenant_id', ${ tenantId }::text, true)`;
  const getTenantId = p(await sql`select current_setting('request.tenant_id')`)[0];
})
```
