### ISSUE TITLE
sql.simple() for multiple statement queries without parameters 

### ISSUE THREAD

**Issue by Cheprer** [porsager/postgres#472]
Hi would be nice to create ``` sql``.simple() ``` with similar functionality as sql.unsafe(\`\`) except it won't accept any parameters and you will be able to invoke multiple sql statements in there. Useful for DB initialisation.

Solution for now:  To use "simple" queries you can use sql.unsafe(query) and no query arguments. That will implicitly create it as a simple query.

**Comment by gilbert** [comment]
Thanks! Can we get the type defs for it too?
