### ISSUE TITLE
The query does not turn into a prepared request

### ISSUE THREAD

**Issue by budarin** [porsager/postgres#478]
try to make the query several times
 
```js
const result = await pg`select * from ${schema}.root(${pg.json(props)}::jsonb )`;
```

then I look at the results of the query

```sql
SELECT relfilenode FROM pg_class WHERE relname = 'pg_prepared_statements';
```

but there is not a single prepared request

Why? What am I doing wrong?

**Comment by porsager** [comment]
Not sure how that check works, but try with `select * from pg_prepared_statements` from the same session.

**Comment by budarin** [comment]
Thanks!
it creates prepared request
