### ISSUE TITLE
Production environment setup guide?

### ISSUE THREAD

**Issue by sks147** [porsager/postgres#482]
I need to use this package in a production environment and I'm not able to find sufficient documentation for setting up few things like:

1. Health checks.
```javascript
const checkPostgres = async function() {
    try {
        const session = await postgres.connection
        if(!session || !session.isOpen) {
            throw new Error('Postgres is not connected')
        }
    } catch (error) {
        throw new Error('Postgres is not initialized')
    }
}
```
I want to implement a health check similar to this, which I can hit using a `/healthcheck` api and know if postgres connection is working or not.

2. Handling connection, reconnect, disconnect events **SIMILAR** to this code snippet
```javascript
const connect = async function (connString, dbName) {
	let db;
	try {
		const client = await postgres.connect(connString);
		client.on('connected', function () {
			console.log('postgres_connection_open');
		});
		client.on('disconnect', function (error) {
			console.error('postgres_connection_close', error.stack);
		});
		client.on('reconnect', function (error) {
			console.error('postgres_connection_reconnect', error.stack);
		});
		db = client.db(dbName);
		console.log(`Connected successfully to ${connString} ${dbName} database.`);
	} catch (error) {
		console.error(`[connect] : ${error.stack}`);
	}
	return db;
};

```

Can anybody from the community, please share how they have setup `postgres.js` with these things setup properly?

**Comment by porsager** [comment]
Hi @sks147 .. All connection handling is done by Postgres.js itself, so you don't need to do anything yourself.

If you need a health check I would simply suggest doing eg.
```
sql`select true as online`
```
