### ISSUE TITLE
Not able to handle bigint, returns string instead

### ISSUE THREAD

**Issue by sks147** [porsager/postgres#486]
I have kept `userId` as `bigint` in postgres in wallet table.
Running a select query returns `userId` as `string` instead of `number`
```json
{"userId":"166226718100043","money":900}
```

**Comment by porsager** [comment]
see https://github.com/porsager/postgres#numbers-bigint-numeric

**Comment by sks147** [comment]
Thanks for quick resolution. Sorry for creating redundant issue, was working late, missed reading this section before creating issue.
