### ISSUE TITLE
how to set dynamic where key?

### ISSUE THREAD

**Issue by transtone** [porsager/postgres#489]
in some case, it want use a dynamic column like this:
```sql
select id,name from users where ${column} = ${id}
```

how can I do this?

**Comment by porsager** [comment]
https://github.com/porsager/postgres#dynamic-column-selection

```
sql`
  select id,name from users where ${ sql(column) } = ${id}
`
```

**Comment by transtone** [comment]
thx. 
I use 
```sql
sql`  select id,name from users where ${ sql(column) } = ${sql(id)}`
```
go a error. 

ATTENTION: value no need `sql()`!!!

**Comment by porsager** [comment]
In sql you have keywords, identifiers and values.

A value such as `id` should simply be added raw as I had put in the example above. An identifier such as a column name og a table name should be wrapped in `sql(column)`, and keywords should be written using tagged template strings, such as ``` sql`desc` ```.

Hope that clears it up a bit ;)

**Comment by porsager** [comment]
Please let me know if you have ideas for improving the documentation on this?

**Comment by transtone** [comment]
Add a example with [dynamic-column-selection](https://github.com/porsager/postgres#dynamic-column-selection) in `where` is welcome.

**Comment by porsager** [comment]
Alright, how about the differentiation between values, keywords and identifiers? I was curious how you ended up wanting to put id into sql().

Either way, a PR is much welcome for that `where` addition.
