### ISSUE TITLE
Transform not working on returned results

### ISSUE THREAD

**Issue by the-red-herring** [porsager/postgres#491]
I am trying to convert the column names of the returned results from an sql query so that they are camelCase rather than PascalCase.
![image](https://user-images.githubusercontent.com/14847896/193659612-3af536cb-2a3c-44e4-a76c-185c2274b631.png)
this is how I have setup the connection (note: I have also tried the postgres.camel, postgres.kebab to see if that would change anything, as well as a custom function that I have verified should work).

I am consistently getting back this however:
![image](https://user-images.githubusercontent.com/14847896/193660631-ce3b5f19-4842-44e2-9f74-cbdf2a3f8746.png)
From what I understand of the readme, I would expect _IngredientId_ to be _ingredientId_ for the setup in the first screenshot, and _Name_ to be _name_

Perhaps the config I am using is not correct though?

**Comment by porsager** [comment]
What is the actual column name in the db? 

Those helpers only convert to/from snake_case

**Comment by the-red-herring** [comment]
Ah okay, I see now in the examples the db column names are in snake_case - thank you for clarifiying that :)

I did try a custom function but this did not seem to work either. I will double check it.
