### ISSUE TITLE
LISTEN with a "." character

### ISSUE THREAD

**Issue by darrachequesne** [porsager/postgres#495]
Hi! Is it possible to listen to a channel which has a "." character in its name?

```js
const channel = "a.b";

await sql.listen(channel, (payload) => {
  console.log(payload);
});

await sql.notify(channel, "hello");
```

throws `Uncaught (in promise) PostgresError: syntax error at or near "."`

Is there a way to escape this character?

**Comment by porsager** [comment]
Hah, nice catch! That's actually my fault because I was using the identifier escape function for channel names. That is great when you want to write schema.table, but not great for channel names ;) I've fixed it, and I'll make a release with this fix this week.

Thank you!

**Comment by darrachequesne** [comment]
Awesome, thanks a lot :+1:
