### ISSUE TITLE
Question: When does one need to use `sql` on query fragements and when not?

### ISSUE THREAD

**Issue by ChristophP** [porsager/postgres#496]
The docs mention that sometimes it's ok to use plain template parameters to place things into a query template like this.
```js
  const users = await sql`
    select
      name,
      age
    from users
    where age > ${ age }
  `
```

In other cases though interpolated values need to be wrapped in a `sql()` call.

```js
const table = 'users'
    , column = 'id'

sql`
  select ${ sql(column) } from ${ sql(table) }
`
```

Even though there are good examples in the docs it's not 100% clear to when `sql()` is needed and when not? Is it only needed for anything else other than scalar values? What about strings like a table name?

Maybe I'm missing something but i would be nice to mention that in the docs more explicitly

**Comment by porsager** [comment]
A PR for the docs would be great if you've already scoured all of it and didn't find a good explanation.

``` ${ sql`` } ``` is for one or more keywords or sql
`${ sql() }` is for identifiers
`${ 'somevalue' } is for values

**Comment by ChristophP** [comment]
Awesome thank you for your quick reply, that overview helps a lot.
I can try to open a PR for the docs once I finish what I'm working on atm.

I have one additional question, that came up for me.

If `${sql``}` is for fragments, what is the difference between that and `${sql.unsafe("")}` for a fragment?

**Comment by porsager** [comment]
The reason ``` sql`` ```  is more safe than ``` sql.unsafe() ``` is that you cannot pass user strings to ``` sql`` ```, it will only be strings that you actually verified and have in code.

For instance the simple case of wanting to let a user decide on sort order. If you allow them to pass the string and put it in ```
select * from some_table
order by name ${ sql.unsafe(order) }
``` 

you would open yourself up to sql injections, whereas if you use ``` sql`` ``` you won't:

```
select * from some_table
order by name ${ order === 'desc' ? sql`desc` : sql`asc` }
```

**Comment by ChristophP** [comment]
Ah ok that makes sense.

So all in all would if I understand correctly
`sql`` ` will
- escape number, date or string values when passed in directly
- quote identifiers when strings are passed in via `sql()`
- build query parts when objects or arrays are passed in via `sql()`
- use the string as is, when passed in via `sql.unsafe()`.

**Comment by ChristophP** [comment]
I added a PR with some additional info for the docs https://github.com/porsager/postgres/pull/504
