### ISSUE TITLE
sql string?

### ISSUE THREAD

**Issue by fjf2002** [porsager/postgres#50]
Hi again porsager,

I like your lightweight library quite a lot, but I'm facing a problem:

As far as I understand, ``sql`...` `` builds the SQL String and submits it instantaneously to the DB for execution.

And I can't pass an artibrary string to `sql` insted of a template expression, can I?

Is there any way I can store an SQL query as a String or a kind of "prepared statement without parameters", that is just stored and maybe executed later in another function?

**Comment by fjf2002** [comment]
Perhaps it is OK just as it is now, but I have to wrap my head around it. I could build lambda/arrow expressions

    () => { sql`SELECT 1` }

and pass these around...

**Comment by porsager** [comment]
Yeah 👍 That's how to do it 😉 There's no reason for this library to provide an opinionated abstraction for that. 

One small nit to your example is to use implicit return by removing the curly brackets or be sure to return the ```sql``  ``` result.  

So:
```
const users = () => sql`select * from users`
```
