### ISSUE TITLE
Question: best way to set GUC variable

### ISSUE THREAD

**Issue by clarknova** [porsager/postgres#501]
Hello, I want to set guc variables for a series of requests. It seems like the only way to do that is with a transaction because of connection pooling? Am I correct?

If I set the pool size to 1 are the guc variables reset if the connection is returned?

In any case this is a great library and I enjoy using it very much.

**Comment by porsager** [comment]
@clarknova are you variables supposed to be global (per connection) or local (per statement)?

You can set them as options for the startup query so they're set from the beginning of any connection - like this:

```js
postgres({
  connection: {
    'your.variable': 'a thing',
    'your.other_variable': 'something fun'
  }
})
```

If they should be local to each query, then yes, either a transaction, or if you can describe some more of your use case, I might have some other tricks.

**Comment by clarknova** [comment]
Thank you for taking the time to answer:

I want to use row security policies. 
After the user logs in, I add (for example) his jwt to the current_setting
`set request.jwt to '{"claims": ["xy"], "user_id":123}';`
and write my policies around this information.

I saw this technique used in postgrest and by extension supabase and I find the idea quite charming.
For Reference: https://postgrest.org/en/stable/auth.html#web-users-sharing-role

**Comment by umquat** [comment]
HI all, resurrecting this :)

Same question. Also learning from postgrest and trying to use the same technique in a web app.

I managed to set a bunch of settings like so:

```javascript
if (req.headers[TENANT_HEADER] != "null") {
    // change to anon role

    await sql`set role to ${sql(process.env.DB_ANON)}`
      .then(() => {
        sql`set traffic.tenant to ${sql(req.headers[TENANT_HEADER])}`;
      })
      .catch((err) => {
        console.log("ERR", err.message);
      });
}
```
Is this The Way(c) ?

**Comment by porsager** [comment]
You should use transactions for this. Any other method has the potential of leaking the user context..
