### ISSUE TITLE
Race condition in deno for ending connection

### ISSUE THREAD

**Issue by AndLut** [porsager/postgres#502]
Hello,

I have the problem, that when executing my tests, I always get the note on leaking async ops:
`1 async operation to sleep for a duration was started before this test, but was completed during the test. Async operations should not complete in a test if they were not started in that test.`

As written by Deno, this error is due to some timeouts/intervals not being closed before the next test starts. 

I tried to look further into this issue, and think it is due to the way ending the postgres connection works. When calling the `.end()` method, the `socket.once('closed', resolve)` method is invoked, which in turn invokes the `closed(hadError)` function. The important part here is, that all the timers get cleared in the `closed(hadError)` method. Maybe here the race condition already starts, as the `closed(hadError)` function is async, but it is not awaited in the `.end()` method?
Would a possible solution be to cancel all the timers in the `.end()` method as well?

Minimal working code example to try the issue (needs a working postgres instance and the host, database and port env variables set):

~~~
import postgres from 'https://deno.land/x/postgresjs@v3.3.1/mod.js';
import {
  assertStrictEquals,
} from 'https://deno.land/std@0.134.0/testing/asserts.ts';
import {
  beforeAll,
  describe,
  it,
} from 'https://deno.land/std@0.137.0/testing/bdd.ts';

describe('sample describe', () => {
  beforeAll(async () => {
    const sql = postgres({ user: 'postgres', keep_alive: 0 });
    await sql`select * from pg_sequences`;
    await sql.end();
  });

  it('sample it', async () => {
    const sql = postgres({ user: 'postgres', keep_alive: 0 });
    await sql`select * from pg_sequences`;
    assertStrictEquals(true, true);
    await sql.end();
  });
});
~~~

Thank you in advance!

**Comment by tmikaeld** [comment]
That's because postgrejs always opens the connection on first data request, to avoid this and not get leaks, you can do it like this:

```javascript
Deno.test('Super test', async (t) => {
  await sql`select 1`;
  yourcodehere();
  await sql.end();
});
```

**Comment by AndLut** [comment]
Thanks for the reply, but that was exactly what I was doing (see minimal code example).
Anyways, this issue seems to be resolved now, as it does not appear anymore with the same code :)
