### ISSUE TITLE
Question: Best practice for PostGIS geography type

### ISSUE THREAD

**Issue by jimutt** [porsager/postgres#503]
Hi! 
I have a schema in a DB with PostGIS enabled with a column `position geography(POINT, 4326)`, but I'm not sure what would be the preferred way to insert data to this column, in a safe way & for dynamic insert queries.  

I would like to insert some objects where the expected insert value looks like this string-formated point:  `'POINT(12.0 13.0)'`. 

For example:
```sql
insert into table_x ("position") values ('POINT(12.0 13.0)')
```

Let's say my JS object looks like this:
```Javascript
{
   position: { lat: 12.0, lng: 13.0 } 
}
```

I've not managed to create a custom type handler with success for the oid 17087 geography type, and if I try to assign the column's value as follows I receive a `parse error - invalid geometry` error: 
```Javascript
sql`'POINT(${d.position.lng} ${d.position.lat})'`
```

But if I assign the same value statically without trying to inject dynamic values it works: 
```Javascript
sql`'POINT(12.0 13.0)'`
```

I realize this is more of a support request than a technical problem. But if you're able to quickly spot which (likely to be obvious) mistake I'm doing our point me in the preferred direction for what would be an idiomatic solution, I'd be very grateful 🙏

**Comment by porsager** [comment]
Yeah, getting these complex values right isn't always straight forward. You can either do it using a custom type, or using a PostgreSQL function, so that you can pass every parameter by them selves.

Here's a custom type sample for `point`:
```js
postgres({
  ...options,
  types: {
    point: {
      to: 600,
      from: [600],
      serialize: ([x, y]) => '(' + x + ',' + y + ')',
      parse: (x) => x.slice(1, -1).split(',').map(x => +x)
    }
  }
})
```

You can also insert point using the point function, which you tried above, you were just missing a comma between lat and lng, so this should work:
sql`'POINT(${d.position.lng}, ${d.position.lat})'`

The annoyance with not using a custom type is that you also receive the string version of a point, so instead of eg. an array [lat, lng] you receive a string like `'(12.25, 40.354)'`

Hope that helps a bit ;)

**Comment by thejasonxie** [comment]
I know this is very late but the best way I've found to do this is using the [wkx](https://www.npmjs.com/package/wkx) library like so:

```js
 postgres({
    types: {
      geography: {
        to: 26166,
        from: [26166],
        serialize: (value: any) => wkx.Geometry.parseGeoJSON(value).toWkb(),
        parse: (value: any) =>
          wkx.Geometry.parse(Buffer.from(value, 'hex')).toGeoJSON(),
      },
    },
  }),
```

**Comment by JAForbes** [comment]
For anyone else landing here from google.  To get @thejasonxie's approach working for me, I had to coerce the buffer to a hex string, create the geo json point type from the coordinates and get a different type id from the pg types table.  Hopefully helps someone:

```sql
select * from pg_catalog.pg_type where typname = 'geography';
```

```js
const sql = postgres(..., {
	types: {
		geography: {
			to: 21718,
			from: [21718],
			serialize: ({ longitude, latitude }) =>
				wkx.Geometry.parseGeoJSON({
					type: 'Point',
					coordinates: [longitude, latitude],
				})
					.toWkb()
					.toString('hex'),
			parse: (value) =>
				wkx.Geometry.parse(Buffer.from(value, 'hex')).toGeoJSON(),
		},
	},
})

await sql`
  insert into example(geo) 
  values(${sql.typed.geography({ longitude: x, latitude: y })})
`
```

Hope that helps someone!

**Comment by thejasonxie** [comment]
> For anyone else landing here from google. To get @thejasonxie's approach working for me, I had to coerce the buffer to a hex string, create the geo json point type from the coordinates and get a different type id from the pg types table. Hopefully helps someone:
> 
> Update: I also had to use an env var for the OID because it was different for me locally vs prod.
> 
> Update 2: I ended up not using custom types because they don't work with `json_to_recordset`, so instead we just pass a manual geojson point object, and manually use `ST_X` and `ST_Y` on the way out.
> 
> ```sql
> select * from pg_catalog.pg_type where typname = 'geography';
> ```
> 
> ```js
> const sql = postgres(..., {
> 	types: {
> 		geography: {
> 			to: Number(process.env.GEOGRAPHY_OID),
> 			from: [Number(process.env.GEOGRAPHY_OID)],
> 			serialize: ({ longitude, latitude }) =>
> 				wkx.Geometry.parseGeoJSON({
> 					type: 'Point',
> 					coordinates: [longitude, latitude],
> 				})
> 					.toWkb()
> 					.toString('hex'),
> 			parse: (value) =>
> 				wkx.Geometry.parse(Buffer.from(value, 'hex')).toGeoJSON(),
> 		},
> 	},
> })
> 
> await sql`
>   insert into example(geo) 
>   values(${sql.typed.geography({ longitude: x, latitude: y })})
> `
> ```
> 
> Hope that helps someone!

Yeah thanks! I never had to do inserts until now and kept getting an issue. The coerce of buffer to a hex string works!
```js
serialize: (value: {}) => wkx.Geometry.parseGeoJSON(value).toWkb().toString('hex'),
```
