### ISSUE TITLE
add support for `select function_name(${sql([1,2,3])})`

### ISSUE THREAD

**Issue by usrtax** [porsager/postgres#507]
as title
now will cause error  because use escapeIdentifier
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/110233389/196303696-c3fe01aa-1b65-4300-ac84-e5aa8e06efba.png">

**Comment by porsager** [comment]
You should use it like `select function_name(${ 1 }, ${ 2 }, ${ 3 })`
