### ISSUE TITLE
os.userInfo is not a function

### ISSUE THREAD

**Issue by Ostricker** [porsager/postgres#51]
https://github.com/porsager/postgres/blob/7a4ef4bc5a13c26cbb290b2188f35bb22d0fb87d/lib/index.js#L493

Node v12.13.0
OS: Windows 10
Usage: inside Electron + React

Anyway this line is giving me error - TypeError: os.userInfo is not a function.

As per SO question and answer -> https://stackoverflow.com/a/56253238 os.userInfo() cant be called from browser. 

One solution is deleting os.userInfo().username and replacing it with empty quotes, which i did in my project. User should be able to put username inside env var or options.

**Comment by porsager** [comment]
This will only be called if you don't set the user in any of the other ways. Isn't that an option for you?

**Comment by Ostricker** [comment]
Yes :) I have only stumbled upon this because I have incorrectly used env variable. But it seems more appropriate to give user some more readable error then this. But do what you will, its not that big of a deal :)

**Comment by porsager** [comment]
Ah I see.. Goodie :)

Doesn't the stack trace give a proper indication of the error? Mind posting the entire stack trace for the error? 

It's a lot of custom error handling which might even lead to brittle errors instead if I tried to handle this specific scenario. Do you have ideas for how to handle it better?

**Comment by Ostricker** [comment]
This is the error:
index.js:463 Uncaught TypeError: os.userInfo is not a function
    at parseOptions (index.js:463)
    at Postgres (index.js:43)
    at new _PgSQLFrame (PgSQLFrame.ts:25)
    at Module../src/electrontool/commontools/lib/DBFrames/PgSQLFrame.ts (PgSQLFrame.ts:133)

As for how to handle it:
Option 1: Dont use it :D  `|| os.userInfo().username` -> `|| ''`
Option 2: Safe getter - 
`javascript
 public getSafeObject(fn: Function): any {
    try {
      return fn();
    } catch (e) {
      return "";
    }}`
and then call it as this - `javascript
getSafeObject(()=> os.userInfo().username)`

I dont think there is other way to handle it without try/catch, so other options are just variants of try and catch.

**Comment by porsager** [comment]
Ah, I see what you mean, that's pretty obvious ;) Fixed
