### ISSUE TITLE
Advance delete query [howto]

### ISSUE THREAD

**Issue by weinr0ck** [porsager/postgres#512]
Hello,

I have an advanced case of how to build a delete query. My problem exists in a graph database. I have two tables `components` which contain the vertices and `component_edge` which are the edges. What I'd like to do is delete more than one edge at a time. However, the way that the graph is setup, I want to specify the 'from' and 'to' column in the query.

This is my edge table
```
CREATE TABLE "public"."component_edge" (
  "from" uuid NOT NULL,
  "to" uuid NOT NULL,
  PRIMARY KEY ("from","to")
)
```

I want to do something like this:
```
DELETE FROM component_edge
  WHERE
    (
       (
         "from" = '98f402ad-9b68-4bb9-a371-bb9f71ab3839' AND
         "to" = 'a3af8f29-95b3-4f76-ab4f-3bc20d0c9c63'
       ) OR
       (
         "from" = 'a3af8f29-95b3-4f76-ab4f-3bc20d0c9c63' AND
         "to" = '16947876-244f-4382-a325-475e549d517c'
       ) OR
       ...
    )
```
How do I build this query? Can I concat multiple where clauses? How do I get rid of the last 'OR' statement?

**Comment by porsager** [comment]
While you can build it dynamically I would suggest to use [`delete from using`](https://www.postgresql.org/docs/current/sql-delete.html) and a cte instead.

It could look like this:
```js
const toDelete = [{
  from: '98f402ad-9b68-4bb9-a371-bb9f71ab3839',
  to: 'a3af8f29-95b3-4f76-ab4f-3bc20d0c9c63'
},
  from: 'a3af8f29-95b3-4f76-ab4f-3bc20d0c9c63',
  to: '16947876-244f-4382-a325-475e549d517c'
}]

const xs = await sql`
  with xs as (
    select "from", "to"
    from (values ${
      sql(toDelete.map(({ from, to }) => [from, to]))
    }) as x("from", "to")
  )
  delete from component_edge c
  using xs
  where c.from = xs.from and c.to = xs.to
`
```
