### ISSUE TITLE
The status field must be present

### ISSUE THREAD

**Issue by budarin** [porsager/postgres#515]
Like other similar packages (for example, ioredis), postgres needs the `status` field

Wrapping postgres calls in a `try/catch` block is expensive for services in cases when the connection is broken and there is an attempt to reconnect

For example, instead of such a code
```js
try {
  return await sql`...`;
} catch(error) {
  return {}
}
```
we can use much more efficient code while reconnecting is in progress
```js
if (sql.status === postgres.statuses.READY) {
  return await sql`...`;
} else {
  return {};
}

**Comment by mattbishop** [comment]
Except, sql can throw errors like socket failure. How would you deal with that?

**Comment by budarin** [comment]
If an error occurs during the call, I would assign the `connecting` status and while under the hood postgres is trying to restore the connection - other queries will not attempt to call `sql` until the connection is restored and the status is set to ready and so will not generate an exception

**Comment by porsager** [comment]
I think you should be able to achieve what you're looking for if we land the connections-stats branch. Mind checking? 

See https://github.com/porsager/postgres/issues/443#issuecomment-1606258604

**Comment by budarin** [comment]
It's no longer easier to explain - I brought the code!)

wrapping any call in try/catch every time is tedious and clogs up the code.

Look at how it is implemented in redis - it is not necessary to try to call the service if it is unavailable and there is an attempt to connect inside under the hood and you do not want to make an extra call to get an error! The status of the current state of the service would really help

**Comment by jacobbogers** [comment]
Super job `npm i   "https://github.com/porsager/postgres.git#connection-stats"` works snappy

**Comment by jacobbogers** [comment]
there is an undocumented(?) **socket** property in the `options` object, example

```typescript
const sql = postgres({
    username: 'postgres',
    password: 'postgres',
    socket(options) {
        console.log('creating socket', options);
        // @ts-ignore
        return net.createConnection({ host: '0.0.0.0', port: 5432 });
    }
});

// @ts-ignore
console.log(sql.connections);
/*sql.connections.onchange = (...args) => {
    console.error(args);
};*/
// @ts-ignore

console.log(sql.connections);
// @ts-ignore
sql.connections.onchange = (...args) => {
    console.error(args);
};
try {
    // @ts-ignore
    const data = await sql`select * from pg_tables`.forEach((row, result) => {
        const { schemaname, tablename, tableowner } = row;
        console.log(`${schemaname}\t${tablename}\t${tableowner}`);
    });
    // @ts-ignore
    console.log(sql.connections.idle);
    // @ts-ignore
    console.log(sql.connections.open);
} catch (err) {
    console.log('err', err);
}
// @ts-ignore
console.log(sql.connections);
```

**Comment by jacobbogers** [comment]
Had another idea (just brainstorming) maybe it would be a good idea to make like a "plugin system" driven by lifecycle hooks for postgresjs so ppl can modify behavior (connections/status/callback whatever),

**Comment by jacobbogers** [comment]
I will try to make a PR for this, i like the pattern 

```
for (;;){
    const result = await sql.doConnect(1000);
    //-> "open", or "close" or whatever
    if (result === 'open') break;
    // log connection is offline
}
```
My 2cts
if the connection is open the function is a no-op, otherwise it waits (timeout) and

**Comment by porsager** [comment]
I think we are projection issues from other drivers here, that just doesn't even need to be solved in Postgres.js, because there is no such problem.

Can you show some actual cases from using postgres.js where there has been an issue that this would solve?

**Comment by budarin** [comment]
in pet or training projects, there are no problems, but when the service is highly loaded `try/catch` there are a lot of resources to maintain the processing process compared to a single cmp instruction`!

if performance is not a priority, then of course it is not a problem to wrap the call twice in try/catch :)

**Comment by porsager** [comment]
Why would you need to wrap in try catch? The connection handling is seamless, which is exactly why I say I think you're projecting other drivers behaviour when it isn't necessary.

**Comment by budarin** [comment]
because I do not know what state the service is in and to avoid problems I have to wrap it in try/catch to understand what the error is

**Comment by porsager** [comment]
Well if you are interested in performance, why are you running a service where you don't expect that your database is available? 🤨 

What is it you then do in that catch?

**Comment by budarin** [comment]
do you think that in redis people suffer from bullshit and came up with the status of the service from nothing to do? :)

**Comment by porsager** [comment]
Well, I've seen a lot of shit in node libraries, so I don't take anything for granted.

But how about trying to help me understand why you think you need it, instead of appealing to some authority I know nothing of?

**Comment by jacobbogers** [comment]
> Well if you are interested in performance, why are you running a service where you don't expect that your database is available? raised_eyebrow
> 
> What is it you then do in that catch?

Are u setious?  Whatever...forking your repo...i cant believe what i am reading

**Comment by budarin** [comment]
Yes, I would have been happy to help you understand the problem when I was in the context of development and then I ran into a problem and wrote this issue, but they started responding to it a year later! And I'm busy with other questions right now, I'll be able to formulate a thought more specifically when I come back to the part of the project that I just had to leave as it is because there was no reaction.

**Comment by porsager** [comment]
@jacobbogers I'm dead serious - If I just add any user request without a critical eye on it, and understand the issue and requirements probably, this wouldn't be a very nice library.

No need to get churlish, I am actually curious. If not we wouldn't be having this discussion.

**Comment by porsager** [comment]
@budarin Sounds great. As you know, I'm busy just the same as you, and as much as I wish I could reply timely to issues, there is only so much time in the day. I don't mind leaving this open until you can find some time again ;)

**Comment by jacobbogers** [comment]
Its ok bro.. i respect your decision. I just dont have the time for this. You have a great day

**Comment by budarin** [comment]
@porsager I promise to describe the problem in more detail when I get back to work on the service if you don't close the issue (just now I've been transferred to the frontend and I'm all over my head there for now)

**Comment by budarin** [comment]
@porsager in principle, now we can close this discussion - I added an issue to my projects to deal with this issue when I return to it

**Comment by porsager** [comment]
@budarin Ok, feel free to reopen then.

And good luck with that frontend stuff 😉

**Comment by budarin** [comment]
@porsager Thanks! 

And of course, many thanks to you for such a great job on this project! 💔 🔥
I'm sorry if it seemed that I was incorrect somewhere - it's all translation difficulties)

**Comment by porsager** [comment]
@budarin You're welcome ❤️

Right - communication is always delicate, but good job with the translator then ! English is not my first language either, but I think we got there near the end 😅
