### ISSUE TITLE
Necessary settings for lazy release of connections in the pool

### ISSUE THREAD

**Issue by budarin** [porsager/postgres#518]
We have services that have a peak short-term load and we must adequately withstand it, so we set the pool size to 30-50 connections for these services

The problem is that after peak loads, services practically do not use the connection pool - they use a maximum of 1-2 connections, but the connections remaining in the pool hang and sometimes do not allow other services to establish connections due to exceeding the maximum allowed connections in the database

I would like to be able to configure the lazy return of connections based on their non-use time

**Comment by porsager** [comment]
Would setting idle_timeout to the desired value not be able to solve this?

**Comment by budarin** [comment]
I'm sorry, I missed it
