### ISSUE TITLE
Unable to delete multiple rows using composite keys

### ISSUE THREAD

**Issue by 0xStrobe** [porsager/postgres#519]
I have a table `test_table` created with:

```sql
CREATE TABLE IF NOT EXISTS test_table (
  user_id bytea NOT NULL,
  nickname text NOT NULL,
  PRIMARY KEY (user_id, nickname)
);
```

I'm trying to write a function which takes a list of `(user_id, nickname)` pairs and delete them from the table. However, I'm hitting a weird `UNDEFINED_VALUE: Undefined values are not allowed` error and can't figure out why. The error was thrown during the query building stage.

My deletion function:

```ts
// helper function to convert a hex string '1234abcd' to Buffer
const _toBytea = (user_id: string) => sql.typed.bytea(Buffer.from(user_id, "hex"));

export const deletePairs = async (pairs: { user_id: string; nickname: string }[]) => {
  const result = await sql`
    DELETE FROM test_table WHERE (user_id, nickname) IN ${sql(
      pairs.map(({ user_id, nickname }) => ({ user_id: _toBytea(user_id), nickname })),
      "user_id",
      "nickname"
    )};
  `;
  return result;
};
```

When I run the following, I get `UNDEFINED_VALUE: Undefined values are not allowed`:

```ts
try {
  const result = await deletePairs([{user_id: "1234abcd", nickname: "okay"}])
} catch (e) {console.log(e)}
```

I can't figure out what is happening. If I console log out `pairs.map(({ user_id, nickname }) => ({ user_id: _toBytea(user_id), nickname }))`, I get correct data 
```ts
[
  {
    user_id: Parameter { value: Buffer(4) [ 18, 52, 171, 205 ], type: 17, array: undefined },
    nickname: "okay"
  }
]
```

I was able to batch insert with `user_id, nickname` pairs without issue.

**Comment by 0xStrobe** [comment]
I transformed `undefined` to `null` in my `postgres(OPTIONS)`, and was able to get it through building the query, which resulted in the following query and params:

```sql
DELETE FROM test_table WHERE (user_id, nickname) IN ($1,$2);
```

```
{ parameters: [ null, null ], paramTypes: [ 0, 0 ] }
```

Why are my pairs not present in the params payload?

**Comment by 0xStrobe** [comment]
I ended up using `.unsafe` to work around it, but still curious what's the recommended way to fix it.

**Comment by porsager** [comment]
The helper you're using is only valid for `insert into table ...`. 

For the `in` check you should pass an array of arrays instead of an object. like this:

```js
sql(
  pairs.map(({ user_id, nickname }) => [_toBytea(user_id), nickname])
)
```

**Comment by 0xStrobe** [comment]
@porsager Yes I tried that way as well, but ended up with a type error and I can't figure out how to map my pairs into `(($1,$2), ($3,$4), ...)` otherwise, if I did a direct map/flatmap.

My code:
```ts
const result = await sql`
    DELETE FROM test_table WHERE (user_id, nickname) 
    IN ${sql(pairs.map(({ user_id, nickname }) => [_toBytea(user_id), nickname]))};
  `;
```

Typescript error on `pairs.map(({ user_id, nickname }) => [_toBytea(user_id), nickname])`:
```
No overload matches this call.
  Overload 1 of 2, '(first: (string | Parameter<Buffer>)[][] & readonly EscapableArray[]): Helper<(string | Parameter<Buffer>)[][], []>', gave the following error.
    Argument of type '(string | Parameter<Buffer>)[][]' is not assignable to parameter of type '(string | Parameter<Buffer>)[][] & readonly EscapableArray[]'.
      Type '(string | Parameter<Buffer>)[][]' is not assignable to type 'readonly EscapableArray[]'.
        Type '(string | Parameter<Buffer>)[]' is not assignable to type 'EscapableArray'.
          Type 'string | Parameter<Buffer>' is not assignable to type 'string | number'.
            Type 'Parameter<Buffer>' is not assignable to type 'string | number'.  Overload 2 of 2, '(template: TemplateStringsArray, ...parameters: readonly ParameterOrFragment<Buffer>[]): PendingQuery<Row[]>', gave the following error.
    Argument of type '(string | Parameter<Buffer>)[][]' is not assignable to parameter of type 'TemplateStringsArray'.
      Property 'raw' is missing in type '(string | Parameter<Buffer>)[][]' but required in type 'TemplateStringsArray'.
```

**Comment by seanxwzhang** [comment]
Did you eventually figure out? @0xStrobe

**Comment by data-envoy** [comment]
Hi @porsager I don't think this issue should be closed.

Similar queries like the one below are throwing an error.

```sql
SELECT id FROM key_value_store WHERE (key, value) IN ${sql([
  ['a', 'b'],
  ['c', 'd'],
])} 
```

`PostgresError: syntax error at or near ","`

Or attempting as a flat array

```sql
SELECT id FROM key_value_store WHERE (key, value) IN ${sql(['a', 'b', 'c', 'd'])} 
```

`PostgresError: input of anonymous composite types is not implemented`

**Comment by data-envoy** [comment]
I found the solution. Each sql array item must be wrapped in sql

```sql
SELECT id FROM key_value_store 
WHERE (key, value) 
IN  ${
  sql([
    sql(['a', 'b']), 
    sql(['a', 'b'])
  ])
}
```

@0xStrobe cc @seanxwzhang 

I guess that means your code would be 

```sql
const result = await sql`
    DELETE FROM test_table WHERE (user_id, nickname) 
    IN ${sql(pairs.map(({ user_id, nickname }) => sql([_toBytea(user_id), nickname]) ))};
`;
```
