### ISSUE TITLE
Interpolation of SQL functions in wrapped object parameter?

### ISSUE THREAD

**Issue by tx0c** [porsager/postgres#521]
when data contains no wrapped SQL functions, this indeed work,

```js
await sql` UPDATE table SET ${ sql(objectData) } WHERE ... ;`
```

but when the `objectData` contains wrapped SQL functions, like this is not working:

```js
await sql` UPDATE table SET ${ sql({ column1: value1, column2: sql`now()` }) } WHERE ... ;`
```

workaround is to move column2 out of the sql object data wrapper, this works:

```js
await sql` UPDATE table SET ${ sql({ column1: value1 }) }, column2=${sql`now()`} WHERE ... ;`
```

**Comment by el-gato-de-nieve** [comment]
I have created mr, actually it's working but will see if maintainer accept it
https://github.com/porsager/postgres/pull/522/files

**Comment by porsager** [comment]
Seems fixed some time ago
