### ISSUE TITLE
Docs/Guide for mock db responses for testing

### ISSUE THREAD

**Issue by fayzaan** [porsager/postgres#523]
We're transitioning from PG to Postgres.js and would like to test that the DB queries are generated as expected based on the current implementation.

Can you share documentation or best practice to mock out the DB response?

Currently I have had to run the queries against a running local db to get postgres.js to run `describe()` and compare the returned SQL String against our expectations.

Ideally we would like to not have to run a live DB to run the tests.

Also I noticed that the returned string SQL does not map the values in the String, so we get a SQL string such as:

``` SELECT * FROM DB WHERE id = $1 ``` and I cannot find the mappings in the response from `describe()`. Which means we have to assume what $1 will be replaced with, which could throw off testing. It would be better to either replace them with the values or just include a separate object/array with what each variable will be replaced with.

e.x.

```
{
	"string": "SELECT * FROM DB WHERE id = $1",
	"variables": {
		"$1": "b8a88de1-d2ec-4b8c-99b2-68178674a59a"
	}
}
```

OR

```
{
	"string": "SELECT * FROM DB WHERE id = $1",
	"variables": ["b8a88de1-d2ec-4b8c-99b2-68178674a59a"]
}
```

OR

```
{
	"string": "SELECT * FROM DB WHERE id = 'b8a88de1-d2ec-4b8c-99b2-68178674a59a'"
}
```

thanks!

**Comment by porsager** [comment]
There is a property called `parameters` with the replacement values in describe. Doing any form of replacement is out of the scope of this library.

**Comment by wiseman** [comment]
On this topic, is there a way to run `describe` and do this sort of unit testing without having a live database running?
