### ISSUE TITLE
Postgres not serialize byte[] on insert and update

### ISSUE THREAD

**Issue by el-gato-de-nieve** [porsager/postgres#527]
It works properly if we need to insert/update bytea 
but on arrays is fails with error
column "columname" is of type bytea[] but expression is of type bytea

**Comment by porsager** [comment]
Should be fixed in https://github.com/porsager/postgres/pull/392

**Comment by sfalihi** [comment]
unfortianatly not woking testing in version 3.4.4

my error is : column "body" is of type bytea[] but expression is of type bytea
log of my variable is : [ Buffer(39) [ 200, 184, 239, 112, 67, 3, 21, 40, 135, 197, 105, 221, 114, 115, 46, 218, 200, 40, 214, 82, 66, 98, 117, 233, 200, 71, 2, 221, 254, 114, 205, 58, 248, 28, 10, 124, 161, 172, 18 ] ]
and when i try to insert it like below error shown: 
sql`insert into .. values (${variable}) ... `

**Comment by porsager** [comment]
Right - your buffer is inside an array. shows clearly in the log you just pasted.

**Comment by sfalihi** [comment]
after so many attempts this solution works perfectly with correctly scaping also: 

sql`INSERT ... VALUES(ARRAY[${yourBufferArray.reduce(
          (acc, curr, index) =>
            index === 0 ? sql`${curr}` : sql`${acc}, ${curr}`
        )}]::bytea[]);`
