### ISSUE TITLE
How to connect database custom schema

### ISSUE THREAD

**Issue by osieltorres** [porsager/postgres#535]
This is more a question than an issue, and it is basically related to know if is possible to connect to PostgreSQL custom database schema instead of default "public" schema?

I have look in doc, but I could not find any connection option to specify a database schema like:
```ts
const sql = postgres('postgres://username:password@host:port/database?current_schema=custom');
```

**Comment by porsager** [comment]
You need to use the connection parameter named `search_path` instead of `current_schema`.
