### ISSUE TITLE
timetz oid=1266 missing

### ISSUE THREAD

**Issue by fjf2002** [porsager/postgres#54]
Hello,

in https://github.com/porsager/postgres/blob/master/lib/types.js the type `timetz` is missing (oid 1266) (?).

**Comment by porsager** [comment]
What would you want to parse it into other than a string? I don't think there's a fitting default in JavaScript.

**Comment by fjf2002** [comment]
Ok thanks

**Comment by porsager** [comment]
Sorry, I hope I didn't come off uninterested, I was really curious if you had something in mind, or if maybe I missed something?

**Comment by fjf2002** [comment]
Sorry for my latest and very short answer.

Meanwhile I've learnt that 
* according to https://wiki.postgresql.org/wiki/Don't_Do_This, timetz is a bad idea.
* and the JavaScript Date data type does not seem to be really sane to me.
Furthermore, the Javascript libraries that I use do not seem to be able to deal with the Javascript Date type - they take a plain string.

That's why my project has currently gotten in the direction that I even switch off your parser for the date and time data types, just using plain strings.

(So to be clear, this issue now is 100% irrelevant for me :-) )
