### ISSUE TITLE
Database connection events

### ISSUE THREAD

**Issue by abdisamadm4** [porsager/postgres#540]
Hi team, i started using your client package, but it does not have events which you can control like when to connect, disconnect and when there is error is the connection, if there is an issue in your connection you never know it untill you make a a call to the postgres server.

It does not seem to be a big change, hopefully you add that feature soon.

**Comment by porsager** [comment]
Connections come and go, and idle at various times in the pool of connections. Errors are thrown when and where errors occur, so there is no plan to add this at the moment.
