### ISSUE TITLE
`.simple()` is not documented

### ISSUE THREAD

**Issue by paulovieira** [porsager/postgres#541]
This method was added after the request in #472, but is not yet documented.

I would be happy to send a PR for this, but I'm not sure if I understand the difference between these two:
- `sql.unsafe('select 1; select 2;')`
- ``sql`select 1; select 2;`.simple()``

It seems the difference is that in the first case the string with the query is not known in advance (and so can be prone to attacks), while in the second case the string with the query is fixed. Is that it?

@Cheprer, can you help?

**Comment by porsager** [comment]
Thanks to both of you :) A PR would be appreciated. 

Another note is that I think I'll remove the implicit change to simple with unsafe in v4, to prevent any confusion, and allow unsafe to reap the benefits of prepared statements as well by default.

**Comment by kailash360** [comment]
@porsager 
Can I work on this issue?

**Comment by porsager** [comment]
Sure thing 👍
