### ISSUE TITLE
not able to work with string templates properly

### ISSUE THREAD

**Issue by Dhruv-Garg79** [porsager/postgres#544]
I am trying to do something like this:

```
const res = await sql`select * from ${this.tableName}`;
```

the above code results in error - `PostgresError: syntax error at or near "$1"`

it works if I use static table name.

postgres library version: 3.3.3
node version: 14

**Comment by porsager** [comment]
Check the docs ;) https://github.com/porsager/postgres#table-names

**Comment by Dhruv-Garg79** [comment]
@porsager thanks. But I also wanted to know if it is possible to use plain strings somehow like in the example?

**Comment by porsager** [comment]
Not sure i understand. Why can't you do like in the example?

**Comment by Dhruv-Garg79** [comment]
I was trying to make a layer of my own abstraction over your library so wanted to keep everything as simple strings. I will do like the example only.
