### ISSUE TITLE
Two-way transform for undefined and null

### ISSUE THREAD

**Issue by user72356** [porsager/postgres#548]
Using null in my codebase is a no-no and was banished in favor of undefined. pg of course uses null exclusively. I appreciate that postgres.sql has a transform of undefined to null in the direction client -> DB, but there is no null to undefined from DB -> client.

I ended up using a combination of `undefined: null` and a value transform in my postgres() options. Can I suggest a more straightforward way of doing it? Maybe a two-way transform for undefined -> null -> undefined in the same way that the case transforms work? 

Or maybe the ability to provide a `to` transform for values?

This is what I use at the moment:

```
export const sql = postgres(
    "CONNECTION_STRING",
    {
        transform:
        {
            undefined: null, 
            value:
            {
                from: value => value === null ? undefined : value
            }
        }
    });
```

**Comment by porsager** [comment]
I think that what you're doing now is just fine, considering the edge case ;)
