### ISSUE TITLE
Question: Implementing RLS based on a runtime parameter

### ISSUE THREAD

**Issue by JannisKoeksel** [porsager/postgres#553]
As described e.g. here:  https://aws.amazon.com/de/blogs/database/multi-tenant-data-isolation-with-postgresql-row-level-security/#Alternative-approach:~:text=Alternative%20approach
I want to implement RLS based on a runtime parameter scoped to the current database connection session. 
1) How to set the parameter for ever connection in the pool ? 
2) Is there a on connect event or something similar ?
3) Is using one instance of postgres per "tenant" the best solution ?

**Comment by JannisKoeksel** [comment]
Thanks!

One more thing: 
How to handle max connections ?

**Comment by porsager** [comment]
👍

That's just the `max` property in the options object, which defaults to 10.

**Comment by JannisKoeksel** [comment]
I should have been clearer with my Question: 
Because of the instance of postgres per "tenant" I was wondering if it is possible to limit the total amount of connections. 
So e.g. there are at most 2 * tenant connections allowed but if some tenants don't need there's, the others can use up to the 10/instance connections. I'm not even sure if that  is a actual problem or if I should just set the idle timeout to a relatively short duration.
