### ISSUE TITLE
inserting jsonb?

### ISSUE THREAD

**Issue by bonesoul** [porsager/postgres#556]
how can i insert an object as jsonb? couldn't find any examples. should i set supplymy data with JSON.stringify() or a plain object?

```
CREATE TABLE public.reputation
(
  id integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
   ...
  rewards jsonb NOT NULL,
```

```
      await sql`INSERT INTO
        reputation(
          rewards
        )
        VALUES(
          ${sql(reputation.rewards)}
        )
```

**Comment by bonesoul** [comment]
I've accomplished it with: 

`          ${sql.json(reputation.rewards as unknown as JSONValue)}`

now is there a way that i can expand the rows jsonb data as an object?

**Comment by porsager** [comment]
Just pass the js object/array directly. sql.json is deprecatedOn 16 Feb 2023, at 15.18, Hüseyin Uslu ***@***.***> wrote:﻿
I've accomplished it with:
          ${sql.json(reputation.rewards as unknown as JSONValue)}
now is there a way that i can expand the rows jsonb data as an object?

**Comment by bonesoul** [comment]
When I try directly pass the object, I get a typescript error, but will try it again.
