### ISSUE TITLE
could not determine data type of parameter $1

### ISSUE THREAD

**Issue by Dhruv-Garg79** [porsager/postgres#557]
I am trying to write this query, but not able to figure out how to write with this library. It is working on the pgadmin.

```
	const res = await sql`SELECT *, ts_rank_cd(search_vector, query) AS rank
	FROM ${sql(this.tableName)}, to_tsquery('english', '${query}') AS query
	WHERE connection_id = ${id} and search_vector @@ query
	ORDER BY rank DESC offset ${offset} limit ${limit}`;
```

I am getting this error for `${query}` - `could not determine data type of parameter $1`.

If I replace the query with a hard coded string, it works fine. please help me with this, thanks.

**Comment by Dhruv-Garg79** [comment]
@porsager can you please help?

**Comment by porsager** [comment]
Remove the single quotes around `${query}`. It should be `glish', ${query})` instead of `glish', '${query}')` 😉

**Comment by elhananjair** [comment]
@porsager I have a case where I wanted to use ${} appending with date, like this:

```
let today = new Date();

async function fetchData() {
  return sql`select sum(charge) from mytable where date between '${today.getFullYear()}-01-01  and '${today.getFullYear()}-01-31'`
}
```
But I am getting the same error, how can I use that in such cases?
