### ISSUE TITLE
Dynamic Limit based on variable

### ISSUE THREAD

**Issue by tchar** [porsager/postgres#560]
Hello,

I am having problems with using dynamic limit.

Here is an example
```javascript
const limit = 2;
const results = await sql`
      SELECT * FROM mytable
      WHERE 
        id= ${id}
      LIMIT ${limit}
    `;
```

And the error I get is
```javascript
Unhandled error: TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (2)
```

I also tried wrapping the limit into `sql(limit)` or `sql(String(limit)` or `${String(limit)}` but nothing works. Other errors I get:
```javascript
Unhandled error: PostgresError: column "2" does not exist
```

Is there any way around this? I would like to avoid raw queries.

**Comment by porsager** [comment]
Year query is just fine, so this is most likely what you're passing in the id value and not limit.

**Comment by tchar** [comment]
Seems you are right. I found the issue. Just for reference the value I was passing was fine, but I had instantiated SQL with custom bigint and had a bug somewhere there.

```javascript
  this.sql = postgres({
    ...options,
    types: {
      bigint: {
        to: 20,
        from: [20],
        serialize: (v: number) => //Function with a bug here,
        parse: (v: string) => parseInt(v)
      }
    }
  });
```

Closing this for now. Thank you for the immediate response.
Cheers,
tchar
