### ISSUE TITLE
Select timestamp column not returning UTC

### ISSUE THREAD

**Issue by martinbohlmann** [porsager/postgres#563]
Hi everyone. I have an issue with timestamps. Reading other issues (i.e. https://github.com/porsager/postgres/issues/388) I figured that TIMESTAMPTZ would solve it, and it does. But I still want to understand why I get an unexpected result when using TIMESTAMP when all my dates are stored in UTC. So I created a script you can run and see for yourself. My issue is that when I store "new Date()" this gets stored as UTC and I can query the value correctly from another client (DBeaver). Now if I query the same value from sql I get an unexpected result, shifted 1 hour back, instead of getting the UTC.

```
async function run_tests2(sql) {
  await sql`drop table if exists dummy`;
  await sql`create table dummy (d1 TIMESTAMP, d2 TIMESTAMPTZ)`;
  const now = new Date();
  console.log("now=", now);
  let res = await sql`insert into dummy (d1,d2) values (${now}, ${now}) returning d1, d2`;
  console.log("d1=", res[0].d1);
  console.log("d2=", res[0].d2);
  res = await sql`select now()::text as nt`;
  console.log("nt=", res[0].nt);
}
```

The output is

```
now= 2023-03-02T13:35:01.041Z
d1= 2023-03-02T12:35:01.041Z
d2= 2023-03-02T13:35:01.041Z
nt= 2023-03-02 13:35:25.610016+00
```

Expected: now, d2 (TIMESTAMPTZ) and nt all return 13:35 in UTC (my local time is 14:35)
Unexpected: d1 (TIMESTAMP) shows 12:35 (one hour less than UTC, two hours behind my local time).

Running the select query in DBeaver I got the result as expected.
```
d1                     |d2                           |
-----------------------+-----------------------------+
2023-03-02 13:35:01.041|2023-03-02 14:35:01.041 +0100|
```

My hypothesis is that sql writes UTC to Timestamp, but makes a miss conversion when reading it.

Thanks for your help.

**Comment by SacDeNoeuds** [comment]
Hello ! :wave:
I had the same issue, it had to do with the [built-in date parser](https://github.com/porsager/postgres/blob/master/src/types.js#L28) of the lib:
```js
const types = {
   ...,
  date: {
    to: 1184,
    from: [1082, 1114, 1184],
    serialize: x => (x instanceof Date ? x : new Date(x)).toISOString(),
    parse: x => {
      console.info({ x })
       // produces '2023-03-10 18:00:14.62+00' for TIMESTAMPZ 
       // produces '2023-03-10 18:00:14.62' for TIMESTAMP
      return new Date(x)
    }
  },
  // Fix:
  timestamp: {
    to: 1114, // TIMESTAMP pg_type oid
    from: [1114], // TIMESTAMP pg_type oid
    serialize: x => (x instanceof Date ? x : new Date(x)).toISOString(),
    parse: x => new Date(x + 'Z'),
  },
}
```
The JavaScript Date constructor needs a `'Z'` or a `+00` at the end to consider it UTC, if not present JS considers the date to be local :shrug: 
```js
new Date('2023-03-10 18:00:14.62') // => 2023-03-10 17:00:14.62 for me (1h more than UTC)
new Date('2023-03-10 18:00:14.62Z') // => 2023-03-10 18:00:14.62Z
new Date('2023-03-10 18:00:14.62+00') // => 2023-03-10 18:00:14.62Z
```
