### ISSUE TITLE
Do not start transaction if no queries are executed

### ISSUE THREAD

**Issue by ayZagen** [porsager/postgres#565]
I believe title describes the feature request.

Here is a very SIMPLE snippet to reproduce:
```js
await sql.begin( async trx => { 
  throw new Error('fail');
} );
```
Executed queries:
```sql
begin  []
rollback []
```

Everything working as expected but it would be great having an option to start transaction lazily - meaning it will begin just before a query executed.

Thanks/

**Comment by porsager** [comment]
Do the potential failing work before calling sql.begin? sql.begin waits for an available connection to reserve it, so I don't have any intention of making it lazy.
