### ISSUE TITLE
Document that sql.unsafe can be embedded as a fragment in larger sql expressions

### ISSUE THREAD

**Issue by JAForbes** [porsager/postgres#566]
Absolute hidden gem I was not aware of until just now.  It'd be great to document it.

E.g.

```js
create or replace trigger ${sql(triggerName)}
after ${sql.unsafe(eventType)}
...
```

I think this information should still be hidden in the summary tag, but its great to know you don't have to make the entire query unsafe, you can just inject an unsafe fragment.

Would you accept a PR adding a sentence or two and a code example?

**Comment by porsager** [comment]
Oh right 😊 For sure, that'd be great ! 

btw, texted you on gitter (matrix), are you still available there? 😊

**Comment by JAForbes** [comment]
Oh did you? I'll check, I never go on there anymore! 😄
