### ISSUE TITLE
`deno check` fails for vendored postgresjs

### ISSUE THREAD

**Issue by ChristianSiegert** [porsager/postgres#574]
**Steps to reproduce:**

1. Create a .ts file and import postgresjs:
    ```ts
    // main.ts
    import "https://deno.land/x/postgresjs@v3.3.4/mod.js";
    ```
2. Run `deno vendor main.ts`
3. Run `deno check --import-map=vendor/import_map.json main.ts`

**Expected:** No errors

**Actual:** Errors are reported for postgresjs:
```
Check file:///<redacted>/main.ts
error: TS2367 [ERROR]: This comparison appears to be unintentional because the types 'rmdirOptions | undefined' and 'boolean' have no overlap.
    if (options === false) {
        ~~~~~~~~~~~~~~~~~
    at file:///<redacted>/vendor/deno.land/std@0.132.0/node/_fs/_fs_rmdir.ts:82:9
```

Environment:
```
deno --version
deno 1.32.1 (release, x86_64-apple-darwin)
v8 11.2.214.9
typescript 5.0.2
```

Since the type checking error occurs in the std lib, I assume updating to a newer Deno std lib version will resolve the error.

**Comment by porsager** [comment]
Sounds about right.

**Comment by ChristianSiegert** [comment]
The issue is closed but not resolved. `porsager/postgres` must update its imports of the Deno std lib to a newer version.

**Comment by bombillazo** [comment]
For some reason I cant use this library in deno due to this error:
```
TypeError: globalThis.addEventListener is not a function
    at new Process (https://deno.land/std@0.132.0/node/process.ts:194:16)
    at https://deno.land/std@0.132.0/node/process.ts:357:76
```
