### ISSUE TITLE
Insert helper fails on jsonb column when passed an array of booleans

### ISSUE THREAD

**Issue by evelant** [porsager/postgres#575]
repro: https://github.com/evelant/postgresjs-jsonb-array-bug

If you have a jsonb column and attempt to use the insert helper with an array of booleans for that column it will fail with

```
column "test_col" is of type jsonb but expression is of type boolean
```

When inserting/updating large objects that contain some jsonb arrays of booleans this makes the helper unusable.

**Comment by porsager** [comment]
This looks related to #392
