### ISSUE TITLE
Dynamic column selection with functions

### ISSUE THREAD

**Issue by joemays** [porsager/postgres#588]
First, thanks for this wonderful library and all of your hard work!

Sometimes I need to select columns with functions, e.g.:

```typescript
const cities = await sql`SELECT name, ST_AsText(location) as loc_txt FROM city`;
```

I  couldn't find a good way to do this dynamically.  For example, the following fails:

```typescript
const columns = ['name', 'ST_AsText(location) as loc_txt'];
const cities = await sql`SELECT ${sql(columns)} FROM city`;
```

...I realize I can do it with `sql.unsafe`:

```typescript
const columns = ['name', 'ST_AsText(location) as loc_txt'];
const cities = await sql`SELECT ${sql.unsafe(columns.join(','))} FROM city`;
```

Maybe I missed something?  Or perhaps the columns array could include `sql` fragments for functions as well as traditional `string` column names?

```typescript
const columns = ['name', sql`ST_AsText(location) as loc_txt`];
```

Thanks again!

**Comment by porsager** [comment]
Thanks a lot for the kind words, and apologies for the late response.

You should be able to do it like this:

```
const columns = ['name', sql`ST_AsText(location) as loc_txt`];
const cities = await sql`SELECT ${sql(columns)} FROM city`;
```
