### ISSUE TITLE
Question: Where did you figure out all the client messages?

### ISSUE THREAD

**Issue by lifeiscontent** [porsager/postgres#589]
Hi there, I was wondering if you could share how you learned about all the binary formats of the client messages? I've currently figured out a few of them, but still unsure how to read the message protocol docs and just "know" what they should be, specifically things like SASL. Thanks for the awesome library :D

**Comment by boromisp** [comment]
This is a good starting point: https://www.postgresql.org/docs/current/protocol.html

**Comment by lifeiscontent** [comment]
@boromisp Yeah, but the actual explanation of each is pretty bare, e.g. what's a string vs byten

**Comment by porsager** [comment]
@lifeiscontent very nice question.. I would love to answer more thoroughly, but I haven't got the time right now. There's this thing with the Postgres docs that suddenly the structure just clicks and they become much easier to navigate. The meat of the messages are in a subpage to the one @boromisp linked - more specifically here: https://www.postgresql.org/docs/current/protocol-message-formats.html

I think we talked a bit about how I went about it in this interview here as well: https://www.youtube.com/watch?v=xCyok5iVZnI

Hopefully I can get back and expand some more on this ;)

**Comment by lifeiscontent** [comment]
Thanks for the info, I've managed make sense of the protocol now, thank you 🎉
