### ISSUE TITLE
Feature request: Streamed input

### ISSUE THREAD

**Issue by naturalethic** [porsager/postgres#59]
Like the `.file` method, but accepts a stream.

**Comment by porsager** [comment]
Interesting, what is the use case?

**Comment by naturalethic** [comment]
Say I have a several gigabyte csv file I want transformed into sql statements and sent up to server.  You already have streaming from the server, seems complementary to add it the other direction.

**Comment by TobiasNickel** [comment]
I would think the stream support would be on the csv library, it need to be able to pause, to accommodate for different speeds that postgres or the csv reading has. Reading the csv will in most cases be much faster, as it is so simple.

`csv-parse`, `csvtojson` or `papaparse`, all have some kind of stream support.  Currently I personally would choose csvtojson as you can control the speed by subscribing with an promise / async function. To speed things up, using an array it should be easy to do insert chunks.

You can still use a transaction, to ensure, that all or no data get imported.

@porsager do you have any thoughts and opinion? The more I think about it the more I think it is a good question @naturalethic .

**Comment by porsager** [comment]
This is something I think best solved in userland. There are so many ways to handle csv, and postgres even has built in ways, like [copy](https://www.postgresql.org/docs/current/sql-copy.html) which is probably the best if you have several gigabyte.

```sql
copy your_table(column1, column2, column3) from 'path/to/file.csv' with (format csv)
```

If you need to make transformations on the fly to the csv data in node, solving it in userland should be fine. I don't think it warrants building anything into this library. The necessary constructs to handle this seamlessly are already there.

**Comment by naturalethic** [comment]
Ok.  Now that I think about it, if I have an open connection+transaction, and send queries to that transaction, these are sent immediately over the same connection, so that is equivalent to this case.

If I needed streaming, I could wrap this behavior easily enough.

**Comment by porsager** [comment]
Cool. Feel free to post here what you come up with ;)
