### ISSUE TITLE
typescript throws error for import

### ISSUE THREAD

**Issue by bodycombathuang** [porsager/postgres#591]
I use import postgres from "postgres" in typescript

in tsc --noEmit, thre is error
 Module '"C:/project/src/node_modules/postgres/types/index"' can only be default-imported using the 'esModuleInterop' flag
how to resolve?

**Comment by porsager** [comment]
Just add `esModuleInterop: true` to your ts.config ;)

**Comment by bodycombathuang** [comment]
{
  "include": ["./**/*.ts"],
  "compilerOptions": {
    "tsBuildInfoFile": "build/tsconfig.tsbuildinfo",
    "downlevelIteration": true,
    // base
    "alwaysStrict": true,
    "charset": "utf8",
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "noEmitHelpers": true,
    "noImplicitUseStrict": false,
    // strict
    "types": ["node"],
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    // cjs/babel interop
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "composite": true,

    "target": "es2017",
    "module": "esnext",
    "lib": ["dom", "es2017"],
    "declaration": true,
    "declarationMap": true,
    "jsxFactory": "createElement",
    "outDir": "build",
    "sourceMap": true
  }
}
it is already true

**Comment by bodycombathuang** [comment]
if I use import * as postgres from postgres
it seems, const sql = postgres(`${process.env.DB_CONNECT_STRING}`); trhows error

**Comment by porsager** [comment]
I don't use typescript, but a quick google shows that it might be due to the first line `"include": ["./**/*.ts"],` ? Could you try to remove it to see if it solves the issue?

**Comment by bodycombathuang** [comment]
removing it does not work , can I use import * as postgre from postgres?

**Comment by porsager** [comment]
I suppose so - try it, if it works, I don't see why not ;)
