### ISSUE TITLE
SQL query logging

### ISSUE THREAD

**Issue by cayter** [porsager/postgres#595]
Is there a reason why this library doesn't accept logger for logging the SQL queries with time consumed? The suggested [approach](https://github.com/porsager/postgres/issues/368#issuecomment-1128722614) here doesn't work as the underlying function returns a Promise and the same method is also used for building the query.

**Comment by porsager** [comment]
Yeah, I haven't needed it. I use pg_stat_statements..

**Comment by cayter** [comment]
I'm just wondering if there's a plan to add this as it'd be useful for OpenTelemetry to trace the query so that we don't have wrap another layer or manually trace every where we call postgres method that runs the query.

**Comment by porsager** [comment]
There's some work on this now - I'm tracking it in https://github.com/porsager/postgres/issues/461#issuecomment-1606294308
