### ISSUE TITLE
Error: self-signed certificate

### ISSUE THREAD

**Issue by Oschenker** [porsager/postgres#597]
### Discussed in https://github.com/porsager/postgres/discussions/596

<div type='discussions-op-text'>

<sup>Originally posted by **Oschenker** May 14, 2023</sup>
Hello everyone. I use Postgres.Js to connect to postgreSQL db on render.com. When I connect to db from my lockal computer I have no error and everything works fine. When I am trying to deploy my app on render.com and use internal connection (internal host) I immediatly have this error:
Error: self-signed certificate
 at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34
 at TLSSocket.emit (node:events:513:28)
 at TLSSocket._finishInit (node:_tls_wrap:959:8)
 at ssl.onhandshakedone (node:_tls_wrap:743:12)
Failed to prune sessions: self-signed certificate

What is a problem? I tried to use different values for SSL connection parameter as diescribed in Postgres.Js documentation. Nothing works.</div>

**Comment by porsager** [comment]
check out https://github.com/porsager/postgres#ssl
