### ISSUE TITLE
Add the option to lazy connect to postgres

### ISSUE THREAD

**Issue by omardoma** [porsager/postgres#60]
Thank you for the awesome client. I was wondering if there is a possibility of adding an option to disable automatic connection to Postgres, and instead add a function that starts the connection manually. It is similar to ioredis' `lazyConnect` option shown [here](https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options).

I basically have logic in place at the startup of my server to connect to each service I am using such as the database, cache and message queue, before I start listening on the port, something like this:

```ts
async function startServer(): Promise<void> {
  await Promise.all([
    connectToDB(),
    connectToES(),
    connectToCache(),
    connectToEventQueue()
  ]);
  server = http.createServer(app);
  await listen();
  const addr = server.address();
  const bind = typeof addr === 'string' ? `pipe ${addr}` : `port ${addr.port}`;
  loggingService.log(`Listening on ${bind}`);
}

async function closeServer(): Promise<void> {
  await unlisten();
  server = null;
  await Promise.all([
    disconnectFromDB(),
    disconnectFromES(),
    disconnectFromCache(),
    disconnectFromEventQueue()
  ]);
}

```

So what I need is to call a function that starts the connection manually for Postgres, is that possible?

**Comment by porsager** [comment]
Sure thing :) Postgres is already lazy, so simply doing `const sql = postgres()` won't actually connect to the database.

In your case you could simply do ``` sql`select 1` ``` to open the first connection ;)

**Comment by omardoma** [comment]
Oh really, great! thanks a lot for the fast response and keep up the great work!
