### ISSUE TITLE
Missing stack-trace with `ECONNRESET` `unhandledRejection`

### ISSUE THREAD

**Issue by zone117x** [porsager/postgres#600]
We're running a production server that has occasional postgres server restarts. It appears we have a bug in our service where retry-able postgres errors are not handled correctly, and we end up with an `unhandledRejection`.

The logging code looks like:
```js
process.once('unhandledRejection', error => logger.error(error));
```

The problem we're facing is that the error and the stack trace does not include enough information to indicate where our bug is at. This is all we get in the stack trace:
```
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

I'm looking through the postgres js source, and the async/promise handling is pretty complex. It somewhat makes sense to me how the async call stack is lost.

Is there a recommended approach to debugging this kind of issue? I'm curious if there's a mechanism to force capture the async call stack and log it in the `unhandledRejection` handler.

**Comment by porsager** [comment]
Are you sure this is related to Postgres.js? Curious if you can get any more info out, I haven't seen this in my uses before.

**Comment by porsager** [comment]
Would be nice if you could create a repro I can look into. If you get that, we'll reopen.
