### ISSUE TITLE
Hang in transaction even max_lifetime is set

### ISSUE THREAD

**Issue by felix98765** [porsager/postgres#608]
With this config:

```typescript
postgres(connection, {
    max: 1,
    idle_timeout: 20, // 20 seconds
    max_lifetime: 20, // 20 seconds
})
```

I would expect the following code to block other queries for at most 20 seconds, but instead it will block other queries for 60 minutes.

```typescript
await sql.begin(async (sql) => {
    await sleep(1000 * 60 * 60) // 60 mins

    await sql`
        insert ...
    `
})
```

other normal queires (without begin() and no sleep) will be blocked for the whole 60 minutes:
```typescript
await sql`select ...`
```

**Comment by porsager** [comment]
When you begin a transaction you cannot run other queries on the same connection, so when you artificially keep the transaction open for 60 minutes, it will block for those 60 minutes.

The idle_timeout is as the name suggests the timeout a connection is idle before we close it, and the max_lifetime timeout is graceful, so it is a reconnect that happens after that time when any pending queries are done.

What you are looking for is perhaps statement_timeout, but that is a setting you pass to PostgreSQL and not something this library handles.

You can pass it like this:

const sql = postgres({
  connection: {
    statement_timeout: 20 * 1000 // PostgreSQL expects milliseconds
  }
})
