### ISSUE TITLE
How to update default value in db

### ISSUE THREAD

**Issue by waynelinks** [porsager/postgres#61]
Hi there

I have the following table 
```
BEGIN TRANSACTION;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
  id uuid DEFAULT uuid_generate_v4 (),
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email text UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  role TEXT NOT NULL DEFAULT 'basic',
  isActivated BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt timestamp WITH time zone DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp WITH time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMIT;
```
This is my code to insert values
```
const [newUser] = await sql`INSERT INTO users ${sql(
    user,
    'firstname',
    'lastname',
    'email',
    'password',
  )} returning *`
```

This is my req.body values i pass through to server
```
{
	"firstname": "Test",
	"lastname": "test",
	"email": "example.links@gmail.com",
	"password": "password",
	"role": "admin"
}
```
You'll notice from the table the role property defaults to basic if no role is specified. However, in this example I'm specifying role with value admin.

When I check the inserted user values, I see role is not updated to admin.

Here's the payload of my JWT, role property defaults to basic and is not updated
```
{
  "id": "10a9ac24-9440-4d80-a099-4b7dbf52046a",
  "firstname": "Test",
  "lastname": "test",
  "email": "example.links@gmail.com",
  "role": "basic",
  "isactivated": false,
  "createdat": "2020-04-21T10:48:10.217Z",
  "updatedat": "2020-04-21T10:48:10.217Z",
  "iat": 1587466100,
  "exp": 1587467000,
  "aud": "EMAIL_SERVICE",
  "iss": "AUTH_SERVICE",
  "sub": "10a9ac24-9440-4d80-a099-4b7dbf52046a"
}
```

How do I refactor this snippet to update role property if specified?
```
const [newUser] = await sql`INSERT INTO users ${sql(
    user,
    'firstname',
    'lastname',
    'email',
    'password',
  )} returning *`
```

**Comment by porsager** [comment]
You can do it by not using the query helper and then use `coalesce` and `default` like this:

```js
const [newUser] = await sql`INSERT INTO users (
  firstname,
  lastname,
  email,
  password,
  role
) values (
  ${ user.firstname },
  ${ user.lastname },
  ${ user.email },
  ${ user.password },
  coalesce(${ user.role || null }, default)
)
returning *`
```

**Comment by waynelinks** [comment]
@porsager  Thanks for the quick response

I implemented above, got the following error: ``ERROR:  DEFAULT is not allowed in this context at character 146 ``

I tried the following, which worked, maybe not in the way I expected.
``` 
const [newUser] = await sql`INSERT INTO users (
    firstname,
    lastname,
    email,
    password,
    role
  ) values (
    ${user.firstname},
    ${user.lastname},
    ${user.email},
    ${user.password},
    ${user.role || 'basic'}
  )
  returning *`
```
Again, thanks for the help, much appreciated.

**Comment by porsager** [comment]
Ah yes, that's fine too. 

Small note though, is that you don't use the default value from the schema like that, so now you have 2 sources of truth, but that might be ok for you..

I actually wasn't aware it was not allowed to use the `default` keyword like that, so TIL too :)
