### ISSUE TITLE
`sql.notify` not available in transaction context

### ISSUE THREAD

**Issue by santicalcagno** [porsager/postgres#611]
Basically this:

```js
sql.notify('test'); // works
sql.begin(sql => {
  sql.notify('test')  // throws Uncaught TypeError: sql.notify is not a function
}}
```

Is that expected behavior? I am under the impression that `NOTIFY` should work in a transaction context as per the [docs](https://www.postgresql.org/docs/15/sql-notify.html).

As a workaround I think `sql.unsafe` works.

Coincidentally, I think the same applies to `sql.listen`, although I only have a use case for `.notify`ing in transactions.

PS: Thanks for this library! ❤️

**Comment by porsager** [comment]
Oh that's a good catch. Thank you!

sql.listen won't work cause it's using a dedicated connection for that, but sql.notify should work with the transaction instance as well.
