### ISSUE TITLE
Password as async function

### ISSUE THREAD

**Issue by miles-po** [porsager/postgres#615]
In some situations (such as IAM authentication in AWS or rotating creds in a secrets manager), the password isn't a static string. The first call is straightforward enough, but if the client is long-lived (ie. hours or days), that token or secret may expire.

Rather than try to calculate and inject dynamically into the postgres library, would it be possible to accept either a static string or an async function? This way if another connection is needed in the pool, the function can be invoked to get the current credentials.

```js
const sql = postgres({
  // ...,
  password: async () => generateToken(),
  // ...,
})
```

This functionality is available in pg, but I much prefer the API, speed, and flexibility of postgres. Thanks for all your amazing work on this project!

**Comment by porsager** [comment]
Have you tried? 😉

**Comment by miles-po** [comment]
Aha! Undocumented. 🙂

**Comment by porsager** [comment]
Hehe, PR much welcomed ;) 

Oh and thank you for the kind words as well
