### ISSUE TITLE
Possible performance issue with aggregate functions

### ISSUE THREAD

**Issue by adamtysonsmith** [porsager/postgres#617]
Love this library first of all, its amazing. Thank you 🙏 

I am hoping to get some insight on how to speed up some aggregate queries. Let's say I have a query like this:
```
SELECT sum(clicks) 
FROM analytics 
WHERE company_id = ${companyId} 
  AND date > NOW() - INTERVAL '30 day';
```

Here are some times I am experiencing:
- remote database using psql: ~70ms
- postgres.js in app: ~800ms
- node-postgres in app: ~500ms

I was surprised to see that node-postgres was faster 😖  but obviously I don't want to use it!! How can I speed this up?

Also want to note that the `clicks` column is type INTEGER and I think the result comes back as type NUMERIC (1700). Not sure if this is why.

Update: these are not the first queries that run against the db, so I am assuming that the db is warmed up at the time of the query

**Comment by porsager** [comment]
Thanks! 

And no, you should expect Postgres.js to be like psql or faster!

I think I've seen a similar issue before, related to numeric, but I'm not sure. I'm gonna dig a little. 

Could you make a repro setup I can test?

**Comment by porsager** [comment]
Ok, I think I found it. It might be related to your `companyId` - What is the type of your `company_id` column?

Could you try to add explicit cast like this? `WHERE company_id = ${companyId}::int8` and insert the correct type if it is not int8?

**Comment by porsager** [comment]
Nono, that shouldn't be necessary. The important part is ensuring the input parameter is the correct type so that the right indexes will be used. 
So, is the type of the company_id column `text` ?

**Comment by porsager** [comment]
Could you try to run `select pg_typeof(company_id) from analytics limit 1` and post the response?

**Comment by adamtysonsmith** [comment]
I now have 2 tables to test on:

analytics:
`pg_typeof
-----------
 text`

analytics_using_integer_ids:
`pg_typeof
-----------
 bigint`
 
 It seems that the table using integers ids is actually slower

**Comment by adamtysonsmith** [comment]
Posting the full table here also
```
    CREATE TABLE analytics (
      id serial PRIMARY KEY,
      company_id TEXT,
      campaign_id TEXT,
      date TIMESTAMP,
      clicks INTEGER,
      full_link TEXT,
      short_link TEXT,
      created TIMESTAMP DEFAULT NOW(),
      CONSTRAINT unique_datapoint UNIQUE (date, full_link)
    );
```

**Comment by porsager** [comment]
There's definately something fishy going on. Does it help to hint the type by doing `::text` for the text version, and `int8` for the other? 

Would love to see some more context so I can try to repro here.

**Comment by adamtysonsmith** [comment]
Hey thanks, the type casts did not seem to have any effect. I have tried several variations.

I am on a faster network today and that seemed to reduce the timing to ~ 450ms

This timing is consistent regardless of 
- type cast ::text, ::int8, ::integer
- whether the table uses integer or text for company_id
- whether there are records in the table or not!

Are you seeing something similar locally?

**Comment by porsager** [comment]
No can't really reproduce here. Would also like to see how you measure this timing difference. You are maybe including the conection creation time when measuring postgres.js

**Comment by porsager** [comment]
Hey @adamtysonsmith - any news on this matter?

**Comment by adamtysonsmith** [comment]
We can close this, if I am able to provide a reproducible environment to test this I will open another ticket. Thanks for all the help!

**Comment by porsager** [comment]
Aww pity - I was very curious :) Love myself a performance chase :P
