### ISSUE TITLE
./node_modules/postgres/src/connection.js:1:0 Module not found: Can't resolve 'net' in Next 13 app

### ISSUE THREAD

**Issue by AmyBlankenship** [porsager/postgres#632]
I started my project from [create-next app with-postgres](https://github.com/vercel/next.js/tree/canary/examples/with-postgres) and modified it heavily to use my own tables and the Next 13 app directory. The branch of my project that shows the issue is [here](https://github.com/AmyBlankenship/next-contacts-example/tree/feat/add-address).

Steps to Reproduce:

1. clone the branch
2. npm install
3. create env.local to match your desired db
4. ley up
5. yarn dev
6. launch page
7. Create at least one friend
8. Click friend to select
9. Hover over or click "New Contact"

Expected result: page preloads or loads without error coming from within postgres library
Actual result:
![image](https://github.com/porsager/postgres/assets/6306216/2dd8a762-52b5-4622-a435-597f41dbc80b)

I tried changing the postgres options as implied in the Readme, but this did not fix the problem.
When I added console.log statements in the DB file, I could see the sql constant getting created multiple times. I feel this is related to the problem.

**Comment by AmyBlankenship** [comment]
> Ok, so this looks like a next.js bundling issue. I think they might be able to help you better if you submit your issue to the next.js repo that contains the example.

Done https://github.com/vercel/next.js/issues/52516

**Comment by porsager** [comment]
I hope you figure out your issue @AmyBlankenship . It doesn't seem to be related to Postgres.js specifically but rather the bundling of node modules in that next.js setup. You're very welcome to post the solution once you find it here, if it might help others.

**Comment by AmyBlankenship** [comment]
The issue was that the server action was not marked 'use server', and so the bundler was trying to bundle this on the client side. An easy mistake to make, a hard mistake to understand and debug.

**Comment by nonfungible-dev** [comment]
> The issue was that the server action was not marked 'use server', and so the bundler was trying to bundle this on the client side. An easy mistake to make, a hard mistake to understand and debug.

Thanks for the solution on this, @AmyBlankenship!
