### ISSUE TITLE
How to restore delta of Databse in case of rollback

### ISSUE THREAD

**Issue by satish-chef** [porsager/postgres#633]
We are using PostgreSQL in AWS RDS service.  We are planning upgrade of PostgreSQL major version from 12.11 to 14.7.  We will take a manual snapshot before upgrade.  Let's say we have to do a rollback after 7 or 24 hours, is there a way to extract the delta of the new changes that have gone into the upgraded RDS database at the time of rollback ? 
Do you have any tool/suggestions on how to take care of this scenario ?

**Comment by porsager** [comment]
It doesn't seem like a things that's related to Postgres.js - Did you post this in the right repo?

**Comment by satish-chef** [comment]
@porsager I don't see any proper github project of PostgreSQL where I can post this.  Can you please tell me where I can post it ?

**Comment by porsager** [comment]
Sorry, I wouldn't know. This is probably something you'd hire expert help for.
