### ISSUE TITLE
JSON/JSONB parsing does not seem to work.  

### ISSUE THREAD

**Issue by niranjan94** [porsager/postgres#634]
Version: `3.3.5`

```js
const sql = postgres(config.get('db.url'), {
  transform: {
    ...postgres.camel,
    undefined: null,
  },
});

const result = await sql`SELECT request FROM api_calls LIMIT 1`)
```

`request` is a JSONB column. But it is returned as a `string` in `result[0].request`

**Comment by porsager** [comment]
You might have saved a json string in that column?

**Comment by porsager** [comment]
Hehe... Not at all. Only guessed it since I've done the same myself 😉

**Comment by bringmebac** [comment]
@niranjan94 how exactly did you resolve it. I have json object which I insert by running:

const data = [{
   someColumnA: 'a',
   jsonBColumn: {foo: 1...}
}]
 sql`Insert into my_table ${sql(data)};`

This approach seem to causes nested properties to have escaped quotes -> \"foo\": ...

**Comment by andrewrothman** [comment]
I'm seeing this. The "data" property should be returned as an object, right? I get an object back with "node-postgres"

```javascript
const pg = require("pg");
const pool = new pg.Pool();
await pool.query("SELECT * FROM "Interactions" WHERE id = $1", ["abc"]);

Result {
  command: 'SELECT',
  rowCount: 1,
  oid: null,
  rows: [
    {
      id: 'abc',
      data: [Object],
...
await sql.unsafe("SELECT * FROM "Interactions" WHERE id = $1", ["abc"]);

Result(1) [
    {
        id: 'abc',
        data: '{"foo": "bar"}'
    }
]
```
