### ISSUE TITLE
`transform` behavior inconsistent across environments

### ISSUE THREAD

**Issue by coreyward** [porsager/postgres#635]
I thought I misunderstood how `transform: camel` worked because queries like `SELECT some_field FROM my_table` were coming back with data like `[{ some_field: "the value" }]` when run from my Next.js app (via requests), but today I noticed the transformation works as I expected when I run from the console. 

The two environments are running queries by importing from my `lib/database.ts` file, so the configuration should be the same. Something like this: 

```ts
import postgres, { camel } from "postgres"

// Development config
const config = {
  transform: camel,
  idle_timeout: 120,
  max_lifetime: 60 * 30,
  max: 30,
  ssl: false,
}

export const sql = postgres(process.env.POSTGRES_URL, config)
```

Then I use it like this: 

```ts
import { sql } from "@/lib/database"

export const getSomeData = () => {
  return sql<{ other_id: number }[]>`
    SELECT other_id FROM this_table;
  `
}
```

If I call this in the REPL or from Jest tests, I get `[{ otherId: 1 }, { otherId: 2 }]` back.
If I call it in `getServerSideProps` in Next, I get `[{ other_id: 1 }, { other_id: 2 }]`.

This holds for queries that don't access data. E.g., ``const res = await sql`SELECT 1 as test_value` `` produces `{ test_value: 1 }` when run in Next, but this test passes in Jest:

```ts
import { sql } from "@/lib/database"

test("fields are camelized", async () => {
  const res = await sql`SELECT 1 as test_value`
  expect(res[0].testValue).toBeDefined()
  expect(res[0].test_value).toBeUndefined()
})
```

I also confirmed that my database configuration file is in fact responsible for the camelizing behavior: removing the `transform: camel` line causes the Jest tests to fail.

I'm not sure why this might be happening. I suspect something might be different between the CJS and ESM versions of the library, but it's just a guess. Any insight would be appreciated!

**Comment by porsager** [comment]
Yeah, I don't have any chance to debug these bundlers. 

Feel free to reopen if you have any trace.
