### ISSUE TITLE
SET value TO json results in PostgresError: syntax error at or near "$1"

### ISSUE THREAD

**Issue by jescowuester** [porsager/postgres#640]
I have a query that looks like this:

```js
	const claims = '{"role":"authenticated","sub":"8609034g-e897-4631-ad07-15d3ebdd7999"}'

	const data = await sql.begin('ISOLATION LEVEL SERIALIZABLE', async (sql) => {
		await sql`SET session role authenticated`
		
		await sql`SET request.jwt.claims TO ${claims}` // <-- this breaks
		
		const changed = await sql`SELECT id, message FROM test`

		return changed
	})
```

I tried every variation I could think off to insert the `sub` claim into my query, but it always results in the error `PostgresError: syntax error at or near "$1"`. 
I also tried using `sql.json` which resulted in `PostgresError: invalid input syntax for type json`
I also tried inlining the json in the request directly and only passing the sub value via interpolation, but that failed as well.

**Comment by porsager** [comment]
Use the `set_config` and `current_setting` functions instead, as they support parameters 😉 https://www.postgresql.org/docs/9.3/functions-admin.html
