### ISSUE TITLE
Feature request: Support arrays of tagged templates for dynamic sql

### ISSUE THREAD

**Issue by claytongulick** [porsager/postgres#656]
I'm doing some dynamic sql building, and struggling with how to support multiple dynamic WHERE clauses.

I do something like:

```javascript
        for(let i=0; i<keys.length; i++) {
            let key = i;
            if(i == 0)
                conditions.push(sql`where ${sql(key)} = ${row[key]}`);
            else
                conditions.push(sql`and ${sql(key)} = ${row[key]}`);
        }
```

and I'm trying to use that like:

```javascript
await sql`update some_table set foo = 'bar' ${conditions}`;
```

Unfortunately, it doesn't seem to work currently because arrays of tagged literals don't seem to be supported - unless I'm missing something?

I was hoping it would work the same way lit-html does with being able to do ``` sql`${ some_array.map(_ => sql`<some dynamic sql>`)}`  ``` kind of thing.

My current (nasty) solution is this:

```javascript
            let result = await sql`
            update ${sql(table)}
            set ${sql(row, columns)}
            ${keys.length ? sql`where ${sql(keys[0])} = ${row[keys[0]]}`:sql``}
            ${keys.length == 2 ? sql`and ${sql(keys[1])} = ${row[keys[1]]}`:sql``}
            ${keys.length == 3 ? sql`and ${sql(keys[2])} = ${row[keys[2]]}`:sql``}
            ${keys.length == 4 ? sql`and ${sql(keys[3])} = ${row[keys[3]]}`:sql``}
            ${keys.length == 5 ? sql`and ${sql(keys[4])} = ${row[keys[4]]}`:sql``}
            `;
```

**Comment by claytongulick** [comment]
@20after4 I'm not too sure where you're seeing that in the source?

When I try the above, it tries to use a Builder (because it detects conditions as being an array) - when it calls escapeIdentifiers, I get an error on str.replace missing because it's not recursively resolving the Query instance.

The weird thing is that I feel like I had tried this before and had it working, but no love now. Hmm. This doesn't work:

```javascript
 ${conditions.length ?
        sql`
        where ${sql(conditions)}
        `:sql``
        }
```

Where conditions is a simple array of templates:

```javascript
let conditions = [];
        if(filters.specialty)
            conditions.push(
                sql`provider_specialty.cms_specialty_code in ${sql(filters.specialty)}`
            )
```

**Comment by xuxucode** [comment]
Try replacing `${sql(conditions)}` with `${conditions}` to avoid the `Builder`, because `postgres` supports [fragment array](https://github.com/porsager/postgres/blob/v3.3.5/src/types.js#L112)

**Comment by porsager** [comment]
spot on @xuxucode - thanks :)
