### ISSUE TITLE
Help on usage without fixed string (not tagged template literal)

### ISSUE THREAD

**Issue by FabioZumbi12** [porsager/postgres#66]
Hi all,

I trying to use queries using select command from variables, not from fixed strings.

What i trying:

```
var cmd = MyObject.IncomingCommandFromMyObject
sql`${cmd}`
```

But i got `syntax error at or near "$1"`

Tryied to use `sql(cmd)` and `sql(cmd, [])` too but got `Error: Query not called as a tagged template literal`

How to proceed?

**Comment by Minigugus** [comment]
If your `var cmd = MyObject.IncomingCommandFromMyObject` is a properly escaped SQL query, you can use [`sql.unsafe(cmd, [])`](https://github.com/porsager/postgres#the-connection-pool)

`sql(cmd)` escapes parameters as valid SQL column names.

**Comment by FabioZumbi12** [comment]
Thank you!!

`sql.unsafe(cmd)` it worked!!
