### ISSUE TITLE
Question: How to build queries with dynamic filters on JSONB field?

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [porsager/postgres#669]
Hello there,

I am trying to build a query that has dynamic JSONB field filters. 
I get the following error:
`column "metadata ->>'fieldName'" does not exists`. I can see what is happening here. The filter part gets wrapped by double quotes & so it is considered as a column name. I could not find any references related to this in README page. Is it possible to build queries with dynamic JSONB filters? If it is, how do I do that?

Good day!

**Comment by porsager** [comment]
right, you'd need to split that op like so:

```js
await sql`
  select
    ${ sql('metadata') }->>${ 'fieldName' } as x
  from (values ('{"fieldName": 42}'::jsonb)) as x(metadata)
`
```
