### ISSUE TITLE
Support large objects

### ISSUE THREAD

**Issue by pauldraper** [porsager/postgres#67]
Compare with https://github.com/Joris-van-der-Wel/node-pg-large-object

**Comment by porsager** [comment]
Oh interesting. 

I probably won't have time to look closer myself any time soon, but PR's are most welcome 😉

**Comment by yckao** [comment]
I recently write an package with same interface as https://github.com/Joris-van-der-Wel/node-pg-large-object.
https://www.npmjs.com/package/postgres-large-object
Maybe you can give it a try
