### ISSUE TITLE
Unable to construct on conflict with multiple columns dynamically

### ISSUE THREAD

**Issue by nnmrts** [porsager/postgres#671]
Whatever I'm trying, I'm unable to make an insert query with an on conflict clause depending on two or more columns...

What I want to do:

```sql
insert into table
	(a, b, c)
	values (1, 2, 3)
on conflict (a, b)
do update set
	(
		a = excluded.a
		b = excluded.b
		c = excluded.c
	)
```

To do this, after some general issues, I followed the comment https://github.com/porsager/postgres/issues/217#issuecomment-1156958623 and this is what I came up with:

```js
/**
 * Upsert data into a table.
 *
 * @param {Function} db - Postgres instance.
 * @param {string} table - Table name.
 * @param {object} data - Data to upsert. Looks like this: {a: 1, b: 2, c: 3}.
 * @param {Array} conflict - Conflict columns. Looks like this: ["a", "b"].
 *
 * @return {Promise} - Promise.
 */
const upsert = async (
	db,
	table,
	data,
	conflict
) => {
	const conflictString = conflict.map((x, i) => db`${i ? db`,` : db``}${db(x)}`);
	const updateSetClause = Object.keys(data[0]).map((x, i) => db`${i ? db`,` : db``}${db(x)} = excluded.${db(x)}`);

	return db`
	  insert into ${db(table)} ${db(data)}
	  on conflict (${conflictString})
	  do update set ${updateSetClause}
	`;
};
```

But the result looks like this and obviously fails:

```sql
insert into "table" ("a","b","c")values($1,$2,$3)
on conflict ( "a, b")
do update set  "a" = excluded."a" ,"b" = excluded."b" ,"c" = excluded."c"
```

Is it possible to fix this without using `unsafe`?

**Comment by porsager** [comment]
Not bad, but why are you saying it obviously fails? Looks correct to me based on the sample input.

**Comment by nnmrts** [comment]
@porsager Ah sorry, didn't make it clear: `on conflict ( "a, b")` is invalid, I think it should either be `on conflict ( "a", "b")` or `on conflict ( a, b)`

**Comment by porsager** [comment]
It works when I test it. I think your conflict array might look like this: `['a, b']` instead of this `['a', 'b']`.

**Comment by nnmrts** [comment]
Don't ask me why but yeah, that was the issue. I'm sorry........

**Comment by porsager** [comment]
Cool :) It even caught my eye in your sample as well, so understandable :D
