### ISSUE TITLE
problem getting the results for a view or function

### ISSUE THREAD

**Issue by gitsemaphore** [porsager/postgres#676]
When I call a view or function in the postgres, the results returns ONLY the columns.  For example:

```
const pgsql = postgres(connectionObj);
const dbResult = await pgsql`SELECT * FROM public.data_view_customer`
```

The `dbResult` only will contain the `dbResult.columns` with the column of the `public.data_view_customer`

If I put the sql of the view in the sql the, the `dbResult` works as expected.  Did something changed?

**Comment by porsager** [comment]
The result "is" the actual rows. See the very first part of the docs https://github.com/porsager/postgres#usage

Just try to `console.log(dbResult)` and you'll see it. The columns property just contains column information and is most likely something you'd rarely use.

**Comment by gitsemaphore** [comment]
Ah I see now. It is when the the dbResult.count = 0.  Nevermind regarding the issue. Closing it.
