### ISSUE TITLE
Support custom PostgreSQL types: composite types, range types

### ISSUE THREAD

**Issue by pauldraper** [porsager/postgres#68]
The paradigm here seems to be *reading* types uses the return PostgreSQL type ids, and *writing* types uses the JS type.

To support custom types under this paradigm, I suggest:

1. A connection parameter or a function that collects necessary information from pg_type/pg_attribute.
2. Two new classes `new Composite('mytype', value)` and `new `Range('myrange', start, end)` to use for type inspection.

**Comment by porsager** [comment]
Is this not covered by [custom types](https://github.com/porsager/postgres#types) . 

One thing i would like to add though is reading custom types by name as well instead of only oid

**Comment by pauldraper** [comment]
It essentially is. Thanks.
