### ISSUE TITLE
Simple delete query is not working for me

### ISSUE THREAD

**Issue by elhananjair** [porsager/postgres#687]
I am trying to run a delete query, I have an array that contains values to delete from the table, but it is not deleting. 

```
let totalNum = [] //this contains an array of numbers
//e.g totalNum = [122, 322, 424, 233];

async function deleteNum(){
    try {
        totalNum.map(async num => await sql`delete from mytable.numlist where digit = ${ num } returning digit`)
    } catch (e) {
        console.log("Error Found: " + e.message)
    }
}

deleteNum().catch(e => console.log(e));
```
It is not deleting from the table, what am I missing here?

**Comment by priyanshu-101** [comment]
@elhananjair this code is in which file?

**Comment by priyanshu-101** [comment]
Please assign it to me 
I will solve it

**Comment by elhananjair** [comment]
> @elhananjair this code is in which file?

it seems there was some issue with my async await implementation, it works now.
