### ISSUE TITLE
Update README.md example

### ISSUE THREAD

**Issue by flipcc** [porsager/postgres#69]
## Claimed misbehavior

[Line 93](https://github.com/porsager/postgres/blame/master/README.md#L93) states that:

```
A query will always return a `Promise` which resolves to a results array `[...]{ rows, command }`.
```

## Proposed change

This could be adjusted to:

```diff
-- A query will always return a `Promise` which resolves to a results array `[...]{ rows, command }`.
++ A query will always return a `Promise` which resolves to a results array `[{rowObj}, {rowObj}, ..., rows, command]`.
```

## Motivation

Now, one can see that an array is returned, that will have 3 entries, even when only one row is returned. 

-----
As a question on the side: Can this bevahior be dependent on a config switch? So that one could use this switch to get only the array of results?

Otherwise: great great package! Thank you so much!

**Comment by Minigugus** [comment]
> As a question on the side: Can this bevahior be dependent on a config switch? So that one could use this switch to get only the array of results?

The result is already a [*real*](https://github.com/porsager/postgres/blob/master/lib/connection.js#L118) [array](https://github.com/porsager/postgres/blob/master/lib/backend.js#L121). It's just that properties [`count`](https://github.com/porsager/postgres/blob/master/lib/backend.js#L83), [`command`](https://github.com/porsager/postgres/blob/master/lib/backend.js#L85) and [`columns`](https://github.com/porsager/postgres/blob/master/lib/backend.js#L191) are added to this array. Also, the `rows` property doesn't exist.

In a TypeScript way, a correct definition seams to be `Query[] & { count: number, command: string, columns: { name: T, type: number, parser(raw: string): any }[] }` .

*NOTE : I wrote #8 :stuck_out_tongue_winking_eye:*

**Comment by flipcc** [comment]
@Minigugus 
Ah ok! That is a superb development. I guess I close this issue than. Thanks for the work on 7 and 8.

**Comment by flipcc** [comment]
@Minigugus 
Is there a way, that  `result.length !== result.count` could arise? Any inside here would be really appreciated. 

Thank you very much for your effort.

**Comment by Minigugus** [comment]
This can happen with `.stream` or `.cursor`, since the resulting promise does not keep references from processed rows (the array is empty). In fact, the `count` attribute is the actual number of rows sent by the server, while `length` is the number of rows in the array returned by the promise. Thus, this shouldn't happen with regular queries. :wink:

**Comment by porsager** [comment]
@flipcc It's actually primarily relevant with eg. `update` or `inserts`. The `count` property will contain how many rows where updated / inserted, but you won't have any items in the array unless you specify `returning ...` in your query.

**Comment by flipcc** [comment]
Ah very well. That is good to know. Thank you very much for this inside and the help!
