### ISSUE TITLE
Error: dependencies are imported but could not be resolved: cloudflare:sockets

### ISSUE THREAD

**Issue by jadbox** [porsager/postgres#691]
I'm using another Vite project that is not meant to deploy on Cloudflare. However, it's not complaining about the import listed for cloudflare:sockets. Is there a work around in the library to not trip this error for non-cloudflare projects?

```
Error: The following dependencies are imported but could not be resolved: cloudflare:sockets
  ```

**Comment by porsager** [comment]
I think the bundler should have a way to choose the right export. If not, I'll end up adding every single bundler name to the exports, and then there's a the next problem. Suddenly someone want's to use those bundlers with Cloudflare 😅

**Comment by porsager** [comment]
Did you find any way around this?
