### ISSUE TITLE
Fragment not supported in insert helper?

### ISSUE THREAD

**Issue by Pyrolistical** [porsager/postgres#695]
I have a `Buffer` which I want to cast to a `UUID` during insert, and this works.
```js
sql`
  INSERT INTO "some_table"(id, name)
  VALUES
    (CAST(ENCODE(${id}, 'hex') AS UUID), ${name})
`
```

I need to do that cast a lot, so I extracted as `as_uuid`:
```js
const as_uuid = (id: Buffer) => sql`CAST(ENCODE(${id}, 'hex') AS UUID)`
sql`
  INSERT INTO "some_table"(id, name)
  VALUES
    (${as_uuid(id)}, ${name})
`
```

But but when I convert that to use the insert helper, I get a type error.

```js
const as_uuid = (id: Buffer) => sql`CAST(ENCODE(${id}, 'hex') AS UUID)`
sql`
  INSERT INTO "some_table"
    ${sql({
      id: as_uuid(id), // errors with Index signature for type 'string' is missing in type 'PendingQuery<any>'
      name
    })}
`
```

Is this a missing feature or a type bug?

**Comment by porsager** [comment]
You can't put fragments as parameter values, so that's why.

I think you should look into [custom types](https://github.com/porsager/postgres#custom-types) instead as a way to solve it, by converting the Buffer you have to a hex string in the serialize function.
