### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Minigugus** [porsager/postgres#7]
What about supporting Typescript ?
Just a simple `types.d.ts` would be enough, no need to fully rewrite the project :smile: 

Pro
 * Much more easy than reading the doc
 * Direct documentation with JSdoc and parameters validation (intellisense)

Con
 * Must be in sync with the implemented code

**Comment by porsager** [comment]
Yes that would be great :)

I'm not a Typescript user myself, and thought someone would be kind enough to PR that at some point if they needed it.

Is it something you'd be interested in trying out?

**Comment by Minigugus** [comment]
I'd be glad to, but I'm very busy these days... :disappointed:  I'll work on it as soon as I have time :wink:
