### ISSUE TITLE
Connection timeout with cloudflare hyperdrive

### ISSUE THREAD

**Issue by eduardvercaemer** [porsager/postgres#702]
I setup my hyperdrive connection as per https://developers.cloudflare.com/hyperdrive/get-started/
(I tried a supabase database and also a neon database). In either case, requests fail with
```
Uncaught (in response) Error: write CONNECT_TIMEOUT xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.hyperdrive.local:5432
```

Exact code, tested with `wrangler dev --remote`:
```js
import postgres from "postgres";

export default {
  async fetch(request, env, ctx) {
    const url = env.HYPERDRIVE.connectionString;
    console.info("using", url);

    const sql = postgres(env.HYPERDRIVE.connectionString);
    const rows = await sql`select now()`;
    return Response.json(rows);
  },
};
```

I then switched the code to use regular `pg` library and it works as expected, so it looks like this is a "postgres" (as in this library) issue.

**Comment by anirudhsama** [comment]
I'm also facing the same issue. Can also confirm that it works fine with the `pg` library.

**Comment by anirudhsama** [comment]
If it helps in debugging, the hyperdrive connection string has sslmode=disabled as a query param. It will be like `postgresql://user:password@xxxx.hyperdrive.local:5432/dbxxx?sslmode=disable`

**Comment by eduardvercaemer** [comment]
Btw this is exclusively a postgres + hyperdrive issue. Using pg library or skipping hyperdrive and using postgres server directly both work as expected.

**Comment by porsager** [comment]
What happens if you remove the sslmode part? I am not a computer, so can't try anything myself.

**Comment by ItsWendell** [comment]
@porsager I tried both removing the sslmode query in the URL before passing it to postgres.js and adding ```{
          rejectUnauthorized: false,
        }``` to ssl option, in both cases, timeouts.

**Comment by KianNH** [comment]
The `CONNECT_TIMEOUT` error is fixed by https://github.com/porsager/postgres/commit/09e6cb5247c514e5cf50faced6452fae956edeb9, so you will want to upgrade to at least [3.4.1](https://github.com/porsager/postgres/releases/tag/v3.4.1).

**Comment by porsager** [comment]
Thanks a lot for confirming @KianNH
