### ISSUE TITLE
Benchmarks for "Fastest full-featured node & deno client" claims?

### ISSUE THREAD

**Issue by Phara0h** [porsager/postgres#704]
Are there any benchmarks that support this project is the fastest? I have an postgres client thats full featured ORM and was built for speed and would be very curious if your actually faster than my project. https://github.com/Phara0h/Adost

**Comment by hastebrot** [comment]
`pg` and `pg-native` are listed in the benchmark, https://github.com/porsager/postgres-benchmarks#results

the benchmark page is linked on the very top of the readme.
![Screenshot 2023-10-25 at 17 59 22](https://github.com/porsager/postgres/assets/496255/ba70a929-2b64-45bf-b373-9f6209ddcf1b)

**Comment by vitaly-t** [comment]
I am the author of [pg-promise], and seeing how many questionable results you have in your benchmark output, I cannot trust it...

Library [pg-promise] is built on top of [pg], and yet you have so many tests that indicate that [pg-promise] well outperforms its own underlying driver? That is kind of impossible, being a wrapper on top of [pg] and [pg-native], it cannot outperform its own underlying drivers.

I think you should review how you test those things...

[pg-promise]:https://github.com/vitaly-t/pg-promise
[pg]:https://github.com/brianc/node-postgres
[pg-native]:https://github.com/brianc/node-pg-native

**Comment by hastebrot** [comment]
I reran the benchmarks on `node` and indeed it does not match. `pg-promise` is faster than `pg` in some benchmark table column. (MacBook Pro, 2023, Apple M3 Pro, 36 GB)

```
❯ git clone https://github.com/porsager/postgres-benchmarks
❯ rm package-lock.json
❯ bun install
❯ createdb $LOGNAME
❯ bun start
$ node index.js
client     |         select |     select_arg |    select_args |   select_where
:--------- | -------------: | -------------: | -------------: | -------------:
postgres   |  0.049s (2.7x) |  0.049s (4.8x) |  0.070s (4.1x) |  0.062s (5.1x)
pg-promise |  0.111s (1.2x) |  0.116s (2.0x) |  0.177s (1.6x) |  0.203s (1.6x)
pg-promise-native |  0.111s (1.2x) |  0.118s (2.0x) |  0.179s (1.6x) |  0.208s (1.5x)
pg         |  0.103s (1.3x) |  0.201s (1.2x) |  0.248s (1.2x) |  0.286s (1.1x)
pg-native  |  0.110s (1.2x) |  0.116s (2.0x) |  0.173s (1.7x) |  0.215s (1.5x)
slonik     |  0.132s (1.0x) |  0.234s (1.0x) |  0.291s (1.0x) |  0.317s (1.0x)
client;select;select_arg;select_args;select_where
postgres;0,049;0,049;0,070;0,062
pg-promise;0,111;0,116;0,177;0,203
pg-promise-native;0,111;0,118;0,179;0,208
pg;0,103;0,201;0,248;0,286
pg-native;0,110;0,116;0,173;0,215
slonik;0,132;0,234;0,291;0,317
```

**Comment by vitaly-t** [comment]
Well, it's kind of an anomaly, for a library to outperform its own sub-driver 😄
