### ISSUE TITLE
Support for GAS Google Apps Script?

### ISSUE THREAD

**Issue by jlprado** [porsager/postgres#710]
Do you plan to support Google Apps Script? Thanks,

**Comment by porsager** [comment]
It's the first time I'm hearing about it, so no - no plans yet 😋

**Comment by jlprado** [comment]
Just to mention some interest on this matter: Google Apps Script lacks a JDBC driver to postgres as stated in this issue from 2011, that has already 149 stars (how many GAS users were interested enough to search and vote for this issue):
JDBC support for postgresql https://issuetracker.google.com/issues/36752790
thanks,

**Comment by porsager** [comment]
Well if google apps script can do tcp then I don't see why it shouldn't be possible?

**Comment by jlprado** [comment]
They can do urlFetch():
https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app

**Comment by porsager** [comment]
Ok, then sorry no, that's not in the scope of this library. You should look into having a service in between.
