### ISSUE TITLE
sql.simple() for DB initialization and typescript support

### ISSUE THREAD

**Issue by mukulgupta21** [porsager/postgres#714]
# Problem

I have a use-case where I have a DDL script to initialise the database. Something similar to below:

```sql
CREATE DATABASE dbName with owner dbuser ;

CREATE TABLE IF NOT EXISTS table (
  col1 VARCHAR(255) NOT NULL,
  col2 VARCHAR(255) NOT NULL,
);
```

I'm trying to use it as below:
```typescript
await (sql`${sql.unsafe(sqlScript)}` as any).simple();
```

which results in the following error:

```
Error creating database PostgresError: CREATE DATABASE cannot run inside a transaction block
```

EDIT: I realize this is not possible to do in postgresql since one cannot switch a database without re-initializing the connection (aka backend).

# Questions: 
- What is the recommended way to do this? I'd like to maintain the multiple statement SQL script independently.
- Can we get typescript support for `simple` method?

**Comment by iby** [comment]
Have a look at https://github.com/porsager/postgres/issues/198 – looks like a similar case 👍
