### ISSUE TITLE
Return Single Object Instead of Array?

### ISSUE THREAD

**Issue by chauhankiran** [porsager/postgres#717]
Consider the following query.

```js
  return await sql`
    select
      *
    from users
    where
      email = ${email} and password = ${password}
  `;
```

This will return a single user.

And there always be scenario where we're interested to fetch only single row than multiple row results. So, it there a way that we can only return just a single object (`{}`) instead array of object (`[{}]`)? As of now, I need to write like `user[0].id` instead of `user.id`.

**Comment by porsager** [comment]
Destructuring for the win 😉

```js
const [user] = await sql`...`
```

And if you don't want the temporary variable you can do destructuring in `.then` like this:

```js
return await sql`...`.then(([x]) => x)
```
