### ISSUE TITLE
text[] is being returned as string

### ISSUE THREAD

**Issue by joshxyzhimself** [porsager/postgres#718]
Hi everyone!

Long story short, I was using Kysely + Postgres.js using `kysely-postgres-js`, however the columns with `text[]` type are being returned as unparsed string array instead of a string array.

Returned value is `'{example,example2}'` instead of `['example', 'example2']`

Related issue is here: https://github.com/igalklebanov/kysely-postgres-js/issues/8

The related issue contains a comparison example of outputs from kysely and postgres.js. The `SELECT * FROM roles` statement at postgres.js returns the correctly parsed output; kysely does not.

@igalklebanov said:

- Kysely, nor this dialect, perform any data transformation. The underlying driver (postgres.js) could be responsible.
- It could be that the reserved connections are behaving differently.

However I tried to test the reserved connection below:

```js
const reserved = await sql.reserve();
const porsager_postgres_select_reserved = await reserved`SELECT * FROM private.roles`;
await reserved.release();
console.log(JSON.stringify({ porsager_postgres_select_reserved }, null, 2));
```

The output seems fine:

```
{
  "porsager_postgres_select_reserved": [
    {
      "id": "cb5c9d7a-15a6-4d9a-bd6d-dac958a3bd03",
      "name": "administrator",
      "scope": [
        "example",
        "example2"
      ]
    }
  ]
}
```

My question is, could there be other things that could cause the `text[]` column to not be parsed correctly?

Thank you!

**Comment by porsager** [comment]
Thanks a lot for the description @joshxyzhimself ! There was indeed an issue with reserved connections not being properly initialized. I've pushed a fix, and I'll make a release now.
