### ISSUE TITLE
[Feature request] add sql.unnest helper

### ISSUE THREAD

**Issue by xiaoyu-tamu** [porsager/postgres#72]
Could we add a sql.unnest helper similar to slonik#sql.unnset?[[doc](https://github.com/gajus/slonik#slonik-query-building-sql-unnest)] [[implementation](https://github.com/gajus/slonik/blob/master/src/sqlFragmentFactories/createUnnestSqlFragment.js)]

It's really helpful when doing bulk insert/update

**Comment by porsager** [comment]
This is doable like this already right?
```js
sql`
  select
    bar,
    baz
  from unnest(
    ${ sql.array([1, 2]) }::int4[],
    ${ sql.array(['foo', 'bar']) }::text[]
  ) as x(bar, baz)
`

I'm not sure I see the value proposition in the helper, so maybe you could add some examples?

**Comment by qpwo** [comment]
For future readers, here's how I formatted/encoded multiple arrays at once:

```ts
const rows = [[1, [2,3]], [4, [5,6]], [7, [8,9]]]

await sql`
  select num, pair
  from (VALUES
    ${sql(rows.map(([num,pair])=>[num,sql.array(pair)]))}
  ) as x(num, pair)
`
/*
Result(3) [
  { num: '1', pair: [ '2', '3' ] },
  { num: '4', pair: [ '5', '6' ] },
  { num: '7', pair: [ '8', '9' ] }
]*/
```

@porsager Maybe the readme could use some tips on inserting arrays and json and explain the `sql.array` and `sql.json` helpers?

**Comment by tx0c** [comment]
> @porsager Maybe the readme could use some tips on inserting arrays and json and explain the `sql.array` and `sql.json` helpers?

:+1: the `sql.array` and `sql.json` need to be documented
