### ISSUE TITLE
Not able to cast as decimal

### ISSUE THREAD

**Issue by gagan-bansal** [porsager/postgres#726]
Here is my example:

```javascript
const postgres = require('postgres');
const sql = postgres();

(async () => {
  let result = await sql`SELECT 1.5::decimal as score`;
  console.log(typeof result[0].score);
  result = await sql`SELECT 1.5 as score`;
  console.log(typeof result[0].score);
})();
```

For both output is `string`. Am I doing something wrong?

**Comment by porsager** [comment]
Decimal can't be represented in js `Number` without loosing precision, so it would be irresponsible to cast implicitly. Instead you can eg. cast to `::float` in sql

**Comment by gagan-bansal** [comment]
Thank you @porsager, that was quite helpful.
