### ISSUE TITLE
Error: Cannot resolve "cloudflare:sockets" from "...\node_modules\.pnpm\postgres@3.4.0\node_modules\postgres\cf\polyfills.js" and externals are not allowed!

### ISSUE THREAD

**Issue by dev-cetus** [porsager/postgres#727]
hi,
I'm using Nuxt 3 v3.8, and I'm trying to deploy to cloudflare with the `cloudflare` preset. But I get the following error:
![image](https://github.com/porsager/postgres/assets/61233505/7fbd69ce-0bd8-4ea6-8450-0150043b3aaf)
I've seen that you've already created a fix for this error, but I'm using version `3.4.0` of `postgres` and the error is still there...

My wrangler.toml file contains the line:
```toml
node_compat = true
```

**Comment by dev-cetus** [comment]
Doesn't work, same error... You can check de [code](https://github.com/splrge/vexa-jobs). <br>
build it with 
```bash
$env:NITRO_PRESET='cloudflare'; $env:NUXT_JWT_SECRET='djisiu'; $env:DATABASE_URL='postgres://postgres:postgres@localhost:5432/postgres'; pnpm run build
```
(database is not required for build)

**Comment by porsager** [comment]
Sorry, but I'm not going to debug why some other build tool doesn't know how to handle this. Create an issue in their repo.

**Comment by bllchmbrs** [comment]
@dev-cetus , did you figure out how to get this working?

I am trying to run Cloudflare Pages with Nuxt `3.4.3` and this library(postgres) and it fails with the same approximate error.

```
[error] Cannot resolve "cloudflare:sockets" from "/opt/buildhome/repo/node_modules/postgres/cf/polyfills.js" and externals are not allowed!
```

I don't know what to do next in order to at least try to get this working.

**Comment by MickL** [comment]
Same issue Vercel Edge Functions. This issue is not regarding Cloudflare, but regarding serverless edge workers environments. This project does not work on serverless edge workers. @porsager do you mind reopening this issue?

I wonder why `postgres` adds this polyfills anyway. If they would be removed and rather be optional the problem might be solved.

**Comment by minemos** [comment]
Any updates?

**Comment by porsager** [comment]
Try installing latest from github `npm install porsager/postgres`

I'll make a release soon if that works fine 😉

**Comment by chenrui333** [comment]
I just tried `npm install porsager/postgres`, got this error instead

```
 ⨯ ./node_modules/.pnpm/postgres@https+++codeload.github.com+porsager+postgres+tar.gz+f58cd4f3affd3e8ce8f53e42799672d86cd2c70b/node_modules/postgres/src/connection.js:1:1
Module not found: Can't resolve 'net'
```

**Comment by porsager** [comment]
@chenrui333 what platform are you trying to use it on?

**Comment by chenrui333** [comment]
I am using vercel edge runtime for the backend. Switch off resolved the issue if that helps.

**Comment by porsager** [comment]
Yeah. You can't make tcp connections from vercel edge, so Postgres.js won't work there. Neon works because the proxy through websockets.

**Comment by johnnyicon** [comment]
Found this solution on Stackoverflow, and it worked for me. I'm deploying a Nuxt 3 app to CF Pages.
```
nitro: {
  preset: 'netlify-edge',
  rollupConfig: {
      external: ['postgres']
  }
}
```
Source: https://stackoverflow.com/questions/78498288/deploying-nuxt-app-with-postgres-to-cloudflare-fails

Hope it helps!
