### ISSUE TITLE
@types/postgres is missing

### ISSUE THREAD

**Issue by TodorTotev** [porsager/postgres#73]
Hello. After finding your library I was like - whoa, finally.

However, after trying to install the yarn package of @types/postgres I have realized that it is missing.

It would be lovely if you can do something about it. If you don't have the time I can do it for you.
![Screenshot 2020-05-14 at 17 06 04](https://user-images.githubusercontent.com/51530311/81944279-349e1680-9605-11ea-8f02-8d43ab6f65a4.png)

**Comment by porsager** [comment]
Thanks a lot :)

It's coming ... https://github.com/porsager/postgres/pull/8
