### ISSUE TITLE
Update multiple rows in one query

### ISSUE THREAD

**Issue by chuck-huey** [porsager/postgres#74]
This is the sql query
```sql
update ratings as r1
SET	
  rating = r2.rating,
  label = CAST (r2.label AS ratings_label),
  updated_at = CAST(r2.updated_at as timestamptz)
from (values
  ('5f046102-e418-4ccd-8637-bf5318a25abb','Total Lockdown NEW', 'GREEN', '2020-05-17T09:21:36.966Z'),
  ('c9871f1a-c961-4743-b65d-4c5517eadb62','Partial Lockdown NEW', 'YELLOW', '2020-05-17T09:21:36.966Z'),
  ('99874e80-5846-417f-a89f-0b2c64fc42c6','Curfew NEW', 'RED', '2020-05-17T09:21:36.966Z')
) 
as r2(id, rating, label, updated_at)
where r1.id = CAST(r2.id as uuid)
```

Using postgres;
```js
sql`UPDATE ratings as r1
    SET
      rating = r2.rating,
      label = CAST (r2.label AS ratings_label),
      updated_at = CAST(r2.updated_at as timestamptz)
    FROM (values (${ratingsRecords})) AS r2(id, rating, label, updated_at)
    WHERE r1.id = CAST(r2.id as uuid)
  `
```

Where `ratingsRecords` is an array of objects containing `id, rating, label, updated_at` fields.

I keep getting this error

```json
"table \"r2\" has 3 columns available but 4 columns specified"
```

What am I getting wrong??

**Comment by porsager** [comment]
Hi @chuck-huey ..

Sorry, this one slipped my radar.

This is one of the cases v1 doesn't cover very well. I finally have some time available to finish v2 that will also include a fix for this.

You would do it like this once it lands:
```js
sql`UPDATE ratings as r1
    SET
      rating = r2.rating,
      label = CAST (r2.label AS ratings_label),
      updated_at = CAST(r2.updated_at as timestamptz)
    FROM (values ${ sql(ratingsRecords, 'id', 'rating', 'label', 'updated_at') }) AS r2(id, rating, label, updated_at)
    WHERE r1.id = CAST(r2.id as uuid)
  `
```

A few things to note.
- I've wrapped `ratingsRecords` in the `sql()` function which is what you'll use for any dynamic query of this nature
- I've removed the surrounding parenthesis
- I've added the key names explicitly to make the query safe and also check for potential undefined values

I'll let you know here as soon as something is ready on master that let's you do this.

Until then you'll either have to do the query differently, or concat it yourself and use `sql.unsafe`.

**Comment by chuck-huey** [comment]
Thanks for responding @porsager

I think I'll wait for v2. I'm wary of writing insecure code to the app I'm working on.

**Comment by xiaoyu-tamu** [comment]
is this available in v2.0.0-beta.0?

**Comment by porsager** [comment]
Hi @xiaoyu-tamu .. Unfortunately not, but I've got something in the works I just need to finish tests for and it'll be included in the next release.

**Comment by porsager** [comment]
Let's track this in #12 🙂
