### ISSUE TITLE
Disable prepared_statements option?

### ISSUE THREAD

**Issue by danjrichards** [porsager/postgres#76]
Hi
I'm liking this library, so firstly thank you very much for writing it!

I'm using it to run some health check queries by starting each in a promise, then looping over my list of promises to await the result.
This generally works, but ~20% of the time I get a `prepared statement "p1" already exists` error thrown.
I don't see a way of disabling the use of prepared statements, but maybe I'm missing something?

Thanks
Dan

**Comment by porsager** [comment]
Hi Dan.

Thank you very much.

I've found an issue with this, that is fixed in the upcoming v2, but unfortunately I haven't had time to backport it to v1.

Would you maybe try to see if the issue persist with `master` here on github? (`npm i porsager/postgres`)

**Comment by danjrichards** [comment]
It's working well with v2, thanks @porsager!

My use case right now is OK with prepared statements being used, but I know there are some circumstances where it needs to be disabled, such as when using pgbouncer in transaction pooling mode.
It would be great if that could that be added as a configuration option...?

Many thanks
Dan

**Comment by porsager** [comment]
Cool, thanks for checking!

Prepared statements should actually work well with pgbouncer in v2, but yes, even so, there should be a way to opt out. 

I'll see if I can fit it in before v2 release.
