### ISSUE TITLE
insert table not work 

### ISSUE THREAD

**Issue by lonelysnows** [porsager/postgres#775]
async function addUser(){
  const users = [{
    name: 'Murray',
    age: 68,
  },
  {
    name: 'Walter',
    age: 80
  }] 
  console.log('in')
  let res=await sql`insert into users ${ sql(users) }`.describe();
  console.log(res);
  return 'add success'
}

outcome:
{
  string: "insert into users (\"name\",\"age\")values($1,$2),($3,$4)",
  types: [ 1043, 20, 1043, 20 ],
  name: "ykl9i57au42",
  columns: [],
}
but the table don't add two rows

**Comment by Louis-Tian** [comment]
remove the `describe()` at the end your statement.
