### ISSUE TITLE
syntax error at or near "$1"

### ISSUE THREAD

**Issue by kquadri** [porsager/postgres#808]
Hello. I'm trying to make a dynamic request. but I'm getting this error "PostgresError: syntax error at or near "$1"".
Can you tell me what I'm doing wrong?

const query = 'SELECT 1';
 const result = await  sql \`${query}`

**Comment by porsager** [comment]
Postgres.js uses tagged templates to ensure you don't create unsafe queries from strings. I really hope the documentation should cover all these, so would you mind giving that a read again, and then if it still doesn't make sense reopen this issue, and we can look at what's missing?
