### ISSUE TITLE
nested transactions

### ISSUE THREAD

**Issue by devirtua** [porsager/postgres#826]
Hi,
Can nested transactions be used in this library? I could not find any information about this.
I have different transactions, and sometimes I need to use multiple transactions together to build a new transaction.

**Comment by porsager** [comment]
Yes, you need to look at savepoints then. There is no such thing as nested transactions in PostgreSQL.

https://github.com/porsager/postgres?tab=readme-ov-file#savepoint-await-sqlsavepointname-fn---fn
