### ISSUE TITLE
Next.js: Error: A "use server" file can only export async functions. Found "sql" that is not an async function.

### ISSUE THREAD

**Issue by jezmck** [porsager/postgres#828]
After updating Next.js from [14.1.1 to 14.1.2](https://github.com/vercel/next.js/compare/v14.1.1...v14.1.2), I get

> `Error: A "use server" file can only export async functions. Found "sql" that is not an async function.`

Presumably due to [this commit](https://github.com/vercel/next.js/commit/714020fba310c1509c402ff5417016347a32a37e).

**Comment by porsager** [comment]
So this should be in issue create in the Next.js repo?

**Comment by jezmck** [comment]
Ah, sorry, I've now realised that it's not this package's own export of `sql` but mine;

```ts
const sql = postgres(process.env.DATABASE_URL as string);
export default sql;
// ...
export async function getLatest...() { ... }
```

**Comment by SSbit01** [comment]
Use `server-only` package for modules and libraries and `'use server'` in server actions.

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment
