### ISSUE TITLE
ERROR:  could not load library

### ISSUE THREAD

**Issue by BGW1001** [porsager/postgres#835]
I have been trying to get PostgreSQL 16.2, compiled by Visual C++ build 1937, 64-bit  running on a win11 machine. I am having a number of issues, but one that looks very much like a bug

CREATE EXTENSION plpython3u;

Throws this error. ERROR:  could not load library "C:/Program Files/PostgreSQL/16/lib/plpython3.dll": The specified module could not be found.

But the file clearly exists in that directory. 

But the because it is a windows machine the path should really be "C:\Program Files\PostgreSQL\16\lib\plpython3.dll". Looks like some unix style file paths are in use. 

Is this a bug? or just misleading output. In any case that command does not work in my environment. 

PS running the sql shell as admin or not admin makes no difference. 

<img width="531" alt="image" src="https://github.com/porsager/postgres/assets/98311543/14d74652-05b1-4500-b976-89fbdf209d47">

**Comment by porsager** [comment]
You're probably in the wrong place 😉 This is a JavaScript postgres driver, not PostgreSQL itself 😊

**Comment by BGW1001** [comment]
Oh. Any idea where I can log an issue?
