### ISSUE TITLE
dynamic column selection with column naming alias is not working

### ISSUE THREAD

**Issue by benjamin79** [porsager/postgres#849]
Hi,

i have an array (columnsToSelect) of columns to which i want add another one

`columnsToSelect.push("(firstname || ' ' || lastname) as fullname");`

`SELECT ${sql(columnsToSelect)} FROM ${sql(table)}`

I tried different combinations with " and ' but without success.

error:
`missing FROM-clause entry for table`

Is this possible?

thanks

**Comment by porsager** [comment]
You need to use fragments to create the ` as ?` parts. 

https://github.com/porsager/postgres?tab=readme-ov-file#building-queries
