### ISSUE TITLE
CONNECT_TIMEOUT error

### ISSUE THREAD

**Issue by henryzhang03** [porsager/postgres#851]
I am running this client on Bun, and upon running it, it always runs into a code "CONNECT_TIMEOUT" error on even the first request. My connection setup is:

```js
  db = postgres(process.env.DB_CONNECTION_STRING!, {
    host: process.env.DB_HOST, // Postgres ip address[s] or domain name[s]
    port: Number(process.env.DB_PORT), // Postgres server port[s]
    database: process.env.DB_NAME, // Name of database to connect to
    username: process.env.DB_USERNAME, // Username of database user
    password: process.env.DB_PASSWORD // Password of database user
  });
```
  
  I don't really know whats going on, but was wondering if I was doing something wrong or if this is a known issue.

**Comment by porsager** [comment]
it's a bug in bun if the same thing works with node 😉 https://github.com/porsager/postgres/issues/817#issuecomment-2030285794
