### ISSUE TITLE
Support Temporal.Instant for Timestamp columns

### ISSUE THREAD

**Issue by zadeviggers** [porsager/postgres#856]
The Temporal API is now available in Deno. Given this library's popularity in the Deno ecosystem, I think it would make sense to support passing `Temporal.Instant` objects the same way we can currently pass Date objects.

You can easily convert a `Temporal.Instant` to a `Date` like so:
```js
// From the Temporal cookbook: https://tc39.es/proposal-temporal/docs/instant.html#interoperability-with-date
instant = Temporal.Instant.from('2020-01-01T00:00:00.123456789+05:30');
                                                           // => 2019-12-31T18:30:00.123456789Z
date = new Date(instant.epochMilliseconds);
```

Supporting the more advanced `Temporal` types, like `Temporal.ZonedDateTime` for `Timestamptz`s or `Temporal.Duration` for `Interval`s, could also be an interesting thing to pursue in the future.

**Comment by langpavel** [comment]
Note that you must run `deno --unstable-temporal`

**Comment by porsager** [comment]
Should be fairly trivial with a custom type? https://github.com/porsager/postgres?tab=readme-ov-file#custom-types

**Comment by Abion47** [comment]
@porsager Now that the Temporal API is in Stage 4 for ECMAScript, has wide support in [most major browsers and JS runtimes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#browser_compatibility), and a robust [polyfill](https://www.npmjs.com/package/temporal-polyfill#comparison-with-js-temporalpolyfill) for everything else, official support for Temporal types should be reconsidered. While this is something that can be fairly easily achieved with a custom type, it's already an existing pain point that the library uses `Date` by default to parse date-times and timestamps resulting in the loss of microsecond or lower resolution, and now that a better alternative is on the cusp of being the new standard, this is going to become a deal-breaker for some in the near future.

**Comment by sina-heidariaan** [comment]
If you need this today: temporal-sql maps Postgres timestamptz/timestamp/date/time/timetz/interval to TC39 Temporal (Instant/PlainDateTime/PlainDate/PlainTime/Duration) for pg / postgres.js / Drizzle / Prisma. It handles the fiddly bits — interval⇄Duration and microsecond precision — and keeps Date out entirely. npm: temporal-sql · repo: github.com/sina-heidariaan/temporal-sql
