### ISSUE TITLE
Is insert/update to a boolean supported for truthy strings?

### ISSUE THREAD

**Issue by rytido** [porsager/postgres#858]
Based on the [postgres docs](https://www.postgresql.org/docs/current/datatype-boolean.html) and [the parse function I could find](https://github.com/porsager/postgres/blob/cc688c642fc98c4338523d3e281e03bf0c3417b8/src/types.js#L26), I would expect this to result in a true. Am I missing something?

```js
sql.begin(async (sql) => {
  await sql`create temp table t(boolcol boolean)`;
  const x = { boolcol: "t" };
  await sql`insert into t ${sql(x)}`;
  await sql`update t set ${sql(x)}`;
  console.log(await sql`select boolcol from t`);
});
```

`Result(1) [ { boolcol: false } ]`

**Comment by porsager** [comment]
The parse function is what is used when values is retrieved from the db, so you should look at the serialize function for what is sent ` serialize: x => x === true ? 't' : 'f' ` https://github.com/porsager/postgres/blob/cc688c642fc98c4338523d3e281e03bf0c3417b8/src/types.js#L25
