### ISSUE TITLE
Conditional WHERE clause

### ISSUE THREAD

**Issue by henryzhang03** [porsager/postgres#860]
Hi, I looked through some of the older issues regarding this but they did not solve my problem. Here is my code snippet

```js
    let whereClause = '';

    if (fragments.length > 0) {
      whereClause = db`WHERE ${fragments.join(' AND ')}`;
    }

    const newPairs = await db`
      SELECT * FROM NewPairs
      ${whereClause ? whereClause : db``}
      ORDER BY ${db(orderBy)} ${orderDirection.toUpperCase() === 'ASC' ? db`ASC` : db`DESC`}
      LIMIT 100 OFFSET 0
    `;
```

fragments just contains 0 or many of these for example:
```js
db`sell_count <= ${sellCountTo}`
```

I keep getting an empty response from my DB but im not sure why, even though If I write out the full query and query my DB, it returns with a populated response.

**Comment by langpavel** [comment]
Replace `let whereClause = '';`
with `let whereClause = db'';`

**Comment by porsager** [comment]
You can't join on an array of fragments as that will just result in a stringified version of it. Use eg. flatMap and only insert and if i !== 0. Eg ``` xs.flatMap((x, i) => i ? [sql`and`, x] : x) ```

**Comment by vijay8i** [comment]
@porsager sorry for commenting on a closed issue; couldn't help myself in being able to follow your answer. In a different context I tried to follow your suggestion, and constructed the OP's query as below; should this work?

```js
let whereClause = '';

if (fragments.length > 0) {
  // Use flatMap to dynamically add AND between fragments
  const conditions = fragments.flatMap((fragment, i) => 
    i > 0 ? [db`AND`, fragment] : [fragment]
  );

  // Build the WHERE clause using the conditions
  whereClause = db`WHERE ${db(...conditions)}`;
}

const newPairs = await db`
  SELECT * FROM NewPairs
  ${whereClause ? whereClause : db``}
  ORDER BY ${db(orderBy)} ${orderDirection.toUpperCase() === 'ASC' ? db`ASC` : db`DESC`}
  LIMIT 100 OFFSET 0
`;
```

**Comment by Nayawana** [comment]
Its ok sir thax for the hep

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vijay8i** [comment]
> @porsager sorry for commenting on a closed issue; couldn't help myself in being able to follow your answer. In a different context I tried to follow your suggestion, and constructed the OP's query as below; should this work?

Never mind.  Another [post/response](https://github.com/porsager/postgres/issues/845#issuecomment-2092488452) of yours cleared up my confusion. Sorry for the noise. I can delete my question and this follow up if you want me to. Thanks.
