### ISSUE TITLE
Error:  column \"typcategory\" does not exist - Postgres 8.2

### ISSUE THREAD

**Issue by eboats** [porsager/postgres#87]
I'm trying to integrate with an old version of Postgres ( 8.2 ) and am getting the below error when it's trying to connect. It looks like it may be due to a query in the postgres file  /lib/index.js 

          select oid, typelem
          from pg_catalog.pg_type
          where typcategory = 'A'

Does this postgres package not support older versions of Postgres?

{"severity_local":"ERROR","code":"42703","position":"82","file":"parse_expr.c","line":"556","routine":"transformColumnRef","status":500,"stack":"Error: column \"typcategory\" does not exist\n    at Object.generic (node_modules/postgres/lib/types.js:200:5)\n    at Object.ErrorResponse

**Comment by porsager** [comment]
Hi @eboats . Sorry for the late reply. I see now that typcategory was first added in Postgres 8.4, but to be honest I haven't tested with 8.x versions. Maybe we can add testing for each postgres version easily once https://github.com/porsager/postgres/pull/100 lands and github actions are set up for testing.

**Comment by porsager** [comment]
If anyone should have a dire need for support < 8.4 feel free to reopen, and we can consider if it's feasible. I'll close this for now.
