### ISSUE TITLE
How to bulk insert/upsert?

### ISSUE THREAD

**Issue by brielov** [porsager/postgres#88]
I have to sync an xml feed with a postgres database. So far, I download and parse the xml and then I do:

```javascript
const products = [...]
sql`insert into products ${sql(products, 'sku', 'title')}`
```

The first time runs fine, but when it encounters a duplicatte `sku` it fails, so how could I handle `on conflict (sku) do update...` using this approach?

**Comment by xiaoyu-tamu** [comment]
have you tried append `on conflict (sku) do update... `?

**Comment by brielov** [comment]
@xiaoyu-tamu I don’t know exactly how to finish that line, can you provide an example of how would you do it?

**Comment by xiaoyu-tamu** [comment]
`INSERT INTO customer ${sql([])}
  ON CONFLICT ON CONSTRAINT some_constraint_key
  DO UPDATE SET first_name      = EXCLUDED.first_name;`

**Comment by porsager** [comment]
I hope @xiaoyu-tamu could help you. If you still have an issue feel free to reopen.

**Comment by LordZardeck** [comment]
@porsager Is there a way to accomplish the example @xiaoyu-tamu without having to provide each of the column names manually in the `UPDATE SET`?

**Comment by xerosanyam** [comment]
Some examples of upsert for future readers:
Both are valid syntax.
```js
await sql`
INSERT INTO market_info $ {sql(result)}
ON CONFLICT (company_code)
    DO UPDATE SET
        (company_name, market_cap, country) = (EXCLUDED.company_name, EXCLUDED.market_cap, EXCLUDED.country)`
```

```js
await sql`
INSERT INTO market_info $ {sql(result)}
ON CONFLICT (company_code)
    DO UPDATE SET
        company_name = EXCLUDED.company_name, market_cap = EXCLUDED.market_cap, country = EXCLUDED.country`
```
----
@LordZardeck  I don't think we can get away without writing UPDATE SET values. that is a requirement by postgres.

**Comment by porsager** [comment]
It's actually possible to make the columns dynamic too like this:

```js
// Assuming result is an array of objects
sql`
  INSERT INTO market_info ${ sql(result) }
  ON CONFLICT (company_code) DO UPDATE
  SET ${ 
    Object.keys(result[0]).map((x, i) =>
      sql`${ i ? sql`,` : sql``}${ sql(x) } = excluded.${ sql(x) }`
    )
  }
`
```
