### ISSUE TITLE
Query Hooks 

### ISSUE THREAD

**Issue by spacetoha** [porsager/postgres#880]
Hi, 

Are there any plans to extend the connection interface with query hooks to integrate with monitoring applications like open-telemetry, sentry, etc? If yes when can we expect it and how would be possible to prioritize this feature request? 

Thanks, 
Anton

**Comment by porsager** [comment]
Did you check the https://github.com/porsager/postgres/tree/query-stats branch and https://github.com/porsager/postgres/issues/461#issuecomment-1606294308 ?
