### ISSUE TITLE
Cloudflare:    I/O  Error

### ISSUE THREAD

**Issue by zhihengGet** [porsager/postgres#884]
Hi guys, i have been getting 

Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall performance."

how do u avoid this ? i have idle_timeout to zero, max_timeout to default, i create a new instance in sveltekit `hook.server.ts`

i feel like  `locals.sql=postgres( ) ` does not really create new instance

**Comment by zhihengGet** [comment]
figured out, i initialized sql instance too early by the time it is used, it already lost

**Comment by styxpilled** [comment]
@zhihengGet Can you share how you're initializing it without it leaking through requests? I can't seem to get it to work.

**Comment by styxpilled** [comment]
@GwFreak01 It's been quite some time, so I don't remember what exactly needs to be done, but from what I can tell creating the instance in the hooks handle and storing it in locals works. Then use it via `locals.sql`.
```ts
export const handle: Handle = async ({ event, resolve }) => {
  const sql = postgres(DATABASE_URL);
  event.locals.sql = sql;
  return resolve(event);
};
```
