### ISSUE TITLE
Convert to ES6 module

### ISSUE THREAD

**Issue by ghost** [porsager/postgres#89]
why using module.exports whne you can import/export?

**Comment by Minigugus** [comment]
Because Node.JS ESM support is still experimental and using import/export means adding a build step, which break the 0 dependencies principle :wink:

**Comment by nainardev** [comment]
Atleast dont close this issue until its done

**Comment by porsager** [comment]
Actually @minigugus, if you looks back before 1.0 release in the commits I had the source in import/export syntax, and then a small script to convert to commonjs, hehe.. The reason I removed it was because I didn't want to spend more time setting up dual packages (it didn't seem set in stone then), and I also liked being able to just instantly test stuff out.. 

I think the time is better now, so I'd be fine digging the conversion script back out, convert and also help us in the progress of making Postgres.js deno compatible 😉

**Comment by Minigugus** [comment]
> I think the time is better now, so I'd be fine digging the conversion script back out, convert and also help us in the progress of making Postgres.js deno compatible

Awesome :smile: Maybe this can help https://github.com/Minigugus/postgres-deno :smirk: :wink: 

Also, if you are ready for ES6 modules, what about full TypeScript conversion (still Deno compatible :wink:)?

**Comment by stalniy** [comment]
Nodejs 14 is LTS NOW, supports import/export and dual package loading. So, it’s time to migrate :)

**Comment by maxpain** [comment]
Any updates?

**Comment by porsager** [comment]
@maxpain There's a PR now, you're welcome to try out [`npm install porsager/postgres#esm`](https://github.com/porsager/postgres/pull/231)

I still need to test this for all supported node versions using both cjs and esm before I can merge..

**Comment by elhananjair** [comment]
Hello friends I really wish this library supports CommonJS of importing packages using `require`, many libraries I am using here mainly support that.

**Comment by porsager** [comment]
It does 😉

**Comment by elhananjair** [comment]
> It does 😉

ow wow, therefore I can use 

```
const postgres = require('postgres')

const sql = postgres({ /* options */ }) // will use psql environment variables
export default SQL
```
This is very nice, can you please add this as an example to the documentation? 
Thanks

**Comment by porsager** [comment]
Sorry, I was just taking it as a given 😋 Make a PR with a comment in the very first code sample, I think that's good enoughOn 30 Jul 2024, at 14.46, Amanuel Elhanan ***@***.***> wrote:﻿

It does 😉

ow wow, therefore I can use
const postgres = require('postgres')

const sql = postgres({ /* options */ }) // will use psql environment variables
export default SQL

This is very nice, can you please add this as an example to the documentation?
Thanks
