### ISSUE TITLE
Is it possible to execute a parameterized query with separate sql and bindings?

### ISSUE THREAD

**Issue by jacobcons** [porsager/postgres#898]
I basically have sql and bindings generated dynamically from a query builder 

A toy example:
```js
const sql = 'SELECT * FROM users WHERE id = $1';
const params = [1];
```

And so I was just wondering if it's possible to execute these dynamically built queries with your library as a parameterized query?

Loving the project overall, thank you so much.

**Comment by porsager** [comment]
You're looking for sql.unsafe ;) https://github.com/porsager/postgres?tab=readme-ov-file#unsafe-raw-string-queries
