### ISSUE TITLE
Feature Request: sql() handle undefined column name

### ISSUE THREAD

**Issue by xiaoyu-tamu** [porsager/postgres#91]
use case: defined columns dynamically.

Currently, the following code will fail

```
const data = { phone: null }

const user = {
 name:"Peter"
 phone: data.phone
}

// only update phone when it is defined
sql(user, 'name', data.phone ? 'phone' : undefined)
```

As a workaround, I currently do 
`sql(user, ...['name', data.phone ? 'phone' : undefined].filter(Boolean))`

But typescript is complain string is not assignable to `'name' | 'phone'`, 

I have to cast type as any
`sql(user, ...['name', data.phone ? 'phone' : undefined].filter(Boolean) as any)`

It would be nice sql() can filter out undefined by itself. 

This way, type of `column_names` can accept undefined.

**Comment by porsager** [comment]
Wouldn't the above work by not spreading? `sql(user, ['name', data.phone ? 'phone' : undefined].filter(Boolean))`

**Comment by porsager** [comment]
Feel free to reopen for further discussion if that doesn't solve the problem.
