### ISSUE TITLE
Show All - is count: null

### ISSUE THREAD

**Issue by JSchmidt63** [porsager/postgres#92]
First of all, thank you for this Postgres lightweight alternative. Great work.

I am not sure that is by design?		
const version = await sql`SHOW ALL`;
console.log(version);
console.log("count: "+ version.count + " command: " + version.command + " length: " + version.length);

**Comment by porsager** [comment]
Hi @JSchmidt63 .. Thank you :)

The query `SHOW ALL` doesn't return a count, but only the command name, so I think `count: null` is good enough. The count is a PostgreSQL protocol response which is just translated directly. It's not to be compared with the length of the array as that represents the rows being returned for a query.

**Comment by JSchmidt63** [comment]
Thank you for the fast the comment.  👍

**Comment by porsager** [comment]
You're welcome ;)
