### ISSUE TITLE
How to connect my db running on a private network?

### ISSUE THREAD

**Issue by mayrsascha** [porsager/postgres#929]
I've been hosting my PostgreSQL on render.com since recently. They give 2 options to connect to their database:

1. External URL (a "normal" database URL string) as specified in your README here
2. An "internal URL" AKA over a private network as [described here](https://docs.render.com/private-network) and [here](https://docs.render.com/databases#connecting-with-the-internal-url)

When I use the internal database URL, postgres.js won't let me connect to the database and throws an error `Error: getaddrinfo ENOTFOUND <internal host name string here>`, while I have another web service running that is using [Node PG](https://github.com/brianc/node-postgres) and it works using that client.

I'm unfamiliar with private networks but would have assumed `postgres.js` would let me connect to the database on the private network because my host is recommending connecting that way for lower latency.

**Comment by porsager** [comment]
Should be fine, so yeah - you're doing something different than in that other service... Did you insert the `<internal host name string here>` string in the error you posted, or did you maybe forget to do that in the connection string?

**Comment by mayrsascha** [comment]
Thanks for the quick reply @porsager I'm using the same connection string and the same connection options in both services, I checked that. Seems to be a hosting issue after all then.
