### ISSUE TITLE
CONNECTION_CLOSED with PgBouncer

### ISSUE THREAD

**Issue by deman4ik** [porsager/postgres#93]
Sometimes I have CONNECTION_CLOSED errors while using PgBouncer in transaction mode.

Any suggestions how I can may be tweak some connection parameters to prevent those kind of errors?

Direct connection to Pg seems working fine.

**Comment by porsager** [comment]
Could you give postgres@beta a shot?

**Comment by deman4ik** [comment]
@porsager It turns out I’m already using it on dev environment. So this problem occurs in beta version.

**Comment by porsager** [comment]
Ahha.. It seems that if you run in transaction mode [`Protocol-level prepared plans`](https://www.pgbouncer.org/features.html#fnref:2) which Postgres.js does automatically for you, is not allowed with PgBouncer. It says in the footnote that 

> It is possible to add support for that into PgBouncer. 

But it doesn't lead to anywhere, so maybe it's something they're looking at for the future?

I would say this is another good reason to add an option to disable the automatic prepared statements in Postgres.js, which was also mentioned in another issue.
