### ISSUE TITLE
Running the test suite

### ISSUE THREAD

**Issue by akheron** [porsager/postgres#95]
I could not find any documentation on how to run the test suite on my machine, so here are the steps I needed to take to make it work. I'm on Arch Linux.

Turn SSL on and configure password encryption in `postgresql.conf`:

```
ssl = on
password_encryption = scram-sha-256
```

Add `server.crt` and `server.key` as per the "Creating Certificates" section in https://www.postgresql.org/docs/12/ssl-tcp.html.

Create users and allow your own user to create and drop databases:

```sql
create user postgres_js_test password null;
create user postgres_js_test_clear password 'postgres_js_test_clear';
create user postgres_js_test_md5 password 'postgres_js_test_md5';
create user postgres_js_test_scram password 'postgres_js_test_scram';

-- If a user with your own username does not yet exist:
create user YOUR-USER createdb password null;

-- If your own username exists but does not have the permission to
-- create databases:
alter user YOUR-USER createdb;
```

Configure access control in `pg_hba.conf`:

```
# This should already be on by default; Trust all unix domain socket connections.
local  all                all                                           trust

# Allow test users to connect to the postgres_js_test database
host   postgres_js_test   postgres_js_test           127.0.0.1/32       trust
host   postgres_js_test   postgres_js_test_clear     127.0.0.1/32       password
host   postgres_js_test   postgres_js_test_md5       127.0.0.1/32       md5
host   postgres_js_test   postgres_js_test_scram     127.0.0.1/32       scram-sha-256

# Allow your own username to connect to the postgres database (for
# tests that use the default connection params)
host   postgres           YOUR-USER                  127.0.0.1/32       trust
```

On my machine, the postgres unix domain socket is in `/run/postgresql` instead of `/tmp`, so I changed the path in the `Unix socket` test case in `tests/index.js` near line 880.

Then run `npm test`.

Hope this helps!

**Comment by Minigugus** [comment]
Amazing! :+1:

Do you think you can create a Dockerfile with this configuration, to make it easier to set up a test environment? It could also be useful for setting up a CI :wink:

**Comment by akheron** [comment]
Sure, see #100

**Comment by porsager** [comment]
So nice @akheron , and shame on me for not having included this from the get go! Thank you! 

We should include this in the readme.md as well.. Maybe include it in the pull request?

**Comment by porsager** [comment]
I've improved a bit on this with https://github.com/porsager/postgres/blob/master/tests/bootstrap.js
