### ISSUE TITLE
Incorrect generation of dynamic values

### ISSUE THREAD

**Issue by piotrek-toolla** [porsager/postgres#956]
I have a complex query and part of it is following:
```
postgres=>     SELECT x.id FROM (values (1), (2), (3)) as x(id) WHERE x.id < 2;
 id 
----
  1
(1 row)
```
This query naturally works.
I'd like to build it with your library and pass the array of integers such as:
```
  const elements = [1, 2, 3];
  const result = await sql`
    SELECT x.id
    FROM (values ${sql(elements.map((elem) => `(${elem})`))}) as x(id)
    WHERE x.id < 2
  `;
```
Unfortunately, it fails with `PostgresError: operator does not exist: text < integer`. Forcing it to:
```
  const elements = [1, 2, 3];
  const result = await sql`
    SELECT x.id
    FROM (values ${sql(elements.map((elem) => `(${elem})`))}) as x(id)
    WHERE x.id::int < 2
  `;
```
doesn't help because then I get: `PostgresError: invalid input syntax for type integer: "(1)"`. A workaround seems to be:
```
  const elements = [1, 2, 3];
  const result = await sql`
    SELECT x.id
    FROM (values ${sql.unsafe(elements.map((elem) => `(${elem})`))}) as x(id)
    WHERE x.id < 2
  `;
```
but it uses `unsafe` construct which I don't like.
Am I forced to use the `unsafe`? Is it a bug in the library or a missing feature?

**Comment by michal-perlakowski** [comment]
Add sql call in the value returned by the map callback:

```
elements.map((elem) => sql`(${elem})`))
```

**Comment by piotrek-toolla** [comment]
Thanks @michal-perlakowski 
The working solution is:
```
  const elements = [1, 2, 3];
  const result = await sql`
    SELECT x.id
    FROM (values ${sql(elements.map((elem) => sql`(${elem})`))}) as x(id)
    WHERE x.id::int < 2
  `;
```

**Comment by porsager** [comment]
@piotrek-toolla I think the idiomatic way to do this would be:

```js
const xs = [1, 2, 3]
await sql`
  select 
    id
  from unnest(${ xs }::int[]) as x(id)
  where x.id < 2
`
```
