### ISSUE TITLE
Does this client support Redshift or other Postgres-compatible databases?

### ISSUE THREAD

**Issue by satire-foxfire** [porsager/postgres#957]
Libraries like `pg` appear to work out of the box with any Postgres-compatable database, but if I try this library with Redshift, any and all queries seem to result in a `PostgresError: column b.typarray does not exist` error regardless of how many tweaks or attempts I make.

Could someone confirm whether this library is intended or designed to work outside of official Postgres itself?

Otherwise, really like the library and would love to use it over `pg`, but unfortunately I need something that works with Redshift as well :(

**Comment by porsager** [comment]
Just add `fetch_types: false` to options 😉 

Works with any postgres wire protocol compatible DB

**Comment by satire-foxfire** [comment]
@porsager Awesome, thanks!
