### ISSUE TITLE
error 42601 syntax error 

### ISSUE THREAD

**Issue by SMAY666** [porsager/postgres#973]
Hello! I try to create table and receive the error. I wrote this code 
await pgConnection.sql`create table if not exists users (id serial primary key not null)`
 It works correct, the table is created. But if I replace "users" to `${this.name}` with value "users1"
 
await pgConnection.sql`create table if not exists ${this.name} (id serial primary key not null)` 
request will be failed with error 42601 despite the fact that the requests are the same

**Comment by tilemanrenovations** [comment]
Do you have any more updates on your pull request?

Get Outlook.vip for iOS<https://aka.ms/o0ukef>
________________________________
From: Matvey ***@***.***>
Sent: Wednesday, October 30, 2024 3:38:46 AM
To: porsager/postgres ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [porsager/postgres] error 42601 syntax error (Issue #973)


Hello! I try to create table and receive the error. I wrote this code
await pgConnection.sqlcreate table if not exists users (id serial primary key not null) It works correct, the table is created. But if I replace "users" to `${this.name}` with value "users1" `await pgConnection.sql`create table if not exists ${this.name} (id serial primary key not null) request will be failed with error 42601 despite the fact that the requests are the same

**Comment by porsager** [comment]
It's in the docs.. Use `sql()`

**Comment by SMAY666** [comment]
> It's in the docs.. Use `sql()`

May I get example?
