### ISSUE TITLE
periods in string split string

### ISSUE THREAD

**Issue by bobbymannino** [porsager/postgres#987]
if you have a string "bonobo.bob@bom.com" no matter how you insert it;

"sql`call new_user(${email})`"
"sql`call new_user(${sql(email)})`"

I end up with the sql `call new_user ("bonobo"."bob@bom"."com")`

Why is this happening? im sure its me but I cant figure out why?

**Comment by chiuwah** [comment]
If you put the email in an object and then insert it in the sql request, it should work:

```javascript
const user = { email: 'bonobo.bob@bom.com' }

await sql.`insert into users ${ sql(user, 'email') }
```

**Comment by bobbymannino** [comment]
I did this and it worked for me so I think I can close this
