### ISSUE TITLE
`delete from` with a dynamic `like` expression does not work

### ISSUE THREAD

**Issue by insidewhy** [porsager/postgres#994]
```typescript
const match = `test-${testType}-${testPrefix}-%`
await sql`delete from table where name like ${match}`
```

This doesn't delete any rows, so I used `describe` and saw it sends what looks like a correct query, but the result of the `describe` does not show what parameter it would send.

I think maybe the `match` is getting mangled. The documentation has an example of a `select` expression with a dynamic `like`, and I followed that, with particular attention to the "do not quote" stuff.

**Comment by porsager** [comment]
This looks perfectly fine from a query point of view, so you probably just have your match wrong 😅

**Comment by insidewhy** [comment]
> This looks perfectly fine from a query point of view, so you probably just have your match wrong 😅

The query is correct, if I replace the variable with a hard coded string it works

**Comment by porsager** [comment]
Give me something reproducible and I'll look into it.
